// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./math/common ./math/mat2d ./math/vec2 ../../Viewpoint ../../core/promiseUtils ../../geometry/SpatialReference ../../geometry/Geometry ../../geometry/Point ../../geometry/Extent ../../geometry/support/webMercatorUtils ../../geometry/support/scaleUtils ../../geometry/support/spatialReferenceUtils".split(" "),function(Q,f,p,g,e,y,K,L,z,u,M,v,A,N){function B(a,b,d,c){return c&&(d&&!c.equals(d)&&v.canProject(c,d))&&c.isWebMercator?(c.isWebMercator?(d=b[1],89.99999<d?d=89.99999:
-89.99999>d&&(d=-89.99999),d=Math.sin(p.toRadian(d)),a=e.set(a,p.toRadian(b[0])*s,0.5*s*Math.log((1+d)/(1-d)))):(d=p.toDegree(b[0]/s),a=e.set(a,d-360*Math.floor((d+180)/360),p.toDegree(0.5*Math.PI-2*Math.atan(Math.exp(-1*b[1]/s))))),a):e.copy(a,b)}function t(a){return a.wkid?a:a.spatialReference||L.WGS84}function m(a,b){return b.type?e.set(a,b.x,b.y):e.copy(a,b)}function w(a,b){return Math.max(a.width/b[0],a.height/b[1])*C(a.spatialReference)}function r(a,b,d){var c;if(!a)return null;if(Array.isArray(a)&&
2===a.length&&"number"===typeof a[0]&&"number"===typeof a[1])return new u(a);if(a.reduce)return a.reduce(function(a,c){return r(c,b,a)},d);a instanceof z?c=a:a.geometry&&(c=a.geometry);if(!c)return null;a="point"===c.type?new M({xmin:c.x,ymin:c.y,xmax:c.x,ymax:c.y,spatialReference:c.spatialReference}):c.extent;if(!a)return null;c=v.canProject(a,b);if(!a.spatialReference.equals(b)&&c)a=v.project(a,b);else if(!c)return null;return d=d?d.union(a):a.clone()}function D(a,b){if(!a)return new y({targetGeometry:new u,
scale:0,rotation:0});var d=b.spatialReference,c=b.size,q=b.currentViewpoint,h=b.constraints,f=null;"esri.Viewpoint"===a.declaredClass?f=a:a.viewpoint?f=a.viewpoint:a.target&&"esri.Viewpoint"===a.target.declaredClass&&(f=a.target);var k=null;if(f&&f.targetGeometry)k=f.targetGeometry;else if(a instanceof z)k=a;else if(a||a&&(a.hasOwnProperty("center")||a.hasOwnProperty("extent")||a.hasOwnProperty("target")))k=r(a.center,d)||r(a.extent,d)||r(a.target,d)||r(a,d);!k&&q&&q.targetGeometry?k=q.targetGeometry:
!k&&b.extent&&(k=b.extent);var g=t(k);d||(d=t(b.spatialReference||b.extent||k));var l=m(e.create(),k.center?k.center:k),d=new u(B(l,l,g,d),d),g=null,g=f&&f.targetGeometry&&"point"===f.targetGeometry.type?f.scale:a.hasOwnProperty("scale")&&a.scale?a.scale:a.hasOwnProperty("zoom")&&-1!==a.zoom&&h&&h.effectiveLODs?h.zoomToScale(a.zoom):Array.isArray(k)||"point"===k.type||"extent"===k.type&&0===k.width&&0===k.height?b.extent?w(b.extent,c):q.scale:w(k.extent,c),c=0;f?c=f.rotation:a.hasOwnProperty("rotation")?
c=a.rotation:q&&(c=q.rotation);h&&(h.rotationEnabled||(c=0),h.snapToZoom&&(g=h.snapScale(g)),0!==h.effectiveMinScale&&(g=Math.min(h.effectiveMinScale,g)),0!==h.effectiveMaxScale&&(g=Math.max(h.effectiveMaxScale,g)));return new y({targetGeometry:d,scale:g,rotation:c})}function l(a,b){var d=a.targetGeometry,c=b.targetGeometry;d.x=c.x;d.y=c.y;d.spatialReference=c.spatialReference;a.scale=b.scale;a.rotation=b.rotation;return a}function E(a,b,d){return!d?e.scale(a,b,0.5):e.set(a,0.5*(b[0]-d.right+d.left),
0.5*(b[1]-d.bottom+d.top))}function O(a,b,d){f.getTransform(a,b,d);return g.invert(a,a)}function x(a,b,d){var c=p.toRadian(b.rotation)||0;b=Math.abs(Math.cos(c));c=Math.abs(Math.sin(c));return e.set(a,Math.round(d[1]*c+d[0]*b),Math.round(d[1]*b+d[0]*c))}function n(a){return a.scale*(1/(96*(A.getUnitValueForSR(a.targetGeometry.spatialReference)||F)*G))}function C(a){return 96*(A.getUnitValueForSR(a)||F)*G}function H(a){return a.isWrappable?(a=N.getInfo(a),a.valid[1]-a.valid[0]):0}function I(a,b){return Math.round(H(a)/
b)}var G=39.37,F=6370997*Math.PI/180,s=6378137,P=180/Math.PI;f.create=D;f.copy=l;f.getAnchor=E;f.getExtent=function(){var a=e.create();return function(b,d,c){var e=d.targetGeometry;m(a,e);d=0.5*n(d);b.xmin=a[0]-d*c[0];b.ymin=a[1]-d*c[1];b.xmax=a[0]+d*c[0];b.ymax=a[1]+d*c[1];b.spatialReference=e.spatialReference;return b}}();f.setExtent=function(a,b,d,c,e){f.centerAt(a,b,d.center);a.scale=w(d,c);e&&e.constraints&&e.constraints.constrain(a);return a};f.getOuterExtent=function(){var a=e.create(),b=e.create();
return function(d,c,e){m(a,c.targetGeometry);x(b,c,e);e=0.5*n(c);d.set({xmin:a[0]-e*b[0],ymin:a[1]-e*b[1],xmax:a[0]+e*b[0],ymax:a[1]+e*b[1],spatialReference:c.targetGeometry.spatialReference});return d}}();f.getClippedExtent=function(){var a=e.create(),b=e.create();return function(d,c,e){var f=n(c),g=c.targetGeometry.spatialReference,k=I(g,f);m(a,c.targetGeometry);x(b,c,e);g.isWrappable&&b[0]>k&&(b[0]=k);c=0.5*f;d.set({xmin:a[0]-c*b[0],ymin:a[1]-c*b[1],xmax:a[0]+c*b[0],ymax:a[1]+c*b[1],spatialReference:g});
return d}}();f.getOuterSize=x;f.getPaddingScreenTranslation=function(){var a=e.create();return function(b,d,c){return e.sub(b,e.scale(b,d,0.5),E(a,d,c))}}();var J=function(){var a=g.create(),b=e.create();return function(d,c,q,h){var l=n(c);c=p.toRadian(c.rotation)||0;e.set(b,l,l);g.fromScaling(a,b);g.rotate(a,a,c);g.translate(a,a,f.getPaddingScreenTranslation(b,q,h));g.translate(a,a,[0,h.top-h.bottom]);return e.set(d,a[4],a[5])}}();f.getResolution=n;f.getResolutionToScaleFactor=C;f.getMatrix=function(){var a=
e.create(),b=e.create(),d=e.create();return function(c,f,h,l,k){e.negate(a,f);e.scale(b,h,0.5);e.set(d,1/l,-1/l);g.identity(c);g.translate(c,c,b);k&&g.rotate(c,c,k);g.scale(c,c,d);g.translate(c,c,a);return c}}();f.getTransform=function(){var a=e.create();return function(b,d,c){var e=n(d),h=p.toRadian(d.rotation)||0;m(a,d.targetGeometry);return f.getMatrix(b,a,c,e,h)}}();f.getTransformNoRotation=function(){var a=e.create();return function(b,d,c){var e=n(d);m(a,d.targetGeometry);return f.getMatrix(b,
a,c,e,0)}}();f.getWorldWidth=H;f.getWorldScreenWidth=I;f.createAsync=function(a,b){return K.resolve(D(a,b))};f.angleBetween=function(){var a=e.create(),b=e.create(),d=e.create();return function(c,f,h){e.subtract(a,c,f);e.normalize(a,a);e.subtract(b,c,h);e.normalize(b,b);e.cross(d,a,b);c=Math.acos(e.dot(a,b)/(e.length(a)*e.length(b)))*P;0>d[2]&&(c=-c);isNaN(c)&&(c=0);return c}}();f.addPadding=function(){var a=e.create();return function(b,d,c,e){var f=b.targetGeometry;l(b,d);J(a,d,c,e);f.x+=a[0];f.y+=
a[1];return b}}();f.removePadding=function(){var a=e.create();return function(b,d,c,e){var f=b.targetGeometry;l(b,d);J(a,d,c,e);f.x-=a[0];f.y-=a[1];return b}}();f.centerAt=function(){var a=e.create();return function(b,d,c){l(b,d);d=b.targetGeometry;var e=t(c),f=t(d);m(a,c);B(a,a,e,f);d.x=a[0];d.y=a[1];return b}}();f.pixelSizeAt=function(a,b,d){return n(b)};f.resize=function(){var a=e.create();return function(b,d,c,g,h){h||(h="center");e.sub(a,c,g);e.scale(a,a,0.5);c=a[0];g=a[1];switch(h){case "center":e.set(a,
0,0);break;case "left":e.set(a,-c,0);break;case "top":e.set(a,0,g);break;case "right":e.set(a,c,0);break;case "bottom":e.set(a,0,-g);break;case "top-left":e.set(a,-c,g);break;case "bottom-left":e.set(a,-c,-g);break;case "top-right":e.set(a,c,g);break;case "bottom-right":e.set(a,c,-g)}f.translateBy(b,d,a);return b}}();f.rotateBy=function(a,b,d){l(a,b);a.rotation+=d;return a};f.rotateTo=function(a,b,d){l(a,b);a.rotation=d;return a};f.scaleBy=function(){var a=e.create();return function(b,d,c,g,h){l(b,
d);0!==c&&(f.toMap(a,g,d,h),b.scale=d.scale/c,f.toScreen(a,a,b,h),f.translateBy(b,b,e.set(a,a[0]-g[0],g[1]-a[1])));return b}}();f.scaleTo=function(a,b,d){l(a,b);a.scale=d;return a};f.scaleAndRotateBy=function(){var a=e.create();return function(b,d,c,g,h,n){l(b,d);0!==c&&(f.toMap(a,h,d,n),b.scale=d.scale/c,b.rotation+=g,f.toScreen(a,a,b,n),f.translateBy(b,b,e.set(a,a[0]-h[0],h[1]-a[1])));return b}}();f.toMap=function(){var a=g.create();return function(b,d,c,f){return e.transformMat2d(b,d,O(a,c,f))}}();
f.toScreen=function(){var a=g.create();return function(b,d,c,g){return e.transformMat2d(b,d,f.getTransform(a,c,g))}}();f.translateBy=function(){var a=e.create(),b=g.create();return function(d,c,f){l(d,c);var h=n(c),m=d.targetGeometry;g.fromRotation(b,p.toRadian(c.rotation)||0);g.scale(b,b,e.fromValues(h,h));e.transformMat2d(a,f,b);m.x+=a[0];m.y+=a[1];return d}}()});