// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang dojox/gfx/_base ../../Color ../../core/screenUtils".split(" "),function(x,e,s,t,y,f){function u(a){var c=a.style,b=null;if(a){var d=a.constructor;switch(a.type){case n:c!==d.STYLE_CROSS&&c!==d.STYLE_X&&(b=a.color);break;case p:c===d.STYLE_SOLID?b=a.color:c!==d.STYLE_NULL&&(b=s.mixin({},t.defaultPattern,{src:z+c+".png",width:10,height:10}));break;case q:b=s.mixin({},t.defaultPattern,{src:a.url,width:f.pt2px(a.width)*a.xscale,height:f.pt2px(a.height)*a.yscale,
x:f.pt2px(a.xoffset),y:f.pt2px(a.yoffset)});break;case v:b=a.color}}return b}function r(a){if(!a)return null;var c,b=a.constructor,d=f.pt2px(a.width);switch(a.type){case p:case q:case n:c=r(a.outline);break;case w:a.style!==b.STYLE_NULL&&0!==d&&(c={color:a.color,style:A(a.style),width:d,cap:a.cap,join:a.join===b.JOIN_MITER?f.pt2px(a.miterLimit):a.join});break;default:c=null}return c}var q="picture-fill-symbol",p="simple-fill-symbol",w="simple-line-symbol",n="simple-marker-symbol",v="text-symbol",
z=x.toUrl("../../symbols/patterns/"),B={left:"start",center:"middle",right:"end",justify:"start"},C={top:"text-before-edge",middle:"central",baseline:"alphabetic",bottom:"text-after-edge"};e.getSVGAlign=function(a){return a=(a=a.horizontalAlignment)&&B[a.toLowerCase()]||"middle"};e.getSVGBaseline=function(a){return(a=a.verticalAlignment)&&C[a.toLowerCase()]||"alphabetic"};e.getSVGBaselineShift=function(a){return"bottom"===a.verticalAlignment?"super":null};e.getFill=u;e.getStroke=r;var A=function(){var a=
{};return function(c){if(a[c])return a[c];var b=c.replace(/-/g,"");return a[c]=b}}();e.getShapeDescriptors=function(a){if(!a)return{defaultShape:null,fill:null,font:null,stroke:null};var c={defaultShape:null,fill:u(a),font:null,stroke:r(a)},b=a.constructor,d=b.defaultProps,g=null;switch(a.type){case n:var e=a.style,d=0.5*f.pt2px(a.size||d.size),h=-d,l=+d,m=-d,k=+d;switch(e){case b.STYLE_CIRCLE:g={type:"circle",cx:0,cy:0,r:d};break;case b.STYLE_CROSS:g={type:"path",path:"M "+h+",0 L "+l+",0 M 0,"+
m+" L 0,"+k+" E"};break;case b.STYLE_DIAMOND:g={type:"path",path:"M "+h+",0 L 0,"+m+" L "+l+",0 L 0,"+k+" L "+h+",0 Z"};break;case b.STYLE_SQUARE:g={type:"path",path:"M "+h+","+k+" L "+h+","+m+" L "+l+","+m+" L "+l+","+k+" L "+h+","+k+" Z"};break;case b.STYLE_X:g={type:"path",path:"M "+h+","+k+" L "+l+","+m+" M "+h+","+m+" L "+l+","+k+" E"};break;case b.STYLE_PATH:g={type:"path",path:a.path||""}}break;case w:g={type:"path",path:"M -15,0 L 15,0 E"};break;case q:case p:g={type:"path",path:"M -10,-10 L 10,0 L 10,10 L -10,10 L -10,-10 E"};
break;case "picture-marker-symbol":g={type:"image",x:-Math.round(f.pt2px(a.width)/2),y:-Math.round(f.pt2px(a.height)/2),width:f.pt2px(a.width),height:f.pt2px(a.height),src:a.source&&a.source.imageData?"data:"+a.source.contentType+";base64,"+a.source.imageData:a.url||""};break;case v:b=a.font,e=f.pt2px(b.size),g={type:"text",text:a.text,x:0,y:0.25*e,align:"middle",decoration:a.decoration||b&&b.decoration,rotated:a.rotated,kerning:a.kerning},c.font=b&&{size:e+"px",style:b.style,variant:b.variant,weight:b.weight,
family:b.family}}c.defaultShape=g;return c};e.defaultThematicColor=new y([128,128,128])});