// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/has dojo/_base/lang ../Symbol3D ./jsonUtils ./Thumbnail ./StyleOrigin ../../core/urlUtils ../../core/promiseUtils ../../core/Error ../../request ../../portal/Portal ../../portal/PortalQueryParams".split(" "),function(J,c,r,z,A,B,s,t,m,g,h,C,D,u){function l(a,b){a=m.normalize(m.makeAbsolute(a,b));var d=a.lastIndexOf("/");return-1===d?{url:a,base:a,filename:null}:{url:a,base:a.slice(0,d),filename:a.slice(d+1)}}function E(a,b){v(a,function(a){return l(a,b).url})}function F(a,
b){a.symbolLayers&&a.symbolLayers.forEach(b)}function v(a,b){F(a,function(a){if((a=a.resource)&&a.href)a.href=b(a.href)})}function G(a){v(a,function(a){return/\.svg$/.test(a)?(a.slice(0,a.length-4)+".png").replace("/resource/","/resource/png/"):a})}function n(a,b){a=z.clone(a);E(a,b);(r("ie")||r("trident"))&&G(a);return B.fromJSON(a)}function w(a,b){var d=l(a,b&&b.url&&b.url.path);return p(d.url).then(function(b){return{reference:{styleUrl:a},data:b.data,base:d.base,filename:d.filename,styleUrl:a}})}
function H(a,b){var d=b.portal||D.getDefault(),e,f=d.url+" - "+a;return q[f]?g.resolve(q[f]):I(a,d).then(function(a){e=a;return a.fetchData()}).then(function(b){b={data:b,base:e.itemUrl,filename:"data",styleName:a};return q[f]=b})}function I(a,b){return b.load().then(function(){if(!b.stylesGroupQuery)throw new h("layer-templates:styles-group-query-missing","The styles group query needs to be configured in the portal to query styles");var a=new u({disableExtraQuery:!0,query:b.stylesGroupQuery});return b.queryGroups(a)}).then(function(b){b=
b.results;if(!b||!Array.isArray(b)||0===b.length)throw new h("layer-templates:styles-missing","The styles group does not contain any styles");b=b[0];var e=new u({disableExtraQuery:!0,query:'typekeywords:"'+a+'"'});return b.queryItems(e)}).then(function(b){b=b.results;if(!b||!Array.isArray(b)||0===b.length)throw new h("layer-templates:style-missing","The style '${styleName}' is not part of the styles group",{styleName:a});return b[0].load()})}function x(a,b){return a.styleUrl?w(a.styleUrl,b):a.styleName?
H(a.styleName,b):g.reject(new h("layer-templates:style-url-and-name-missing","Either styleUrl or styleName is required in layerDefinition"))}function y(a,b,d){for(var e=function(e){if(e.name===b){var f=l(e.webRef,a.base);return{value:p(f.url).then(function(c){if((c=n(c.data,f.base))&&c.isInstanceOf(A))e.thumbnail&&(e.thumbnail.href?c.thumbnail=new s.default({url:e.thumbnail.href}):e.thumbnail.imageData&&(c.thumbnail=new s.default({url:"data:image/png;base64,"+e.thumbnail.imageData}))),a.styleUrl?
c.styleOrigin=new t({portal:d.portal,styleUrl:a.styleUrl,name:b}):a.styleName&&(c.styleOrigin=new t({portal:d.portal,styleName:a.styleName,name:b}));return c})}}},f=0,k=a.data.items;f<k.length;f++){var c=e(k[f]);if("object"===typeof c)return c.value}return g.reject(new h("layer-templates:symbol-name-not-found","The symbol name '${symbolName}' could not be found",{symbolName:b}))}function p(a){var b={responseType:"json"};/\.json$/.test(a)||(b.query={f:"json"});return C(m.normalize(a),b)}c.fetchStyleFromUrl=
w;var q={};c.fetchStyle=x;c.fetchStyleSymbol=function(a,b){return!a.name?g.reject(new h("layer-templates:style-symbol-reference-name-missing","Missing name in style symbol reference")):x(a,b).then(function(d){return y(d,a.name,b)})};c.fetchSymbolFromStyle=y;c.fetchSymbolSet=function(a){var b=a.data;if(!b.symbolSetUrl)return g.reject(new h("layer-templates:symbol-set-url-missing","Style does not provide symbol set URL",{style:b}));var d=l(b.symbolSetUrl,a.base);return p(d.url).then(function(a){a=a.data;
if(0===a.length||!a[0].name)throw new h("layer-templates:symbol-set-missing-data","Invalid syntax or missing data in symbol set",{style:b});for(var c={},k=0;k<a.length;k++){var g=n(a[k],d.base);c[a[k].name]=g;a[k].name===b.defaultItem&&(c.defaultSymbol=g)}c.defaultSymbol||(c.defaultSymbol=c[a[0].name]);return c})};c.createSymbol=function(a,b){return!a?null:n(a,b&&b.url&&b.url.path)};c.styleNameFromItem=function(a){var b=0;for(a=a.typeKeywords;b<a.length;b++){var c=a[b];if(/^Esri.*Style$/.test(c))return c}}});