// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../../../Color ../../../request ../../../renderers/SimpleRenderer ../../../renderers/ClassBreaksRenderer ../../../renderers/UniqueValueRenderer ../../../core/Accessor ../../../core/HandleRegistry ../../../core/Logger ../../../core/arrayUtils ../../../core/promiseUtils ../../../../esri/layers/support/ExportImageParameters ./colorRampUtils ./sizeRampUtils ./swatchUtils dojo/_base/lang".split(" "),function(v,w,t,p,u,x,y,z,A,n,B,s,C,D,l){var q=z.getLogger("esri.widgets.Legend.support.ActiveLayerInfo");
return x.createSubclass({declaredClass:"esri.widgets.Legend.support.ActiveLayerInfo",constructor:function(){this._legendResponse=null;this._handles=new y;var a=this.watch("tearingDown",function(){this.destroy()}.bind(this));this._handles.add(a,"tearingDown-watcher")},getDefaults:function(){return{legendElements:[]}},destroy:function(){this._handles.destroy();this._legendResponse=this._handles=null},properties:{layer:null,legendElements:{type:Array},ready:!1,tearingDown:!1,title:null,scale:null,updating:!1,
version:{value:0,readOnly:!0,dependsOn:["updating"],get:function(){return this._get("version")+1}},_hasColorRamp:!1,_hasOpacityRamp:!1,_hasSizeRamp:!1},buildLegendElementsForRenderer:function(){this._getRendererLegendElements(this.layer.renderer).then(function(a){this.updating=!0;this.ready=!1;this.legendElements=a;this.legendElements.length&&(this.ready=!0)}.bind(this)).otherwise(function(a){q.warn("error while building legend for layer!",a)}).always(function(){this.updating=!1}.bind(this))},buildLegendElementsForTools:function(){this.layer.sublayers?
this._constructLegendElementsForSublayers():this._getLegendLayers().then(function(a){this.updating=!0;this.ready=!1;this.legendElements=[];a.forEach(function(a){(a=this._generateSymbolTableElementForLegendLayer(a))&&a.infos.length&&this.legendElements.push(a)},this);this.legendElements.length&&(this.ready=!0)}.bind(this)).otherwise(function(a){q.warn("Request to server for legend has failed!",a)}).always(function(){this.updating=!1}.bind(this))},_getLegendLayers:function(a){var d=a&&a.hasDynamicLayers,
c=this._legendResponse;return!d&&c?n.resolve(c):this._legendRequest(d?a.dynamicLayers:null).then(function(a){return this._legendResponse=a=a.data.layers}.bind(this))},_legendRequest:function(a){var d=this.layer,c=d.url.replace(/(\/)+$/,"");a={f:"json",dynamicLayers:a};if(10.01<=d.version){var b=c.indexOf("?"),c=-1<b?c.substring(0,b)+"/legend"+c.substring(b):c+"/legend";d.token&&(c+="?token\x3d"+d.token)}else d=c.toLowerCase().indexOf("/rest/"),c=c.substring(0,d)+c.substring(d+5,c.length),c="https://utility.arcgis.com/sharing/tools/legend?soapUrl\x3d"+
window.escape(c)+"\x26returnbytes\x3dtrue";return w(c,{query:a,callbackParamName:"callback"})},_constructLegendElementsForSublayers:function(){this.updating=!0;this.ready=!1;this.legendElements=[];this._handles.remove("sublayers-watcher");var a=new B({layer:this.layer});this._getLegendLayers(a).then(function(a){var c={};a.forEach(function(a){c[a.layerId]=a});this.legendElements=this._generateLegendElementsForSublayers(this.layer.sublayers,c,this.layer.opacity);this.legendElements.length&&(this.ready=
!0)}.bind(this)).otherwise(function(a){q.warn("Request to server for legend has failed!",a)}).always(function(){a.destroy();this.updating=!1}.bind(this))},_generateLegendElementsForSublayers:function(a,d,c){var b=[];this._handles.add(a.on("change",this._constructLegendElementsForSublayers.bind(this)),"sublayers-watcher");a.forEach(function(a){var f=a.watch("renderer, opacity, title, visible",this._constructLegendElementsForSublayers.bind(this));this._handles.add(f,"sublayers-watcher");a.visible&&
a.legendEnabled&&(f=a&&null!=a.opacity?a.opacity:null,(a=this._generateSymbolTableElementForSublayer(a,d,null!=f?f*c:c))&&a.infos.length&&b.unshift(a))},this);return b},_generateSymbolTableElementForSublayer:function(a,d,c){var b=d[a.id];return!b&&a.sublayers?(d=this._generateLegendElementsForSublayers(a.sublayers,d,c),{type:"symbol-table",title:a.title,infos:d}):this._generateSymbolTableElementForLegendLayer(b,a,c)},_generateSymbolTableElementForLegendLayer:function(a,d,c){if(a){var b=a.layerName,
e=d&&d.renderer;if(e&&(e=d&&d.title?d.title:this._getRendererTitle(e,d)))b&&(e.title=b),b=e;b={type:"symbol-table",title:b,infos:[]};a.legend&&this._isLegendLayerInScale(a,d)&&(d=d?this._sanitizeLegendForSublayer(a.legend,d):a.legend,b.infos=d.map(function(b){var d=b.url;if(b.imageData&&0<b.imageData.length)d="data:image/png;base64,"+b.imageData;else if(0!==d.indexOf("http")){var d=this.layer.url+"/"+a.layerId+"/images/"+d,e=this.layer.token;e&&(d+="?token\x3d"+e)}else return null;return{label:b.label,
src:d,opacity:c,width:b.width,height:b.height}},this).filter(function(a){return!!a}));return b.infos.length?b:null}},_sanitizeLegendForSublayer:function(a,d){if(10.1>this.layer.version||0===a.length)return a;var c=d.renderer,b,e;a.some(function(a){return a.values})&&a.some(function(a,c){a.values||(b=c,e=a,e.label||(e.label="others"));return null!=e});c?"uniqueValue"===c.type?e&&(a.splice(b,1),a.push(e)):"classBreaks"===c.type&&(e&&a.splice(b,1),a.reverse(),e&&a.push(e)):e&&(a.splice(b,1),a.push(e));
return a},_isLegendLayerInScale:function(a,d){var c=d||this.layer,b=!0,e,f;!c.minScale&&0!==c.minScale||!c.maxScale&&0!==c.maxScale?(0===a.minScale&&c.tileInfo&&(e=c.tileInfo.lods[0].scale),0===a.maxScale&&c.tileInfo&&(f=c.tileInfo.lods[c.tileInfo.lods.length-1].scale)):(e=Math.min(c.minScale,a.minScale)||c.minScale||a.minScale,f=Math.max(c.maxScale,a.maxScale));if(0<e&&e<this.scale||f>this.scale)b=!1;return b},_getRendererLegendElements:function(a,d,c){return this._loadRenderer(a,c).then(function(b){this._hasSizeRamp=
this._hasOpacityRamp=this._hasColorRamp=!1;var e=this._getVisualVariableLegendElements(b,d,c)||[],f={type:"symbol-table",title:d&&d.title?d.title:this._getRendererTitle(b,d),infos:[]},g=a.isInstanceOf(t),k=a.isInstanceOf(p),h=a.isInstanceOf(u),m=g||k||h;if(h)b.uniqueValueInfos.forEach(function(a){a.symbol&&f.infos.push({label:a.label||a.value,value:a.value,symbol:a.symbol})},this);else if(k){var r=this._isUnclassedRenderer(b);if(!r||!this._hasSizeRamp)b.classBreakInfos.forEach(function(a){a.symbol&&
f.infos.unshift({label:a.label||(r?null:a.minValue+" - "+a.maxValue),value:[a.minValue,a.maxValue],symbol:a.symbol})}),r&&(f.title=null)}else g&&b.symbol&&f.infos.push({label:b.label,symbol:b.symbol});g=!1;if(m&&(m=b.defaultLabel,(k=b.defaultSymbol)&&!r))f.infos.push({label:m||"others",symbol:k}),g=!0;!g&&(!r||this._hasColorRamp||this._hasSizeRamp||this._hasOpacityRamp)&&e.push({type:"symbol-table",infos:[{label:b.defaultLabel,symbol:b.defaultSymbol}]});b=null;f.infos.length&&e.unshift(f);var l=[];
e.forEach(function(a){a.infos.forEach(function(a){a.symbol&&l.push(this._buildSwatchInfo(a))},this)},this);return n.eachAlways(l).then(function(){return e})}.bind(this))},_buildSwatchInfo:function(a){return D.getSwatchInfo(a.symbol,a.size).then(function(d){a.swatchInfo=d;return a}).otherwise(function(){a.swatchInfo=null;return a})},_getVisualVariableLegendElements:function(a,d,c){var b=a.visualVariables,e=[],f=[],g=[],k=null!=c?c:this.layer.opacity,h=c=null;if(!b)return null;b.forEach(function(a){"color"===
a.type?e.push(a):"size"===a.type?f.push(a):"opacity"===a.type&&g.push(a)});b=[];Array.prototype.push.apply(b,e);Array.prototype.push.apply(b,f);Array.prototype.push.apply(b,g);0===e.length&&(a.isInstanceOf(p)&&a.classBreakInfos&&1===a.classBreakInfos.length)&&(c=(c=a.classBreakInfos[0])&&c.symbol);0===e.length&&a.isInstanceOf(t)&&(c=a.symbol);c&&(-1<c.type.indexOf("3d")?(c=c.symbolLayers.getItemAt(0),c.get("material.color")&&(h=c.material.color)):c.url||(h=c.color),h&&(h=h.toRgba()));return b.map(function(b){if(!(b.legendOptions&&
!1===b.legendOptions.showLegend)){var c=d?d.title:this._getRampTitle(b,this.layer),e=s.getRampBorderColor(a),f=s.getRampOverlayColor(k),g;"color"===b.type?(g={type:"color-ramp",title:c,borderColor:e,overlayColor:f,infos:s.getRampStops(a,b)},this._hasColorRamp||(this._hasColorRamp=null!=g.infos&&g.infos.length)):"size"===b.type?(g={type:"size-ramp",title:c,infos:C.getRampStops(a,b,this._getMedianColor(a),this.scale)},this._hasSizeRamp||(this._hasSizeRamp=null!=g.infos&&g.infos.length)):"opacity"===
b.type&&(g={type:"opacity-ramp",title:c,borderColor:e,overlayColor:f,infos:s.getRampStops(a,b,h)},this._hasOpacityRamp||(this._hasOpacityRamp=null!=g.infos&&g.infos.length));return g.infos&&g}},this).filter(function(a){return!!a})},_loadRenderer:function(a,d){var c=a.isInstanceOf(t),b=a.isInstanceOf(p),e=a.isInstanceOf(u),f=[];if(!c&&!b&&!e)return q.warn("Renderer not supported!"),n.reject();a=a.clone();var g=this._getMedianColor(a),k=null!=d?d:this.layer.opacity;if(b||e)(a.classBreakInfos||a.uniqueValueInfos).forEach(function(a){f.push(this._fetchSymbol(a.symbol,
g,k).then(function(b){a.symbol=b}).otherwise(function(){a.symbol=null}))},this);f.push(this._fetchSymbol(a.symbol||a.defaultSymbol,a.defaultSymbol?null:g,k).then(function(b){c?a.symbol=b:a.defaultSymbol=b}).otherwise(function(){c?a.symbol=null:a.defaultSymbol=null}));return n.eachAlways(f).then(function(){return a})},_fetchSymbol:function(a,d,c){return!a?n.reject():"web-style-symbol"===a.type?a.fetchSymbol().then(function(a){return this._getAppliedCloneSymbol(a,d,c)}.bind(this)).otherwise(function(){q.warn("Fetching web-style-symbol failed!");
return n.reject()}):n.resolve(this._getAppliedCloneSymbol(a,d,c))},_getMedianColor:function(a){var d,c,b;if(!a.visualVariables)return null;b=A.find(a.visualVariables,function(a){return"color"===a.type});if(!b)return null;if(b.colors)d=b.minDataValue,c=b.maxDataValue;else if(b.stops){if(1===b.stops.length)return b.stops[0].color;d=b.stops[0].value;c=b.stops[b.stops.length-1].value}if(null!=d&&null!=c)return a.getColor(d+(c-d)/2,{colorInfo:b})},_getAppliedCloneSymbol:function(a,d,c){if(!a)return a;
a=a.clone();var b=a.type,e=-1<b.indexOf("3d");d&&(d=new v(d.toRgba()),e?this._applyColorTo3dSymbol(a,d):a.color=d);if("simple-line-symbol"===b||"text-symbol"===b){if(!a.color)return;d=a.color.toRgba();d[3]*=c;a.color=d}else"simple-marker-symbol"===b||"simple-fill-symbol"===b?(a.color&&(d=a.color.toRgba(),d[3]*=c,a.color=d),a.outline&&a.outline.color&&(d=a.outline.color.toRgba(),d[3]*=c,a.outline.color=d)):e&&this._applyColorTo3dSymbol(a,null,c);return a},_applyColorTo3dSymbol:function(a,d,c){a.symbolLayers.forEach(function(a){if(a&&
(d&&(a.material||(a.material={}),a.material.color=d),null!=c)){var e;a.material&&a.material.color&&(e=a.material.color.toRgba(),e[3]*=c,a.material.color=e);a.outline&&a.outline.color&&(e=a.outline.color.toRgba(),e[3]*=c,a.outline.color=e)}})},_getRampTitle:function(a,d){var c=a.field,b=a.normalizationField,e=!1,f=!1,g=!1,c=l.isFunction(c)?null:c,b=l.isFunction(b)?null:b;if(a.legendOptions&&a.legendOptions.title)c=a.legendOptions.title;else if(a.valueExpressionTitle)c=a.valueExpressionTitle;else{if(d.renderer.authoringInfo&&
d.renderer.authoringInfo.visualVariables)for(var k=d.renderer.authoringInfo.visualVariables,h=0;h<k.length;h++){var m=k[h];if("colorInfo"===m.type)if("ratio"===m.style){e=!0;break}else if("percent"===m.style){f=!0;break}else if("percentTotal"===m.style){g=!0;break}}c={field:c&&this._getFieldAlias(c,d),normField:b&&this._getFieldAlias(b,d),ratio:e,ratioPercent:f,ratioPercentTotal:g}}return c},_getRendererTitle:function(a,d){if(a.legendOptions&&a.legendOptions.title)return a.legendOptions.title;if(a.valueExpressionTitle)return a.valueExpressionTitle;
var c=this.layer,b=a.field,e,f,g;a instanceof p&&(e=a.normalizationField,f="percent-of-total"===a.normalizationType);b=l.isFunction(b)?null:b;e=l.isFunction(e)?null:e;if(b||e)g={field:d?b:b&&this._getFieldAlias(b,c),normField:d?e:e&&this._getFieldAlias(e,c),normByPct:f};return g},_getFieldAlias:function(a,d){var c=d.popupTemplate,b=c&&c.fieldInfos,c=l.isFunction(a)?null:d.getField&&d.getField(a),e,f;b&&b.some(function(b){if(a===b.fieldName)return f=b,!0});(b=f||c)&&(e=f&&f.label||c&&c.alias||b.name||
b.fieldName);return e},_isUnclassedRenderer:function(a){var d=!1,c=a.visualVariables;a.isInstanceOf(p)&&(a.classBreakInfos&&1===a.classBreakInfos.length)&&c&&(d=a.field?c.some(function(b){return!(!b||!(a.field===b.field&&a.normalizationField==b.normalizationField))}):!!c.length);return d}})});