// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["../../../core/numberUtils","./swatchUtils"],function(p,r){var z=[255,255,255],A=[200,200,200],q=[128,128,128];return{getRampStops:function(a,c,b,d){var e=c.legendOptions,e=e&&e.customValues,l,k,g;g=this._getSizeSymbol(a,b);var f=null!=c.minSize&&null!=c.maxSize;b=c.stops&&1<c.stops.length;var m=!!c.target;if(g&&(e||f||b&&!m)){var h=r.isVolumetricSymbol(g),e=h&&!b?[c.minDataValue,c.maxDataValue]:e||this._getSizeDataValues(a,c,g,d);!e&&b&&(e=c.stops.map(function(a){return a.value}),(l=c.stops.some(function(a){return!!a.label}))&&
(k=c.stops.map(function(a){return a.label})));b=!h||e&&2===e.length;if(!e||!b)return null;var s=e.length-1,t=[12,24],e=e.map(function(b,e){var f=h?t[e]:this._getSize(a,c,g,b,d),m=this._getSizeAppliedCloneSymbol(g,f),n=p.format(b);e===s?n="\x3e "+n:0===e&&(n="\x3c "+n);n=l?k[e]:n;return{value:b,symbol:m,label:n,size:f}},this);return e.reverse()}},_isFillSymbol:function(a){if(a)return-1<a.type.indexOf("3d")?(a=a.symbolLayers,!a?!1:a.some(function(a){return a&&"Fill"===a.type})):-1!==a.type.indexOf("fill-symbol")},
_getSizeSymbol:function(a,c){var b,d;if("simple"===a.type)b=a.symbol;else if("uniqueValue"===a.type||"classBreaks"===a.type)b=(b=(d=a.classBreakInfos||a.uniqueValueInfos)&&d[0])&&b.symbol,d=1<d.length;if(!b||this._isFillSymbol(b))return null;b=b.clone();if(c||d)d=b&&b.type,-1<d.indexOf("3d")?r.isVolumetricSymbol(b)||(-1!==d.indexOf("line-symbol-3d")?b.symbolLayers.forEach(function(a){a.material={color:q}}):b.symbolLayers.forEach(function(a){"Icon"===a.type&&(!a.resource||!a.resource.href)?(a.material=
{color:z},a.outline={color:q,size:1.5}):a.material={color:A}})):-1!==d.indexOf("line-symbol")?b.color=q:(b.color=z,"simple-marker-symbol"===d&&(b.outline={color:q,width:1.5}));return b},_getSizeDataValues:function(a,c,b,d){var e=a.getSizeRangeAtScale(c,d),l=e&&this._interpolateSizeRange(e),k;if(e||l){k=l.map(function(a){return this._getDataValueFromSize(a,c,e)},this);k=p.round(k);for(var g=1;g<k.length-1;g++){var f=this._roundDataValue(a,c,b,k[g],k[g-1],d);f&&(k[g]=f[0],l[g]=f[1])}return k}},_interpolateSizeRange:function(a){var c=
a.minSize;a=(a.maxSize-c)/4;for(var b=[],d=0;5>d;d++)b.push(c+a*d);return b},_getDataValueFromSize:function(a,c,b){var d=b.minSize;b=b.maxSize;var e=c.minDataValue;c=c.maxDataValue;return a=a<=d?e:a>=b?c:(a-d)/(b-d)*(c-e)+e},_roundDataValue:function(a,c,b,d,e,l){var k=this._getSize(a,c,b,d,l);e=this._getSize(a,c,b,e,l);var g,f=p.numDigits(d),m=f.integer,f=f.fractional,h,s,t,q,r,x,y,n,u,v,w;0<d&&1>d&&(g=Math.pow(10,f),d*=g,m=p.numDigits(d).integer);for(m-=1;0<=m&&!(h=Math.pow(10,m),f=Math.floor(d/
h)*h,h*=Math.ceil(d/h),null!=g&&(f/=g,h/=g),s=(f+h)/2,s=p.round([f,s,h],{indexes:[1]})[1],t=this._getSize(a,c,b,f,l),q=this._getSize(a,c,b,h,l),r=this._getSize(a,c,b,s,l),x=p.percentChange(k,t,e,null),y=p.percentChange(k,q,e,null),n=p.percentChange(k,r,e,null),u=20>=x.previous,v=20>=y.previous,u&&v&&(x.previous<=y.previous?(u=!0,v=!1):(v=!0,u=!1)),u?w=[f,t]:v?w=[h,q]:20>=n.previous&&(w=[s,r]),w);m--);return w},_getSizeAppliedCloneSymbol:function(a,c){a=a.clone();var b=a.type;if(-1<b.indexOf("3d"))r.isVolumetricSymbol(a)||
a.symbolLayers.forEach(function(a){"Fill"!==a.type&&(a.size=c)});else switch(b){case "simple-marker-symbol":a.size=c;break;case "picture-marker-symbol":var b=a.width,d=a.height;a.height=c;a.width=c*(b/d);break;case "simple-line-symbol":a.width=c;break;case "text-symbol":a.font&&(a.font.size=c)}return a},_getSize:function(a,c,b,d,e){return a.getSize(d,{sizeInfo:c,scale:e,shape:-1!==b.type.indexOf("marker-symbol")?b.style:null})}}});