// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require dojo/Deferred dojo/_base/lang dojox/gfx/_base ../../../core/sniff ../../../core/screenUtils ../../../core/promiseUtils ../../../core/Error ../../../core/Logger ../../../core/urlUtils ../../../symbols/support/symbolUtils ../../../symbols/support/gfxUtils ../../../request".split(" "),function(C,P,D,z,E,n,q,u,Q,R,S,T,U){var F=C.toUrl("esri/images/Legend/legend3dsymboldefault.png"),V=C.toUrl("esri/symbols/patterns/"),W=[{type:"path",path:"M -15,0 L 15,0 E"}],G=[{type:"path",path:"M -10,-10 L 10,0 L 10,10 L -10,10 L -10,-10 Z"}],
X=[{type:"path",path:"M -2,5 L 12,5 E"}],H=[{type:"path",path:"M 3,12 L 12,0 L 11,-2 L -4,5 L -1,5 L 1,7 L 3,10 L 3,12 Z"},{type:"circle",cx:-2,cy:10,r:5}],Y=[{type:"path",path:"M 0,-10 L -8,5 L -4,6.5 L 0,7 L 4,6.5 L 8,5 Z"}],I=[{type:"path",path:"M 0,7 L -8,-8 L 8,-8 Z"},{type:"path",path:"M -8,-8 L -4,-9.5 L 0,-10 L 4,-9.5 L 8,-8 L 4,-6.5 L 0,-6 L -4,-6.5 Z"}],A=[{type:"path",path:"M -10,-7 L 0,-12 L 10,-7 L 0,-2 L -10,-7 Z"},{type:"path",path:"M -10,-7 L 0,-2 L 0,12 L -10,7 L -10,-7 Z"},{type:"path",
path:"M 0,-2 L 10,-7 L 10,7 L 0,12 L 0,-2 Z"}],J=[{type:"path",path:"M -8,-9 L -8,7 L -4,8.5 L 0,9 L 4,8.5 L 8,7 L 8,-9 Z"},{type:"ellipse",cx:0,cy:-9,rx:8,ry:2}],v=[{type:"path",path:"M 0,-10 L 10,-1 L -1,1 L 0,-10 Z"},{type:"path",path:"M 0,-10 L -1,1 L -8,-1 L 0,-10 Z"},{type:"path",path:"M -1,1 L 0,10 L -8,-1 L -1,1 Z"},{type:"path",path:"M -1,0 L 0,10 L 10,-1 L -1,1 Z"}],B=[{type:"path",path:"M 0,-10 L 10,7 L 0,0 L 0,-10 Z"},{type:"path",path:"M 0,-10 L 0,0 L -8,7 L 0,-10 Z"},{type:"path",path:"M 10,7 L 0,0 L -8,7 L 10,7 Z"}],
Z=Q.getLogger("esri.widgets.Legend.support.swatchUtils"),K=function(a){var c=null;if(a){var b=a.constructor,d=n.pt2px(a.width);switch(a.type){case "simple-fill-symbol":case "picture-fill-symbol":case "simple-marker-symbol":c=K(a.outline);break;case "simple-line-symbol":a.style!==b.STYLE_NULL&&0!==d&&(c={color:a.color,style:$(a.style),width:Math.min(d,80),cap:a.cap,join:a.join===b.JOIN_MITER?n.pt2px(a.miterLimit):a.join});break;default:c=null}}return c},$=function(){var a={};return function(c){if(a[c])return a[c];
var b=c.replace(/-/g,"");return a[c]=b}}(),da=function(a,c){if(0===a.symbolLayers.length)return q.reject(new u("swatchUtils: swatchInfo3D","No symbolLayers in the symbol."));var b=null;switch(a.type){case "point-symbol-3d":b=aa(a,c);break;case "line-symbol-3d":b=ba(a,c);break;case "polygon-symbol-3d":case "mesh-symbol-3d":b=ca(a,c)}return b?b.then(function(a){return a&&null!=a.swatch&&a.swatch.length?a:null}):q.reject(new u("swatchUtils: swatchInfo3D","symbol not supported."))},L=document.createElement("canvas"),
M=document.createElement("canvas"),N=function(a,c,b){c=Math.ceil(c);b=Math.ceil(b);a.width=c;a.height=b;a.style.width=c+"px";a.style.height=b+"px";a=a.getContext("2d");a.clearRect(0,0,c,b);return a},ea=function(a,c,b){return O(a,c,b?!0:!1).then(function(d){var e=d.size,g=e?e.width:c,e=e?e.height:c;if(d.image&&b){var f=N(L,g,e),l=d.image.width,k=d.image.height;if((E("edge")||E("ie"))&&/\.svg$/i.test(a))l-=1,k-=1;f.drawImage(d.image,0,0,l,k,0,0,g,e);f.globalCompositeOperation="source-atop";f.rect(0,
0,g,e);f.fillStyle=b.toCss();f.fill();f=N(M,g,e);f.drawImage(d.image,0,0,l,k,0,0,g,e);f.globalCompositeOperation="multiply";f.drawImage(L,0,0);a=M.toDataURL("image/png")}return{url:a,width:g,height:e}}).otherwise(function(){return{url:a,width:c,height:c}})},fa=function(a,c){var b=c&&c.resource;return(b=b&&b.href)&&"Object"!==c.type?q.resolve(b):a.thumbnail&&a.thumbnail.url?q.resolve(a.thumbnail.url):a.styleOrigin&&(a.styleOrigin.styleName||a.styleOrigin.styleUrl)?S.fetchStyleSymbol(a.styleOrigin,
{portal:a.styleOrigin.portal}).always(function(a){return a&&a.thumbnail&&a.thumbnail.url||F}):q.resolve(F)},aa=function(a,c){var b=[],d=0,e=0;a.symbolLayers.forEach(function(g){var f=g&&g.type,l="Icon"===f;if(l||"Object"===f){var k=(f=s(g))?f.width:0;if(g&&g.resource&&g.resource.href)l=fa(a,g).then(function(a){return ea(a,c||g.size,g.get("material.color"))}).then(function(a){var b=a.width,c=a.height;d=Math.max(d,b+2*k);e=Math.max(e,c+2*k);return[{shape:{type:"image",width:b,height:c,src:a.url}}]}),
b.unshift(l);else{var f=c||g.size?Math.ceil(Math.min(n.pt2px(c||g.size),120)):22,h=g.get("resource.primitive");h||(h=l?"circle":"sphere");d=Math.max(d,f+2*k);e=Math.max(e,f+2*k);b.unshift(q.resolve(ga(g,h,f)))}}});return q.eachAlways(b).then(function(a){var b=[];a.forEach(function(a){a.value?b.push(a.value):a.error&&Z.warn("error while building swatchInfo!",a.error)});return{swatch:b,sizes:[d,e]}})},ba=function(a,c){var b=[],d=0,e=0;a.symbolLayers.forEach(function(a){var f=a&&a.type,l="Line"===f;
if(l||"Path"===f){var k=w(a,0),f=[];l?(f.push({shape:X[0],stroke:k}),e=Math.max(e,k&&k.width||0),d=22):(c=c&&n.pt2px(c)||22,l=h(a,0),k=h(a,-0.2),a=w(a,-0.4),a.width=1,f.push({shape:H[0],fill:k,stroke:a}),f.push({shape:H[1],fill:l,stroke:a}),d=e=Math.max(e,c+1));b.push(f)}});return q.resolve({swatch:b,sizes:[d,e]})},ca=function(a,c){var b="mesh-symbol-3d"===a.type,d=a.symbolLayers,e=[],g=0,f=0;c=c&&n.pt2px(c)||22;d.forEach(function(a){var d=a.type,r="Fill"===d,m="Line"===d,n="Extrude"===a.type,d=[];
if(!b||r){var p=G[0];r?(m=(r=s(a))&&r.width||0,g=Math.max(g,c+m),f=Math.max(f,c+m),d.push({shape:p,fill:h(a,0),stroke:r})):m?(a=(r=w(a,0))&&r.width||0,p={stroke:r,shape:p},g=Math.max(g,22+a),f=Math.max(f,22+a),d.push(p)):n&&(p=w(a,-0.4),r=h(a,0),a=h(a,-0.2),m=0.5*c,m=[{type:"path",path:"M -7,-5 L -2,0 L -2,"+m+" L -7,"+(m-4)+" L -7,-5 Z"},{type:"path",path:"M -2,0 L -2,"+m+" L 10,"+(m-10)+" L 10,-10 L -2,0 Z"},{type:"path",path:"M -7,-5 L -2,0 L 10,-10 L -2,-10 L -7,-5 Z"}],p.width=1,d.push({shape:m[0],
fill:a,stroke:p}),d.push({shape:m[1],fill:a,stroke:p}),d.push({shape:m[2],fill:r,stroke:p}),a=10+0.5*c,g=Math.max(g,17+p.width),f=Math.max(f,a+p.width));e.push(d)}});return q.resolve({swatch:e,sizes:[g,f]})},ga=function(a,c,b){var d=[];b*=0.5;var e=-b,g=+b,f=-b,l=+b;switch(c){case "circle":d.push({shape:{type:"circle",cx:0,cy:0,r:b},fill:h(a,0),stroke:s(a)});break;case "square":d.push({shape:{type:"path",path:"M "+e+","+l+" L "+e+","+f+" L "+g+","+f+" L "+g+","+l+" L "+e+","+l+" Z"},fill:h(a,0),stroke:s(a)});
break;case "cross":d.push({shape:{type:"path",path:"M "+e+",0 L "+g+",0 E"},stroke:x(a)});d.push({shape:{type:"path",path:"M 0,"+f+" L 0,"+l+" E"},stroke:x(a)});break;case "x":d.push({shape:{type:"path",path:"M "+e+","+l+" L "+g+","+f+" E"},stroke:x(a)});d.push({shape:{type:"path",path:"M "+e+","+f+" L "+g+","+l+" E"},stroke:x(a)});break;case "kite":d.push({shape:{type:"path",path:"M 0,"+f+" L "+g+",0 L 0,"+l+" L "+e+",0 L 0,"+e+" Z"},fill:h(a,0),stroke:s(a)});break;case "cone":c=h(a,0);e=h(a,-0.6);
b=y(c,e);b.x1=-5;b.y1=0;b.x2=5;b.y2=0;d.push({shape:Y[0],fill:b});break;case "inverted-cone":c=h(a,0);e=h(a,-0.6);b=y(c,e);b.x1=-5;b.y1=0;b.x2=5;b.y2=0;d.push({shape:I[0],fill:b});d.push({shape:I[1],fill:c});break;case "cube":d.push({shape:A[0],fill:h(a,0)});d.push({shape:A[1],fill:h(a,-0.3)});d.push({shape:A[2],fill:h(a,-0.5)});break;case "cylinder":c=h(a,0);e=h(a,-0.6);b=y(c,e);b.x1=-5;b.y1=0;b.x2=5;b.y2=0;d.push({shape:J[0],fill:b});d.push({shape:J[1],fill:h(a,0)});break;case "diamond":d.push({shape:v[0],
fill:h(a,-0.3)});d.push({shape:v[1],fill:h(a,0)});d.push({shape:v[2],fill:h(a,-0.3)});d.push({shape:v[3],fill:h(a,-0.7)});break;case "sphere":c=h(a,0);e=h(a,-0.6);d.push({shape:{type:"circle",cx:0,cy:0,r:b},fill:y(c,e)});break;case "tetrahedron":d.push({shape:B[0],fill:h(a,-0.3)}),d.push({shape:B[1],fill:h(a,0)}),d.push({shape:B[2],fill:h(a,-0.6)})}return d},w=function(a,c){if(!a.material)return{};for(var b=a.material.color.toRgb(),d="rgba(",e=0;3>e;e++)d+=Math.min(Math.max(b[e]+191.25*c,0),255)+
",";d+=a.material.color.a+");";b=a.size?n.pt2px(a.size):0.75;return{color:d,width:Math.min(b,80)}},h=function(a,c){if(!a.material||!a.material.color){var b=Math.min(Math.max(T.defaultThematicColor.r+191.25*c,0),255);return[b,b,b,100]}for(var b=a.material.color.toRgb(),d=0;3>d;d++)b[d]=Math.min(Math.max(b[d]+191.25*c,0),255);b.push(a.material.color.a);return b},x=function(a){return!a.outline?{color:"rgba(0,0,0,1)",width:1.5}:s(a)},s=function(a){var c=a.outline,b=a.material&&a.material.color,b=b&&b.toRgba().toString();
if(!c)return"Fill"===a.type&&"255,255,255,1"===b?{color:"#bdc3c7",width:0.75}:null;a=n.pt2px(c.size)||0;return{color:"rgba("+(null!=c.color?c.color.toRgba():"255,255,255,1")+")",width:Math.min(a,80)}},y=function(a,c){return{type:"linear",x1:0,y1:0,x2:4,y2:4,colors:[{color:a,offset:0},{color:c,offset:1}]}},O=function(a,c,b){if(!a)return q.reject(new u("swatchUtils: imageDataSize","href not provided."));var d;if(R.isDataProtocol(a)){var e=new Image;e.src=a;if(e.complete)d=q.resolve({data:e});else{var g=
new P;d=g.promise;e.onload=function(){g.resolve({data:e})};e.onerror=g.reject}}else b||(a+=(-1===a.indexOf("?")?"?":"\x26")+"legend\x3d1"),d=U(a,{responseType:"image",allowImageDataAccess:b});return d.then(function(a){a=a.data;var d=a.width,e=a.height,g=d/e,h={},q;"object"===typeof c&&c.maxSize?(q=n.pt2px(c.maxSize),c=Math.max(d,e)):(q=120,c=c?n.pt2px(c):22);c=Math.min(c,q);1>=g?(h.height=c,h.width=Math.ceil(h.height*g)):(h.width=c,h.height=Math.ceil(h.width/g));return{image:b?a:null,size:h}}).otherwise(function(d){if(b)return O(a,
c,!1);throw d;})};return{getSwatchInfo:function(a,c){var b;if(-1===a.type.indexOf("3d")){var d=K(a);b=null;var e=a.style;if(a){var g=a.constructor;switch(a.type){case "simple-marker-symbol":e!==g.STYLE_CROSS&&e!==g.STYLE_X&&(b=a.color);break;case "simple-fill-symbol":e===g.STYLE_SOLID?b=a.color:e!==g.STYLE_NULL&&(b=D.mixin({},z.defaultPattern,{src:V+e+".png",width:10,height:10}));break;case "picture-fill-symbol":b=D.mixin({},z.defaultPattern,{src:a.url,width:n.pt2px(a.width)*a.xscale,height:n.pt2px(a.height)*
a.yscale,x:n.pt2px(a.xoffset),y:n.pt2px(a.yoffset)});break;case "text-symbol":b=a.color}}b={fill:b,stroke:d};var f=a.constructor,h=f.defaultProps,e=null,d=d?d.width:0,k=g=0;switch(a.type){case "simple-marker-symbol":var r=a.style,k=Math.min(n.pt2px(a.size||h.size),120),h=0.5*k,m=-h,s=+h,p=-h,t=+h,g=k;switch(r){case f.STYLE_CIRCLE:e={type:"circle",cx:0,cy:0,r:h};break;case f.STYLE_CROSS:e={type:"path",path:"M "+m+",0 L "+s+",0 M 0,"+p+" L 0,"+t+" E"};break;case f.STYLE_DIAMOND:e={type:"path",path:"M "+
m+",0 L 0,"+p+" L "+s+",0 L 0,"+t+" L "+m+",0 Z"};break;case f.STYLE_SQUARE:e={type:"path",path:"M "+m+","+t+" L "+m+","+p+" L "+s+","+p+" L "+s+","+t+" L "+m+","+t+" Z"};break;case f.STYLE_X:e={type:"path",path:"M "+m+","+t+" L "+s+","+p+" M "+m+","+p+" L "+s+","+t+" E"};break;case f.STYLE_PATH:e={type:"path",path:a.path||""}}break;case "simple-line-symbol":e=W[0];k=Math.max(d,22);d=0;break;case "picture-fill-symbol":case "simple-fill-symbol":e=G[0];break;case "picture-marker-symbol":g=Math.min(n.pt2px(a.width),
120);f=Math.min(n.pt2px(a.height),120);e={type:"image",x:-Math.round(g/2),y:-Math.round(f/2),width:g,height:f,src:a.source&&a.source.imageData?"data:"+a.source.contentType+";base64,"+a.source.imageData:a.url||""};k=f;break;case "text-symbol":f=a.font,k=g=r=Math.min(n.pt2px(f.size),120),e={type:"text",text:a.text,x:0,y:0.25*z.normalizedLength(f?r:0),align:"middle",decoration:a.decoration||f&&f.decoration,rotated:a.rotated,kerning:a.kerning},b.font=f&&{size:r,style:f.style,variant:f.variant,decoration:f.decoration,
weight:f.weight,family:f.family}}e?(b.shape=e,b=q.resolve({swatch:[[b]],sizes:[(g||22)+d,(k||22)+d]})):b=q.reject(new u("swatchUtils: swatchInfo2D","symbol not supported."))}else b=da(a,c);return b},isVolumetricSymbol:function(a){a=a&&a.symbolLayers;return!a?!1:a.some(function(a){a=a&&a.type;return"Object"===a||"Path"===a||"Extrude"===a})}}});