// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["require","exports","./StyleDefinition","./StyleProperty","./Filter"],function(f,h,g,k,l){f=function(){function a(b,a,c){this.type=b;this.id=a.id;this.source=a.source;this.sourceLayer=a["source-layer"];this.minzoom=a.minzoom;this.maxzoom=a.maxzoom;this.filter=a.filter;this.layout=a.layout;this.paint=a.paint;this.z=c;switch(b){case 0:this._layoutDefinition=g.StyleDefinition.backgroundLayoutDefinition;this._paintDefinition=g.StyleDefinition.backgroundPaintDefinition;break;case 1:this._layoutDefinition=
g.StyleDefinition.fillLayoutDefinition;this._paintDefinition=g.StyleDefinition.fillPaintDefinition;break;case 2:this._layoutDefinition=g.StyleDefinition.lineLayoutDefinition;this._paintDefinition=g.StyleDefinition.linePaintDefinition;break;case 3:this._layoutDefinition=g.StyleDefinition.symbolLayoutDefinition,this._paintDefinition=g.StyleDefinition.symbolPaintDefinition}this._layoutProperties=this._parseLayout(this.layout);this._paintProperties=this._parsePaint(this.paint)}a.prototype.getFeatureFilter=
function(){return void 0!==this._featureFilter?this._featureFilter:this._featureFilter=l.createFilter(this.filter)};a.prototype.hasLayoutProperty=function(a){var d=this._layoutProperties;return d&&d[a]?!0:!1};a.prototype.hasPaintProperty=function(a){var d=this._paintProperties;return d?void 0!==d[a]:!1};a.prototype.getLayoutValue=function(a,d){var c,e=this._layoutProperties;e&&(e=e[a])&&(c=e.getValue(d));e=this._layoutDefinition[a];void 0===c&&(c=e["default"]);"enum"===e.type&&(c=e.values.indexOf(c));
return c};a.prototype.getPaintValue=function(a,d){var c,e=this._paintProperties;e&&(e=e[a])&&(c=e.getValue(d));e=this._paintDefinition[a];void 0===c&&(c=e["default"]);"enum"===e.type&&(c=e.values.indexOf(c));return c};a.prototype._parseLayout=function(a){var d={},c;for(c in a)d[c]=new k(this._layoutDefinition[c],a[c]);return d};a.prototype._parsePaint=function(a){var d={},c;for(c in a)d[c]=new k(this._paintDefinition[c],a[c]);return d};return a}();h.StyleLayer=f;f=function(){return function(a,b){this.cap=
a.getLayoutValue("line-cap",b);this.join=a.getLayoutValue("line-join",b);this.miterLimit=a.getLayoutValue("line-miter-limit",b);this.roundLimit=a.getLayoutValue("line-round-limit",b)}}();h.LineLayout=f;f=function(){return function(a,b,d){this.allowOverlap=a.getLayoutValue("icon-allow-overlap",b);this.ignorePlacement=a.getLayoutValue("icon-ignore-placement",b);this.optional=a.getLayoutValue("icon-optional",b);this.rotationAlignment=a.getLayoutValue("icon-rotation-alignment",b);this.size=a.getLayoutValue("icon-size",
b);this.rotate=a.getLayoutValue("icon-rotate",b);this.padding=a.getLayoutValue("icon-padding",b);this.keepUpright=a.getLayoutValue("icon-keep-upright",b);this.offset=a.getLayoutValue("icon-offset",b);d&&(1===this.rotationAlignment&&!a.hasLayoutProperty("icon-rotation-alignment"))&&(this.rotationAlignment=0)}}();h.IconLayout=f;f=function(){return function(a,b,d){this.allowOverlap=a.getLayoutValue("text-allow-overlap",b);this.ignorePlacement=a.getLayoutValue("text-ignore-placement",b);this.optional=
a.getLayoutValue("text-optional",b);this.rotationAlignment=a.getLayoutValue("text-rotation-alignment",b);this.font=a.getLayoutValue("text-font",b);this.maxWidth=a.getLayoutValue("text-max-width",b);this.lineHeight=a.getLayoutValue("text-line-height",b);this.letterSpacing=a.getLayoutValue("text-letter-spacing",b);this.justify=a.getLayoutValue("text-justify",b);this.anchor=a.getLayoutValue("text-anchor",b);this.maxAngle=a.getLayoutValue("text-max-angle",b);this.size=a.getLayoutValue("text-size",b);
this.rotate=a.getLayoutValue("text-rotate",b);this.padding=a.getLayoutValue("text-padding",b);this.keepUpright=a.getLayoutValue("text-keep-upright",b);this.transform=a.getLayoutValue("text-transform",b);this.offset=a.getLayoutValue("text-offset",b);d&&(1===this.rotationAlignment&&!a.hasLayoutProperty("text-rotation-alignment"))&&(this.rotationAlignment=0)}}();h.TextLayout=f});