// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require ../core/declare ../core/promiseUtils dojo/_base/array dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/support/scaleUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessoire".split(" "),function(H,I,w,h,D,y,J,E,F,K,L,G,M){var z;return I(M,{declaredClass:"esri.views.PopupManager",classMetadata:{properties:{map:{dependsOn:["view.map"],readOnly:!0}}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache=
{};this.view=null},_clickHandle:null,_featureLayersCache:null,enabled:!1,_enabledSetter:function(a){this._clickHandle&&(a?this._clickHandle.resume():this._clickHandle.pause());return a},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(a){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);a&&(this._clickHandle=D.pausable(a,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());return a},getMapLayer:function(a){var c;
if(a&&(c=a.findLayerById()))if(a=c.id,this._featureLayersCache[a]){var g=a.lastIndexOf("_");-1<g&&(a=a.substring(0,g),c=this.map.findLayerById(a))}return c},_showPopup:function(a){function c(){p.clear();p.close()}function g(b){return k.allLayerViews.find(function(a){return a.layer===b})}function e(b){if(null==b)return!1;var a=g(b);return null==a?!1:b.loaded&&!a.suspended&&(b.popupEnabled&&b.popupTemplate||"graphics"===b.type||a.getPopupData)}function A(b){return(b=g(b))&&b.hasDraped}var k=this.view,
p=k.popup,q=this,r=[],v="3d"===k.type;h.forEach(this.map.layers.toArray(),function(b){b.isInstanceOf(G)?h.forEach(b.layers.toArray(),function(b){e(b)&&(!v||A(b))&&r.push(b)}):e(b)&&(!v||A(b))&&r.push(b)});0<k.graphics.length&&r.push(k.graphics);var d=null;if(a.graphic&&(a.graphic.popupTemplate||e(a.graphic.layer)))d=a.graphic;if(!r.length&&!d)c();else{var f=[],n=!!d;if(d)if(d.layer&&"scene"===d.layer.type)f.unshift(this._fetchSceneAttributes(d.layer,[d]));else{if(d.getEffectivePopupTemplate()){var m=
new y;f.unshift(m.resolve([d]))}}else{m=q._calculateClickTolerance(r);d=a.mapPoint;if(!d){c();return}var x=1;k.state&&(x=k.state.resolution);(f=k.basemapTerrain)&&f.overlayManager&&(x=f.overlayManager.overlayPixelSizeInMapUnits(d));m*=x;f&&!f.spatialReference.equals(k.spatialReference)&&(m*=F.getUnitValueForSR(f.spatialReference)/F.getUnitValueForSR(k.spatialReference));var f=d.clone().offset(-m,-m),d=d.clone().offset(m,m),s=new K(Math.min(f.x,d.x),Math.min(f.y,d.y),Math.max(f.x,d.x),Math.max(f.y,
d.y),k.spatialReference),f=r.map(function(b){var d;if("imagery"===b.type){d=new L;d.geometry=a.mapPoint;var c=g(b),e={rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0};e.layerView=c;d=b.queryVisibleRasters(d,e).then(function(b){n=n||0<b.length;return b})}else if("csv"!==b.type&&(q._featureLayersCache[b.id]||"function"===typeof b.queryFeatures&&(0===b.mode||1===b.mode)))c=b.createQuery(),c.geometry=s,d=b.queryFeatures(c).then(function(b){b=b.features;n=n||0<b.length;return b});else{if("map-image"===
b.type)return c=g(b),c.getPopupData(s);var e=[],f;"esri.core.Collection\x3cesri.Graphic\x3e"===b.declaredClass?(c=b,f=!0):"graphics"===b.type?(c=b.graphics,f=!0):(c=(c=g(b))&&c.loadedGraphics,f=!1);c&&(e=c.filter(function(b){return b&&(!f||b.popupTemplate)&&b.visible&&s.intersects(b.geometry)}).toArray());0<e.length&&(n=!0,d="scene"===b.type?q._fetchSceneAttributes(b,e):w.resolve(e))}return d}).filter(function(b){return!!b}),t=function(b){return b.reduce(function(b,a){return b.concat(a.items?t(a.items):
a)},[])},f=t(f)}!h.some(f,function(b){return!b.isFulfilled()})&&!n?c():f.length&&p.open({promises:f,location:a.mapPoint})}},_fetchSceneAttributes:function(a,c){return this.view.whenLayerView(a).then(function(g){var e=this._getOutFields(a.popupTemplate),h=c.map(function(a){return g.whenGraphicAttributes(a,e).otherwise(function(){return a})});return w.eachAlways(h)}.bind(this)).then(function(a){return a.map(function(a){return a.value})})},_getSubLayerFeatureLayers:function(a,c){var g=c||new y,e=[],
A=a.length,k=Math.floor(this.view.extent.width/this.view.width),p=this.view.scale,q=!1,r=this,v=0;a:for(;v<A;v++){var d=a[v],f=d.dynamicLayerInfos||d.layerInfos;if(f){var n=null;if(d._params&&(d._params.layers||d._params.dynamicLayers))n=d.visibleLayers;for(var n=E._getVisibleLayers(f,n),m=E._getLayersForScale(p,f),x=f.length,s=0;s<x;s++){var t=f[s],b=t.id,u=d.popupTemplates[b];if(!t.subLayerIds&&u&&u.popupTemplate&&-1<h.indexOf(n,b)&&-1<h.indexOf(m,b)){if(!z){q=!0;break a}var B=d.id+"_"+b,l=this._featureLayersCache[B];
if(!l||!l.loadError)l||((l=u.layerUrl)||(l=t.source?this._getLayerUrl(d.url,"/dynamicLayer"):this._getLayerUrl(d.url,b)),l=new z(l,{id:B,drawMode:!1,mode:z.MODE_SELECTION,outFields:this._getOutFields(u.popupTemplate),resourceInfo:u.resourceInfo,source:t.source}),this._featureLayersCache[B]=l),l.setDefinitionExpression(d.layerDefinitions&&d.layerDefinitions[b]),l.setGDBVersion(d.gdbVersion),l.popupTemplate=u.popupTemplate,l.setMaxAllowableOffset(k),l.setUseMapTime(!!d.useMapTime),d.layerDrawingOptions&&
(d.layerDrawingOptions[b]&&d.layerDrawingOptions[b].renderer)&&l.setRenderer(d.layerDrawingOptions[b].renderer),e.push(l)}}}}if(q){var w=new y;H(["../layers/FeatureLayer"],function(b){z=b;w.resolve()});w.then(function(){r._getSubLayerFeatureLayers(a,g)})}else{var C=[];h.forEach(e,function(b){if(!b.loaded){var a=new y;D.once(b,"load, error",function(){a.resolve()});C.push(a.promise)}});C.length?J(C).then(function(){e=h.filter(e,function(b){return!b.loadError&&b.isVisibleAtScale(p)});g.resolve(e)}):
(e=h.filter(e,function(b){return b.isVisibleAtScale(p)}),g.resolve(e))}return g.promise},_getLayerUrl:function(a,c){var g=a.indexOf("?");return-1===g?a+"/"+c:a.substring(0,g)+"/"+c+a.substring(g)},_getOutFields:function(a){var c;"esri.PopupTemplate"===a.declaredClass&&a.fieldInfos?(c=[],h.forEach(a.fieldInfos,function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==e&&0!==e.indexOf("relationships/"))&&c.push(a.fieldName)})):c=["*"];return c},_calculateClickTolerance:function(a){var c=
6;h.forEach(a,function(a){if(a=a.renderer)"esri.renderer.SimpleRenderer"===a.declaredClass?((a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset))),a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))):("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)&&h.forEach(a.infos,function(a){(a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset)));a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))})});return c},_clickHandler:function(a){function c(a){return g.allLayerViews.find(function(c){return c.layer===
a})}var g=this.view,e=g.map,h=a.screenPoint,k=this;if(g.popup&&g.ready){var p="3d"===g.type,q=e.allLayers.some(function(a){if(a.isInstanceOf(G))return!1;var e;null==a?e=!1:(e=c(a),e=null==e?!1:a.loaded&&!e.suspended&&(a.popupEnabled&&a.popupTemplate||"graphics"===a.type||e.getPopupData));if(e&&!(e=!p))e=(a=c(a))&&a.hasDraped;return e?!0:!1});null!=h?this.view.hitTest(h.x,h.y).then(function(c){0<c.results.length?k._showPopup(c.results[0]):q&&k._showPopup(a)}):k._showPopup(a)}}})});