// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../../layers/LayerView ../../../geometry/Extent ../../../core/urlUtils ../../../core/promiseUtils ../../../core/HandleRegistry ../../../layers/support/ExportImageParameters ./support/projectExtentUtils ../lib/glMatrix ../webgl-engine/Stage ../webgl-engine/lib/Texture ../webgl-engine/lib/RenderGeometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/GeometryUtil ../webgl-engine/materials/Material ../webgl-engine/lib/Util".split(" "),function(q,z,r,A,B,C,D,E,h,F,G,H,I,J,k){var s=k.assert,
K=E.mat4d,l=k.VertexAttrConstants;q=q.createSubclass({declaredClass:"esri.views.3d.layers.DynamicLayerView3D",supportsDraping:!0,hasDraped:!0,drawingOrder:0,_updatingOverlay:!1,_handles:null,_exportImageParameters:null,_imageVersion:null,constructor:function(){this._extents=[];this._images=[];this.fullExtentInViewSpatialReference=null;this._handles=new B},initialize:function(){this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._handles.add(this.watch("suspended",function(a){if(a)this.clear(),
this.emit("draped-data-change");else{a=this._extents.length;for(var c=0;c<a;c++)this.fetch(c)}}.bind(this)));this._exportImageParameters=new C({layer:this.layer});var a=this.notifyChange.bind(this,"suspended");this._handles.add([this.watch("fullOpacity",this._opacityChangeHandler.bind(this)),this.layer.watch("minScale",a),this.layer.watch("maxScale",a),this._exportImageParameters.watch("version",function(a){this._imageVersion!==a&&(this._imageVersion=a,this._refetch())}.bind(this))],"layer");this.view.resourceController.registerIdleFrameWorker(this,
{idleBegin:function(){this._hasScaleRange()&&this.notifyChange("suspended")}});(a=D.toView(this).then(function(a){this.fullExtentInViewSpatialReference=a}.bind(this)))&&this.addResolvingPromise(a)},destroy:function(){this.clear();this._handles.destroy();this.view.resourceController.deregisterIdleFrameWorker(this);this._exportImageParameters&&(this._exportImageParameters.layer=null,this._exportImageParameters.destroy(),this._exportImageParameters=null)},getPopupData:function(a){var b=this.view.scale;
return this.layer.allSublayers.filter(function(a){var e=0===a.minScale||b<=a.minScale,d=0===a.maxScale||b>=a.maxScale;return a.popupTemplate&&a.visible&&e&&d}).map(function(c){var b=c.createQuery();b.geometry=a;b.outFields=this.getTemplateOutFields(c.popupTemplate);return c.queryFeatures(b).then(function(a){return a.features})},this)},getTemplateOutFields:function(a){if(!a||!a.fieldInfos)return["*"];var b=[];a.fieldInfos.forEach(function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==
e&&0!==e.indexOf("relationships/"))&&b.push(a.fieldName)});return b},setDrapingExtent:function(a,b,c,e){var d=(b[2]-b[0])/(b[3]-b[1]);this._extents[a]={extent:b,spatialReference:c,imageSize:1.0001<d?[e,e/d]:0.9999>d?[e*d,e]:[e,e]};this.suspended||this.fetch(a)},fetch:function(a){var b=this._extents[a],c=b.extent,e=new z(c[0],c[1],c[2],c[3],b.spatialReference);this._exportImageParameters.scale!==this.view.scale&&(this._exportImageParameters.scale=this.view.scale);this._imageVersion=this._exportImageParameters.version;
this._images[a]||(this._images[a]={texture:null,material:null,rendergeometry:null,domImage:null,domImageCancelled:!1,worldExtent:c,loading:!1});var d=this._images[a];d.loading=!0;d.imageUrlPromise&&d.imageUrlPromise.cancel();d.domImageCancelled=!0;var f={extent:e,width:b.imageSize[0],height:b.imageSize[1]};d.imageUrlPromise=A.wrapCallback(function(a){this.layer.getImageUrl(f,a)}.bind(this));d.imageUrlPromise.then(function(b){d.imageUrlPromise=null;d.domImage||(d.domImage=new Image);var e=d.domImage;
0!==b.indexOf("data:")&&r.canUseXhr(b)&&(e.crossOrigin="anonymous");e.src=r.normalize(b);d.domImageCancelled=!1;e.onload=function(){d.domImageCancelled||(d.worldExtent=c,this._createStageObjects(a,e),0===a&&(this._images[1]&&this._images[1].rendergeometry)&&this._createStageObjects(1,null),d.loading=!1,this._evaluateUpdatingState(),this.emit("draped-data-change"))}.bind(this);e.onerror=function(){d.domImageCancelled||(d.loading=!1,this._clearDomImage(d),this._evaluateUpdatingState())}.bind(this);
this._evaluateUpdatingState()}.bind(this))},clear:function(){for(var a in this._images)this.clearImage(a)},clearImage:function(a){if(a=this._images[a])a.rendergeometry&&(this.view._stage.getTextureGraphicsRenderer().removeRenderGeometries([a.rendergeometry]),a.rendergeometry=null),a.texture&&(this.view._stage.remove(h.ModelContentType.TEXTURE,a.texture.getId()),a.texture=null),a.material&&(this.view._stage.remove(h.ModelContentType.MATERIAL,a.material.getId()),a.material=null),this._clearDomImage(a),
a.loading=!1},canResume:function(){if(!this.inherited(arguments))return!1;var a=this.layer.minScale,b=this.layer.maxScale;if(0<a||0<b){var c=this.view.scale;if(c<b||0<a&&c>a)return!1}return!0},_refetch:function(){for(var a=0;a<this._extents.length;a++)this._extents[a]&&this.fetch(a)},_drawingOrderSetter:function(a,b){if(a!==b){var c={};this._images.forEach(function(b){b&&b.material&&(b.material.setRenderPriority(a),c[b.material.getId()]=!0)});k.objectEmpty(c)||(this.view._stage.getTextureGraphicsRenderer().updateRenderOrder(c),
this.emit("draped-data-change"))}return a},_hasScaleRange:function(){return 0<this.get("layer.minScale")||0<this.get("layer.maxScale")},_opacityChangeHandler:function(a){this._images.forEach(function(b){b&&b.material&&b.material.setParameterValues({opacity:a})}.bind(this));this.emit("draped-data-change")},_clearDomImage:function(a){a.domImage&&(a.domImage.removeAttribute("src"),a.domImage.removeAttribute("onload"),a.domImage.removeAttribute("onerror"),a.domImage=null)},_evaluateUpdatingState:function(){this.notifyChange("updating")},
isUpdating:function(){if(this._updatingOverlay)return!0;var a=!1,b;for(b in this._images)if(this._images[b].loading){a=!0;break}return a},_createStageObjects:function(a,b){var c=this.view._stage,e=c.getTextureGraphicsRenderer(),d=this._images[a];b?(d.texture&&c.remove(h.ModelContentType.TEXTURE,d.texture.getId()),d.texture=new F(b,"dynamicMapLayer",{width:b.width,height:b.height}),c.add(h.ModelContentType.TEXTURE,d.texture)):s(d.texture);d.material?b&&d.material.setParameterValues({textureId:d.texture.getId()}):
(d.material=new J({ambient:[1,1,1],diffuse:[0,0,0],transparent:!0,opacity:this.fullOpacity,textureId:d.texture.getId(),receiveSSAO:!1},"dynamicMapLayer"),d.material.setRenderPriority(this.drawingOrder),c.add(h.ModelContentType.MATERIAL,d.material));if(0===a)c=d.worldExtent,c=I.createSquareGeometry([[c[0],c[1],-1],[c[2],c[1],-1],[c[2],c[3],-1],[c[0],c[3],-1]],!0);else{s(1===a);c=this._images[0].worldExtent;if(!c)return;c=L(c,d.worldExtent,-1)}var f=new G(c);f.material=d.material;f.origin={vec3:[0,
0,0],id:"0_0"};f.transformation=K.identity();f.name="dynamicMapLayer";f.uniqueName="dynamicMapLayer#"+c.id;e.addRenderGeometries([f]);d.rendergeometry&&e.removeRenderGeometries([d.rendergeometry]);d.rendergeometry=f}});var L=function(){var a=new Float32Array([0,0,1]);return function(b,c,e){var d=[b[1]-c[1],b[3]-b[1],c[3]-b[3],123456],f=[b[0]-c[0],b[2]-b[0],c[2]-b[2],123456],h=c[2]-c[0],q=c[3]-c[1],t=0<f[0]&&0<f[2]?3:2;b=0<d[0]&&0<d[2]?3:2;var n=(b+1)*(t+1),g=new Float32Array(3*n),n=new Float32Array(2*
n);b=new Uint32Array(6*(b*t-1));for(var w=0,k=0,r=0,m=0,p=0,u=0;4>u;u++){var s=d[u];if(!(0>=s)){for(var x=0,v=0;4>v;v++){var y=f[v];0>=y||(g[k++]=c[0]+x,g[k++]=c[1]+w,g[k++]=e,n[r++]=x/h,n[r++]=w/q,3>v&&(3>u&&!(1===v&&1===u))&&(b[p++]=m,b[p++]=m+1,b[p++]=m+t+1,b[p++]=m+1,b[p++]=m+t+2,b[p++]=m+t+1),m++,x+=y)}w+=s}}c={};c[l.POSITION]={size:3,data:g};c[l.NORMAL]={size:3,data:a};c[l.UV0]={size:2,data:n};e={};d=new Uint32Array(b.length);for(g=0;g<d.length;g++)d[g]=0;e[l.POSITION]=b;e[l.NORMAL]=d;e[l.UV0]=
b;return{faces:{type:"triangle",indices:e,positionKey:l.POSITION},vertexAttr:c,id:H.getNewId().toString()}}}();return q});