// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators dojo/promise/all ./graphics/Graphics3DLayerViewCore ./graphics/graphicUtils ./support/LayerViewUpdatingPercentage ../../layers/LayerView ../../../layers/FeatureLayer ../../../renderers/support/renderingInfoUtils ../../../layers/graphics/controllers/SnapshotController ../support/PromiseLightweight ../../../core/watchUtils ./support/projectExtentUtils ../../../core/Error ../../../core/promiseUtils ../../../layers/graphics/QueryEngine".split(" "),
function(A,B,m,f,d,n,p,q,r,s,t,u,v,w,x,y,g,h,z){return function(l){function a(){l.call(this);this.controller=null;this.supportsDraping=!0;this._overlayUpdating=null;this._progressMaxNumNodes=0;this._eventHandles=[];this._controllerClientSideFiltering=!1;this.fullExtentInViewSpatialReference=this._suspendResumeExtent=null;this._isUpdating=!1}m(a,l);Object.defineProperty(a.prototype,"drawingOrder",{set:function(b){this.layerViewCore.graphicsCore.setDrawingOrder(b);this._set("drawingOrder",b)},enumerable:!0,
configurable:!0});Object.defineProperty(a.prototype,"hasDraped",{get:function(){return this.layerViewCore.graphicsCore.hasDraped},enumerable:!0,configurable:!0});a.prototype.initialize=function(){var b=this;this.layerViewCore=new p({owner:this,layer:this.layer,spatialIndexRequired:!0,frustumVisibilityEnabled:!0,scaleVisibilityEnabled:!0,labelingEnabled:this.layer.isInstanceOf(t),elevationAlignmentEnabled:!0,verticalScaleEnabled:!0,updateSuspendResumeExtent:function(){return b.updateSuspendResumeExtent()},
updateClippingExtent:function(a){return b.updateClippingExtent(a)}});this.addResolvingPromise(this.layerViewCore.initialize());this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.createController();this.addResolvingPromise(this.validateMaximumFeatureCount());this.addResolvingPromise(this.validateGeometryType());var a=y.toView(this).then(function(a){b.fullExtentInViewSpatialReference=a});a&&this.addResolvingPromise(a);this._evaluateUpdatingState()};a.prototype.destroy=function(){this._eventHandles.forEach(function(b){return b.remove()});
this._eventHandles=null;this.controller&&(this.controller.destroy(),this.controller=null);this.layerViewCore&&(this.layerViewCore.destroy(),this.layerViewCore=null);this.loadedGraphics=null};a.prototype.getRenderingInfo=function(b){if((b=u.getRenderingInfo(b,{renderer:this.layer.renderer}))&&b.color){var a=b.color;a[0]/=255;a[1]/=255;a[2]/=255}return b};a.prototype.getGraphicsFromStageObject=function(b,a){var c=b.getMetadata().graphicId,e=null;this.loadedGraphics&&this.loadedGraphics.some(function(b){return b.uid===
c?(e=b,!0):!1});var k=new w.Promise;null!==e?k.done(e):k.reject();return k};a.prototype.getGraphics3DGraphics=function(){return this.layerViewCore.graphicsCore.getGraphics3DGraphics()};a.prototype.getGraphics3DGraphicsKeys=function(){return this.layerViewCore.graphicsCore.getGraphics3DGraphicsKeys()};a.prototype.queryGraphics=function(){return this._queryEngine?this._queryEngine.queryFeatures():this._rejectQuery()};a.prototype.queryFeatures=function(b){return this._queryEngine?this._queryEngine.queryFeatures(b):
this._rejectQuery()};a.prototype.queryObjectIds=function(b){return this._queryEngine?this._queryEngine.queryObjectIds(b):this._rejectQuery()};a.prototype.queryFeatureCount=function(b){return this._queryEngine?this._queryEngine.queryFeatureCount(b):this._rejectQuery()};a.prototype.queryExtent=function(b){return this._queryEngine?this._queryEngine.queryExtent(b):this._rejectQuery()};a.prototype.whenGraphicBounds=function(b){return this.layerViewCore.graphicsCore.whenGraphicBounds(b)};a.prototype._rejectQuery=
function(){return h.reject(new g("FeatureLayerView3D","Not ready to execute query"))};a.prototype._notifySuspendedChange=function(){this.notifyChange("suspended")};a.prototype._notifyDrapedDataChange=function(){this.notifyChange("hasDraped");this.emit("draped-data-change")};a.prototype.canResume=function(){return this.inherited(arguments)&&this.layerViewCore&&this.layerViewCore.canResume()};a.prototype._evaluateUpdatingState=function(){if(this.layerViewCore.elevationAlignment){var b;b=0+this.layerViewCore.elevationAlignment.numNodesUpdating();
b+=this.layerViewCore.graphicsCore.numNodesUpdating();var a;a=(a=(a=(a=this.controller&&this.controller.isQueryInProgress)||this._overlayUpdating)||this.layerViewCore.graphicsCore.needsIdleUpdate())||!(this.view.basemapTerrain&&this.view.basemapTerrain.ready);var c;c=(c=0<b||a)||this.layerViewCore.spatialIndex.isUpdating();this._progressMaxNumNodes=Math.max(b,this._progressMaxNumNodes);0===b&&(this._progressMaxNumNodes=1);this._isUpdating=c;this.notifyChange("updating");this._set("updatingPercentageValue",
a?100:100*b/this._progressMaxNumNodes)}else this._isUpdating=!1,this.notifyChange("updating"),this._set("updatingPercentageValue",100)};a.prototype.isUpdating=function(){return this._isUpdating};a.prototype.createController=function(){var a=this,d=this.layer.createGraphicsController({layerView:this,options:{maxPageSize:300,extent:this.view.clippingArea}});x.whenTrueOnce(this.view,"basemapTerrain.ready",function(){n([a,d]).then(function(c){c=c[1];c instanceof v&&(a.controller=c,a._eventHandles.push(a.controller.watch("isQueryInProgress",
function(){return a._evaluateUpdatingState()})));a.loadedGraphics=c.graphics;a._queryEngine=new z({features:a.loadedGraphics,objectIdField:a.layer.objectIdField});a._evaluateUpdatingState()})})};a.prototype.updateClippingExtent=function(a){if(this.controller){if(this._controllerClientSideFiltering)return!1;this.controller.extent?(this.controller.extent=null,this._controllerClientSideFiltering=!0):this.controller.extent=a;return!0}return!1};a.prototype.updateSuspendResumeExtent=function(){return this._suspendResumeExtent=
q.enlargeExtent(this.layerViewCore.graphicsCore.computedExtent,this._suspendResumeExtent,1.2)};a.prototype.validateGeometryType=function(){var a=this.layer;switch(a.geometryType){case "multipatch":case "multipoint":return h.reject(new g("featurelayerview3d:unsupported-geometry-type","Unsupported geometry type ${geometryType}",{geometryType:a.geometryType}))}};a.prototype.validateMaximumFeatureCount=function(){return 0>a.maximumFeatureCount||!this.layer.url?h.resolve():this.layer.queryFeatureCount().then(function(b){if(b>
a.maximumFeatureCount)throw new g("featurelayerview3d:maximum-feature-count-exceeded","The maximum number of allowed features (${maximumFeatureCount}) has been exceeded (layer has ${numberOfFeatures} features)",{maximumFeatureCount:a.maximumFeatureCount,numberOfFeatures:b});})};a.prototype.getStats=function(){var a=this.layerViewCore.graphicsCore.getGraphics3DGraphics(),d="null",c=this._suspendResumeExtent;c&&(d=[c[0],c[1],c[2],c[3]].map(function(a){return a.toPrecision(4)}).join(", "));var c="null",
e=this.layerViewCore.graphicsCore.computedExtent;e&&(c=[e.xmin,e.ymin,e.xmax,e.ymax].map(function(a){return a.toPrecision(4)}).join(", "));return{numCollection:this.loadedGraphics.length,numGraphics:Object.keys(a).length,numElevationUpdating:this.layerViewCore.elevationAlignment.numNodesUpdating(),numSpatialIndexUpdating:this.layerViewCore.spatialIndex.numNodesUpdating(),numGraphicsUpdating:this.layerViewCore.graphicsCore.numNodesUpdating(),visibilityFrustum:this.layerViewCore.frustumVisibility.canResume(),
visibilityScale:this.layerViewCore.scaleVisibility.canResume(),resumeExtent:d,computedExtent:c,updating:this.updating,suspended:this.suspended}};a.maximumFeatureCount=-1;f([d.property()],a.prototype,"drawingOrder",null);f([d.property()],a.prototype,"loadedGraphics",void 0);f([d.property()],a.prototype,"hasDraped",null);f([d.property()],a.prototype,"controller",void 0);return a=f([d.subclass("esri.views.3d.layers.FeatureLayerView3D")],a)}(d.declared(s,r))});