// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/HandleRegistry ../../../core/watchUtils ../../../core/promiseUtils ../../../request ../../layers/LayerView ../support/projectionUtils ../support/orientedBoundingBox ./support/LayerViewUpdatingPercentage ../lib/glMatrix ./i3s/I3SBinaryReader ./i3s/I3SUtil ./i3s/PointRenderer ./i3s/PagedNodeIndex ./i3s/LoDUtil ./i3s/LEPCC dojo/Deferred dojo/promise/all dojo/errors/CancelError ../webgl-engine/lib/RenderSlot".split(" "),
function(Q,R,A,m,h,B,k,C,u,D,v,E,F,p,q,w,G,H,r,I,J,x,K,L){function y(c,b){void 0===b&&(b="RGB");for(var a=0;a<c.length;a++){var e=c[a];if(e.name===b&&null!=e.attributeValues&&"UInt8"===e.attributeValues.valueType&&3===e.attributeValues.valuesPerElement)return e}return null}function s(c,b){for(var a=0;a<c.length;a++){var e=c[a];if(e.name===b)return e}return null}function z(c){var b=[];c.forEach(function(a){return b.push(a)});return b}function M(c){var b=null,a=c.renderer,e=!1;a&&"pointCloudUniqueValueRenderer"===
a.type?b=s(c.attributeStorageInfo,a.field):a&&"pointCloudStretchRenderer"===a.type?b=s(c.attributeStorageInfo,a.field):a&&"pointCloudClassBreaksRenderer"===a.type?b=s(c.attributeStorageInfo,a.field):(b=a&&"pointCloudRGBRenderer"===a.type?y(c.attributeStorageInfo,a.field):y(c.attributeStorageInfo),e=null!=b);(c=null!=b?"embedded-elevation"===b.encoding:a&&"elevation"===a.field.toLowerCase())&&(b=null);return{renderer:a,attributeInfo:b,useElevation:c,isRGBAttribute:e}}function N(c,b,a,e){var l=c.renderer,
g=c.attributeInfo,d=c.useElevation;c=c.isRGBAttribute;if(d){for(var g=a.length/3,f=new Float64Array(g),n=0;n<g;n++)f[n]=a[3*n+2];a=f}else a=b&&q.readBinaryAttribute(g,b,e);if(b&&c)return a;if(b&&l&&"pointCloudUniqueValueRenderer"===l.type){f=l.colorUniqueValueInfos;b=new Uint8Array(3*e);l=t(l.fieldTransformType);for(d=0;d<e;d++){g=l?l(a[d]):a[d];g+="";for(c=0;c<f.length;c++)if(0<=f[c].values.indexOf(g)){b[3*d]=f[c].color.r;b[3*d+1]=f[c].color.g;b[3*d+2]=f[c].color.b;break}}return b}if((b||d)&&l&&
"pointCloudStretchRenderer"===l.type){f=l.stops;b=new Uint8Array(3*e);l=t(l.fieldTransformType);for(d=0;d<e;d++)if(g=l?l(a[d]):a[d],c=f.length-1,g<f[0].value)b[3*d]=f[0].color.r,b[3*d+1]=f[0].color.g,b[3*d+2]=f[0].color.b;else if(g>=f[c].value)b[3*d]=f[c].color.r,b[3*d+1]=f[c].color.g,b[3*d+2]=f[c].color.b;else for(c=1;c<f.length;c++)if(g<f[c].value){g=(g-f[c-1].value)/(f[c].value-f[c-1].value);b[3*d]=f[c].color.r*g+f[c-1].color.r*(1-g);b[3*d+1]=f[c].color.g*g+f[c-1].color.g*(1-g);b[3*d+2]=f[c].color.b*
g+f[c-1].color.b*(1-g);break}return b}if((b||d)&&l&&"pointCloudClassBreaksRenderer"===l.type){f=l.colorClassBreakInfos;b=new Uint8Array(3*e);l=t(l.fieldTransformType);for(d=0;d<e;d++){g=l?l(a[d]):a[d];for(c=0;c<f.length;c++)if(g>=f[c].minValue&&g<=f[c].maxValue){b[3*d]=f[c].color.r;b[3*d+1]=f[c].color.g;b[3*d+2]=f[c].color.b;break}}return b}return null}function t(c){return null==c||"none"===c?null:"low-four-bit"===c?function(b){return b&15}:"high-four-bit"===c?function(b){return(b&240)>>4}:"absolute-value"===
c?function(b){return Math.abs(b)}:"modulo-ten"===c?function(b){return b%10}:null}var O=p.vec4d.create();return function(c){function b(){c.apply(this,arguments);this.maximumPointCount=4E6;this._renderer=null;this._rendererAdded=!1;this._renderedNodes=new Set;this._idleUpdatesEnabled=this._updateViewNeeded=!0;this._lodFactor=1;this._handles=new B;this._indexQueue=[];this._workQueue=[];this._idleQueue=[];this._indexPagesLoading=new Map;this._loadingNodes=new Map;this._totalWork=0;this._index=null;this._nodeIdArray=
[]}A(b,c);Object.defineProperty(b.prototype,"pointScale",{get:function(){var a=this.layer.renderer&&this.layer.renderer.pointSizeAlgorithm;return a&&"pointCloudSplatAlgorithm"===a.type?a.scaleFactor:1},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"inverseDensity",{get:function(){return this.layer.renderer?96/this.layer.renderer.pointsPerInch:5},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"_clippingBox",{get:function(){var a=[];return v.extentToBoundingBox(this.view.clippingArea,
a,this.view.renderSpatialReference)?a:null},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;w.checkPointCloudLayerValid(this.layer);w.checkPointCloudCompatibleWithView(this.layer,this.view);this._initRenderer();var e=this._initNodePages(),b={idleBegin:function(){return a._idleBegin()},idleEnd:function(){return a._idleEnd()},needsUpdate:function(){return!0},idleFrame:function(e){return a._idleFrame(e)}};e.then(function(){a._handles.add(k.init(a,"suspended",function(e){e?
a.view.resourceController.deregisterIdleFrameWorker(a):a.view.resourceController.registerIdleFrameWorker(a,b)}))});this._handles.add(k.watch(this,"_clippingBox",function(){return a._updateViewNeeded=!0}));this._handles.add(k.watch(this.layer,"renderer",function(){return a._rendererChanged()}));this.addResolvingPromise(e)};b.prototype.destroy=function(){this.view.resourceController.deregisterIdleFrameWorker(this);this._handles.destroy();this._destroyRenderer()};b.prototype._initRenderer=function(){var a=
this;this._renderer=new G;this._handles.add(k.init(this,"_clippingBox",function(e){a._renderer.clippingBox=e}));this._handles.add(k.init(this,"suspended",function(e){a._setPointsVisible(!e)}));this._handles.add(k.init(this,"pointScale",function(e){a._renderer.scaleFactor=e}));this._handles.add(k.init(this,["inverseDensity","maximumPointCount"],function(){a._updateViewNeeded=!0}));this._handles.add(k.init(this.view,"qualitySettings.sceneService.pointCloud.lodFactor",function(e){a._lodFactor=e;a._updateViewNeeded=
!0}))};b.prototype._destroyRenderer=function(){this._setPointsVisible(!1)};b.prototype._setPointsVisible=function(a){a&&!this._rendererAdded?(this.view._stage.addExternalRenderer([L.OPAQUE_EXTERNAL],this._renderer),this._rendererAdded=!0):!a&&this._rendererAdded&&(this.view._stage.removeExternalRenderer(this._renderer),this._rendererAdded=!1)};b.prototype._rendererChanged=function(){var a=this;this._renderedNodes.forEach(function(e){return a._removeFromRenderer(e)});this._updateViewNeeded=!0};b.prototype.displayNodes=
function(a){this.cancelLoading();this._workQueue=r.nodeDiff(z(this._renderedNodes),a,this._index);r.sortFrontToBack(this._workQueue,this.view._stage.getCamera().viewForward,this._index);this._totalWork=this._computeWork();this._updateLoading()};b.prototype.cancelLoading=function(){var a=[];this._loadingNodes.forEach(function(e){return a.push(e)});this._loadingNodes.clear();for(var e=0;e<a.length;e++)a[e].cancel();this._totalWork=0;this._updateLoading()};b.prototype._idleBegin=function(){this._idleUpdatesEnabled&&
(this._updateViewNeeded=!1,this.updateViewWhenIdle())};b.prototype._idleEnd=function(){this.cancelLoading()};b.prototype._idleFrame=function(a){if(this._idleUpdatesEnabled){this._updateViewNeeded&&!a.done()&&(this._updateViewNeeded=!1,this.updateViewWhenIdle());for(;0<this._indexQueue.length&&!a.done();)this._processIndexQueue();for(;0<this._workQueue.length&&this._canSchedule(this._workQueue[0])&&!a.done();)this._processWorkQueue();for(;0<this._idleQueue.length&&!a.done();)this._idleQueue.shift().resolve()}};
b.prototype._schedule=function(){var a=new J;this._idleQueue.push(a);return a.promise};b.prototype._processIndexQueue=function(){var a=this,e=this._indexQueue.shift();this._indexPagesLoading.set(e,this._loadNodePage(e));this._indexPagesLoading.get(e).then(function(b){a._index.addPage(e,b);a._updateViewNeeded=!0}).always(function(){a._indexPagesLoading.delete(e)})};b.prototype._canSchedule=function(a){if(8<=this._loadingNodes.size)return!1;for(var e=0;e<a.remove.length;e++)if(!this._renderedNodes.has(a.remove[e]))return!1;
return!0};b.prototype._processWorkQueue=function(){var a=this,e=this._workQueue.shift();if(0===e.load.length)for(var b=0;b<e.remove.length;b++)this._removeFromRenderer(e.remove[b]);else{if(8<e.load.length&&1===e.remove.length)for(var c=r.splitWorkEntry(e,this._index),e=c[0],b=1;b<c.length;b++)this._workQueue.push(c[b]);x(e.load.map(function(b){a._loadingNodes.has(b)||a._loadingNodes.set(b,a.loadNode(b));return a._loadingNodes.get(b)})).then(function(b){for(var c=0;c<e.load.length;c++)a._addToRenderer(e.load[c],
b[c]);for(c=0;c<e.remove.length;c++)a._removeFromRenderer(e.remove[c])}).always(function(){for(var b=0;b<e.load.length;b++)a._loadingNodes.delete(e.load[b]);a._updateLoading()});this._updateLoading()}};b.prototype._computeWork=function(){for(var a=0,b=0;b<this._workQueue.length;b++)a+=this._workQueue[b].load.length;a+=this._loadingNodes.size;a+=(this._indexQueue.length+this._indexPagesLoading.size)*this._index.pageSize;return a+=this._updateViewNeeded?100:0};Object.defineProperty(b.prototype,"updating",
{get:function(){return 0<this._computeWork()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updatingPercentageValue",{get:function(){var a=this._computeWork();return 100*Math.max(0,this._totalWork-a)/this._totalWork},enumerable:!0,configurable:!0});b.prototype._updateLoading=function(){this.notifyChange("updating");this.notifyChange("updatingPercentageValue")};b.prototype._initNodePages=function(){var a=this;this._index=new H(this.layer.spatialReference,this.view.renderCoordsHelper.spatialReference,
this.layer.store.index.nodePerIndexBlock);this._traverseVisible=this._index.createVisibilityTraverse();return this._loadNodePage(0).then(function(b){a._index.addPage(0,b)})};b.prototype._loadNodePage=function(a){return this._requestJSON(this.layer.parsedUrl.path+"/nodepages/"+a*this._index.pageSize).then(function(a){return a.data.nodes})};b.prototype.updateViewWhenIdle=function(){for(var a=this.inverseDensity/this._lodFactor,b=this.maximumPointCount*this._lodFactor,c=this._computeNodesForMinimumDensity(a),
g=this._computePointCount(c),d=Math.sqrt(g/(0.75*b));g>b;)a*=d,c=this._computeNodesForMinimumDensity(a),g=this._computePointCount(c),d=Math.sqrt(2);this.displayNodes(c)};b.prototype._computePointCount=function(a){for(var b=0,c=0;c<a.length;c++){var g=this._index.getNode(a[c]);g&&(b+=g.pointCount)}return b};b.prototype._computeNodesForMinimumDensity=function(a){var b=this,c=this.view._stage.getCamera(),g=c.frustumPlanes,d=this._clippingBox,f=c.viewForward,n=p.vec3d.dot(f,c.eye),P=p.vec4d.set4(f[0],
f[1],f[2],-n,O),h=c.perPixelRatio,m=a*a,k=this._nodeIdArray;k.length=0;this._traverseVisible({frustumPlanes:g,clippingBox:d},{predicate:function(a,c,d){if(!d)return!1;if(0===c.childCount)return k.push(a),!1;d=b._index.getRenderObb(a);return b._computeAveragePixelArea(d,c.effectiveArea,c.pointCount,P,h)<=m?(k.push(a),!1):!0},pageMiss:function(a,c){k.push(a);0>b._indexQueue.indexOf(c)&&b._indexQueue.push(c)}});return k};b.prototype._computeAveragePixelArea=function(a,b,c,g,d){a=E.minimumDistancePlane(a,
g);return b/(a*a)/(4*d*d)/c};b.prototype.loadNode=function(a){var b=this,c=this._index.getNode(a),g=M(this.layer),d=null,f=null;return this._schedule().then(function(){var n=null!=c.resourceId?c.resourceId:a;d=b.loadGeometry(n);g.attributeInfo&&(f=b.loadAttribute(n,g.attributeInfo));return x([d,f])}).then(function(a){var d=a[1],f=b.readGeometry(b.layer.store.defaultGeometrySchema,a[0]),k=N(g,d,f,c.pointCount);return b._schedule().then(function(){return{positions:f,rgb:k}})}).then(function(c){var d=
c.positions;c=c.rgb;var f=p.vec3.create(b._index.getRenderCenter(a)),d=b._transformCoordinates(d,f);return{origin:d.origin,points:d.points,rgb:c}}).otherwise(function(a){a instanceof K&&(d&&d.cancel(),f&&f.cancel());return C.reject(a)})};b.prototype.readGeometry=function(a,b){if(null==a.encoding||""===a.encoding){for(var c=q.createGeometryDataIndex(b,a,!1),g=q.createTypedView(b,c.vertexAttributes.position),d=c.header.fields,c=[d.offsetX,d.offsetY,d.offsetZ],d=[d.scaleX,d.scaleY,d.scaleZ],f=g.length/
3,k=new Float64Array(3*f),h=0;h<f;h++)k[3*h]=g[3*h]*d[0]+c[0],k[3*h+1]=g[3*h+1]*d[1]+c[1],k[3*h+2]=g[3*h+2]*d[2]+c[2];return k}if("lepcc-xyz"===a.encoding)return I.decodeXYZ(b).result};b.prototype.loadGeometry=function(a){return this._requestBinary(this.layer.parsedUrl.path+"/nodes/"+a+"/geometries/0").then(function(a){return a.data})};b.prototype.loadAttribute=function(a,b){return this._requestBinary(this.layer.parsedUrl.path+"/nodes/"+a+"/attributes/"+b.key).then(function(a){return a.data})};b.prototype._requestJSON=
function(a){return u(a,{query:{f:"json",token:this.layer.token},responseType:"json"})};b.prototype._requestBinary=function(a){return u(a,{query:{token:this.layer.token},responseType:"array-buffer"})};b.prototype._removeFromRenderer=function(a){this._renderedNodes.has(a)&&(this._renderer.removeNode(""+a),this._renderedNodes.delete(a))};b.prototype._addToRenderer=function(a,b){if(!this._renderedNodes.has(a)){this._renderedNodes.add(a);var c=this._index.getNode(a),g=0.5*Math.sqrt(c.effectiveArea/c.pointCount),
d=b.rgb;if(null==d){d=new Uint8Array(3*c.pointCount);for(c=0;c<d.length;c++)d[c]=255}this._renderer.addNode({id:""+a,coordinates:b.points,origin:b.origin,pointRadius:g,rgb:d})}};b.prototype._transformCoordinates=function(a,b){var c=a.length/3;if(!v.bufferToBuffer(a,this.layer.spatialReference,0,a,this.view.renderCoordsHelper.spatialReference,0,c))throw Error("Can't reproject");for(var g=new Float32Array(3*c),d=0;d<c;d++)g[3*d]=a[3*d]-b[0],g[3*d+1]=a[3*d+1]-b[1],g[3*d+2]=a[3*d+2]-b[2];return{points:g,
origin:b}};b.prototype.getStats=function(){var a=this;return{"Rendered Nodes":this._renderedNodes.size,"Rendered Points":z(this._renderedNodes).reduce(function(b,c){return b+a._index.getNode(c).pointCount},0),"Loading Nodes":this._loadingNodes.size,"Index Queue":this._indexQueue.length,"Work Queue":this._workQueue.length}};m([h.property()],b.prototype,"view",void 0);m([h.property()],b.prototype,"layer",void 0);m([h.property({readOnly:!0,dependsOn:["layer.renderer.pointSizeAlgorithm"]})],b.prototype,
"pointScale",null);m([h.property({readOnly:!0,dependsOn:["layer.renderer.pointsPerInch"]})],b.prototype,"inverseDensity",null);m([h.property()],b.prototype,"maximumPointCount",void 0);m([h.property({readOnly:!0,dependsOn:["view.clippingArea"]})],b.prototype,"_clippingBox",null);m([h.property()],b.prototype,"updating",null);m([h.property()],b.prototype,"updatingPercentageValue",null);return b=m([h.subclass("esri.views.3d.layers.PointCloudLayerView3D")],b)}(h.declared(D,F))});