// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/libs/gl-matrix/mat4 ../GeometryUtils ./BackgroundRenderer ./LineRenderer ./FillRenderer ./SymbolRenderer ./TileInfoRenderer ./FadeRecorder".split(" "),function(u,v,e,m,n,p,q,r,s,t){return function(){function d(a,b,c){void 0===c&&(c=!0);this._extrudeRotateVector=new Float32Array([0,0,1]);this._extrudeScaleVector=new Float32Array([1,1,1]);this._state={rotation:0,width:0,height:0};this._cachedRotation=this._cachedHeight=this._cachedWidth=0;this._pixelRatio=1;this._SpriteMosaic=
a;this._glyphMosaic=b;this._ignoreSpeed=!c;this._backgroundRenderer=new n;this._lineRenderer=new p;this._fillRenderer=new q;this._symbolRenderer=new r;this._tileInfoRenderer=new s;this._fadeRecorder=new t.FadeRecorder(300);this._extrudeMatrix=new Float32Array(16);this._extrudeNoRotationMatrix=new Float32Array(16);this._backgroundColor=new Float32Array([1,0,0,1])}d.prototype.setStateParams=function(a,b,c){this._pixelRatio=b;this._fadeRecorder.recordLevel(c);this._state=a;if(this._state.width!==this._cachedWidth||
this._state.height!==this._cachedHeight||this._state.rotation!==this._cachedRotation)this._extrudeScaleVector[0]=2/a.width,this._extrudeScaleVector[1]=-2/a.height,e.identity(this._extrudeMatrix),e.rotate(this._extrudeMatrix,this._extrudeMatrix,-a.rotation*m.C_DEG_TO_RAD,this._extrudeRotateVector),e.scale(this._extrudeMatrix,this._extrudeMatrix,this._extrudeScaleVector),e.transpose(this._extrudeMatrix,this._extrudeMatrix),e.identity(this._extrudeNoRotationMatrix),e.scale(this._extrudeNoRotationMatrix,
this._extrudeNoRotationMatrix,this._extrudeScaleVector),e.transpose(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix),this._cachedWidth=this._state.width,this._cachedHeight=this._state.height,this._cachedRotation=this._state.rotation};d.prototype.drawClippingMasks=function(a,b){if(0!==b.length){a.setDepthWriteEnabled(!1);a.setDepthTestEnabled(!1);a.setStencilTestEnabled(!0);a.setBlendingEnabled(!1);a.setColorMask(!1,!1,!1,!1);a.setStencilOp(7680,7680,7681);a.setClearStencil(0);a.clear(a.gl.STENCIL_BUFFER_BIT);
for(var c=0;c<b.length;c++){var f=b[c];f.attached&&f.visible&&(a.setStencilFunctionSeparate(1032,519,f.stencilData.reference,f.stencilData.mask),a.setStencilWriteMask(f.stencilData.mask),this._backgroundRenderer.renderSolidColor(a,{u_matrix:f.tileTransform.transform,u_normalized_origin:f.tileTransform.displayCoord,u_coord_range:f.coordRange,u_depth:0,u_color:this._backgroundColor}))}a.setColorMask(!0,!0,!0,!0);a.setBlendingEnabled(!0);a.setStencilWriteMask(255)}};d.prototype.renderDebug=function(a,
b){var c=b.key;this._backgroundColor.set([c.col%2,c.row%2,0===c.col%2&&0===c.row%2?1:0,0.5]);this._backgroundRenderer.renderSolidColor(a,{u_matrix:b.tileTransform.transform,u_normalized_origin:b.tileTransform.displayCoord,u_coord_range:b.coordRange,u_depth:0,u_color:this._backgroundColor})};d.prototype.renderBucket=function(a,b,c,f,h,g,d,e){switch(b.type){case 0:2!==h&&this._renderBackground(a,c,h,g,d,e);break;case 1:2!==h&&this._renderFill(a,b,c,h,g,d,e);break;case 2:1===h&&this._renderLine(a,b,
c,g,d,e);break;case 3:2===h&&this._renderSymbol(a,b,c,f,g,d,e)}};d.prototype.renderTileInfo=function(a,b){this._tileInfoRenderer.render(a,b)};d.prototype.needsRedraw=function(){return this._fadeRecorder.needsRedraw()};d.prototype._renderBackground=function(a,b,c,f,d,e){this._backgroundRenderer.render(a,b,c,f,d,this._SpriteMosaic,this._SpriteMosaic.pixelRatio,e)};d.prototype._renderLine=function(a,b,c,d,e,g){this._lineRenderer.render(a,b,c,this._state,d,e,this._SpriteMosaic,this._extrudeMatrix,this._SpriteMosaic.pixelRatio,
g)};d.prototype._renderFill=function(a,b,c,d,e,g,k){this._fillRenderer.render(a,b,c,this._state.rotation,d,e,g,this._SpriteMosaic,this._extrudeMatrix,this._SpriteMosaic.pixelRatio,k)};d.prototype._renderSymbol=function(a,b,c,d,e,g,k){var l=!0;d===e.key.level&&(l=!1);a.setStencilTestEnabled(l);this._symbolRenderer.render(a,b,c,this._state.rotation,this._fadeRecorder.getFadeValues(this._ignoreSpeed),e,g,this._SpriteMosaic,this._glyphMosaic,this._extrudeMatrix,this._extrudeNoRotationMatrix,this._SpriteMosaic.pixelRatio,
k)};return d}()});