// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/has ../../core/promiseUtils ../../core/requireUtils ../../layers/Layer ../../renderers/support/styleUtils".split(" "),function(r,g,k,h,s,t,u){function v(d,a,b){var c;return s.when(r,"../../layers/"+a).then(function(a){var f={};d.itemId&&(f.portalItem={id:d.itemId,portal:b.context.portal});c=new a(f);c.read(d,b.context);return u.loadStyleRenderer(c,b.context).then(function(){return h.resolve(c)})})}function n(d,a){var b=d.layerType||d.type;!b&&(a&&a.defaultLayerType)&&
(b=a.defaultLayerType);var c;switch(a.context.origin){case "web-scene":switch(a.context.layerContainerType){case "basemap":c=l;break;case "ground":c=w;break;default:c=m}break;default:switch(a.context.layerContainerType){case "basemap":c=x;break;default:c=y}}return v(d,c[b]||"UnknownLayer",a)}function p(d,a,b){return!a||!a.filter?b:b.then(function(c){var b=a.filter(c);return void 0===b?h.resolve(c):b instanceof t?h.resolve(b):b})}function q(d,a,b){if(!a)return[];for(var c=[],g=[],f=0;f<a.length;f++){var e=
a[f],k=n(e,b);c.push(k);g.push(null);if("GroupLayer"===e.layerType&&e.layers&&Array.isArray(e.layers)&&0<e.layers.length){e=e.layers.map(function(a){return n(a,b)});c.push.apply(c,e);for(var l=0;l<e.length;l++)g.push(k)}}var m={};return c.map(function(a,c){var e=function(a,b){m[b.id]=c;var d=a.findIndex(function(a){if(!a.id)return!1;a=m[a.id];return void 0===a?!1:c<a});0>d&&(d=void 0);a.add(b,d)},f=p(d,b,a).then(function(a){if(null===g[c])e(d,a);else return g[c].then(function(b){e(b.layers,a);return h.resolve(a)});
return h.resolve(a)});z&&(f=f.otherwise(function(a){console.error(a.toString?a.toString():a);return h.reject(a)}));return f})}var z=0,m={ArcGISFeatureLayer:"FeatureLayer",ArcGISMapServiceLayer:"MapImageLayer",PointCloudLayer:"PointCloudLayer",ArcGISSceneServiceLayer:"SceneLayer",IntegratedMeshLayer:"IntegratedMeshLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",OpenStreetMap:"OpenStreetMapLayer",
WebTiledLayer:"WebTileLayer",CSV:"CSVLayer",DefaultTileLayer:"TileLayer"};k("disable-feature:jkieboom/vector-tiles")||(m.VectorTileLayer="VectorTileLayer");var w={ArcGISTiledElevationServiceLayer:"ElevationLayer",DefaultTileLayer:"ElevationLayer"},l={ArcGISTiledMapServiceLayer:"TileLayer",ArcGISTiledImageServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",WebTiledLayer:"WebTileLayer",DefaultTileLayer:"TileLayer"};k("disable-feature:jkieboom/vector-tiles")||(l.VectorTileLayer="VectorTileLayer");
var y={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISStreamLayer:"StreamLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",CSV:"CSVLayer",GeoRSS:"UnsupportedLayer",KML:"UnsupportedLayer",
WMS:"UnsupportedLayer",DefaultTileLayer:"TileLayer"},x={ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",bingLayer:"UnsupportedLayer",WMS:"UnsupportedLayer",DefaultTileLayer:"TileLayer"};g.createLayer=n;g.processLayer=p;g.populateLayers=q;g.populateOperationalLayers=
function(d,a,b){return q(d,a,b)}});