// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["require","exports","./ModelContentType","./ModelDirtyTypesTs","./Util"],function(A,B,x,C,y){var z=y.objectEmpty,u=y.assert;return function(){function d(a){this._residentGeomRecords={};this._dirtyGeomRecords={};this._dirtyMaterials={};this._model=a}d.prototype._getResidentGeometryRecords=function(){return this._residentGeomRecords};d.prototype._getDirtyGeometryRecords=function(){return this._dirtyGeomRecords};d.prototype.getDirtyMaterials=function(){return z(this._dirtyMaterials)?null:this._dirtyMaterials};
d.prototype.clearDirtyMaterials=function(){this._dirtyMaterials={}};d.prototype.hasDirtyGeometryRecords=function(){for(var a in this._dirtyGeomRecords)for(var b in this._dirtyGeomRecords[a]){var c=this._dirtyGeomRecords[a][b];if(c&&!z(c))return!0}return!1};d.prototype.handleUpdate=function(a,b,c){u(this[b],"ModelDirtySet doesn't know how to process "+b);return this[b](a,c)};d.prototype.getAddRemoveUpdateList=function(a){return this.getAddRemoveUpdateListFilteredByLayers(Object.keys(this._dirtyGeomRecords),
a)};d.prototype.getAddRemoveUpdateListFilteredByLayers=function(a,b){for(var c=[],d=[],e=[],f=0;f<a.length;f++){var h=a[f];if(h in this._dirtyGeomRecords)for(var g in this._dirtyGeomRecords[h]){var r=this._dirtyGeomRecords[h][g];if(r){var l=this._createObjectRecordObjIfNonexistent(this._residentGeomRecords,h,g),t;for(t in r){var p=r[t],v=p[0],n=p[1],p=p[2],s=n&2&&p&1;if(n&4||s){var k=l[t];k?d.push.apply(d,k[1]):4===n&&u(!1,"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid remove");b&&k&&delete l[t]}if(n&
1||s){var k=[v,[]],w=this._model.get(x.OBJECT,g);this._model.getGeometryRenderGeometries(w,v,k[1]);c.push.apply(c,k[1]);b&&(l[t]=k)}if(n&2&&!s)if(k=l[t],w=this._model.get(x.OBJECT,g),k){n=k[1];s=n.length;if(p&2)for(var k=w.getVisibleIndexRanges(v),m=0;m<s;m++){var q=n[m];q.displayedIndexRange=k?k[q.componentIdx]:void 0}if(p&16)for(m=0;m<s;m++)q=n[m],w.getCombinedStaticTransformation(v,q.transformation),q.updateTransformation(q.transformation);for(m=0;m<s;m++)q=n[m],e.push({renderGeometry:q,updateType:p})}else u(!1,
"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid update")}}}b&&delete this._dirtyGeomRecords[h]}return[c,d,e]};d.prototype.getResidentRenderGeometries=function(){return this.getResidentRenderGeometriesFilteredByLayers(Object.keys(this._residentGeomRecords))};d.prototype.getResidentRenderGeometriesFilteredByLayers=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(d in this._residentGeomRecords)for(var e in this._residentGeomRecords[d]){var f=this._residentGeomRecords[d][e];if(f)for(var h in f)b.push.apply(b,
f[h][1])}}return b};d.prototype.hideFaceRange=function(a,b,c){c=c||this._getParentLayerId(a);this._updateOrCreateDirtyRecord(a,b,c,2,0,0,2,5,2)};d.prototype.unhideAllFaceRange=function(a,b){for(var c=0;c<a.getGeometryRecords().length;c++)this._updateOrCreateDirtyRecord(a,a.getGeometryRecords()[c],b,2,0,0,2,5,2)};d.prototype.vertexAttrsUpdated=function(a,b,c){this._updateOrCreateDirtyRecord(a,b,c,2,0,0,2,5,4)};d.prototype.colorAttrsUpdated=function(a,b,c){this._updateOrCreateDirtyRecord(a,b,c,2,0,
0,2,5,8)};d.prototype.matChanged=function(a){this._dirtyMaterials[a.getId()]=!0};d.prototype.layerAdded=function(a){for(var b=a.getObjects(),c=0;c<b.length;c++)this.layObjectAdded(a,b[c])};d.prototype.layerRemoved=function(a){for(var b=a.getObjects(),c=0;c<b.length;c++)this.layObjectRemoved(a,b[c])};d.prototype.layObjectAdded=function(a,b){for(var c=a.getId(),d=b.getGeometryRecords(),e=0;e<d.length;e++)this.objGeometryAdded(b,d[e],c)};d.prototype.layObjectRemoved=function(a,b){for(var c=a.getId(),
d=b.getGeometryRecords(),e=0;e<d.length;e++)this.objGeometryRemoved(b,d[e],c)};d.prototype.layObjectReplaced=function(a,b){this.layObjectRemoved(a,b[0]);this.layObjectAdded(a,b[1])};d.prototype.objDirty=function(a,b){b=b||this._getParentLayerId(a);var c=a.getId(),c=this._createObjectRecordObjIfNonexistent(this._residentGeomRecords,b,c),d;for(d in c)this._updateOrCreateDirtyRecord(a,c[d][0],b,2,0,2,0,5,1)};d.prototype.objTransformation=function(a,b){b=b||this._getParentLayerId(a);var c=a.getId(),c=
this._createObjectRecordObjIfNonexistent(this._residentGeomRecords,b,c),d;for(d in c)this._updateOrCreateDirtyRecord(a,c[d][0],b,2,0,0,2,5,16)};d.prototype.objGeometryAdded=function(a,b,c){this._updateOrCreateDirtyRecord(a,b,c,1,4,0,0,0)};d.prototype.objGeometryRemoved=function(a,b,c){this._updateOrCreateDirtyRecord(a,b,c,4,1,2,0,0)};d.prototype.objGeometryReplaced=function(a,b){this.objGeometryRemoved(a,b[0]);this.objGeometryAdded(a,b[1])};d.prototype.objGeometryTransformation=function(a,b){this.objGeometryReplaced(a,
b)};d.prototype._updateOrCreateDirtyRecord=function(a,b,c,d,e,f,h,g,r){c=c||this._getParentLayerId(a);var l=a.getId();a=b.getId();c=this._createObjectRecordObjIfNonexistent(this._dirtyGeomRecords,c,l);(l=c[a])?(b=l[1],b&e?delete c[a]:b&f?(l[1]=d,l[2]=r):b&h?l[2]|=r:b&g||u(!1,"ModelDirtySet.objGeometryAdded: inconsistent state")):c[a]=[b,d,r]};d.prototype._createObjectRecordObjIfNonexistent=function(a,b,c){a[b]||(a[b]={});a[b][c]||(a[b][c]={});return a[b][c]};d.prototype._getParentLayerId=function(a){return a.parentLayer.id};
d.prototype.formatDebugInfo=function(a){var b=["ADD","UPD",void 0,"REM"];if(a)return"";a="";for(var c in this._dirtyGeomRecords)for(var d in this._dirtyGeomRecords[c]){var e=this._dirtyGeomRecords[c][d];if(e){0<a.length&&(a+="\n");a+=c+"."+d;var f=[],h;for(h in e){var g=e[h][1];f[g]||(f[g]=[]);f[g].push(e[h][0].geometry.id)}for(e=0;e<f.length;e++)if(f[e]){a+=" "+b[e-1]+": ";for(g=0;g<f[e].length;g++)a+=f[e][g]+", "}}}return a};return d}()});