// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./gl-matrix ./Util dojo/has ./PerformanceTimer".split(" "),function(w,D,A,s,E,F){function x(b,a,c){c=c||b;c[0]=b[0]+a;c[1]=b[1]+a;c[2]=b[2]+a;return c}var g=A.vec3d;w=function(){function b(a,c,d){this._maximumObjectsPerNode=10;this._maximumDepth=20;this._autoResize=!0;this._outsiders=[];d&&(void 0!==d.maximumObjectsPerNode&&(this._maximumObjectsPerNode=d.maximumObjectsPerNode),void 0!==d.maximumDepth&&(this._maximumDepth=d.maximumDepth),void 0!==d.autoResize&&(this._autoResize=
d.autoResize));isNaN(a[0])||isNaN(a[1])||isNaN(a[2])||isNaN(c)?this._root=new e(null,g.createFrom(0,0,0),0.5):this._root=new e(null,a,c/2)}Object.defineProperty(b.prototype,"center",{get:function(){return this._root.center},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"size",{get:function(){return 2*this._root.halfSize},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"root",{get:function(){return this._root.node},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"outsiders",{get:function(){return this._outsiders.slice()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"maximumObjectsPerNode",{get:function(){return this._maximumObjectsPerNode},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"maximumDepth",{get:function(){return this._maximumDepth},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"autoResize",{get:function(){return this._autoResize},enumerable:!0,configurable:!0});b.prototype.add=function(a){a=
this._objectOrObjectsArray(a);this._grow(a);for(var c=e.acquire(),d=0;d<a.length;d++){var n=a[d];c.init(this._root);0===n.getBSRadius()||isNaN(n.getBSRadius())||!this._autoResize&&!this._fitsInsideTree(this._boundingSphereFromObject(n,u))?this._outsiders.push(n):this._add(n,c)}e.release(c)};b.prototype.remove=function(a,c){for(var d=this._objectOrObjectsArray(a),n=e.acquire(),b=!0,f=0;f<d.length;f++){var b=d[f],h=this._boundingSphereFromObject(c||b,u);0===h.radius||isNaN(h.radius)||!this._autoResize&&
!this._fitsInsideTree(h)?b=null!=s.arrayRemove(this._outsiders,b):(n.init(this._root),b=this._remove(b,h,n))}e.release(n);this._shrink();return b};b.prototype.update=function(a,c){this.remove(a,c);this.add(a)};b.prototype.forEachAlongRay=function(a,c,d){this._forEachTest(function(d){x(d.center,2*-d.halfSize,k);x(d.center,2*d.halfSize,m);return s.rayBoxTest(a,c,k,m)},d)};b.prototype.forEachInBoundingBox=function(a,c,d){this._forEachTest(function(d){for(var b=2*d.halfSize,f=0;3>f;f++)if(d.center[f]+
b<a[f]||d.center[f]-b>c[f])return!1;return!0},d)};b.prototype.forEachNode=function(a){this._forEachNode(this._root,function(c){return a(c.node,c.center,2*c.halfSize)})};b.prototype._forEachTest=function(a,c){this._outsiders.forEach(c);this._forEachNode(this._root,function(d){return a(d)?(d=d.node,d.terminals.forEach(c),null!==d.residents&&d.residents.forEach(c),!0):!1})};b.prototype._forEachNode=function(a,c){for(var d=e.acquire().init(a),b=[d];0!==b.length;){d=b.pop();if(c(d)&&!d.isLeaf())for(var p=
0;p<d.node.children.length;p++)d.node.children[p]&&b.push(e.acquire().init(d).advance(p));e.release(d)}};b.prototype._objectOrObjectsArray=function(a){Array.isArray(a)||(y[0]=a,a=y);return a};b.prototype._remove=function(a,c,d){r.length=0;d.advanceTo(c,function(a,c){r.push(a.node,c)})?(a=null!=s.arrayRemove(d.node.terminals,a),d=0===d.node.terminals.length):(a=null!=s.arrayRemove(d.node.residents,a),d=0===d.node.residents.length);if(d)for(d=r.length-2;0<=d&&this._purge(r[d],r[d+1]);d-=2);return a};
b.prototype._nodeIsEmpty=function(a){if(0!==a.terminals.length)return!1;if(null!==a.residents)return 0===a.residents.length;for(var c=0;c<a.children.length;c++)if(a.children[c])return!1;return!0};b.prototype._purge=function(a,c){0<=c&&(a.children[c]=null);return this._nodeIsEmpty(a)?(null===a.residents&&(a.residents=[]),!0):!1};b.prototype._add=function(a,c){c.advanceTo(this._boundingSphereFromObject(a,u))?c.node.terminals.push(a):(c.node.residents.push(a),c.node.residents.length>this._maximumObjectsPerNode&&
c.depth<this._maximumDepth&&this._split(c))};b.prototype._split=function(a){var c=a.node.residents;a.node.residents=null;for(var d=0;d<c.length;d++){var b=e.acquire().init(a);this._add(c[d],b);e.release(b)}};b.prototype._grow=function(a){if(0!==a.length&&this._autoResize&&(a=this._boundingSphereFromObjects(a,this._boundingSphereFromObject,q),!isNaN(a.radius)&&!(0===a.radius||this._fitsInsideTree(a))))if(this._nodeIsEmpty(this._root.node))g.set(a.center,this._root.center),this._root.halfSize=1.25*
a.radius;else{var c=e.acquire();this._rootBoundsForRootAsSubNode(a,c);this._placingRootViolatesMaxDepth(c)?this._rebuildTree(a,c):this._growRootAsSubNode(c);e.release(c)}};b.prototype._rebuildTree=function(a,c){var d=this;g.set(c.center,v.center);v.radius=c.halfSize;var b=this._boundingSphereFromObjects([a,v],function(a){return a},B),p=e.acquire().init(this._root);this._root.initFrom(null,b.center,1.25*b.radius);this._forEachNode(p,function(a){d.add(a.node.terminals);null!==a.node.residents&&d.add(a.node.residents);
return!0});e.release(p)};b.prototype._placingRootViolatesMaxDepth=function(a){var c=0;this._forEachNode(this._root,function(a){c=Math.max(c,a.depth);return!0});return c+Math.log(a.halfSize/this._root.halfSize)*Math.LOG2E>this._maximumDepth};b.prototype._rootBoundsForRootAsSubNode=function(a,c){for(var d=a.radius,b=a.center,g=-Infinity,f=this._root.center,h=this._root.halfSize,l=0;3>l;l++){var e=b[l]+d-(f[l]+h),k=Math.max(0,Math.ceil((f[l]-h-(b[l]-d))/(2*h))),e=Math.max(0,Math.ceil(e/(2*h)))+1,m=Math.pow(2,
Math.ceil(Math.log(k+e)*Math.LOG2E)),g=Math.max(g,m);t[l].min=k;t[l].max=e}for(l=0;3>l;l++)k=t[l].min,e=t[l].max,d=(g-(k+e))/2,k+=Math.ceil(d),e+=Math.floor(d),z[l]=f[l]-h-2*k*h+(e+k)*h;return c.initFrom(null,z,g*h,0)};b.prototype._growRootAsSubNode=function(a){var c=this._root.node;g.set(this._root.center,q.center);q.radius=this._root.halfSize;this._root.init(a);a.advanceTo(q,null,!0);a.node.children=c.children;a.node.residents=c.residents;a.node.terminals=c.terminals};b.prototype._shrink=function(){if(this._autoResize)for(;;){var a=
this._findShrinkIndex();if(-1===a)break;this._root.advance(a);this._root.depth=0}};b.prototype._findShrinkIndex=function(){if(0!==this._root.node.terminals.length||this._root.isLeaf())return-1;for(var a=null,c=this._root.node.children,d=0,b=0;b<c.length&&null==a;)d=b++,a=c[d];for(;b<c.length;)if(c[b++])return-1;return d};b.prototype._fitsInsideTree=function(a){var c=this._root.center,d=this._root.halfSize,b=a.center;return a.radius<=d&&b[0]>=c[0]-d&&b[0]<=c[0]+d&&b[1]>=c[1]-d&&b[1]<=c[1]+d&&b[2]>=
c[2]-d&&b[2]<=c[2]+d};b.prototype._boundingSphereFromObject=function(a,c){g.set(a.getCenter(),c.center);c.radius=a.getBSRadius();return c};b.prototype._boundingSphereFromObjects=function(a,c,d){if(1===a.length){var b=c(a[0],q);g.set(b.center,d.center);d.radius=b.radius}else{k[0]=Infinity;k[1]=Infinity;k[2]=Infinity;m[0]=-Infinity;m[1]=-Infinity;m[2]=-Infinity;for(var e=0;e<a.length;e++){var b=c(a[e],q),f=k,h=b.center,l=b.radius;f[0]=Math.min(f[0],h[0]-l);f[1]=Math.min(f[1],h[1]-l);f[2]=Math.min(f[2],
h[2]-l);f=m;h=b.center;b=b.radius;f[0]=Math.max(f[0],h[0]+b);f[1]=Math.max(f[1],h[1]+b);f[2]=Math.max(f[2],h[2]+b)}g.scale(g.add(k,m,d.center),0.5);d.radius=Math.max(m[0]-k[0],m[1]-k[1],m[2]-k[2])/2}return d};return b}();var e=function(){function b(a,c,d,b){void 0===d&&(d=0);this.center=g.create();this.initFrom(a,c,d,0)}b.prototype.init=function(a){return this.initFrom(a.node,a.center,a.halfSize,a.depth)};b.prototype.initFrom=function(a,c,d,e){void 0===a&&(a=null);void 0===d&&(d=this.halfSize);void 0===
e&&(e=this.depth);this.node=a||b.createEmptyNode();c&&g.set(c,this.center);this.halfSize=d;this.depth=e;return this};b.prototype.advance=function(a){var c=this.node.children[a];c||(c=b.createEmptyNode(),this.node.children[a]=c);this.node=c;this.halfSize/=2;this.depth++;a=C[a];this.center[0]+=a[0]*this.halfSize;this.center[1]+=a[1]*this.halfSize;this.center[2]+=a[2]*this.halfSize;return this};b.prototype.advanceTo=function(a,c,d){for(void 0===d&&(d=!1);;){if(this.isTerminalFor(a))return c&&c(this,
-1),!0;if(this.isLeaf()&&!d)return c&&c(this,-1),!1;this.isLeaf()&&(this.node.residents=null);var b=this._childIndex(a);c&&c(this,b);this.advance(b)}};b.prototype.isLeaf=function(){return null!=this.node.residents};b.prototype.isTerminalFor=function(a){return a.radius>this.halfSize/2};b.prototype._childIndex=function(a){a=a.center;for(var c=this.center,b=0,e=0;3>e;e++)c[e]<a[e]&&(b|=1<<e);return b};b.createEmptyNode=function(){return{children:[null,null,null,null,null,null,null,null],terminals:[],
residents:[]}};b.acquire=function(){if(0===this._pool.length)return new b;var a=this._pool[this._pool.length-1];this._pool.length--;return a};b.release=function(a){this._pool.push(a)};b._pool=[];return b}(),C=[[-1,-1,-1],[1,-1,-1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,-1,1],[-1,1,1],[1,1,1]],y=[null],z=g.create(),k=g.create(),m=g.create(),r=[],u={center:g.create(),radius:0},q={center:g.create(),radius:0},v={center:g.create(),radius:0},B={center:g.create(),radius:0},t=[{min:0,max:0},{min:0,max:0},{min:0,
max:0}];return w});