// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./IntervalUtilities ./ModelDirtyTypesTs ./Float32ArrayList ./InstanceBufferData ./Lighting ../materials/internal/SimpleGLMaterial ../materials/internal/TexOnlyGLMaterial ./LinearDepthTextureHelper ./NormalTextureHelper ./HighlightTextureHelper ./RenderPass ./RenderSlot ./RenderContext ./ExternalRendererContainer ./StencilRenderingHelper ./BitSet ./Util ./gl-matrix ../../../webgl/Texture ../../../webgl/VertexArrayObject ../../../webgl/BufferObject ../../../webgl/Util ./FxaaRenderPass ./SmaaRenderPass ../../../webgl/enums ./DefaultVertexBufferLayouts ./DefaultVertexAttributeLocations".split(" "),
function(T,U,V,sa,W,ca,da,X,ea,fa,ga,ha,B,A,ia,ja,ka,la,F,N,Y,O,P,G,ma,na,ta,oa,Q){var E=F.assert,Z=F.array2object,$=F.objectEmpty,J=F.getFirstObjectValue,R=F.setMatrixTranslation3;T=N.vec2d;U=N.vec3d;var S=N.vec4d,C=N.mat4d,pa=F.VertexAttrConstants,H=C.identity();F=U.create();var qa=1535,aa={proj:H,view:H,nearFar:[-1,1],origin:F};F=function(){function e(a,b,d,c,f){this._lighting=new da;this._mat2dataMerged={};this._mat2dataInstanced={};this._renderOrder=[];this._externalRenderers=new ja;this._renderContext=
new ia;this._framesRendered=0;this._isRendering=!1;this._pixelRatio=1;this._threshold=qa;this._needsRender=!0;this._stats=new ra;this.ssaoEnabled=!1;this.renderOptions={antialiasing:"smaa",earlyOcclusionPixelDraw:!1};this._programRep=a;this._materialRep=b;this._textureRep=d;this._orderedRendering=f;this._rctx=c;b=c.gl;this._fxaaPass=new ma(c);this._smaaPass=new na(c);this._selectionMaterial=new X(a,S.createFrom(0.1,0.2,0.9,0.4),b.EQUAL);this._selectionMaterialLines=new X(a,S.createFrom(0.1,0.2,0.9,
0.4),b.EQUAL,b.LINES);this._renderContext.lightingData=this._lighting.get();c.setDepthTestEnabled(!0);c.setFaceCullingEnabled(!0);c.setBlendingEnabled(!1);c.setBlendFunctionSeparate(770,771,1,771);this._bindParameters={view:null,proj:null,viewInvTransp:null,nearFar:null,lightingData:null,viewport:null,framebufferTex:null,shadowMap:null,origin:null,pixelRatio:null,instanceParameters:null,depthFBO:null,normalFBO:null,extensions:{angleInstancedArrays:c.extensions.angleInstancedArrays}};this._linearDepthTextureHelper=
new fa(c);this._normalTextureHelper=new ga(c);this._highlightTextureHelper=new ha(c);this._stencilRenderingHelper=new ka(c);this._initializeFramebufferTexture();this._initializeIeTextureFix()}e.prototype._initializeQuadVAO=function(){if(!this._quadVAO){var a=this._rctx,b=new Float32Array([-1,-1,0,0,0,1,-1,0,1,0,-1,1,0,0,1,1,1,0,1,1]);this._quadVAO=new O(a,Q.Default3D,{geometry:oa.Pos3Tex},{geometry:P.createVertex(a,35044,b)})}};e.prototype._initializeFramebufferTexture=function(){var a=this._rctx.gl,
a=this._rctx.contextAttributes.alpha?a.RGBA:a.RGB,b=new Y(this._rctx,{target:3553,pixelFormat:a,dataType:5121,samplingMode:9728,wrapMode:33071,width:4,height:4});this._framebuffer={format:a,texture:b,copied:!1}};e.prototype._initializeIeTextureFix=function(){if(6408===this._framebuffer.format){for(var a=new Uint8Array(64),b=0;64>b;b++)a[b]=255;this._ieFixTexture=new Y(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:4,height:4});this._ieFixMaterial=new ea(this._programRep,
this._ieFixTexture,S.createFrom(1,1,1,1),!0,519)}};e.prototype.dispose=function(){for(var a in this._mat2dataMerged){this._releaseMaterials(a);var b=this._mat2dataMerged[a],d;for(d in b.origin2data)b.origin2data[d].vao.dispose(!0)}this._mat2dataMerged=null;for(a in this._mat2dataInstanced)for(d in this._releaseMaterials(a),b=this._mat2dataInstanced[a],b.origin2data)b.origin2data[d].vao.dispose(!0);this._mat2dataInstanced=null;this._quadVAO&&(this._quadVAO.dispose(!0),this._quadVAO=null);this._ieFixTexture&&
(this._ieFixTexture.dispose(),this._ieFixTexture=null);this._framebuffer.texture.dispose();this._framebuffer.texture=null;this._linearDepthTextureHelper.getEnableState()&&this._linearDepthTextureHelper.disable();this._normalTextureHelper.getEnableState()&&this._normalTextureHelper.disable();this._highlightTextureHelper.getEnableState()&&this._highlightTextureHelper.setEnableState(!1);this._stencilRenderingHelper.getEnableState()&&this._stencilRenderingHelper.setEnableState(!1)};e.prototype.setLightingData=
function(a){this._lighting.set(a);this._needsRender=!0};e.prototype.getLightingData=function(){return this._lighting.get()};e.prototype.setPixelRatio=function(a){this._pixelRatio=a;this._needsRender=!0};e.prototype.getPixelRatio=function(){return this._pixelRatio};e.prototype.addExternalRenderer=function(a,b){this._externalRenderers.addRenderer(a,b);return!0};e.prototype.removeExternalRenderer=function(a){this._externalRenderers.removeRenderer(a);return!0};e.prototype.getExternalRenderers=function(){return this._externalRenderers};
e.prototype.resetNeedsRender=function(){this._needsRender=!1;this._externalRenderers.resetNeedsRender()};e.prototype.needsRender=function(){return this._needsRender||this._externalRenderers.needsRender()};e.prototype.getCombinedStats=function(){this._stats.VBOallocatedSize=0;this._stats.VBOoptimalSize=0;this._stats.VBOusedSize=0;for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data){var c=b.origin2data[d];this._stats.VBOallocatedSize+=c.buffer.getArray().length;
this._stats.VBOusedSize+=c.buffer.getSize();this._stats.VBOoptimalSize+=c.optimalCount}}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)c=b.origin2data[d],this._stats.VBOallocatedSize+=c.buffer.getArray().length,this._stats.VBOusedSize+=c.buffer.getSize(),this._stats.VBOoptimalSize+=c.optimalCount;this._stats.VBOallocatedSize*=0.00390625;this._stats.VBOusedSize*=0.00390625;this._stats.VBOoptimalSize*=0.00390625;return this._stats};e.prototype.setSelectionObject=function(a,
b){a?(Array.isArray(a)?this._selectionIndices=this._name2indices(Z(a)):this._selectionIndices=this._name2indices(Z([a])),this._selectionFaceIndexRange=void 0,null!=b&&1===b.length&&(this._selectionFaceIndexRange=[[3*b[0][0],3*b[0][1]]])):this._selectionFaceIndexRange=this._selectionIndices=void 0;this._needsRender=!0};e.prototype.renderGeometrySlots=function(a){this._externalRenderers.render(A.INTERNAL_MATERIAL,a);this._renderInternalSlot(A.STENCIL_MATERIAL,a);this._externalRenderers.render(A.OPAQUE_TERRAIN,
a);this._renderInternalSlot(A.OPAQUE_MATERIAL,a);this._externalRenderers.render(A.OPAQUE_EXTERNAL,a);a.ssaoHelper&&a.ssaoHelper.bindAll(this._programRep);this._renderInternalSlot(A.TRANSPARENT_MATERIAL,a);this.renderOptions.earlyOcclusionPixelDraw&&this._renderInternalSlot(A.OCCLUSION_PIXELS,this._renderContext);this._externalRenderers.render(A.TRANSPARENT_EXTERNAL,a);a.ssaoHelper&&a.ssaoHelper.bindAll(this._programRep);this._externalRenderers.render(A.TRANSPARENT_TERRAIN,a)};e.prototype._renderHighlights=
function(a,b,d,c){var f=!!c&&c.getEnableState()&&void 0!==this._selectionIndices;this._highlightTextureHelper.setEnableState(f);f&&(this._highlightTextureHelper.setupFBOs(a),this._highlightTextureHelper.prepareHighlightPass(),this.renderGeometryPass(B.MATERIAL_HIGHLIGHT,a,b,this._selectionIndices,this._selectionFaceIndexRange),this._rctx.clear(this._rctx.gl.DEPTH_BUFFER_BIT),this._renderInternalSlot(A.OVERLAY,this._renderContext),this._highlightTextureHelper.finish(d),b=this._highlightTextureHelper.getHighlightFBO(),
c.render(a,d,b))};e.prototype._renderUnordered=function(a,b,d,c,f,h,k){var m=this._rctx;this._isRendering=!0;this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._renderContext.pass=B.MATERIAL;this._renderContext.camera=a;this._renderContext.shadowMap=d;this._renderContext.ssaoHelper=c;this._renderContext.offscreenRenderingHelper=h;this._renderContext.stencilRenderingHelper=this._stencilRenderingHelper;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();
this._renderContext.normals=this._normalTextureHelper.getNormalFBO();this._renderContext.highlight=this._highlightTextureHelper.getHighlightFBO();this._renderContext.visibleContent=b;this._renderContext.filterContent=null;this._renderContext.filterFaceRange=null;this._renderContext.options=this.renderOptions;this._renderContext.rctx=this._rctx;h.setEnableState(!0);h.initializeFrame(a);this._externalRenderers.render(A.BACKGROUND,this._renderContext);this.renderGeometrySlots(this._renderContext);this._externalRenderers.render(A.POSTPROCESSING_ATMOSPHERE,
this._renderContext);switch(this.renderOptions.antialiasing){case "none":d=a.viewport;d=C.ortho(d[0],d[2],d[1],d[3],-1,1);h.drawQuad(d);this._fxaaPass.disable();this._smaaPass.disable();break;case "fxaa":this._smaaPass.disable();this._fxaaPass.render({colorTexture:h.getColorTexture()},null);break;case "smaa":this._fxaaPass.disable(),this._smaaPass.render({colorTexture:h.getColorTexture()},null)}this.renderOptions.earlyOcclusionPixelDraw||(h.bindFramebuffer(),this._renderInternalSlot(A.OCCLUSION_PIXELS,
this._renderContext));m.bindFramebuffer(null);this._renderContext.framebufferTex=h.getColorTexture();this._renderInternalSlot(A.OVERLAY,this._renderContext);this._renderHighlights(a,b,f,k);this._ieFixMaterial&&!f&&(m.setBlendFunctionSeparate(0,1,1,0),this._ieFixMaterial.bind(m,aa),this._ieFixMaterial.bindView(m,aa),this._initializeQuadVAO(),m.bindVAO(this._quadVAO),m.drawArrays(5,0,G.vertexCount(this._quadVAO,"geometry")),this._ieFixMaterial.release(m),m.setBlendFunctionSeparate(770,771,1,771));this._framesRendered++;
this._isRendering=!1};e.prototype._renderOrdered=function(a,b){var d=this._rctx;this._isRendering=!0;this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._bindParameters.view=a.viewMatrix;this._bindParameters.proj=a.projectionMatrix;this._bindParameters.viewInvTransp=a.viewInverseTransposeMatrix;K[0]=a.near;K[1]=a.far;this._bindParameters.nearFar=K;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=a.fullViewport;this._bindParameters.framebufferTex=
this._framebuffer.texture;this._bindParameters.pixelRatio=this._pixelRatio;this._bindParameters.instanceParameters=void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();this._bindParameters.normalFBO=this._normalTextureHelper.getNormalFBO();for(var c=!0,f=0;f<this._renderOrder.length;f++){var h=this._renderOrder[f][1];if(h.instanced){var k=h.instanced,m=k[B.MATERIAL];if(m&&(!m.isVisible||m.isVisible()))this._renderInternalInstanced(k,m,this._bindParameters,Infinity,b,null,
null,!1),c=!0}if(h.merged&&(k=h.merged,(m=k[B.MATERIAL])&&(!m.isVisible||m.isVisible())))c&&(c=m.getProgram(),d.bindProgram(c),c.setUniformMatrix4fv("model",H),c.hasUniform("modelNormal")&&c.setUniformMatrix4fv("modelNormal",H),c=!1),this._renderInternalMerged(k,m,this._bindParameters,Infinity)}this._framesRendered++;this._isRendering=!1};e.prototype.render=function(a,b,d,c,f,h,k){this._orderedRendering?this._renderOrdered(a,b):this._renderUnordered(a,b,d,c,f,k,h)};e.prototype.renderAuxiliaryBuffers=
function(a,b,d,c,f,h){h=this.ssaoEnabled;this._linearDepthTextureHelper.setEnableState(h);h&&(this._linearDepthTextureHelper.setupFBOs(a),this._linearDepthTextureHelper.prepareDepthPass(),this.renderGeometryPass(B.MATERIAL_DEPTH,a,b,void 0,void 0,d,c),this._linearDepthTextureHelper.finish(f));this._normalTextureHelper.setEnableState(this.ssaoEnabled);this.ssaoEnabled&&(this._normalTextureHelper.setupFBOs(a),this._normalTextureHelper.prepareNormalPass(),this.renderGeometryPass(B.MATERIAL_NORMAL,a,
b,void 0,void 0,d,c),this._normalTextureHelper.finish(f));this.ssaoEnabled&&c.computeSSAO(a,f,this._linearDepthTextureHelper.getDepthFBO(),this._normalTextureHelper.getNormalFBO());c.bindAll(this._programRep)};e.prototype.renderGeometryPass=function(a,b,d,c,f,h,k){this._isRendering=!0;this._updateGlobalUniforms(b.projectionMatrix);this._renderContext.pass=a;this._renderContext.camera=b;this._renderContext.shadowMap=h;this._renderContext.ssaoHelper=k;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();
this._renderContext.normals=this._normalTextureHelper.getNormalFBO();this._renderContext.visibleContent=d;this._renderContext.filterContent=c;this._renderContext.filterFaceRange=f;this._renderContext.rctx=this._rctx;this.renderGeometrySlots(this._renderContext);this._isRendering=!1};e.prototype.renderSelection=function(a){this._isRendering=!0;for(var b=0;b<A.MAX_SLOTS;++b)this._renderInternalSlot(b,a);this._isRendering=!1};e.prototype._renderInternalSlot=function(a,b){this._bindParameters.view=b.camera.viewMatrix;
this._bindParameters.proj=b.camera.projectionMatrix;this._bindParameters.viewInvTransp=b.camera.viewInverseTransposeMatrix;this._bindParameters.cameraAboveGround=b.camera.aboveGround;K[0]=b.camera.near;K[1]=b.camera.far;this._bindParameters.nearFar=K;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=b.camera.fullViewport;this._bindParameters.framebufferTex=this._renderContext.offscreenRenderingHelper?this._renderContext.offscreenRenderingHelper.getColorTexture():
this._framebuffer.texture;this._bindParameters.shadowMap=b.shadowMap;this._bindParameters.pixelRatio=this._pixelRatio;this._bindParameters.instanceParameters=void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();for(var d in this._mat2dataInstanced){var c=this._mat2dataInstanced[d],f=c[b.pass];f&&(f.beginSlot(a)&&(!f.isVisible||f.isVisible()))&&this._renderInternalInstanced(c,f,this._bindParameters,a,b.visibleContent,b.filterContent,b.filterFaceRange,!1)}if(b.filterContent)for(d in this._mat2dataMerged)c=
this._mat2dataMerged[d],(f=c[b.pass])&&(f.beginSlot(a)&&(!f.isVisible||f.isVisible()))&&this._renderInternalInstanced(c,f,this._bindParameters,a,null,b.filterContent,b.filterFaceRange,!0);else{for(var c=this._programRep.getProgramsUsingUniform("model"),f=this._programRep.getProgramsUsingUniform("modelNormal"),h=0;h<c.length;h++){var k=c[h];k.setUniformMatrix4fv("model",H);-1<f.indexOf(k)&&k.setUniformMatrix4fv("modelNormal",H)}for(d in this._mat2dataMerged)c=this._mat2dataMerged[d],(f=c[b.pass])&&
(f.beginSlot(a)&&(!f.isVisible||f.isVisible()))&&this._renderInternalMerged(c,f,this._bindParameters,a)}this._stencilRenderingHelper.getEnableState()&&a===A.STENCIL_MATERIAL&&this._stencilRenderingHelper.prepareStencilDisabledPass()};e.prototype._renderInternalInstanced=function(a,b,d,c,f,h,k,m){var l=this._rctx,g=l.gl,e=!1,u=b.getDrawMode(l),r=this._bindParameters.extensions.angleInstancedArrays,q;for(q in a.origin2data){var y=a.origin2data[q];d.origin=y.origin;c===A.STENCIL_MATERIAL&&(this._stencilRenderingHelper.setEnableState(!0),
this._stencilRenderingHelper.prepareStencilWritePass());var v=!1;if(b.instanced)for(var w in y.perGeometryDataInfo){var s=y.perGeometryDataInfo[w];e||(b.bind(l,d),e=!0);l.bindVAO(s.vao);var n=b.getProgram();G.assertCompatibleVertexAttributeLocations(s.vao,n);v||(b.bindView(l,d),v=!0);var n=s.to-s.from,p=s.refCount;u===g.TRIANGLES&&(this._stats.trianglesRendered+=p*n/3);r.drawArraysInstancedANGLE(u,s.from,n,p);this._stats.drawCallsAngleInstanced++;this._stats.instancesDrawnAngle+=p}else{var s=y.instances,
t;for(t in s){var n=s[t],p=n.idx,z=n.displayedIndexRange;k&&(z=k);if(!(z&&0===z.length)&&!(f&&!f.get(p)||h&&!h.get(p)))e||(b.bind(l,d),e=!0),v||(l.bindVAO(y.vao),b.bindView(l,d),v=!0),m||b.bindInstance(l,n),this._stats.drawCallsInstanced++,u===g.TRIANGLES&&(this._stats.trianglesRendered+=(n.to-n.from)/3),z?this._drawArraysFaceRange(z,n.from,u):l.drawArrays(u,n.from,n.to-n.from)}}}l.bindVAO(null);e&&b.release(l,d)};e.prototype._drawArraysFaceRange=function(a,b,d){for(var c=this._rctx,f=0;f<a.length;f++){var h=
a[f];c.drawArrays(d,h[0]+b,h[1]-h[0]+1)}this._stats.drawCallsFragmented+=a.length-1};e.prototype._renderInternalMerged=function(a,b,d,c){var f=this._rctx,h=f.gl,k=!1,m;for(m in a.origin2data){var l=a.origin2data[m];d.origin=l.origin;c===A.STENCIL_MATERIAL&&(this._stencilRenderingHelper.setEnableState(!0),this._stencilRenderingHelper.prepareStencilWritePass());if(!(l.displayedIndexRange&&0===l.displayedIndexRange.length)){k||(b.bind(f,d),k=!0);var g=b.getProgram();f.bindVAO(l.vao);G.assertCompatibleVertexAttributeLocations(l.vao,
g);b.bindView(f,d);this._stats.drawCallsMerged++;g=b.getDrawMode(f);g===h.TRIANGLES&&(this._stats.trianglesRendered+=l.vao.vertexBuffers.geometry.size/3);l.displayedIndexRange?this._drawArraysFaceRange(l.displayedIndexRange,0,g):f.drawArrays(g,0,G.vertexCount(l.vao,"geometry"))}}k&&b.release(f,d)};e.prototype._updateGlobalUniforms=function(a){for(var b=this._programRep.getProgramsUsingUniform("proj"),d=0;d<b.length;d++)b[d].setUniformMatrix4fv("proj",a);if(this._lighting){b=this._programRep.getProgramsUsingUniform("lightDirection");
for(d=0;d<b.length;d++)this._lighting.setUniforms(b[d])}};e.prototype.print=function(){var a=Object.keys(this._mat2dataMerged).length,b=Object.keys(this._mat2dataInstanced).length;console.log("number of materials (merged/instanced): "+a+"/"+b);var a=0,d;for(d in this._mat2dataMerged){var b=this._mat2dataMerged[d],c;for(c in b.origin2data)a+=Object.keys(b.origin2data[c].instances).length}var f=0;for(d in this._mat2dataInstanced)for(c in b=this._mat2dataInstanced[d],b.origin2data)f+=Object.keys(b.origin2data[c].instances).length;
console.log("number of instances (merged/instanced): "+a+"/"+f)};e.prototype.isEmpty=function(){for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data)if(!$(b.origin2data[d].instances))return!1}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)if(!$(b.origin2data[d].instances))return!1;return!0};e.prototype.modify=function(a,b,d,c){this._isRendering&&console.warn("Renderer.modify called while rendering");var f=[],h=[];this._mergedOrInstanced(a,
f,h);a=[];var k=[];this._mergedOrInstanced(b,a,k);b={};d&&this._performUpdates(d,b);d=[];this._modifyMerged(f,a,d,b);this._modifyInstanced(h,k,d);this._updateMergedFaceranges(b);this._releaseMaterials(d);this._modifyMaterials(c);this._needsRender=!0};e.prototype._isInstanced=function(a){var b=!1,d=J(a.data.faces.indices).length,b=(b=(b=b||!1===a.material.canBeMerged)||a.material.instanced)||a.material.isBackdrop;return a.singleUse?b:b=b||d>this._threshold};e.prototype._mergedOrInstanced=function(a,
b,d){for(var c=0;c<a.length;++c)1>J(a[c].data.faces.indices).length||(this._isInstanced(a[c])?d.push(a[c]):b.push(a[c]))};e.prototype._performUpdates=function(a,b){for(var d=0;d<a.length;d++){var c=a[d],f=c.renderGeometry,h=this._isInstanced(f),c=c.updateType;c&2&&this._updateFaceranges(f,h,b);c&4||!h&&c&16?this._updateVertexAttributes(f,h):h&&c&16?this._updateInstanceTransformation(f,h):c&8&&this._updateColorAttributes(f)}};e.prototype._updateFaceranges=function(a,b,d){var c=a.material.getId(),f=
a.origin.id,h=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[f],k=h.instances[a.uniqueName];k&&(k.displayedIndexRange=a.displayedIndexRange,b||(d[this._modifiedMergedFacerangesKey(c,f)]=h))};e.prototype._updateMergedFaceranges=function(a){for(var b in a){var d=a[b];d.displayedIndexRange=[];var c=d.instances,f=!0,h;for(h in c){var k=c[h];k.displayedIndexRange?(d.displayedIndexRange.push.apply(d.displayedIndexRange,V.offsetIntervals(k.displayedIndexRange,k.from)),f=!1):d.displayedIndexRange.push([k.from,
k.to-1])}d.displayedIndexRange=f?null:V.mergeIntervals(d.displayedIndexRange)}};e.prototype._updateVertexAttributes=function(a,b){var d=a.material,c=d.getId(),c=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[a.origin.id],f=c.instances[a.uniqueName],h,k;b||(h=a.origin.vec3,R(I,-h[0],-h[1],-h[2]),C.multiply(I,a.transformation,L),C.inverse(L,M),C.transpose(M),h=L,k=M);var m=G.getStride(d.getVertexBufferLayout()),l=m/4;E(f.from+d.getOutputAmount(J(a.data.faces.indices).length)/l===f.to,
"material VBO layout has changed");d.fillInterleaved(a.data,h,k,a.instanceParameters,c.buffer.getArray(),f.from*l);c.vao.vertexBuffers.geometry.setSubData(c.buffer.getArray(),f.from*m,f.from*m,f.to*m)};e.prototype._updateInstanceTransformation=function(a,b){var d=a.origin.vec3,c=(b?this._mat2dataInstanced:this._mat2dataMerged)[a.material.getId()].origin2data[a.origin.id],f=c.instances[a.uniqueName];R(I,-d[0],-d[1],-d[2]);C.multiply(I,a.transformation,f.transformation);C.inverse(f.transformation,f.transformationNormal);
C.transpose(f.transformationNormal,f.transformationNormal);d=c.perGeometryDataInfo[a.data.id];if(c=d.instanceBufferData){var h=c.getSlot(a.idx);c.fill(h,0,f.transformation);c.fill(h,16,f.transformationNormal);f=4*c.getOffset(h);h=G.getStride(d.vao.layout.instance);d.vao.vertexBuffers.instance.setSubData(c.getArray(),f,f,f+h)}};e.prototype._updateColorAttributes=function(a){var b=a.material,d=b.getId(),c=a.origin.id,d=(this._isInstanced(a)?this._mat2dataInstanced:this._mat2dataMerged)[d].origin2data[c],
c=d.instances[a.uniqueName],f={};f[pa.COLOR]=!0;var h=G.getStride(b.getVertexBufferLayout())/4;E(c.from+b.getOutputAmount(J(a.data.faces.indices).length)/h===c.to,"material VBO layout has changed");b.fillInterleaved(a.data,void 0,void 0,a.instanceParameters,d.buffer.getArray(),c.from*h,f);d.vao.vertexBuffers.geometry.setSubData(d.buffer.getArray(),4*c.from*h,4*c.from*h,4*c.to*h)};e.prototype._modifyMerged=function(a,b,d,c){var f=this._rctx;a=this._compMat2delta(a,b,!1);for(var h in a){b=a[h];for(var k in b){var m=
b[k],l=m.optimalCount,g=m.material,e=g.getVertexBufferLayout(),u=G.getStride(e)/4,r=this._mat2dataMerged[h];if(null==r){E(0<l);var q=g.getRenderPriority(),r={origin2data:{}};r[B.MATERIAL]=this._materialRep.aquire(g);r[B.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(g);r[B.MATERIAL_NORMAL]=this._materialRep.aquireNormal(g);r[B.MATERIAL_DEPTH]=this._materialRep.aquireDepth(g);r[B.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(g);this._mat2dataMerged[h]=r;this._orderedRendering&&
this._insertIntoRenderOrder(r,q,"merged")}q=r.origin2data[k];null==q&&(E(0<l),q={instances:{},vao:new O(f,Q.Default3D,{geometry:e},{geometry:P.createVertex(f,35044)}),buffer:new W(l),optimalCount:0,origin:m.origin},r.origin2data[k]=q);if(0<l){var e=q.buffer.getSize(),y=q.buffer.getArray(),r=l<m.sparseCount/2,v=q.buffer.resize(r?l:m.sparseCount),w=m.toRemove;if(r||v){for(var e=0,s=q.buffer.getArray(),r=0,n=w.length;r<n;++r)v=q.instances[w[r].uniqueName],q.optimalCount-=(v.to-v.from)*u,delete q.instances[w[r].uniqueName];
var r={},p;for(p in q.instances)v=q.instances[p],E(null==r[v.from]),r[v.from]=v;for(var t in r){var v=r[t],n=v.from*u,z=v.to*u;s.set(y.subarray(n,z),e);v.from=e/u;e+=z-n;v.to=e/u}E(e===q.optimalCount)}else{r=0;for(v=w.length;r<v;++r)y=w[r].uniqueName,E(void 0!==q.instances[y]),n=q.instances[y].from*u,z=q.instances[y].to*u,q.buffer.erase(n,z),delete q.instances[y],q.optimalCount-=z-n}R(I,-m.origin[0],-m.origin[1],-m.origin[2]);w=m.toAdd;m=!1;r=0;for(y=w.length;r<y;++r)n=w[r],z=n.data,C.multiply(I,
n.transformation,L),C.inverse(L,M),C.transpose(M),v=e,g.fillInterleaved(z,L,M,n.instanceParameters,q.buffer.getArray(),e),z=g.getOutputAmount(J(z.faces.indices).length),s=v+z,E(null==q.instances[n.uniqueName]),v=new ba(n.name,v/u,s/u,n.displayedIndexRange,void 0,void 0,n.idx),n.displayedIndexRange&&(m=!0),q.instances[n.uniqueName]=v,q.optimalCount+=z,e+=z;E(q.optimalCount===l);l=new Float32Array(q.buffer.getArray().buffer,0,q.buffer.getSize());q.vao.vertexBuffers.geometry.setData(l);if(m||q.displayedIndexRange)c[this._modifiedMergedFacerangesKey(h,
k)]=q}else E(0===l),q.vao.dispose(!0),q.vao=null,delete r.origin2data[k],0===Object.keys(r.origin2data).length&&(d.push(h),delete this._mat2dataMerged[h],this._orderedRendering&&this._removeFromRenderOrder(r,"merged"))}}};e.prototype._modifyInstanced=function(a,b,d){a=this._compMat2delta(a,b,!0);b=this._rctx;for(var c in a){var f=a[c],h;for(h in f){var k=f[h];if(0===k.optimalCount)k=this._mat2dataInstanced[c],k.origin2data[h].vao.dispose(!0),delete k.origin2data[h],0===Object.keys(k.origin2data).length&&
(d.push(c),delete this._mat2dataInstanced[c],this._orderedRendering&&this._removeFromRenderOrder(k,"instanced"));else{var e=k.material,l=this._mat2dataInstanced[c];if(null==l){var g=e.getRenderPriority(),l={origin2data:{}};l[B.MATERIAL]=this._materialRep.aquire(e);l[B.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(e);l[B.MATERIAL_NORMAL]=this._materialRep.aquireNormal(e);l[B.MATERIAL_DEPTH]=this._materialRep.aquireDepth(e);l[B.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(e);
this._mat2dataInstanced[c]=l;this._orderedRendering&&this._insertIntoRenderOrder(l,g,"instanced")}var x=e.getVertexBufferLayout(),u=l[B.MATERIAL].instanced?e.getInstanceBufferLayout():void 0,r=u&&G.findAttribute(u,"instanceColor"),q=u&&G.findAttribute(u,"instanceFeatureAttribute"),y=G.getStride(x)/4,g=l.origin2data[h];null==g&&(g={instances:{},vao:new O(b,Q.Default3D,{geometry:x},{geometry:P.createVertex(b,35044)}),buffer:new W(k.optimalCount),optimalCount:0,perGeometryDataInfo:{},origin:k.origin},
l.origin2data[h]=g);var l=g.buffer.getSize(),v=g.buffer.getArray(),w=k.optimalCount<k.sparseCount/2,s=g.buffer.resize(w?k.optimalCount:k.sparseCount),n;for(n in k.perGeometryDelta){var p=g.perGeometryDataInfo[n];if(p&&p.instanceBufferData){var t=k.perGeometryDelta[n].removeCount;0<t&&p.instanceBufferData.prepareFree(t)}}var z=k.toRemove;if(w||s){w=0;for(l=z.length;w<l;++w){s=z[w];delete g.instances[s.uniqueName];n=s.data.id;var D=p=g.perGeometryDataInfo[n];0===--D.refCount&&null==k.dataId2refCount[n]?
(g.optimalCount-=(D.to-D.from)*y,delete g.perGeometryDataInfo[n]):p.instanceBufferData&&p.instanceBufferData.free(s.idx)}var l=0,w=g.buffer.getArray(),s={},A;for(A in g.perGeometryDataInfo)D=g.perGeometryDataInfo[A],E(null==s[D.from]),s[D.from]=D;for(var F in s)D=s[F],t=D.from*y,p=D.to*y,w.set(v.subarray(t,p),l),D.from=l/y,l+=p-t,D.to=l/y;for(var H in g.instances)t=g.instances[H],t.from=g.perGeometryDataInfo[t.dataId].from,t.to=g.perGeometryDataInfo[t.dataId].to}else{w=0;for(v=z.length;w<v;++w)s=
z[w],delete g.instances[s.uniqueName],n=s.data.id,p=g.perGeometryDataInfo[n],0===--p.refCount&&null==k.dataId2refCount[n]?(t=p.from*y,p=p.to*y,g.buffer.erase(t,p),g.optimalCount-=p-t,delete g.perGeometryDataInfo[n]):p.instanceBufferData&&p.instanceBufferData.free(s.idx)}R(I,-k.origin[0],-k.origin[1],-k.origin[2]);for(n in k.perGeometryDelta)if((p=g.perGeometryDataInfo[n])&&p.instanceBufferData)w=k.perGeometryDelta[n].addCount,0<w&&p.instanceBufferData.prepareAllocate(w);v=k.toAdd;w=0;for(z=v.length;w<
z;++w){s=v[w];t=s.data;n=t.id;p=g.perGeometryDataInfo[n];null==p?(e.fillInterleaved(t,void 0,void 0,void 0,g.buffer.getArray(),l),D=e.getOutputAmount(J(t.faces.indices).length),t=l/y,l+=D,p=l/y,g.optimalCount+=D,p={refCount:1,from:t,to:p,vao:null,instanceBufferData:null},u&&(t=G.getStride(u)/4,p.vao=new O(b,Q.Default3D,{geometry:x,instance:u},{geometry:g.vao.vertexBuffers.geometry,instance:P.createVertex(b,35044)}),p.instanceBufferData=new ca(t,k.perGeometryDelta[n].addCount)),g.perGeometryDataInfo[n]=
p):++p.refCount;E(p.from*y<=g.buffer.getSize()&&p.to*y<=g.buffer.getSize());t=C.create();C.multiply(I,s.transformation,t);t=new ba(s.name,p.from,p.to,s.displayedIndexRange,t,s.instanceParameters,s.idx,n);if(p=p.instanceBufferData)D=p.allocate(s.idx),p.fill(D,0,t.transformation),p.fill(D,16,t.transformationNormal),r&&p.fill(D,r.offset/4,s.instanceParameters.color),q&&p.fill(D,q.offset/4,s.instanceParameters.featureAttribute);g.instances[s.uniqueName]=t}E(g.optimalCount===k.optimalCount);e=new Float32Array(g.buffer.getArray().buffer,
0,g.buffer.getSize());g.vao.vertexBuffers.geometry.setData(e);for(n in g.perGeometryDataInfo)if(x=g.perGeometryDataInfo[n],x.vao&&(e=x.vao.vertexBuffers.instance))u=k.perGeometryDelta[n],0<u.addCount+u.removeCount&&(x=x.instanceBufferData.compact(),e.setData(x))}}}};e.prototype._compMat2delta=function(a,b,d){var c={};this._updateMat2delta(a,!0,d,c);this._updateMat2delta(b,!1,d,c);return c};e.prototype._updateMat2delta=function(a,b,d,c){for(var f=0,h=a.length;f<h;++f){var e=a[f],m=e.origin,l=e.material,
g=l.getId(),x=d?this._mat2dataInstanced[g]:this._mat2dataMerged[g],x=x&&x.origin2data[m.id],u=c[g];null==u&&(u={},c[g]=u);g=u[m.id];if(null==g){g={optimalCount:null==x?0:x.optimalCount,sparseCount:null==x?0:x.buffer.getSize(),material:l,toAdd:[],toRemove:[],perGeometryDelta:null,origin:m.vec3};if(d){var r={};if(void 0!==x)for(var q in x.perGeometryDataInfo)r[q]=x.perGeometryDataInfo[q].refCount;g.dataId2refCount=r;g.perGeometryDelta={}}u[m.id]=g}m=l.getOutputAmount(J(e.data.faces.indices).length);
d?(l=e.data.id,x=g.perGeometryDelta[l],x||(x={addCount:0,removeCount:0},g.perGeometryDelta[l]=x),b?(x.addCount++,null==g.dataId2refCount[l]&&(g.dataId2refCount[l]=0),1===++g.dataId2refCount[l]&&(g.optimalCount+=m,g.sparseCount+=m),g.toAdd.push(e)):(x.removeCount++,0===--g.dataId2refCount[l]&&(delete g.dataId2refCount[l],g.optimalCount-=m),g.toRemove.push(e))):b?(g.optimalCount+=m,g.sparseCount+=m,g.toAdd.push(e)):(g.optimalCount-=m,g.toRemove.push(e))}};e.prototype._modifiedMergedFacerangesKey=function(a,
b){return a+"_"+b};e.prototype._insertIntoRenderOrder=function(a,b,d){for(var c=a[B.MATERIAL].getMaterialId(),f=this._renderOrder.length,h=0;h<f&&this._renderOrder[h][0]>=b;){var e=this._renderOrder[h][1];if(e.id===c){E(!e[d],"matData for type already exists");e[d]=a;return}h++}c={id:c,instanced:null,merged:null};c[d]=a;this._renderOrder.splice(h,0,[b,c])};e.prototype._removeFromRenderOrder=function(a,b){for(var d=a[B.MATERIAL].getMaterialId(),c=0;this._renderOrder[c][1].id!==d;)c++;d=this._renderOrder[c][1];
d[b]=null;!d.instanced&&!d.merged&&this._renderOrder.splice(c,1)};e.prototype._updateRenderOrder=function(a,b){for(var d=b.length,c=0;c<d&&b[c][1].id!==a;)c++;if(c<d){var f=b[c][1],f=(f.merged||f.instanced)[B.MATERIAL].getRenderPriority(),e=b[c][0];if(f!==b[c][0]){b[c][0]=f;e=f>e?-1:1;for(c+=e;-1<c&&c<d&&e*b[c][0]>e*f;){var k=b[c];b[c]=b[c-e];b[c-e]=k;c+=e}}}};e.prototype._modifyMaterials=function(a){for(var b in a)this._materialRep.updateMaterialParameters(b)};e.prototype.modifyRenderOrder=function(a){if(this._orderedRendering){for(var b in a)this._updateRenderOrder(b,
this._renderOrder);this._needsRender=!0}};e.prototype._releaseMaterials=function(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)this._materialRep.release(a[b]),this._materialRep.releaseDepthShadowMap(a[b]),this._materialRep.releaseNormal(a[b]),this._materialRep.releaseDepth(a[b]),this._materialRep.releaseHighlight(a[b]);else this._materialRep.release(a),this._materialRep.releaseDepthShadowMap(a),this._materialRep.releaseNormal(a),this._materialRep.releaseDepth(a),this._materialRep.releaseHighlight(a)};
e.prototype._name2indices=function(a){for(var b=new la,d=0;2>d;++d){var c=0===d?this._mat2dataMerged:this._mat2dataInstanced,f;for(f in c){var e=c[f].origin2data,k;for(k in e){var m=e[k].instances,l;for(l in m){var g=m[l];void 0!==a[g.name]&&b.set(g.idx)}}}}return b};return e}();var ra=function(){function e(){this.reset()}e.prototype.reset=function(){this.VBOusedSize=this.VBOoptimalSize=this.VBOallocatedSize=this.instancesDrawnAngle=this.drawCallsFragmented=this.drawCallsMerged=this.drawCallsAngleInstanced=
this.drawCallsInstanced=this.trianglesRendered=0};return e}(),ba=function(){return function(e,a,b,d,c,f,h,k){this.name=e;this.from=a;this.to=b;this.displayedIndexRange=d;this.transformation=c;this.instanceParameters=f;this.idx=h;this.dataId=k;null!=c&&(this.transformationNormal=C.create(),C.set(c,this.transformationNormal),C.inverse(this.transformationNormal,this.transformationNormal),C.transpose(this.transformationNormal,this.transformationNormal))}}(),K=T.create(),I=C.identity(),L=C.create(),M=
C.create();return F});