// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./Renderer ./Camera ./Util ./gl-matrix ../materials/internal/TexOnlyGLMaterial ../../../webgl/Texture ../../../webgl/FramebufferObject ../../../webgl/VertexArrayObject ../../../webgl/BufferObject ../../../webgl/Util ../../../webgl/enums ./DefaultVertexBufferLayouts ./DefaultVertexAttributeLocations".split(" "),function(q,H,s,t,u,p,v,w,x,y,z,A,I,B,C){var D=p.vec3d,E=p.vec4d,m=p.mat4d;q=function(){function c(b,h,d,a,e,f){this._acquiredTextures={};this._clearColor=E.createFrom(0,
0,0,0);this._id2origin={};this._rctx=b;this._canvas=h;this._programRep=d;this._materialRep=a;this._textureRep=e;this._modelDirtySet=f;this._renderer=new s(d,a,e,this._rctx,!0);this._renderer.setLightingData({ambient:[1,1,1,1],diffuse:[0,0,0,0],specular:[0,0,0,0],direction:[0,-1,0]})}c.prototype.dispose=function(){for(var b in this._acquiredTextures)this._acquiredTextures[b].fbo.dispose(),this._textureRep.release(b);this._acquiredTextures=null;this._renderer.dispose();this._renderer=null};c.prototype.addRenderGeometries=
function(b){var h=this;b.forEach(function(b){null==b.origin&&(b.origin=h.getOrigin(b.center,b.bsRadius))});this._renderer.modify(b,[])};c.prototype.removeRenderGeometries=function(b){this._renderer.modify([],b)};c.prototype.updateRenderGeometries=function(b,h){var d=b.map(function(a){return{renderGeometry:a,updateType:h}});this._renderer.modify([],[],d,{})};c.prototype.updateRenderOrder=function(b){0<Object.keys(b).length&&this._renderer.modifyRenderOrder(b)};c.prototype.setBackgroundColor=function(b){this._clearColor=
b};c.prototype.isEmpty=function(){return this._renderer.isEmpty()};c.prototype.processDirtyMaterials=function(){var b=this._modelDirtySet.getDirtyMaterials();b&&this._renderer.modify([],[],[],b);this._modelDirtySet.clearDirtyMaterials()};c.prototype.draw=function(b,h){this.processDirtyMaterials();var d=b.id.toString(),a,e=this._rctx,f=e.gl;if(this._acquiredTextures[d])a=this._acquiredTextures[d].fbo;else{var g=this._textureRep.aquire(d).getGLTexture();a=x.createWithAttachments(this._rctx,g,{colorTarget:0,
depthStencilTarget:0});g=Object.keys(this._acquiredTextures).length;this._acquiredTextures[d]={texture:b,fbo:a,idx:g}}var g=h.width,l=h.height;if(a.width!==g||a.height!==l)a.resize(g,l),a.colorTexture.setSamplingMode(9729);k.near=1;k.far=1E4;e.bindFramebuffer(a);e.setDepthTestEnabled(!1);e.setBlendFunctionSeparate(770,771,1,771);e.setClearColor.apply(e,this._clearColor);e.clear(f.COLOR_BUFFER_BIT);this._renderer.setPixelRatio(h.pixelRatio||1);for(f=0;f<h.views.length;f++)a=h.views[f],k.viewport=a.viewport,
m.ortho(0,a.extent[2]-a.extent[0],0,a.extent[3]-a.extent[1],k.near,k.far,k.projectionMatrix),m.identity(k.viewMatrix),m.translate(k.viewMatrix,[-a.extent[0],-a.extent[1],0]),k.setGLViewport(this._rctx),F&&this._drawTestTexture(g,l,r[this._acquiredTextures[d].idx%r.length]),this._renderer.render(k,G);e.setDepthTestEnabled(!0);e.setBlendFunctionSeparate(770,771,1,771);e.bindFramebuffer(null);e.setViewport(0,0,this._canvas.width,this._canvas.height)};c.prototype._drawTestTexture=function(b,h,d){var a=
this._rctx,e=a.gl;if(!this._testPatternMat){for(var f=new Uint8Array(4*b*h),g=0,l=0;l<h;l++)for(var c=0;c<b;c++){var k=Math.floor(c/10),n=Math.floor(l/10);2>k||2>n||10*k>b-20||10*n>h-20?(f[g++]=255,f[g++]=255,f[g++]=255,f[g++]=255):(f[g++]=255,f[g++]=255,f[g++]=255,k&1&&n&1?f[g++]=c&1^l&1?0:255:f[g++]=k&1^n&1?0:128)}b=new w(a,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:b,height:h},f);this._testPatternMat=new v(this._programRep,b,[1,1,1,1],!0,e.ALWAYS);this._testPatternBindParams=
{proj:m.identity(),view:m.identity(),nearFar:[-1,1],origin:[0,0,0]};e=new Float32Array([-1,-1,0,0,0,1,-1,0,1,0,-1,1,0,0,1,1,1,0,1,1]);this._quadVAO=new y(a,C.Default3D,{geometry:B.Pos3Tex},{geometry:z.createVertex(a,35044,e)})}this._testPatternMat.setColor([d[0],d[1],d[2],1]);this._testPatternMat.bind(a,this._testPatternBindParams);this._testPatternMat.bindView(a,this._testPatternBindParams);a.bindVAO(this._quadVAO);a.drawArrays(5,0,A.vertexCount(this._quadVAO,"geometry"));this._testPatternMat.release(a)};
c.prototype.getOrigin=function(b,h){var d=0,a=10*h/1E4;1<a&&(d=Math.ceil(u.logWithBase(a,2)));var a=1E4*Math.pow(2,d),e=Math.round(b[0]/a),f=Math.round(b[1]/a),g=Math.round(b[2]/a),d=d+"_"+e+"_"+f+"_"+g,c=this._id2origin[d];null==c&&(c={vec3:D.createFrom(e*a,f*a,g*a),id:d},this._id2origin[d]=c);return c};return c}();var F=!1,r=[[1,0.5,0.5],[0.5,0.5,1],[0.5,1,0.5]],G={get:function(){return!0}},k=new t;return q});