//>>built
require({cache:{"dojox/gfx/shape":function(){define("./_base dojo/_base/lang dojo/_base/declare dojo/_base/kernel dojo/_base/sniff dojo/on dojo/_base/array dojo/dom-construct dojo/_base/Color ./matrix".split(" "),function(f,q,p,s,l,c,m,g,h,b){function n(a,d){if(!t)return a.splice(d,1);var b=a.length;if(b){for(;d<b;)a[d]=a[d+1],d++;a.length--}}var t=!!l("chrome"),k=f.shape={};k.Shape=p("dojox.gfx.shape.Shape",null,{constructor:function(){this.parentMatrix=this.parent=this.bbox=this.strokeStyle=this.fillStyle=
this.matrix=this.shape=this.rawNode=null;if(l("gfxRegistry")){var a=k.register(this);this.getUID=function(){return a}}},destroy:function(){l("gfxRegistry")&&k.dispose(this);this.rawNode&&"__gfxObject__"in this.rawNode&&(this.rawNode.__gfxObject__=null);this.rawNode=null},getNode:function(){return this.rawNode},getShape:function(){return this.shape},getTransform:function(){return this.matrix},getFill:function(){return this.fillStyle},getStroke:function(){return this.strokeStyle},getParent:function(){return this.parent},
getBoundingBox:function(){return this.bbox},getTransformedBoundingBox:function(){var a=this.getBoundingBox();if(!a)return null;var d=this._getRealMatrix();return[b.multiplyPoint(d,a.x,a.y),b.multiplyPoint(d,a.x+a.width,a.y),b.multiplyPoint(d,a.x+a.width,a.y+a.height),b.multiplyPoint(d,a.x,a.y+a.height)]},getEventSource:function(){return this.rawNode},setClip:function(a){this.clip=a},getClip:function(){return this.clip},setShape:function(a){this.shape=f.makeParameters(this.shape,a);this.bbox=null;
return this},setFill:function(a){if(!a)return this.fillStyle=null,this;var d=null;if("object"==typeof a&&"type"in a)switch(a.type){case "linear":d=f.makeParameters(f.defaultLinearGradient,a);break;case "radial":d=f.makeParameters(f.defaultRadialGradient,a);break;case "pattern":d=f.makeParameters(f.defaultPattern,a)}else d=f.normalizeColor(a);this.fillStyle=d;return this},setStroke:function(a){if(!a)return this.strokeStyle=null,this;if("string"==typeof a||q.isArray(a)||a instanceof h)a={color:a};a=
this.strokeStyle=f.makeParameters(f.defaultStroke,a);a.color=f.normalizeColor(a.color);return this},setTransform:function(a){this.matrix=b.clone(a?b.normalize(a):b.identity);return this._applyTransform()},_applyTransform:function(){return this},moveToFront:function(){var a=this.getParent();a&&(a._moveChildToFront(this),this._moveToFront());return this},moveToBack:function(){var a=this.getParent();a&&(a._moveChildToBack(this),this._moveToBack());return this},_moveToFront:function(){},_moveToBack:function(){},
applyRightTransform:function(a){return a?this.setTransform([this.matrix,a]):this},applyLeftTransform:function(a){return a?this.setTransform([a,this.matrix]):this},applyTransform:function(a){return a?this.setTransform([this.matrix,a]):this},removeShape:function(a){this.parent&&this.parent.remove(this,a);return this},_setParent:function(a,d){this.parent=a;return this._updateParentMatrix(d)},_updateParentMatrix:function(a){this.parentMatrix=a?b.clone(a):null;return this._applyTransform()},_getRealMatrix:function(){for(var a=
this.matrix,d=this.parent;d;)d.matrix&&(a=b.multiply(d.matrix,a)),d=d.parent;return a}});k._eventsProcessing={on:function(a,d){return c(this.getEventSource(),a,k.fixCallback(this,f.fixTarget,d))},connect:function(a,d,b){"on"==a.substring(0,2)&&(a=a.substring(2));return this.on(a,b?q.hitch(d,b):d)},disconnect:function(a){return a.remove()}};k.fixCallback=function(a,d,b,c){c||(c=b,b=null);if(q.isString(c)){b=b||s.global;if(!b[c])throw['dojox.gfx.shape.fixCallback: scope["',c,'"] is null (scope\x3d"',
b,'")'].join("");return function(f){return d(f,a)?b[c].apply(b,arguments||[]):void 0}}return!b?function(f){return d(f,a)?c.apply(b,arguments):void 0}:function(f){return d(f,a)?c.apply(b,arguments||[]):void 0}};q.extend(k.Shape,k._eventsProcessing);k.Container={_init:function(){this.children=[];this._batch=0},openBatch:function(){return this},closeBatch:function(){return this},add:function(a){var d=a.getParent();d&&d.remove(a,!0);this.children.push(a);return a._setParent(this,this._getRealMatrix())},
remove:function(a,d){for(var b=0;b<this.children.length;++b)if(this.children[b]==a){d||(a.parent=null,a.parentMatrix=null);n(this.children,b);break}return this},clear:function(a){for(var d,b=0;b<this.children.length;++b)d=this.children[b],d.parent=null,d.parentMatrix=null,a&&d.destroy();this.children=[];return this},getBoundingBox:function(){if(this.children){var a=null;m.forEach(this.children,function(d){var c=d.getBoundingBox();c&&((d=d.getTransform())&&(c=b.multiplyRectangle(d,c)),a?(a.x=Math.min(a.x,
c.x),a.y=Math.min(a.y,c.y),a.endX=Math.max(a.endX,c.x+c.width),a.endY=Math.max(a.endY,c.y+c.height)):a={x:c.x,y:c.y,endX:c.x+c.width,endY:c.y+c.height})});a&&(a.width=a.endX-a.x,a.height=a.endY-a.y);return a}return null},_moveChildToFront:function(a){for(var d=0;d<this.children.length;++d)if(this.children[d]==a){n(this.children,d);this.children.push(a);break}return this},_moveChildToBack:function(a){for(var d=0;d<this.children.length;++d)if(this.children[d]==a){n(this.children,d);this.children.unshift(a);
break}return this}};k.Surface=p("dojox.gfx.shape.Surface",null,{constructor:function(){this._parent=this.rawNode=null;this._nodes=[];this._events=[]},destroy:function(){m.forEach(this._nodes,g.destroy);this._nodes=[];m.forEach(this._events,function(a){a&&a.remove()});this._events=[];this.rawNode=null;if(l("ie"))for(;this._parent.lastChild;)g.destroy(this._parent.lastChild);else this._parent.innerHTML="";this._parent=null},getEventSource:function(){return this.rawNode},_getRealMatrix:function(){return null},
isLoaded:!0,onLoad:function(a){},whenLoaded:function(a,d){var b=q.hitch(a,d);if(this.isLoaded)b(this);else c.once(this,"load",function(a){b(a)})}});q.extend(k.Surface,k._eventsProcessing);k.Rect=p("dojox.gfx.shape.Rect",k.Shape,{constructor:function(a){this.shape=f.getDefault("Rect");this.rawNode=a},getBoundingBox:function(){return this.shape}});k.Ellipse=p("dojox.gfx.shape.Ellipse",k.Shape,{constructor:function(a){this.shape=f.getDefault("Ellipse");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=
this.shape;this.bbox={x:a.cx-a.rx,y:a.cy-a.ry,width:2*a.rx,height:2*a.ry}}return this.bbox}});k.Circle=p("dojox.gfx.shape.Circle",k.Shape,{constructor:function(a){this.shape=f.getDefault("Circle");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}}return this.bbox}});k.Line=p("dojox.gfx.shape.Line",k.Shape,{constructor:function(a){this.shape=f.getDefault("Line");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=
this.shape;this.bbox={x:Math.min(a.x1,a.x2),y:Math.min(a.y1,a.y2),width:Math.abs(a.x2-a.x1),height:Math.abs(a.y2-a.y1)}}return this.bbox}});k.Polyline=p("dojox.gfx.shape.Polyline",k.Shape,{constructor:function(a){this.shape=f.getDefault("Polyline");this.rawNode=a},setShape:function(a,d){a&&a instanceof Array?(this.inherited(arguments,[{points:a}]),d&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.inherited(arguments,[a]);return this},_normalizePoints:function(){var a=
this.shape.points,d=a&&a.length;if(d&&"number"==typeof a[0]){for(var b=[],c=0;c<d;c+=2)b.push({x:a[c],y:a[c+1]});this.shape.points=b}},getBoundingBox:function(){if(!this.bbox&&this.shape.points.length){for(var a=this.shape.points,d=a.length,b=a[0],c=b.x,f=b.y,g=b.x,m=b.y,k=1;k<d;++k)b=a[k],c>b.x&&(c=b.x),g<b.x&&(g=b.x),f>b.y&&(f=b.y),m<b.y&&(m=b.y);this.bbox={x:c,y:f,width:g-c,height:m-f}}return this.bbox}});k.Image=p("dojox.gfx.shape.Image",k.Shape,{constructor:function(a){this.shape=f.getDefault("Image");
this.rawNode=a},getBoundingBox:function(){return this.shape},setStroke:function(){return this},setFill:function(){return this}});k.Text=p(k.Shape,{constructor:function(a){this.fontStyle=null;this.shape=f.getDefault("Text");this.rawNode=a},getFont:function(){return this.fontStyle},setFont:function(a){this.fontStyle="string"==typeof a?f.splitFontString(a):f.makeParameters(f.defaultFont,a);this._setFont();return this},getBoundingBox:function(){var a=null;this.getShape().text&&(a=f._base._computeTextBoundingBox(this));
return a}});k.Creator={createShape:function(a){switch(a.type){case f.defaultPath.type:return this.createPath(a);case f.defaultRect.type:return this.createRect(a);case f.defaultCircle.type:return this.createCircle(a);case f.defaultEllipse.type:return this.createEllipse(a);case f.defaultLine.type:return this.createLine(a);case f.defaultPolyline.type:return this.createPolyline(a);case f.defaultImage.type:return this.createImage(a);case f.defaultText.type:return this.createText(a);case f.defaultTextPath.type:return this.createTextPath(a)}return null},
createGroup:function(){return this.createObject(f.Group)},createRect:function(a){return this.createObject(f.Rect,a)},createEllipse:function(a){return this.createObject(f.Ellipse,a)},createCircle:function(a){return this.createObject(f.Circle,a)},createLine:function(a){return this.createObject(f.Line,a)},createPolyline:function(a){return this.createObject(f.Polyline,a)},createImage:function(a){return this.createObject(f.Image,a)},createText:function(a){return this.createObject(f.Text,a)},createPath:function(a){return this.createObject(f.Path,
a)},createTextPath:function(a){return this.createObject(f.TextPath,{}).setText(a)},createObject:function(a,b){return null}};return k})},"dojox/gfx/path":function(){define(["./_base","dojo/_base/lang","dojo/_base/declare","./matrix","./shape"],function(f,q,p,s,l){l=p("dojox.gfx.path.Path",l.Shape,{constructor:function(c){this.shape=q.clone(f.defaultPath);this.segments=[];this.tbbox=null;this.absolute=!0;this.last={};this.rawNode=c;this.segmented=!1},setAbsoluteMode:function(c){this._confirmSegmented();
this.absolute="string"==typeof c?"absolute"==c:c;return this},getAbsoluteMode:function(){this._confirmSegmented();return this.absolute},getBoundingBox:function(){this._confirmSegmented();return this.bbox&&"l"in this.bbox?{x:this.bbox.l,y:this.bbox.t,width:this.bbox.r-this.bbox.l,height:this.bbox.b-this.bbox.t}:null},_getRealBBox:function(){this._confirmSegmented();if(this.tbbox)return this.tbbox;var c=this.bbox,f=this._getRealMatrix();this.bbox=null;for(var g=0,h=this.segments.length;g<h;++g)this._updateWithSegment(this.segments[g],
f);f=this.bbox;this.bbox=c;return this.tbbox=f?[{x:f.l,y:f.t},{x:f.r,y:f.t},{x:f.r,y:f.b},{x:f.l,y:f.b}]:null},getLastPosition:function(){this._confirmSegmented();return"x"in this.last?this.last:null},_applyTransform:function(){this.tbbox=null;return this.inherited(arguments)},_updateBBox:function(c,f,g){g&&(f=s.multiplyPoint(g,c,f),c=f.x,f=f.y);this.bbox&&"l"in this.bbox?(this.bbox.l>c&&(this.bbox.l=c),this.bbox.r<c&&(this.bbox.r=c),this.bbox.t>f&&(this.bbox.t=f),this.bbox.b<f&&(this.bbox.b=f)):
this.bbox={l:c,b:f,r:c,t:f}},_updateWithSegment:function(c,m){var g=c.args,h=g.length,b;switch(c.action){case "M":case "L":case "C":case "S":case "Q":case "T":for(b=0;b<h;b+=2)this._updateBBox(g[b],g[b+1],m);this.last.x=g[h-2];this.last.y=g[h-1];this.absolute=!0;break;case "H":for(b=0;b<h;++b)this._updateBBox(g[b],this.last.y,m);this.last.x=g[h-1];this.absolute=!0;break;case "V":for(b=0;b<h;++b)this._updateBBox(this.last.x,g[b],m);this.last.y=g[h-1];this.absolute=!0;break;case "m":b=0;"x"in this.last||
(this._updateBBox(this.last.x=g[0],this.last.y=g[1],m),b=2);for(;b<h;b+=2)this._updateBBox(this.last.x+=g[b],this.last.y+=g[b+1],m);this.absolute=!1;break;case "l":case "t":for(b=0;b<h;b+=2)this._updateBBox(this.last.x+=g[b],this.last.y+=g[b+1],m);this.absolute=!1;break;case "h":for(b=0;b<h;++b)this._updateBBox(this.last.x+=g[b],this.last.y,m);this.absolute=!1;break;case "v":for(b=0;b<h;++b)this._updateBBox(this.last.x,this.last.y+=g[b],m);this.absolute=!1;break;case "c":for(b=0;b<h;b+=6)this._updateBBox(this.last.x+
g[b],this.last.y+g[b+1],m),this._updateBBox(this.last.x+g[b+2],this.last.y+g[b+3],m),this._updateBBox(this.last.x+=g[b+4],this.last.y+=g[b+5],m);this.absolute=!1;break;case "s":case "q":for(b=0;b<h;b+=4)this._updateBBox(this.last.x+g[b],this.last.y+g[b+1],m),this._updateBBox(this.last.x+=g[b+2],this.last.y+=g[b+3],m);this.absolute=!1;break;case "A":for(b=0;b<h;b+=7)this._updateBBox(g[b+5],g[b+6],m);this.last.x=g[h-2];this.last.y=g[h-1];this.absolute=!0;break;case "a":for(b=0;b<h;b+=7)this._updateBBox(this.last.x+=
g[b+5],this.last.y+=g[b+6],m);this.absolute=!1}var n=[c.action];for(b=0;b<h;++b)n.push(f.formatNumber(g[b],!0));if("string"==typeof this.shape.path)this.shape.path+=n.join("");else{b=0;for(h=n.length;b<h;++b)this.shape.path.push(n[b])}},_validSegments:{m:2,l:2,h:1,v:1,c:6,s:4,q:4,t:2,a:7,z:0},_pushSegment:function(c,f){this.tbbox=null;var g=this._validSegments[c.toLowerCase()];"number"==typeof g&&(g?f.length>=g&&(g={action:c,args:f.slice(0,f.length-f.length%g)},this.segments.push(g),this._updateWithSegment(g)):
(g={action:c,args:[]},this.segments.push(g),this._updateWithSegment(g)))},_collectArgs:function(c,f){for(var g=0;g<f.length;++g){var h=f[g];"boolean"==typeof h?c.push(h?1:0):"number"==typeof h?c.push(h):h instanceof Array?this._collectArgs(c,h):"x"in h&&"y"in h&&c.push(h.x,h.y)}},moveTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"M":"m",c);return this},lineTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);
this._pushSegment(this.absolute?"L":"l",c);return this},hLineTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"H":"h",c);return this},vLineTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"V":"v",c);return this},curveTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"C":"c",c);return this},smoothCurveTo:function(){this._confirmSegmented();
var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"S":"s",c);return this},qCurveTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"Q":"q",c);return this},qSmoothCurveTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"T":"t",c);return this},arcTo:function(){this._confirmSegmented();var c=[];this._collectArgs(c,arguments);this._pushSegment(this.absolute?"A":
"a",c);return this},closePath:function(){this._confirmSegmented();this._pushSegment("Z",[]);return this},_confirmSegmented:function(){if(!this.segmented){var c=this.shape.path;this.shape.path=[];this._setPath(c);this.shape.path=this.shape.path.join("");this.segmented=!0}},_setPath:function(c){c=q.isArray(c)?c:c.match(f.pathSvgRegExp);this.segments=[];this.absolute=!0;this.bbox={};this.last={};if(c){for(var m="",g=[],h=c.length,b=0;b<h;++b){var n=c[b],l=parseFloat(n);isNaN(l)?(m&&this._pushSegment(m,
g),g=[],m=n):g.push(l)}this._pushSegment(m,g)}},setShape:function(c){this.inherited(arguments,["string"==typeof c?{path:c}:c]);this.segmented=!1;this.segments=[];f.lazyPathSegmentation||this._confirmSegmented();return this},_2PI:2*Math.PI});p=p("dojox.gfx.path.TextPath",l,{constructor:function(c){"text"in this||(this.text=q.clone(f.defaultTextPath));"fontStyle"in this||(this.fontStyle=q.clone(f.defaultFont))},getText:function(){return this.text},setText:function(c){this.text=f.makeParameters(this.text,
"string"==typeof c?{text:c}:c);this._setText();return this},getFont:function(){return this.fontStyle},setFont:function(c){this.fontStyle="string"==typeof c?f.splitFontString(c):f.makeParameters(f.defaultFont,c);this._setFont();return this}});return f.path={Path:l,TextPath:p}})},"*noref":1}});
define("dojox/gfx/svg","dojo/_base/lang dojo/_base/sniff dojo/_base/window dojo/dom dojo/_base/declare dojo/_base/array dojo/dom-geometry dojo/dom-attr dojo/_base/Color ./_base ./shape ./path".split(" "),function(f,q,p,s,l,c,m,g,h,b,n,t){function k(e,a){return p.doc.createElementNS?p.doc.createElementNS(e,a):p.doc.createElement(a)}function a(e){return d.useSvgWeb?p.doc.createTextNode(e,!0):p.doc.createTextNode(e)}var d=b.svg={};d.useSvgWeb="undefined"!=typeof window.svgweb;var w=navigator.userAgent,
x=q("ios"),v=q("android"),y=q("chrome")||v&&4<=v?"auto":"optimizeLegibility";d.xmlns={xlink:"http://www.w3.org/1999/xlink",svg:"http://www.w3.org/2000/svg"};d.getRef=function(e){return!e||"none"==e?null:e.match(/^url\(#.+\)$/)?s.byId(e.slice(5,-1)):e.match(/^#dojoUnique\d+$/)?s.byId(e.slice(1)):null};d.dasharray={solid:"none",shortdash:[4,1],shortdot:[1,1],shortdashdot:[4,1,1,1],shortdashdotdot:[4,1,1,1,1,1],dot:[1,3],dash:[4,3],longdash:[8,3],dashdot:[4,3,1,3],longdashdot:[8,3,1,3],longdashdotdot:[8,
3,1,3,1,3]};var z=0;d.Shape=l("dojox.gfx.svg.Shape",n.Shape,{destroy:function(){if(this.fillStyle&&"type"in this.fillStyle){var e=this.rawNode.getAttribute("fill");(e=d.getRef(e))&&e.parentNode.removeChild(e)}if(this.clip&&(e=this.rawNode.getAttribute("clip-path")))(e=s.byId(e.match(/gfx_clip[\d]+/)[0]))&&e.parentNode.removeChild(e);n.Shape.prototype.destroy.apply(this,arguments)},setFill:function(e){if(!e)return this.fillStyle=null,this.rawNode.setAttribute("fill","none"),this.rawNode.setAttribute("fill-opacity",
0),this;var a,d=function(e){this.setAttribute(e,a[e].toFixed(8))};if("object"==typeof e&&"type"in e){switch(e.type){case "linear":a=b.makeParameters(b.defaultLinearGradient,e);e=this._setFillObject(a,"linearGradient");c.forEach(["x1","y1","x2","y2"],d,e);break;case "radial":a=b.makeParameters(b.defaultRadialGradient,e);e=this._setFillObject(a,"radialGradient");c.forEach(["cx","cy","r"],d,e);break;case "pattern":a=b.makeParameters(b.defaultPattern,e),e=this._setFillObject(a,"pattern"),c.forEach(["x",
"y","width","height"],d,e)}this.fillStyle=a;return this}this.fillStyle=a=b.normalizeColor(e);this.rawNode.setAttribute("fill",a.toCss());this.rawNode.setAttribute("fill-opacity",a.a);this.rawNode.setAttribute("fill-rule","evenodd");return this},setStroke:function(e){var a=this.rawNode;if(!e)return this.strokeStyle=null,a.setAttribute("stroke","none"),a.setAttribute("stroke-opacity",0),this;if("string"==typeof e||f.isArray(e)||e instanceof h)e={color:e};e=this.strokeStyle=b.makeParameters(b.defaultStroke,
e);e.color=b.normalizeColor(e.color);if(e){var c=0>e.width?0:e.width;a.setAttribute("stroke",e.color.toCss());a.setAttribute("stroke-opacity",e.color.a);a.setAttribute("stroke-width",c);a.setAttribute("stroke-linecap",e.cap);"number"==typeof e.join?(a.setAttribute("stroke-linejoin","miter"),a.setAttribute("stroke-miterlimit",e.join)):a.setAttribute("stroke-linejoin",e.join);var g=e.style.toLowerCase();g in d.dasharray&&(g=d.dasharray[g]);if(g instanceof Array){var g=f._toArray(g),r;for(r=0;r<g.length;++r)g[r]*=
c;if("butt"!=e.cap){for(r=0;r<g.length;r+=2)g[r]-=c,1>g[r]&&(g[r]=1);for(r=1;r<g.length;r+=2)g[r]+=c}g=g.join(",")}a.setAttribute("stroke-dasharray",g);a.setAttribute("dojoGfxStrokeStyle",e.style)}return this},_getParentSurface:function(){for(var e=this.parent;e&&!(e instanceof b.Surface);e=e.parent);return e},_setFillObject:function(e,a){var c=d.xmlns.svg;this.fillStyle=e;var f=this._getParentSurface().defNode,g=this.rawNode.getAttribute("fill");if(g=d.getRef(g))if(g.tagName.toLowerCase()!=a.toLowerCase()){var h=
g.id;g.parentNode.removeChild(g);g=k(c,a);g.setAttribute("id",h);f.appendChild(g)}else for(;g.childNodes.length;)g.removeChild(g.lastChild);else g=k(c,a),g.setAttribute("id",b._base._getUniqueId()),f.appendChild(g);if("pattern"==a)g.setAttribute("patternUnits","userSpaceOnUse"),c=k(c,"image"),c.setAttribute("x",0),c.setAttribute("y",0),c.setAttribute("width",(0>e.width?0:e.width).toFixed(8)),c.setAttribute("height",(0>e.height?0:e.height).toFixed(8)),c.setAttributeNS?c.setAttributeNS(d.xmlns.xlink,
"xlink:href",e.src):c.setAttribute("xlink:href",e.src),g.appendChild(c);else{g.setAttribute("gradientUnits","userSpaceOnUse");for(f=0;f<e.colors.length;++f){var h=e.colors[f],m=k(c,"stop"),l=h.color=b.normalizeColor(h.color);m.setAttribute("offset",h.offset.toFixed(8));m.setAttribute("stop-color",l.toCss());m.setAttribute("stop-opacity",l.a);g.appendChild(m)}}this.rawNode.setAttribute("fill","url(#"+g.getAttribute("id")+")");this.rawNode.removeAttribute("fill-opacity");this.rawNode.setAttribute("fill-rule",
"evenodd");return g},_applyTransform:function(){if(this.matrix){var e=this.matrix;this.rawNode.setAttribute("transform","matrix("+e.xx.toFixed(8)+","+e.yx.toFixed(8)+","+e.xy.toFixed(8)+","+e.yy.toFixed(8)+","+e.dx.toFixed(8)+","+e.dy.toFixed(8)+")")}else this.rawNode.removeAttribute("transform");return this},setRawNode:function(e){e=this.rawNode=e;"image"!=this.shape.type&&e.setAttribute("fill","none");e.setAttribute("fill-opacity",0);e.setAttribute("stroke","none");e.setAttribute("stroke-opacity",
0);e.setAttribute("stroke-width",1);e.setAttribute("stroke-linecap","butt");e.setAttribute("stroke-linejoin","miter");e.setAttribute("stroke-miterlimit",4);e.__gfxObject__=this},setShape:function(e){this.shape=b.makeParameters(this.shape,e);for(var a in this.shape)if("type"!=a){e=this.shape[a];if("width"===a||"height"===a)e=0>e?0:e;this.rawNode.setAttribute(a,e)}this.bbox=null;return this},_moveToFront:function(){this.rawNode.parentNode.appendChild(this.rawNode);return this},_moveToBack:function(){this.rawNode.parentNode.insertBefore(this.rawNode,
this.rawNode.parentNode.firstChild);return this},setClip:function(e){this.inherited(arguments);var a=e?"width"in e?"rect":"cx"in e?"ellipse":"points"in e?"polyline":"d"in e?"path":null:null;if(e&&!a)return this;"polyline"===a&&(e=f.clone(e),e.points=e.points.join(","));var b,c=g.get(this.rawNode,"clip-path");c&&(b=s.byId(c.match(/gfx_clip[\d]+/)[0]))&&b.removeChild(b.childNodes[0]);e?(b?(a=k(d.xmlns.svg,a),b.appendChild(a)):(c="gfx_clip"+ ++z,this.rawNode.setAttribute("clip-path","url(#"+c+")"),b=
k(d.xmlns.svg,"clipPath"),a=k(d.xmlns.svg,a),b.appendChild(a),this.rawNode.parentNode.insertBefore(b,this.rawNode),g.set(b,"id",c)),g.set(a,e)):(this.rawNode.removeAttribute("clip-path"),b&&b.parentNode.removeChild(b));return this},_removeClipNode:function(){var a,b=g.get(this.rawNode,"clip-path");b&&(a=s.byId(b.match(/gfx_clip[\d]+/)[0]))&&a.parentNode.removeChild(a);return a}});d.Group=l("dojox.gfx.svg.Group",d.Shape,{constructor:function(){n.Container._init.call(this)},setRawNode:function(a){this.rawNode=
a;this.rawNode.__gfxObject__=this},destroy:function(){this.clear(!0);d.Shape.prototype.destroy.apply(this,arguments)}});d.Group.nodeType="g";d.Rect=l("dojox.gfx.svg.Rect",[d.Shape,n.Rect],{setShape:function(a){this.shape=b.makeParameters(this.shape,a);this.bbox=null;for(var d in this.shape)if("type"!=d&&"r"!=d){a=this.shape[d];if("width"===d||"height"===d)a=0>a?0:a;this.rawNode.setAttribute(d,a)}null!=this.shape.r&&(this.rawNode.setAttribute("ry",this.shape.r),this.rawNode.setAttribute("rx",this.shape.r));
return this}});d.Rect.nodeType="rect";d.Ellipse=l("dojox.gfx.svg.Ellipse",[d.Shape,n.Ellipse],{});d.Ellipse.nodeType="ellipse";d.Circle=l("dojox.gfx.svg.Circle",[d.Shape,n.Circle],{});d.Circle.nodeType="circle";d.Line=l("dojox.gfx.svg.Line",[d.Shape,n.Line],{});d.Line.nodeType="line";d.Polyline=l("dojox.gfx.svg.Polyline",[d.Shape,n.Polyline],{setShape:function(a,d){a&&a instanceof Array?(this.shape=b.makeParameters(this.shape,{points:a}),d&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):
this.shape=b.makeParameters(this.shape,a);this.bbox=null;this._normalizePoints();for(var c=[],f=this.shape.points,g=0;g<f.length;++g)c.push(f[g].x.toFixed(8),f[g].y.toFixed(8));this.rawNode.setAttribute("points",c.join(" "));return this}});d.Polyline.nodeType="polyline";d.Image=l("dojox.gfx.svg.Image",[d.Shape,n.Image],{setShape:function(a){this.shape=b.makeParameters(this.shape,a);this.bbox=null;a=this.rawNode;for(var c in this.shape)if("type"!=c&&"src"!=c){var f=this.shape[c];if("width"===c||"height"===
c)f=0>f?0:f;a.setAttribute(c,f)}a.setAttribute("preserveAspectRatio","none");a.setAttributeNS?a.setAttributeNS(d.xmlns.xlink,"xlink:href",this.shape.src):a.setAttribute("xlink:href",this.shape.src);a.__gfxObject__=this;return this}});d.Image.nodeType="image";d.Text=l("dojox.gfx.svg.Text",[d.Shape,n.Text],{setShape:function(e){this.shape=b.makeParameters(this.shape,e);this.bbox=null;e=this.rawNode;var d=this.shape;e.setAttribute("x",d.x);e.setAttribute("y",d.y);e.setAttribute("text-anchor",d.align);
e.setAttribute("text-decoration",d.decoration);e.setAttribute("rotate",d.rotated?90:0);e.setAttribute("kerning",d.kerning?"auto":0);e.setAttribute("text-rendering",y);e.firstChild?e.firstChild.nodeValue=d.text:e.appendChild(a(d.text));return this},getTextWidth:function(){var a=this.rawNode,b=a.parentNode,a=a.cloneNode(!0);a.style.visibility="hidden";var d=0,c=a.firstChild.nodeValue;b.appendChild(a);if(""!=c)for(;!d;)d=a.getBBox?parseInt(a.getBBox().width):68;b.removeChild(a);return d},getBoundingBox:function(){var a=
null;if(this.getShape().text)try{a=this.rawNode.getBBox()}catch(b){a={x:0,y:0,width:0,height:0}}return a}});d.Text.nodeType="text";d.Path=l("dojox.gfx.svg.Path",[d.Shape,t.Path],{_updateWithSegment:function(a){this.inherited(arguments);"string"==typeof this.shape.path&&this.rawNode.setAttribute("d",this.shape.path)},setShape:function(a){this.inherited(arguments);this.shape.path?this.rawNode.setAttribute("d",this.shape.path):this.rawNode.removeAttribute("d");return this}});d.Path.nodeType="path";d.TextPath=
l("dojox.gfx.svg.TextPath",[d.Shape,t.TextPath],{_updateWithSegment:function(a){this.inherited(arguments);this._setTextPath()},setShape:function(a){this.inherited(arguments);this._setTextPath();return this},_setTextPath:function(){if("string"==typeof this.shape.path){var e=this.rawNode;if(!e.firstChild){var c=k(d.xmlns.svg,"textPath"),f=a("");c.appendChild(f);e.appendChild(c)}c=(c=e.firstChild.getAttributeNS(d.xmlns.xlink,"href"))&&d.getRef(c);if(!c&&(f=this._getParentSurface())){var f=f.defNode,
c=k(d.xmlns.svg,"path"),g=b._base._getUniqueId();c.setAttribute("id",g);f.appendChild(c);e.firstChild.setAttributeNS?e.firstChild.setAttributeNS(d.xmlns.xlink,"xlink:href","#"+g):e.firstChild.setAttribute("xlink:href","#"+g)}c&&c.setAttribute("d",this.shape.path)}},_setText:function(){var e=this.rawNode;if(!e.firstChild){var b=k(d.xmlns.svg,"textPath"),c=a("");b.appendChild(c);e.appendChild(b)}e=e.firstChild;b=this.text;e.setAttribute("alignment-baseline","middle");switch(b.align){case "middle":e.setAttribute("text-anchor",
"middle");e.setAttribute("startOffset","50%");break;case "end":e.setAttribute("text-anchor","end");e.setAttribute("startOffset","100%");break;default:e.setAttribute("text-anchor","start"),e.setAttribute("startOffset","0%")}e.setAttribute("baseline-shift","0.5ex");e.setAttribute("text-decoration",b.decoration);e.setAttribute("rotate",b.rotated?90:0);e.setAttribute("kerning",b.kerning?"auto":0);e.firstChild.data=b.text}});d.TextPath.nodeType="text";var A=534<function(){var a=/WebKit\/(\d*)/.exec(w);
return a?a[1]:0}();d.Surface=l("dojox.gfx.svg.Surface",n.Surface,{constructor:function(){n.Container._init.call(this)},destroy:function(){n.Container.clear.call(this,!0);this.defNode=null;this.inherited(arguments)},setDimensions:function(a,b){if(!this.rawNode)return this;var d=0>a?0:a,c=0>b?0:b;this.rawNode.setAttribute("width",d);this.rawNode.setAttribute("height",c);A&&(this.rawNode.style.width=d,this.rawNode.style.height=c);return this},getDimensions:function(){return this.rawNode?{width:b.normalizedLength(this.rawNode.getAttribute("width")),
height:b.normalizedLength(this.rawNode.getAttribute("height"))}:null}});d.createSurface=function(a,c,f){var g=new d.Surface;g.rawNode=k(d.xmlns.svg,"svg");g.rawNode.setAttribute("overflow","hidden");c&&g.rawNode.setAttribute("width",0>c?0:c);f&&g.rawNode.setAttribute("height",0>f?0:f);c=k(d.xmlns.svg,"defs");g.rawNode.appendChild(c);g.defNode=c;g._parent=s.byId(a);g._parent.appendChild(g.rawNode);b._base._fixMsTouchAction(g);return g};q={_setFont:function(){var a=this.fontStyle;this.rawNode.setAttribute("font-style",
a.style);this.rawNode.setAttribute("font-variant",a.variant);this.rawNode.setAttribute("font-weight",a.weight);this.rawNode.setAttribute("font-size",a.size);this.rawNode.setAttribute("font-family",a.family)}};var u=n.Container;l=d.Container={openBatch:function(){if(!this._batch){var a;a=d.useSvgWeb?p.doc.createDocumentFragment(!0):p.doc.createDocumentFragment();this.fragment=a}++this._batch;return this},closeBatch:function(){this._batch=0<this._batch?--this._batch:0;this.fragment&&!this._batch&&(this.rawNode.appendChild(this.fragment),
delete this.fragment);return this},add:function(a){this!=a.getParent()&&(this.fragment?this.fragment.appendChild(a.rawNode):this.rawNode.appendChild(a.rawNode),u.add.apply(this,arguments),a.setClip(a.clip));return this},remove:function(a,b){this==a.getParent()&&(this.rawNode==a.rawNode.parentNode&&this.rawNode.removeChild(a.rawNode),this.fragment&&this.fragment==a.rawNode.parentNode&&this.fragment.removeChild(a.rawNode),a._removeClipNode(),u.remove.apply(this,arguments));return this},clear:function(){for(var a=
this.rawNode;a.lastChild;)a.removeChild(a.lastChild);var b=this.defNode;if(b){for(;b.lastChild;)b.removeChild(b.lastChild);a.appendChild(b)}return u.clear.apply(this,arguments)},getBoundingBox:u.getBoundingBox,_moveChildToFront:u._moveChildToFront,_moveChildToBack:u._moveChildToBack};t=d.Creator={createObject:function(a,b){if(!this.rawNode)return null;var c=new a,f=k(d.xmlns.svg,a.nodeType);c.setRawNode(f);c.setShape(b);this.add(c);return c}};f.extend(d.Text,q);f.extend(d.TextPath,q);f.extend(d.Group,
l);f.extend(d.Group,n.Creator);f.extend(d.Group,t);f.extend(d.Surface,l);f.extend(d.Surface,n.Creator);f.extend(d.Surface,t);d.fixTarget=function(a,b){a.gfxTarget||(a.gfxTarget=x&&a.target.wholeText?a.target.parentElement.__gfxObject__:a.target.__gfxObject__);return!0};d.useSvgWeb&&(d.createSurface=function(a,c,f){var g=new d.Surface;c=0>c?0:c;f=0>f?0:f;if(!c||!f){var h=m.position(a);c=c||h.w;f=f||h.h}a=s.byId(a);var h=a.id?a.id+"_svgweb":b._base._getUniqueId(),l=k(d.xmlns.svg,"svg");l.id=h;l.setAttribute("width",
c);l.setAttribute("height",f);svgweb.appendChild(l,a);l.addEventListener("SVGLoad",function(){g.rawNode=this;g.isLoaded=!0;var a=k(d.xmlns.svg,"defs");g.rawNode.appendChild(a);g.defNode=a;if(g.onLoad)g.onLoad(g)},!1);g.isLoaded=!1;return g},d.Surface.extend({destroy:function(){var a=this.rawNode;svgweb.removeChild(a,a.parentNode)}}),q={connect:function(a,b,c){"on"===a.substring(0,2)&&(a=a.substring(2));c=2==arguments.length?b:f.hitch(b,c);this.getEventSource().addEventListener(a,c,!1);return[this,
a,c]},disconnect:function(a){this.getEventSource().removeEventListener(a[1],a[2],!1);delete a[0]}},f.extend(d.Shape,q),f.extend(d.Surface,q));return d});