// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/watchUtils ../../../core/Accessor ../../../core/HandleRegistry ../../../core/accessorSupport/decorators ../../input/InputManager ../../input/BrowserEventSource ../../input/ViewEvents ../../input/handlers/PreventContextMenu ./handlers/DoubleClickZoom ./handlers/DragPan ./handlers/DragRotate ./handlers/DragZoom ./handlers/KeyPan ./handlers/MouseWheelZoom ./handlers/SingleKeyResetHeading ./handlers/SingleKeyResetTilt ./handlers/PointerDownCancelAnimation".split(" "),
function(k,e,n,f,l,c,p,d,q,r,s,t,u,m,g,v,w,x,y,z,A){k=function(c){function b(){c.apply(this,arguments);this._handles=new p}n(b,c);b.prototype.initialize=function(){var a=this;this.viewEvents=new s.ViewEvents(this.view);this._handles.add([l.whenNot(this.view,"ready",function(){return a._disconnect()}),l.when(this.view,"ready",function(){return a._connect()})])};b.prototype.destroy=function(){this._handles&&(this._handles.removeAll(),this._handles=null);this._disconnect()};Object.defineProperty(b.prototype,
"primaryDragAction",{get:function(){return this._get("primaryDragAction")},set:function(a){if(("pan"===a||"rotate"===a)&&a!==this._get("primaryDragAction"))this._set("primaryDragAction",a),this._updateMode()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"mode",{get:function(){return this._get("mode")},set:function(a){if(("default"===a||"pro"===a)&&a!==this._get("mode"))this._set("mode",a),this._updateMode()},enumerable:!0,configurable:!0});b.prototype._disconnect=function(){this.viewEvents.disconnect();
this._source&&(this._source.destroy(),this._source=null);this._inputManager=null};b.prototype._connect=function(){var a=this.view;this._source=new r.BrowserEventSource(this.view.canvas);var b=new q.InputManager(this._source);b.installHandlers("prevent-context-menu",[new t.PreventContextMenu]);this._modeDragPan=new m.DragPan(a,"primary");this._modeDragRotate=new g.DragRotate(a,"secondary","center");this._modeDragZoom=new v.DragZoom(a,"tertiary");b.installHandlers("navigation",[new A.PointerDownCancelAnimation(a),
new u.DoubleClickZoom(a),new w.KeyPan(a,{left:"ArrowLeft",right:"ArrowRight",forward:"ArrowUp",backward:"ArrowDown",up:"u",down:"j"}),new x.MouseWheelZoom(a),new z.SingleKeyResetTilt(a,"p"),new y.SingleKeyResetHeading(a,"n"),new g.DragRotate(a,"primary","eye",["b"]),new g.DragRotate(a,"secondary","center",["b"]),new m.DragPan(a,"tertiary",["b"]),this._modeDragPan,this._modeDragRotate,this._modeDragZoom]);this.viewEvents.connect(b);this._updateMode()};b.prototype._updateMode=function(){var a=this.primaryDragAction,
a=h.get(this.mode).get(a);this._modeDragPan&&(this._modeDragPan.pointerType=a.pan);this._modeDragRotate&&(this._modeDragRotate.pointerType=a.rotate);this._modeDragZoom&&(this._modeDragZoom.pointerType=a.zoom)};f([d.property()],b.prototype,"view",void 0);f([d.property({value:"pan"})],b.prototype,"primaryDragAction",null);f([d.property({value:"default"})],b.prototype,"mode",null);return b=f([d.subclass("esri.views.3d.input.SceneInputManager")],b)}(d.declared(c));var h=new Map;e=new Map;c=new Map;e.set("pan",
{pan:"primary",rotate:"secondary",zoom:"tertiary"});e.set("rotate",{pan:"secondary",rotate:"primary",zoom:"tertiary"});c.set("pan",{pan:"primary",rotate:"tertiary",zoom:"secondary"});c.set("rotate",{pan:"tertiary",rotate:"primary",zoom:"secondary"});h.set("default",e);h.set("pro",c);return k});