// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["require","exports","./keys","../../core/libs/pep/pep","dojo/sniff"],function(g,l,m,n,e){var h=e("trident"),k=e("edge"),p=e("chrome"),q=e("ff"),r=e("safari");g=function(){function d(b){this._active={};this._activePointerCaptures=new Set;this._keyDownState=new Set;this._element=b;n.applyLocal(b);b.getAttribute("tabindex")||b.setAttribute("tabindex","0");this._eventHandlers={"key-down":this._handleKey,"key-up":this._handleKey,"pointer-down":this._handlePointerDown,"pointer-move":this._handlePointer,
"pointer-up":this._handlePointer,"mouse-wheel":this._handleMouseWheel,"pointer-capture-lost":this._handlePointerCaptureLost};this._initialCssTouchAction=b.style.touchAction;b.style.touchAction="none"}d.prototype.destroy=function(){var b=this;this.activeEvents=this._callback=null;this._activePointerCaptures.forEach(function(c){b._element.releasePointerCapture(c)});this._activePointerCaptures=null;this._element.style.touchAction=this._initialCssTouchAction};Object.defineProperty(d.prototype,"onEventReceived",
{set:function(b){this._callback=b},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"activeEvents",{set:function(b){var c=this,a;for(a in this._active)if(!b||!b.has(a))this._element.removeEventListener(f[a],this._active[a]),delete this._active[a];b&&b.forEach(function(a){if(!c._active[a]&&f[a]){var b=(c._eventHandlers[a]||c._handleDefault).bind(c,a);c._element.addEventListener(f[a],b);c._active[a]=b}})},enumerable:!0,configurable:!0});d.prototype.setPointerCapture=function(b,c){c?
(this._element.setPointerCapture(b.pointerId),this._activePointerCaptures.add(b.pointerId)):(this._element.releasePointerCapture(b.pointerId),this._activePointerCaptures.delete(b.pointerId))};d.prototype._updateNormalizedPointerLikeEvent=function(b,c){var a=this._element.getBoundingClientRect();c.x=b.clientX-Math.round(a.left);c.y=b.clientY-Math.round(a.top);return c};d.prototype._handleKey=function(b,c){var a=m.eventKey(c);a&&"key-up"===b&&this._keyDownState.delete(a);var d={"native":c,key:a,repeat:a&&
this._keyDownState.has(a)};a&&"key-down"===b&&this._keyDownState.add(d.key);this._callback(b,d)};d.prototype._handlePointerDown=function(b,c){var a=this._updateNormalizedPointerLikeEvent(c,{"native":c,x:0,y:0});this._callback(b,a)};d.prototype._handlePointer=function(b,c){var a=this._updateNormalizedPointerLikeEvent(c,{"native":c,x:0,y:0});c.preventDefault();this._callback(b,a)};d.prototype._handleMouseWheel=function(b,c){c.preventDefault();var a=c.deltaY;switch(c.deltaMode){case 0:if(h||k)a=600*
(a/document.documentElement.clientHeight);break;case 1:a*=30;break;case 2:a*=900}h||k?a*=0.7:p||r?a*=0.6:q&&(a*=1.375);var d=Math.abs(a);100<d&&(a=200*(a/d)/(1+Math.exp(-0.02*(d-100))));a=this._updateNormalizedPointerLikeEvent(c,{"native":c,x:0,y:0,deltaY:a});this._callback(b,a)};d.prototype._handlePointerCaptureLost=function(b,c){this._activePointerCaptures.delete(c.pointerId);this._handleDefault(b,c)};d.prototype._handleDefault=function(b,c){var a={"native":c};c.preventDefault();this._callback(b,
a)};return d}();l.BrowserEventSource=g;var f={"key-down":"keydown","key-up":"keyup","pointer-down":"pointerdown","pointer-up":"pointerup","pointer-move":"pointermove","mouse-wheel":"wheel","pointer-capture-got":"gotpointercapture","pointer-capture-lost":"lostpointercapture","context-menu":"contextmenu"}});