// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["require","exports","./EventMatch","../../core/Logger"],function(g,k,l,m){var h=m.getLogger("esri.views.input");g=function(){function b(a,c){this._manager=null;this._incoming={};this._outgoing={};this._outgoingEventTypes=this._incomingEventTypes=this._incomingEventMatches=null;this._name=a;this._hasSideEffects=c}Object.defineProperty(b.prototype,"incomingEventMatches",{get:function(){if(!this._incomingEventMatches){this._incomingEventMatches=[];for(var a in this._incoming)for(var c=0,b=this._incoming[a];c<
b.length;c++)this._incomingEventMatches.push(b[c].match)}return this._incomingEventMatches},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"incomingEventTypes",{get:function(){this._incomingEventTypes||(this._incomingEventTypes=this.incomingEventMatches.map(function(a){return a.eventType}));return this._incomingEventTypes},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"outgoingEventTypes",{get:function(){this._outgoingEventTypes||(this._outgoingEventTypes=Object.keys(this._outgoing));
return this._outgoingEventTypes},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasSideEffects",{get:function(){return this._hasSideEffects},enumerable:!0,configurable:!0});b.prototype.onInstall=function(a){var c=this;this._manager?h.error("This InputHandler has already been registered with an InputManager"):(a.setEventCallback(function(a,b){return c._handleEvent(a,b)}),a.setUninstallCallback(function(){return c._onUninstall()}),this._manager=a)};b.prototype.registerIncoming=function(a,
c,b){var d=this;"function"===typeof c?(b=c,c=[]):c=c||[];a="string"===typeof a?new l.EventMatch(a,c):a;var f=function(){d._incomingEventTypes=null;d._incomingEventMatches=null};c=function(a){var b=d._incoming[a.match.eventType];b&&(a=b.indexOf(a),b.splice(a,1),f(),d._manager&&d._manager.updateDependencies())};b=new n(a,b,{onPause:c,onRemove:c,onResume:function(a){var b=d._incoming[a.match.eventType];b&&-1===b.indexOf(a)&&(b.push(a),f(),d._manager&&d._manager.updateDependencies())}});c=this._incoming[a.eventType];
c||(c=[],this._incoming[a.eventType]=c);c.push(b);f();this._manager&&this._manager.updateDependencies();return b};b.prototype.registerOutgoing=function(a){var b=this;if(this._outgoing[a])throw Error("There is already a callback registered for this outgoing InputEvent: "+a);var e=new p(a,{onEmit:function(a,e){b._manager.emit(a.eventType,e)},onRemove:function(a){delete b._outgoing[a.eventType];b._manager.updateDependencies()}});this._outgoing[a]=e;this._outgoingEventTypes=null;this._manager&&this._manager.updateDependencies();
return e};b.prototype.startCapturingPointer=function(a){this._manager.setPointerCapture(a,!0)};b.prototype.stopCapturingPointer=function(a){this._manager.setPointerCapture(a,!1)};b.prototype._onUninstall=function(){this._manager?this._manager=null:h.error("This InputHandler is not registered with an InputManager")};b.prototype._handleEvent=function(a,b){var e=this._incoming[a.type];if(e)for(var d=0;d<e.length;d++){var f=e[d];if(f.match.matches(a,b)&&(f.callback(a),a.shouldStopPropagation()))break}};
return b}();k.InputHandler=g;var n=function(){function b(a,b,e){this.match=a;this._callback=b;this._handler=e}b.prototype.pause=function(){this._handler.onPause(this)};b.prototype.resume=function(){this._handler.onResume(this)};b.prototype.remove=function(){this._handler.onRemove(this)};Object.defineProperty(b.prototype,"callback",{get:function(){return this._callback},enumerable:!0,configurable:!0});return b}(),p=function(){function b(a,b){this.eventType=a;this._removed=!1;this._handler=b}b.prototype.emit=
function(a){if(!this._removed)this._handler.onEmit(this,a)};b.prototype.remove=function(){this._removed=!0;this._handler.onRemove(this)};return b}()});