// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/string ../lib/lights ../lib/ModelContentType ../lib/ModelDirtySet ../lib/RenderGeometry ../lib/Util ../lib/gl-matrix".split(" "),function(C,D,r,k,e,s,A,m,n){var g=m.assert,t=m.verify,p=n.vec3d,B=n.mat4d,u=m.logWithBase;return function(){function d(){this.dirtySet=new s(this);this.ambientLight=new k.AmbientLight([1,1,1],0.3);this.directionalLight=new k.DirectionalLight([1,1,1],0.7,p.normalize([1,1,1]));this._uniqueName2idx={};this._uniqueIdx=0;this._id2origin={};this.content=
{};for(var a in e)this.content[e[a]]={}}d.prototype.getAll=function(a){a=this.content[a];g(void 0!==a);return a};d.prototype.get=function(a,b){return this.getAll(a)[b]};d.prototype.add=function(a,b){var c=this.content[a];g(void 0!==c);var f=b.getId();g(null==c[f],"Model/Stage already contains object to be added");c[f]=b;a===e.LAYER&&this.notifyDirty(a,b,"layerAdded")};d.prototype.remove=function(a,b){var c=this.content[a];g(void 0!==c);var f=c[b];g(void 0!==f,"Model/Stage doesn't contain object to be removed");
delete c[b];a===e.TEXTURE&&f.unload();a===e.LAYER&&this.notifyDirty(a,f,"layerRemoved");return f};d.prototype.getDirtySet=function(){return this.dirtySet};d.prototype.notifyDirty=function(a,b,c,f){this.dirtySet.handleUpdate(b,c,f)};d.prototype.getAmbientLight=function(){return this.ambientLight};d.prototype.setAmbientLight=function(a){this.ambientLight.set(a)};d.prototype.getDirectionalLight=function(){return this.directionalLight};d.prototype.setDirectionalLight=function(a){this.directionalLight.set(a)};
d.prototype.getSelection=function(){return this.selection};d.prototype.setSelection=function(a,b){this.selection=a;this.selectionFaceRange=b};d.prototype.getSelectionFaceRange=function(){return this.selectionFaceRange};d.prototype.getOrigin=function(a,b,c){void 0===c&&(c=10);var f=0;b=b*c/1E4;1<b&&(f=Math.ceil(u(b,2)));b=1E4*Math.pow(2,f);c=Math.round(a[0]/b);var d=Math.round(a[1]/b);a=Math.round(a[2]/b);var f=f+"_"+c+"_"+d+"_"+a,e=this._id2origin[f];null==e&&(e={vec3:p.createFrom(c*b,d*b,a*b),id:f},
this._id2origin[f]=e);return e};d.prototype.getGeometryRenderGeometries=function(a,b,c){for(var d=a.getId(),e=b.geometry,g=e.getData(),m=!!e.singleUse,k=g.getFaces(),n=g.getVertexAttr(),g=g.getId(),p=b.materials,r=b.instanceParameters,x=a.getCombinedStaticTransformation(b),s=B.maxScale(x),t=b.origin,y=a.getVisibleIndexRanges(b),h=0,u=e.getNumGroups();h<u;++h){var l=e.getBoundingInfo(h),v=b.getId()+"#"+h,q=this._uniqueName2idx[v];null==q&&(q=this._uniqueIdx++,this._uniqueName2idx[v]=q);var z={},w;
for(w in k[h].indices)z[w]=n[w];l=new A({faces:k[h],vertexAttr:z,id:g+"#"+h},l,p[h],x,s,a.getCastShadow(),m,d,v,q,h);l.origin=t||this.getOrigin(l.center,l.bsRadius);l.displayedIndexRange=y?y[h]:null;l.instanceParameters=r?b.instanceParameters[h]:null;c.push(l)}};d.prototype.formatDebugInfo=function(a){var b=[];if(a){b[0]="\x3ctable\x3e";for(var c in e)a=e[c],b[0]+="\x3ctr\x3e\x3ctd\x3e"+a+'\x3c/td\x3e\x3ctd style\x3d"text-align: right"\x3e'+Object.keys(this.getAll(a)).length+"\x3c/td\x3e\x3c/tr\x3e";
b[0]+="\x3c/table\x3e";b[1]=this.dirtySet.formatDebugInfo(!0)}else{b[0]="";for(c in e)a=e[c],b[0]+=r.pad(String(Object.keys(this.getAll(a)).length),6," ")+" "+a+", ";b[1]=this.dirtySet.formatDebugInfo(!1)}return b};d.prototype.validateContent=function(){var a=this.getAll(e.OBJECT),b;for(b in a)this.validateObject(a[b]);var a=this.getAll(e.LAYER),c;for(c in a)this.validateLayer(a[c]);c=this.getAll(e.MATERIAL);for(var d in c)this.validateMaterial(c[d])};d.prototype.validateObject=function(a){a=a.geometryRecords;
for(var b=0;b<a.length;++b){var c=a[b];g(null!=this.get(e.GEOMETRY,c.geometry.id));var d=c.geometry.numGroups;g(d<=c.materials.length,"object materials do not match geometry groups");t(d===c.materials.length,"object materials do not match geometry groups");for(var k=0;k<d;++k)g(null!=this.get(e.MATERIAL,c.materials[k].getId()))}};d.prototype.validateLayer=function(a){a=a.getObjects();for(var b=0;b<a.length;++b){var c=this.get(e.OBJECT,a[b].getId());g(null!=c)}};d.prototype.validateMaterial=function(a){a=
a.getAllTextureIds();for(var b=0;b<a.length;++b){var c=this.get(e.TEXTURE,a[b]);g(null!=c)}};d.ContentType=e;return d}()});