// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/has ../lib/PerformanceTimer ../lib/Camera ../lib/Util ../lib/BitSet ../lib/gl-matrix ./Visualizer".split(" "),function(d,N,O,q,u,B,v,n,w){var r=n.vec3;d=n.vec4d;var y=n.mat4d,s=2E4,k=[0,0],z=y.create(),c=[d.create(),d.create(),d.create(),d.create(),d.create(),d.create()],x={get:function(a){return!0}},l=0;return function(){function a(b,m,a,c){this._content={};this._visibleContent=new v;this._frustumCullingEnabled=!0;this._maxFarNearRatio=s;this._stats={renderGeometriesTotal:0,
renderGeometriesVisible:0,visualizerRenderTimer:null,viewportRenderTimer:null};this._needsRender=!0;this._rctx=c;this._gl=c.gl;this._visualizer=new w(b,m,a,this._rctx);this._camera=new u(r.createFrom(0,100,-100),r.createFrom(0,0,0));l&&(this._stats.visualizerRenderTimer=new q(10),this._stats.viewportRenderTimer=new q(10))}a.prototype.getCombinedStats=function(){var b={},m=this._visualizer.getCombinedStats(),a;for(a in m)b[a]=m[a];b.renderGeometriesTotal=this._stats.renderGeometriesTotal;b.renderGeometriesVisible=
this._stats.renderGeometriesVisible;l&&(b.visualizerTotalRenderTime=this._stats.visualizerRenderTimer.getTotal(),b.visualizerCurrentRenderTime=this._stats.visualizerRenderTimer.getLastFiltered(),b.viewportTotalRenderTime=this._stats.viewportRenderTimer.getTotal(),b.viewportCurrentRenderTime=this._stats.viewportRenderTimer.getLastFiltered(),b.totalNumFramesRendered=this._stats.viewportRenderTimer.getNumMeasurements());void 0!==this._gl.getUsedTextureMemory&&(b.textureMemory=this._gl.getUsedTextureMemory());
void 0!==this._gl.getUsedRenderbufferMemory&&(b.renderbufferMemory=this._gl.getUsedRenderbufferMemory());void 0!==this._gl.getUsedVBOMemory&&(b.VBOMemory=this._gl.getUsedVBOMemory());if(void 0!==this._gl.getUsedTextureMemoryStats){var m=this._gl.getUsedTextureMemoryStats(),c;for(c in m)b["texMem type: "+c]=m[c]}return b};a.prototype.dispose=function(){this._visualizer.dispose();this._visualizer=null};a.prototype.setLightingData=function(b){this._visualizer.setLightingData(b)};a.prototype.getLightingData=
function(){return this._visualizer.getLightingData()};a.prototype.getViewParams=function(b){var a=this._visualizer.getViewParams(b);if(!b||b.frustumCullingEnabled)a.frustumCullingEnabled=this._frustumCullingEnabled;if(!b||b.maxFarNearRatio)a.maxFarNearRatio=this._maxFarNearRatio;return a};a.prototype.setViewParams=function(b){void 0!==b.frustumCullingEnabled&&(this._frustumCullingEnabled=b.frustumCullingEnabled);void 0!==b.maxFarNearRatio&&(this._maxFarNearRatio=-1===b.maxFarNearRatio?s:b.maxFarNearRatio);
this._visualizer.setViewParams(b);this._needsRender=!0};a.prototype.setRenderParams=function(b){this._visualizer.setRenderParams(b)};a.prototype.getRenderParams=function(){return this._visualizer.getRenderParams()};a.prototype.getFrustumObjects=function(){var b={},a;for(a in this._content)this._visibleContent.get(this._content[a].idx)&&(b[this._content[a].name]=1);return b};a.prototype.modify=function(b,a,c,f){this._visualizer.modify(b,a,c,f);this._content=this._visualizer.getContent()};a.prototype.getContent=
function(){return this._content};a.prototype.setSelectionObject=function(b,a){this._visualizer.setSelectionObject(b,a)};a.prototype.setCamera=function(b){this._camera.copyFrom(b);this._computeVisibleContentAndUpdateNearFar();this._needsRender=!0};a.prototype.getCamera=function(){return this._camera};a.prototype.getPickRay=function(b,a,c){return this.pickRayWithBeginPoint(b,void 0,this._camera.viewMatrix,a,c)};a.prototype.pickRayWithBeginPoint=function(b,a,c,f,d){return this._visualizer.getPickRay(b,
a,this._camera,c,f,d)};a.prototype.addExternalRenderer=function(b,a){return this._visualizer.addExternalRenderer(b,a)};a.prototype.removeExternalRenderer=function(b){return this._visualizer.removeExternalRenderer(b)};a.prototype.getExternalRenderers=function(){return this._visualizer.getExternalRenderers()};a.prototype.render=function(b,a){l&&this._stats.viewportRenderTimer.start();var c=this._computeVisibleContentAndUpdateNearFar();l&&this._stats.visualizerRenderTimer.start();this._visualizer.render(this._camera,
b,c,a);l&&(this._stats.visualizerRenderTimer.stop(),this._stats.viewportRenderTimer.stop())};a.prototype.resetNeedsRender=function(){this._needsRender=!1;this._visualizer.resetNeedsRender()};a.prototype.needsRender=function(){return this._needsRender||this._visualizer.needsRender()};a.prototype._computeVisibleContentAndUpdateNearFar=function(){return this._frustumCullingEnabled||0<this._maxFarNearRatio?(k[1]=0,this._computeFrustumCullingAndNearFar(this._camera.eye,this._visibleContent,k),0<this._maxFarNearRatio&&
0<k[1]&&(this._camera.far=k[1],this._camera.near=Math.max(k[0],this._camera.far/this._maxFarNearRatio)),this._visibleContent):x};a.prototype._computeFrustumCullingAndNearFar=function(b,a,d){y.perspective(this._camera.fovY,this._camera.aspect,1,10,z);B.matrix2frustumPlanes(this._camera.viewMatrix,z,c);a.clearAll();this._stats.renderGeometriesTotal=0;this._stats.renderGeometriesVisible=0;b=-Number.MAX_VALUE;var f=-Number.MAX_VALUE,k=c[0][0],l=c[0][1],n=c[0][2],q=c[0][3],r=c[1][0],s=c[1][1],u=c[1][2],
v=c[1][3],w=c[2][0],x=c[2][1],C=c[2][2],D=c[2][3],E=c[3][0],F=c[3][1],G=c[3][2],H=c[3][3],I=c[4][0],J=c[4][1],K=c[4][2],L=c[4][3],M=c[5][3],A;for(A in this._content){var t=this._content[A];this._stats.renderGeometriesTotal++;if(!t.material.isBackdrop){var e=t.center,g=e[0],h=e[1],p=e[2],e=t.bsRadius;if(k*g+l*h+n*p+q>e)continue;if(r*g+s*h+u*p+v>e)continue;if(w*g+x*h+C*p+D>e)continue;if(E*g+F*h+G*p+H>e)continue;h=I*g+J*h+K*p;g=h+e;e=-h+e;g>b&&(b=g);e>f&&(f=e)}a.set(t.idx);this._stats.renderGeometriesVisible++}a=
b!==-Number.MAX_VALUE;f+=M;0<this._stats.renderGeometriesVisible&&a&&(d[0]=0.99*Math.max(1-(b+L),2),d[1]=1.01*Math.max(10+f,d[0]+1))};return a}()});