//>>built
define("xstyle/core/Rule",["xstyle/core/expression","xstyle/core/Definition","put-selector/put","xstyle/core/es6","xstyle/core/utils"],function(n,A,w,x,p){function q(a,b,c){try{a[b]=c}catch(d){}}function l(){}function y(a,b,c,d){if(a.calls){var e;for(c=0;c<a.length;c++){var g=a[c];if(g instanceof r){a.hasOwnProperty(c)||(a[c]=g=s(g));var f=g.ref&&(g.ref.selfResolving?g.ref.apply(b,g.getArgs(),b):n.evaluate(b,[g.caller,g]));void 0!==f&&((e||(e=[])).push(f),g.evaluated=!0)}}}if(e)return b=n.react(function(){for(var c=
0,b=a.slice(),d=0;d<a.length;d++){var e=a[d];e instanceof r&&e.evaluated&&(b[d-1]=a[d-1].slice(0,-e.caller.length),b[d]=arguments[c++])}return b.join("")}),b.skipResolve=!0,d=new A,d.setCompute(b.apply(d,e,d)),d;if(!d)return a.toString()}function r(a){this.caller=a;this.args=[]}function B(a,b,c,d){return p.when(b,function(b){var g=b;b&&b.forRule&&((a._subRuleListeners||(a._subRuleListeners=[])).push(function(a){var b=g.forRule(a,!0);b&&b.forElement?t(a,b,d):c&&c(b)}),b=b.forRule(a));if(b&&b.forElement)return t(a,
b,d);c&&c(b)})}function t(a,b,c){return require(["xstyle/core/elemental"],function(d){d.addRenderer(a,function(a){var d=b.forElement(a);c&&c(d,a)})})}var s=Object.create||function(a){function b(){}b.prototype=a;return new b},m=p.convertCssNameToJs,C={"{":"}","[":"]","(":")"},u=w("div").style;l.prototype={property:function(a){return(this._properties||(this._properties={}))[a]||(this._properties[a]=new Proxy(this.get(a)))},eachProperty:function(a){for(var b=this.values||0,c=0;c<b.length;c++){var d=
b[c];a.call(this,d||"unnamed",b[d])}},fullSelector:function(){return(this.parent?this.parent.fullSelector():"")+(this.selector||"")+" "},newRule:function(a){a=(this.rules||(this.rules={}))[a]=new l;a.disabled=this.disabled;a.parent=this;return a},newCall:function(a){a=new r(a);a.parent=this;return a},addSheetRule:function(a,b){if("@"!=a.charAt(0)){var c=this.styleSheet,d=c.cssRules||c.rules,e=-1<this.ruleIndex?this.ruleIndex:d.length;try{c.addRule(a,b||" ",e)}catch(g){a.match(/-(moz|webkit|ie)-/)||
console.warn("Unable to add rule",a,b)}return d[e]}},onRule:function(){var a=this.getCssRule();if(this.installStyles)for(var b=0;b<this.installStyles.length;b++){var c=this.installStyles[b];q(a.style,c[0],c[1])}},setMediaSelector:function(a){this.isMediaBlock=!0;this.selector=a},setStyle:function(a,b){this.cssRule?q(this.cssRule.style,a,b):(this.installStyles||(this.installStyles=[])).push([a,b])},getCssRule:function(){this.cssRule||(this.cssRule=this.addSheetRule(this.selector,this.cssText));return this.cssRule},
get:function(a){return this.values[a]},elements:function(a){var b=this;require(["xstyle/core/elemental"],function(c){c.addRenderer(b,function(b){a(b)})})},declareDefinition:function(a,b,c){a=a&&m(a);if(!this.disabled){var d=this;if(b.length)if("\x3e"==b[0].toString().charAt(0))a||(this.generator=b,require(["xstyle/core/generate","xstyle/core/elemental"],function(a,c){b=a.forSelector(b,d);c.addRenderer(d,b)}));else{var e=a in u||this.getDefinition(a);if(!c||!e){c=this.definitions||(this.definitions=
{});var g=b[0];if(g.indexOf&&-1<g.indexOf(","))for(var g=b.join("").split(/\s*,\s*/),f=[],h=0;h<g.length;h++)f[h]=n.evaluate(this,g[h]);b[0]&&"{"==b[0].operator?f=b[0]:b[1]&&"{"==b[1].operator&&(f=b[1],p.extend(f,b[0]));f=f||n.evaluate(this,b);if(f.then)var k=f,f={then:function(a){return k.then(function(b){return a(z(b))})}};var z=function(b){b.define&&(b=b.define(d,a));return b};e&&console.warn('Overriding existing property "'+a+'"');return c[a]=z(f)}}else return c=this.definitions||(this.definitions=
{}),c[a]=b}},onArguments:function(a){var b=a.ref;return b&&b.apply(this,a.getArgs(),this)},setValue:function(a,b,c){var d=m(a);if(!this.disabled){var e=this.values||(this.values=[]);e.push(a);e[a]=b;if(a){do{e=(c||this).getDefinition(a);if(void 0!==e){if(this.cssRule&&(!e||!e.keepCSSValue)){var g=this.cssRule.style;d in g&&q(g,d,"")}B(this,e.put(b,this,d))}a=a.substring(0,a.lastIndexOf("-"))}while(a)}d in u&&this._setStyleFromValue(d,b,!0)}},_setStyleFromValue:function(a,b,c){var d=b[0];if(d instanceof
l){c=d.values;for(d=0;d<c.length;d++){var e=c[d];this._setStyleFromValue(a+("main"==e?"":e.charAt(0).toUpperCase()+e.slice(1)),c[e])}}else{if(b.calls){var g=this;if(b.expression=y(b,this,a,!0)){var f=b.expression&&b.expression.valueOf(),h=function(b,c){var d=f&&f.forRule?f.forRule(b,!0):f;if(d&&d.forElement){var e=c&&c.elements;if(e)for(var g=0;g<e.length;g++)for(var h=e[g].querySelectorAll(b.selector),k=0;k<h.length;k++){var l=h[k];q(l.style,a,d.forElement(l))}else t(b,d,function(b,c){q(c.style,
a,b)})}else b.setStyle(a,d)},k=[g];p.when(f,function(a){if((f=a)&&f.forRule)(g._subRuleListeners||(g._subRuleListeners=[])).push(function(a){k.push(a);h(a)});h(g)});b.expression.dependencyOf({invalidate:function(a){p.when(b.expression.valueOf(),function(b){f=b;for(b=0;b<k.length;b++){var c=!0,d=k[b];if(a&&a.rules)for(var c=!1,e=0;e<a.rules.length;e++)if(a.rules[e]===d){c=!0;break}c&&h(d,a)}})}})}}c||this.setStyle(a,b)}},put:function(a){var b=this;return{forRule:function(c){b.extend(c);if("defaults"!=
a&&a&&"string"==typeof a&&b.values)for(var d=a.toString().split(/,\s*/),e=0;e<d.length;e++){var g=b.values[e];g&&c.setValue(g,d[e],b)}}}},extend:function(a,b){(this.derivatives||(this.derivatives=[])).push(a);var c=this.extraSelector;c&&(a.selector+=c);for(var d=this.cssRule.style,e=a.getCssRule().style,g=a.inheritedStyles||(a.inheritedStyles={}),c=0;c<d.length;c++){var f=m(d[c]);if(!e[f]||g[f])e[f]=d[f],g[f]=!0}if(c=this.values){var c=s(c),h=a.values;a.values=h?x.copy(c,h):c}if(b){if(c=this.definitions){var c=
s(c),k=a.definitions;a.definitions=k?x.copy(c,k):c}a.tagName=this.tagName||a.tagName}(a.bases||(a.bases=[])).push(this);f=this._subRuleListeners||0;for(c=0;c<f.length;c++)f[c](a);var l=a.getCssRule().style;this.eachProperty(function(b,c){var d=m(b);"object"==typeof c&&(c=s(c));d in u&&!l[d]&&a._setStyleFromValue(d,c)});if(h&&a.definitions){c=0;for(d=h.length;c<d;c++)f=h[c],e=m(f),a.definitions[e]!==(k&&k[e])&&a.setValue(f,h[e])}if(h=this.generator){if(h instanceof Array){h=h.slice(0);for(c=0;c<h.length;c++)k=
h[c],"{"===k.operator&&(f=a.newRule(),f.selector=k.selector+a.selector.slice(1),f.styleSheet=a.styleSheet||a.cssRule.parentStyleSheet,k.extend(f,!0),h[c]=f)}a.declareDefinition(null,h)}},getDefinition:function(a,b){a=m(a);var c=this;do{var d=c.definitions&&c.definitions[a];void 0===d&&(b&&c[b])&&(d=c[b][a]);c=c.parent}while(void 0===d&&c);return d},newElement:function(){return w((this.tagName||"span")+(this.selector||""))},cssText:""};n.evaluateText=y;var v=r.prototype=new l;v.declareDefinition=v.setValue=
function(a,b){this.args.push(b)};v.toString=function(){var a=this.operator;return a+this.args+C[a]};l.updateStaleProperties=function(){};return l});