// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/Collection ../../core/lang ../../core/Evented ../../core/HandleRegistry ../../core/watchUtils ./ListItem ../../support/Action".split(" "),function(k,g,r,l,m,d,p,s){return k.createSubclass([l],{declaredClass:"esri.widgets.LayerList.LayerListViewModel",constructor:function(){this._actionsOpenMap={};this._itemOpenMap={};this._handles=new m;var b=d.watch(this,"view",function(a){this._handles.remove("layers");this._resetMapItems(a);if(a){var b=d.init(a,"map",function(){this._resetMapItems(a)}.bind(this)),
f=a.allLayerViews.on("change",function(){this._compileList(a)}.bind(this)),e=d.init(this,"createActionsFunction",function(){this._compileList(a)}.bind(this));this._handles.add([b,f,e],"layers")}}.bind(this));this._handles.add(b,"view")},destroy:function(){this._handles.destroy();this.view=this._handles=null;this.operationalItems.removeAll()},properties:{createActionsFunction:{},operationalItems:{value:new g,type:g.ofType(p),readOnly:!0},state:{dependsOn:["view.ready"],readOnly:!0,value:"disabled",
get:function(){return this.get("view.ready")?"ready":"disabled"}},view:{}},triggerAction:function(b){b&&this.emit("trigger-action",{action:b})},_resetMapItems:function(b){this._actionsOpenMap={};this._itemOpenMap={};this._createMapHandles(b);this._compileList(b)},_createMapHandles:function(b){this._handles.remove("map");var a=b&&b.get("map.allLayers");a&&(a=a.on("change",function(){this._compileList(b)}.bind(this)),this._handles.add(a,"map"))},_findLayerView:function(b){var a,c=this.get("view.allLayerViews");
c&&(a=c.find(function(a){return a.layer===b}));return a},_compileList:function(b){var a=b&&b.get("map.layers");this._handles.remove("list-items");var c=[];a&&a.forEach(function(a){var e=this._findLayerView(a),h=a.listMode;"hide"!==h&&(e=this._createListItems(e,a,"hide-children"===h),c.unshift(e));a=d.watch(a,"listMode",function(){this._compileList(b)}.bind(this));this._handles.add(a,"list-items")},this);this.operationalItems.removeAll();this.operationalItems.addMany(c)},_isLayerUpdating:function(b){var a=
!1;"loading"===b?a=!0:"failed"===b&&(a=!1);return a},_isLayerWithinScaleRange:function(b,a){if("number"!==typeof a||!b||!b.maxScale&&!b.minScale)return!0;var c=b.maxScale,d=b.minScale;return 0<d&&a>=d||0<c&&a<=c?!1:!0},_normalizeChildLayers:function(b,a){return a||!b?[]:b.hasOwnProperty("sublayers")?b.sublayers||[]:b.hasOwnProperty("layers")?b.layers||[]:[]},_watchItemProperties:function(b,a){var c=d.init(b,"actionsOpen",function(b){this._actionsOpenMap[a.id]=b}.bind(this)),f=d.init(b,"open",function(b){this._itemOpenMap[a.id]=
b}.bind(this)),e=d.init(b,"visible",function(b){a.visible=b});this._handles.add([e,f,c],"list-items")},_watchLayerProperties:function(b,a,c){var f=d.init(c,"loadError",function(a){b.error=a||null}),e=d.init(c,"title",function(a){b.title=a||""});a=a?d.init(a,"updating",function(a){b.updating=a}):d.init(c,"loadStatus",function(a){b.updating=this._isLayerUpdating(a)}.bind(this));this._handles.add(a,"list-items");a=d.init(c,"visible",function(a){b.visible=a});c=d.init(c,"visibilityMode",function(a){b.visibilityMode=
a});this._handles.add([c,f,e,a],"list-items")},_setupListItem:function(b,a,c,f){this._watchItemProperties(b,c);this._watchLayerProperties(b,a,c);if("function"===typeof this.createActionsFunction&&(a=this.createActionsFunction.call(null,{item:b}))&&a.length)b.actionsSections=a;this._normalizeChildLayers(c,f).forEach(function(a){var c=this._findLayerView(a);a=this._createListItems(c,a,f);b.children.unshift(a)},this);a=d.init(this,"view.stationary",function(){b.visibleAtCurrentScale=this._isLayerWithinScaleRange(c,
this.get("view.scale"))}.bind(this));this._handles.add(a,"list-items")},_createListItems:function(b,a,c){var d=!!this._actionsOpenMap[a.id],e=a.loadError,h=a.title||"",g=!!this._itemOpenMap[a.id],k=b?b.updating:a.loadStatus?this._isLayerUpdating(a.loadStatus):!1,l=a.visible,m=a.visibilityMode,q=this._isLayerWithinScaleRange(a,this.get("view.scale")),n=new p({actionsOpen:d,actionSections:[],children:[],error:e,open:g,title:h,updating:k,visible:l,visibleAtCurrentScale:q,visibilityMode:m});a.always?
a.always(function(){this._setupListItem(n,b,a,c)}.bind(this)):this._setupListItem(n,b,a,c);return n}})});