// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/config dojo/_base/lang dojo/_base/array dojo/Deferred dojo/_base/url dojo/sniff dojo/cookie dojo/io-query dojo/regexp ../kernel ../config ../core/lang ./ServerInfo ../core/urlUtils ../core/deferredUtils ../core/Accessoire ../request ../core/Evented ./OAuthCredential ./OAuthInfo".split(" "),function(E,v,n,g,N,w,F,G,O,P,k,A,u,B,p,H,Q,x,I,J,K){var y={},C=function(a){var b=(new w(a.owningSystemUrl)).host;a=(new w(a.server)).host;var c=/.+\.arcgis\.com$/i;return c.test(b)&&
c.test(a)},D=function(a,b){return!(!C(a)||!b||!g.some(b,function(b){return b.test(a.server)}))},r,M=E(I,{declaredClass:"esri.IdentityManagerBase",constructor:function(){this._portalConfig=n.getObject("esriGeowConfig");this.serverInfos=[];this.oAuthInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[];this._getOAuthHash()},defaultOAuthInfo:null,defaultTokenValidity:60,tokenValidity:null,signInPage:null,useSignInPage:!0,normalizeWebTierAuth:!1,_busy:null,_oAuthHash:null,_gwTokenUrl:"/sharing/generateToken",
_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i,_adminSvcs:/\/admin\/services(\/|$)/i,_agolSuffix:".arcgis.com",_gwDomains:[{regex:/https?:\/\/www\.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/dev\.arcgis\.com/i,tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*dev[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},
{regex:/https?:\/\/.*qa[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(MapServer|GeocodeServer|GPServer|GeometryServer|ImageServer|NAServer|FeatureServer|GeoDataServer|GlobeServer|MobileServer|GeoenrichmentServer|VectorTileServer|SceneServer)).*/ig,_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,
_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_rePortalTokenSvc:/\/sharing(\/rest)?\/generatetoken/i,_publicUrls:[/\/arcgis\/tokens/i,/\/sharing(\/rest)?\/generatetoken/i,/\/rest\/info/i],_createDefaultOAuthInfo:!0,_hasTestedIfAppIsOnPortal:!1,registerServers:function(a){var b=this.serverInfos;b?(a=g.filter(a,function(a){return!this.findServerInfo(a.server)},this),this.serverInfos=b.concat(a)):this.serverInfos=a;g.forEach(a,function(a){a.owningSystemUrl&&
this._portals.push(a.owningSystemUrl);if(a.hasPortal){this._portals.push(a.server);var b=A.request.corsEnabledServers,e=this._getOrigin(a.tokenServiceUrl);p.canUseXhr(a.server)||b.push(a.server.replace(/^https?:\/\//i,""));p.canUseXhr(e)||b.push(e.replace(/^https?:\/\//i,""))}},this)},registerOAuthInfos:function(a){var b=this.oAuthInfos;b?(a=g.filter(a,function(a){return!this.findOAuthInfo(a.portalUrl)},this),this.oAuthInfos=b.concat(a)):this.oAuthInfos=a},registerToken:function(a){var b=this._sanitizeUrl(a.server),
c=this.findServerInfo(b),d=!0,e;c||(c=new B,c.server=this._getServerInstanceRoot(b),c.tokenServiceUrl=this._getTokenSvcUrl(b),c.hasPortal=!0,this.registerServers([c]));(e=this.findCredential(b,a.userId))?(n.mixin(e,a),d=!1):(e=new r({userId:a.userId,server:c.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:this._isServerRsrc(b)?"server":"portal"}),e.resources=[b],this.credentials.push(e));e.emitTokenChange(!1);d||e.refreshServerTokens()},toJSON:function(){return u.fixJson({serverInfos:g.map(this.serverInfos,
function(a){return a.toJSON()}),oAuthInfos:g.map(this.oAuthInfos,function(a){return a.toJSON()}),credentials:g.map(this.credentials,function(a){return a.toJSON()})})},initialize:function(a){if(a){n.isString(a)&&(a=JSON.parse(a));var b=a.serverInfos,c=a.oAuthInfos;a=a.credentials;if(b){var d=[];g.forEach(b,function(a){a.server&&a.tokenServiceUrl&&d.push(a.declaredClass?a:new B(a))});d.length&&this.registerServers(d)}if(c){var e=[];g.forEach(c,function(a){a.appId&&e.push(a.declaredClass?a:new K(a))});
e.length&&this.registerOAuthInfos(e)}a&&g.forEach(a,function(a){a.userId&&(a.server&&a.token&&a.expires&&a.expires>(new Date).getTime())&&(a=a.declaredClass?a:new r(a),a.emitTokenChange(),this.credentials.push(a))},this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);g.some(this.serverInfos,function(c){this._hasSameServerInstance(c.server,a)&&(b=c);return!!b},this);return b},findOAuthInfo:function(a){var b;a=this._sanitizeUrl(a);g.some(this.oAuthInfos,function(c){this._hasSameServerInstance(c.portalUrl,
a)&&(b=c);return!!b},this);return b},findCredential:function(a,b){var c,d;a=this._sanitizeUrl(a);d=this._isServerRsrc(a)?"server":"portal";b?g.some(this.credentials,function(e){this._hasSameServerInstance(e.server,a)&&(b===e.userId&&e.scope===d)&&(c=e);return!!c},this):g.some(this.credentials,function(b){this._hasSameServerInstance(b.server,a)&&(-1!==this._getIdenticalSvcIdx(a,b)&&b.scope===d)&&(c=b);return!!c},this);return c},getCredential:function(a,b){var c,d,e=!0;u.isDefined(b)&&(n.isObject(b)?
(c=!!b.token,d=b.error,e=!1!==b.prompt):c=b);a=this._sanitizeUrl(a);var g=H.makeDeferredCancellingPending(),f=this._isAdminResource(a),h=c&&this._doPortalSignIn(a)?this._getEsriAuthCookie():null;c=c?this.findCredential(a):null;if(h||c)return e=Error("You are currently signed in as: '"+(h&&h.email||c&&c.userId)+"'. You do not have access to this resource: "+a),e.code="IdentityManagerBase.1",e.httpCode=d&&d.httpCode,e.messageCode=d?d.messageCode:null,e.subcode=d?d.subcode:null,e.details=d?d.details:
null,e.log=v.isDebug,g.reject(e),g.promise;if(d=this._findCredential(a,b))return g.resolve(d),g.promise;if(d=this.findServerInfo(a))!d.hasServer&&this._isServerRsrc(a)&&(d._restInfoDfd=this._getTokenSvcUrl(a,!0),d.hasServer=!0);else{h=this._getTokenSvcUrl(a);if(!h)return e=Error("Unknown resource - could not find token service endpoint."),e.code="IdentityManagerBase.2",e.log=v.isDebug,g.reject(e),g.promise;d=new B;d.server=this._getServerInstanceRoot(a);n.isString(h)?(d.tokenServiceUrl=h,d.hasPortal=
!0):(d._restInfoDfd=h,d.hasServer=!0);this.registerServers([d])}e&&(d.hasPortal&&void 0===d._selfReq&&!this._findOAuthInfo(a))&&(d._selfReq={owningTenant:b&&b.owningTenant,selfDfd:this._getPortalSelf(d.tokenServiceUrl.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),a)});return this._enqueue(a,d,b,g,f)},getResourceName:function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&
a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,b,c){var d,e,g,f,h,L,s=this._rePortalTokenSvc.test(a.tokenServiceUrl),q=new w(window.location.href.toLowerCase()),t=this._getEsriAuthCookie(),z,l=!b;f=a.shortLivedTokenValidity;var m;b&&(m=k.id.tokenValidity||f||k.id.defaultTokenValidity,m>f&&(m=f));c&&(d=c.isAdmin,e=c.serverUrl,g=c.token,L=c.ssl,a.customParameters=c.customParameters);if(d)f=a.adminTokenServiceUrl;else{f=a.tokenServiceUrl;
h=new w(f.toLowerCase());t&&(z=(z=t.auth_tier)&&z.toLowerCase());if(("web"===z||a.webTierAuth)&&c&&c.serverUrl&&!L&&"http"===q.scheme&&(p.hasSameOrigin(q.uri,f,!0)||"https"===h.scheme&&q.host===h.host&&"7080"===q.port&&"7443"===h.port))f=f.replace(/^https:/i,"http:").replace(/:7443/i,":7080");l&&s&&(f=f.replace(/\/rest/i,""))}c=n.mixin({query:n.mixin({request:"getToken",username:b&&b.username,password:b&&b.password,serverUrl:e,token:g,expiration:m,referer:d||s?window.location.host:null,client:d?"referer":
null,f:"json"},a.customParameters),method:!l?"post":"auto",disableIdentityLookup:!0,useProxy:this._useProxy(a,c),responseType:"json",callbackParamName:l?"callback":void 0},c&&c.ioArgs);s||(c.withCredentials=!1);return x(f,c).then(function(c){c=c.data;if(!c||!c.token)return c=Error("Unable to generate token"),c.code="IdentityManagerBase.3",c.log=v.isDebug,c;var d=a.server;y[d]||(y[d]={});b&&(y[d][b.username]=b.password);c.validity=m;return c})},isBusy:function(){return!!this._busy},checkSignInStatus:function(a){return this.getCredential(a,
{prompt:!1})},setRedirectionHandler:function(a){this._redirectFunc=a},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},oAuthSignIn:function(){},destroyCredentials:function(){if(this.credentials){var a=this.credentials.slice();g.forEach(a,function(a){a.destroy()})}this.emit("credentials-destroy")},_getOAuthHash:function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));var a=O.queryToObject(a),b=!1;a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username")?
(a.state=JSON.parse(a.state),this._oAuthHash=a,b=!0):a.error&&a.error_description&&(console.log("IdentityManager OAuth Error: ",a.error," - ",a.error_description),"access_denied"===a.error&&(b=!0));if(b&&(!F("ie")||8<F("ie")))window.location.hash=""}},_findCredential:function(a,b){var c=-1,d,e,k,f,h=b&&b.token;d=b&&b.resource;var n=this._isServerRsrc(a)?"server":"portal",s=g.filter(this.credentials,function(b){return this._hasSameServerInstance(b.server,a)&&b.scope===n},this);a=d||a;if(s.length)if(1===
s.length)if(d=s[0],k=(e=(f=this.findServerInfo(d.server))&&f.owningSystemUrl)&&this.findCredential(e,d.userId),c=this._getIdenticalSvcIdx(a,d),h)-1!==c&&(d.resources.splice(c,1),this._removeResource(a,k));else return-1===c&&d.resources.push(a),this._addResource(a,k),d;else{var q,t;g.some(s,function(b){t=this._getIdenticalSvcIdx(a,b);return-1!==t?(q=b,k=(e=(f=this.findServerInfo(q.server))&&f.owningSystemUrl)&&this.findCredential(e,q.userId),c=t,!0):!1},this);if(h)q&&(q.resources.splice(c,1),this._removeResource(a,
k));else if(q)return this._addResource(a,k),q}},_findOAuthInfo:function(a){var b=this.findOAuthInfo(a);b||g.some(this.oAuthInfos,function(c){this._isIdProvider(c.portalUrl,a)&&(b=c);return!!b},this);return b},_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var c=-1;b&&(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))},_useProxy:function(a,b){return b&&b.isAdmin&&!p.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||
!this._isPortalDomain(a.tokenServiceUrl)&&10.1==a.currentVersion&&!p.hasSameOrigin(a.tokenServiceUrl,window.location.href)},_getOrigin:function(a){a=new w(a);return a.scheme+"://"+a.host+(u.isDefined(a.port)?":"+a.port:"")},_getServerInstanceRoot:function(a){var b=a.toLowerCase(),c=b.indexOf(this._agsRest);-1===c&&this._isAdminResource(a)&&(c=b.indexOf("/admin"));-1===c&&(c=b.indexOf("/sharing"));-1===c&&"/"===b.substr(-1)&&(c=b.length-1);return-1<c?a.substring(0,c):a},_hasSameServerInstance:function(a,
b){a=a.toLowerCase();b=this._getServerInstanceRoot(b).toLowerCase();a=a.substr(a.indexOf(":"));b=b.substr(b.indexOf(":"));return a===b},_sanitizeUrl:function(a){a=p.normalize(n.trim(a));var b=(A.request.proxyUrl||"").toLowerCase(),c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+1));return p.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||
this._isAdminResource(a)},_isIdenticalService:function(a,b){var c;if(this._isRESTService(a)&&this._isRESTService(b)){var d=this._getSuffix(a).toLowerCase(),e=this._getSuffix(b).toLowerCase();c=d===e;c||(c=/(.*)\/(MapServer|FeatureServer).*/ig,c=d.replace(c,"$1")===e.replace(c,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:!this._isServerRsrc(a)&&(!this._isServerRsrc(b)&&this._isPortalDomain(a))&&(c=!0);return c},_isPortalDomain:function(a){a=a.toLowerCase();var b=(new w(a)).authority,
c=this._portalConfig,d=-1!==b.indexOf(this._agolSuffix);!d&&c&&(d=this._hasSameServerInstance(this._getServerInstanceRoot(c.restBaseUrl),a));if(!d){if(!this._arcgisUrl&&(c=n.getObject("esri.arcgis.utils.arcgisUrl")))this._arcgisUrl=(new w(c)).authority;this._arcgisUrl&&(d=this._arcgisUrl.toLowerCase()===b)}d||(d=g.some(this._portals,function(b){return this._hasSameServerInstance(b,a)},this));return d=d||this._agsPortal.test(a)},_isIdProvider:function(a,b){var c=-1,d=-1;g.forEach(this._gwDomains,function(e,
g){-1===c&&e.regex.test(a)&&(c=g);-1===d&&e.regex.test(b)&&(d=g)});var e=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)e=!0}else if(1===c){if(1===d||2===d)e=!0}else 2===c?2===d&&(e=!0):3===c&&3===d&&(e=!0);if(!e){var k=this.findServerInfo(b),f=k&&k.owningSystemUrl;f&&(C(k)&&this._isPortalDomain(f)&&this._isIdProvider(a,f))&&(e=!0)}return e},_isPublic:function(a){a=this._sanitizeUrl(a);return g.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,b){var c=-1;g.some(b.resources,
function(b,e){return this._isIdenticalService(a,b)?(c=e,!0):!1},this);return c},_getSuffix:function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){var b,c;if((b=this._isRESTService(a))||this._isAdminResource(a))return c=a.toLowerCase().indexOf(b?this._agsRest:"/admin/"),b=a.substring(0,c)+"/admin/generateToken",a=a.substring(0,c)+"/rest/info",c=x(a,{query:{f:"json"},responseType:"json",callbackParamName:"callback"}).then(function(a){return a.data}),
c.adminUrl_=b,c;if(this._isPortalDomain(a)){var d="";g.some(this._gwDomains,function(b){b.regex.test(a)&&(d=b.tokenServiceUrl);return!!d});d||g.some(this._portals,function(b){this._hasSameServerInstance(b,a)&&(d=b+this._gwTokenUrl);return!!d},this);d||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(d=a.substring(0,c)+this._gwTokenUrl));d||(d=this._getOrigin(a)+this._gwTokenUrl);d&&(b=(new w(a)).port,/^http:\/\//i.test(a)&&"7080"===b&&(d=d.replace(/:7080/i,":7443")),d=d.replace(/http:/i,"https:"));
return d}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_getPortalSelf:function(a,b){"https:"===window.location.protocol?a=a.replace(/^http:/i,"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));return x(a,{query:{f:"json"},responseType:"json",callbackParamName:"callback",crossOrigin:!1,disableIdentityLookup:!0}).then(function(a){return a.data})},_hasPortalSession:function(){return!!this._getEsriAuthCookie()},
_getEsriAuthCookie:function(){var a;if(G.isSupported()){var b=this._getAllCookies("esri_auth"),c;for(c=0;c<b.length;c++){var d=JSON.parse(b[c]);if(d.portalApp){a=d;break}}}return a},_getAllCookies:function(a){var b=[],c=document.cookie.match(RegExp("(?:^|; )"+P.escapeString(a)+"\x3d([^;]*)","g"));if(c)for(a=0;a<c.length;a++){var d=c[a],e=d.indexOf("\x3d");-1<e&&(d=d.substring(e+1),b.push(decodeURIComponent(d)))}return b},_doPortalSignIn:function(a){if(G.isSupported()){var b=this._getEsriAuthCookie(),
c=this._portalConfig,d=window.location.href,e=this.findServerInfo(a);if(this.useSignInPage&&(c||this._isPortalDomain(d)||b)&&(e?e.hasPortal||e.owningSystemUrl&&this._isPortalDomain(e.owningSystemUrl):this._isPortalDomain(a))&&(this._isIdProvider(d,a)||c&&(this._hasSameServerInstance(this._getServerInstanceRoot(c.restBaseUrl),a)||this._isIdProvider(c.restBaseUrl,a))||p.hasSameOrigin(d,a,!0)))return!0}return!1},_checkProtocol:function(a,b,c,d){var e=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;if(0===
n.trim(d).toLowerCase().indexOf("https:")&&0!==window.location.href.toLowerCase().indexOf("https:")&&(!A.request.useCors||!p.canUseXhr(d)&&!p.canUseXhr(p.getProxyUrl(!0).path)))e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1,e||(a=Error("Aborted the Sign-In process to avoid sending password over insecure connection."),a.code="IdentityManagerBase.4",a.log=v.isDebug,console.log(a.message),c(a));return e},_enqueue:function(a,b,c,d,e,g){d||(d=H.makeDeferredCancellingPending());
d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=e;d.refresh_=g;this._busy?this._hasSameServerInstance(this._getServerInstanceRoot(a),this._busy.resUrl_)?(this._oAuthDfd&&this._oAuthDfd.oAuthWin_&&this._oAuthDfd.oAuthWin_.focus(),this._soReqs.push(d)):this._xoReqs.push(d):this._doSignIn(d);return d.promise},_doSignIn:function(a){this._busy=a;var b=this,c=function(c){var d=a.options_&&a.options_.resource,e=a.resUrl_,f=a.refresh_,l=!1;-1===g.indexOf(b.credentials,c)&&(f&&-1!==g.indexOf(b.credentials,f)?
(f.userId=c.userId,f.token=c.token,f.expires=c.expires,f.validity=c.validity,f.ssl=c.ssl,f.creationTime=c.creationTime,l=!0,c=f):b.credentials.push(c));c.resources||(c.resources=[]);c.resources.push(d||e);c.scope=b._isServerRsrc(e)?"server":"portal";c.emitTokenChange();var d=b._soReqs,m={};b._soReqs=[];g.forEach(d,function(a){if(!this._isIdenticalService(e,a.resUrl_)){var b=this._getSuffix(a.resUrl_);m[b]||(m[b]=!0,c.resources.push(a.resUrl_))}},b);a.resolve(c);g.forEach(d,function(a){a.resolve(c)});
b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;l||b.emit("credential-create",{credential:c});b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},d=function(c){a.reject(c);b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},e=function(e,f,g,k){var l=a.sinfo_,m=!a.options_||!1!==a.options_.prompt,h=l.hasPortal&&b._findOAuthInfo(a.resUrl_);b._doPortalSignIn(a.resUrl_)?
(e=b._getEsriAuthCookie(),h=b._portalConfig,e?c(new r({userId:e.email,server:l.server,token:e.token,expires:null})):m?(m="",e=window.location.href,m=b.signInPage?b.signInPage:h?h.baseUrl+h.signin:b._isIdProvider(e,a.resUrl_)?b._getOrigin(e)+"/home/signin.html":l.tokenServiceUrl.replace(b._rePortalTokenSvc,"")+"/home/signin.html",m=m.replace(/http:/i,"https:"),h&&!1===h.useSSL&&(m=m.replace(/https:/i,"http:")),0===e.toLowerCase().replace("https","http").indexOf(m.toLowerCase().replace("https","http"))?
(l=Error("Cannot redirect to Sign-In page from within Sign-In page. URL of the resource that triggered this workflow: "+a.resUrl_),l.code="IdentityManagerBase.5",l.log=v.isDebug,d(l)):b._redirectFunc?b._redirectFunc({signInPage:m,returnUrlParamName:"returnUrl",returnUrl:e,resourceUrl:a.resUrl_,serverInfo:l}):window.location=m+"?returnUrl\x3d"+window.escape(e)):(l=Error("User is not signed in."),l.code="IdentityManagerBase.6",l.log=v.isDebug,d(l))):e?c(new r({userId:e,server:l.server,token:g,expires:u.isDefined(k)?
Number(k):null,ssl:!!f})):h?(e=h._oAuthCred,e||(f=new J(h,window.localStorage),g=new J(h,window.sessionStorage),f.isValid()&&g.isValid()?f.expires>g.expires?(e=f,g.destroy()):(e=g,f.destroy()):e=f.isValid()?f:g,h._oAuthCred=e),e.isValid()?c(new r({userId:e.userId,server:l.server,token:e.token,expires:e.expires,ssl:e.ssl,_oAuthCred:e})):b._oAuthHash&&b._oAuthHash.state.portalUrl===h.portalUrl?(m=b._oAuthHash,l=new r({userId:m.username,server:l.server,token:m.access_token,expires:(new Date).getTime()+
1E3*Number(m.expires_in),ssl:"true"===m.ssl,oAuthState:m.state,_oAuthCred:e}),e.storage=m.persist?window.localStorage:window.sessionStorage,e.token=l.token,e.expires=l.expires,e.userId=l.userId,e.ssl=l.ssl,e.save(),b._oAuthHash=null,c(l)):m?a._pendingDfd=b.oAuthSignIn(a.resUrl_,l,h,a.options_).then(c,d):(l=Error("User is not signed in."),l.code="IdentityManagerBase.6",l.log=v.isDebug,d(l))):m?b._checkProtocol(a.resUrl_,l,d,a.admin_)&&(m=a.options_,a.admin_&&(m=m||{},m.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,
l,m).then(c,d)):(l=Error("User is not signed in."),l.code="IdentityManagerBase.6",l.log=v.isDebug,d(l))},k=function(){var e=a.sinfo_,f=e.owningSystemUrl,h=a.options_,k,l,m,n;h&&(k=h.token,l=h.error,m=h.prompt);n=b._findCredential(f,{token:k,resource:a.resUrl_});!n&&C(e)&&g.some(b.credentials,function(a){this._isIdProvider(f,a.server)&&(n=a);return!!n},b);n?(h=b.findCredential(a.resUrl_,n.userId))?c(h):D(e,b._legacyFed)?(h=n.toJSON(),h.server=e.server,h.resources=null,c(new r(h))):(a._pendingDfd=b.generateToken(b.findServerInfo(n.server),
null,{serverUrl:a.resUrl_,token:n.token,ssl:n.ssl})).then(function(b){c(new r({userId:n.userId,server:e.server,token:b.token,expires:u.isDefined(b.expires)?Number(b.expires):null,ssl:!!b.ssl,isAdmin:a.admin_,validity:b.validity}))},d):(b._busy=null,k&&(a.options_.token=null),(a._pendingDfd=b.getCredential(f.replace(/\/?$/,"/sharing"),{resource:a.resUrl_,owningTenant:e.owningTenant,token:k,error:l,prompt:m})).then(function(c){b._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},function(a){d(a)}))},
f=a.sinfo_.owningSystemUrl,h=this._isServerRsrc(a.resUrl_),p=a.sinfo_._restInfoDfd;p?p.then(function(c){var d=a.sinfo_;d.adminTokenServiceUrl=d._restInfoDfd.adminUrl_;d._restInfoDfd=null;d.tokenServiceUrl=n.getObject("authInfo.tokenServicesUrl",!1,c)||n.getObject("authInfo.tokenServiceUrl",!1,c)||n.getObject("tokenServiceUrl",!1,c);d.shortLivedTokenValidity=n.getObject("authInfo.shortLivedTokenValidity",!1,c);d.currentVersion=c.currentVersion;d.owningTenant=c.owningTenant;(c=d.owningSystemUrl=c.owningSystemUrl)&&
b._portals.push(c);h&&c?k():e()},function(){a.sinfo_._restInfoDfd=null;var b=Error("Unknown resource - could not find token service endpoint.");b.code="IdentityManagerBase.2";b.log=v.isDebug;d(b)}):h&&f?k():a.sinfo_._selfReq?a.sinfo_._selfReq.selfDfd.then(function(c){var d={},e,f,h,g;c&&(e=c.user&&c.user.username,d.username=e,d.allSSL=c.allSSL,f=c.supportsOAuth,h=c.currentVersion,"multitenant"===c.portalMode&&(g=c.customBaseUrl));a.sinfo_.webTierAuth=!!e;return e&&b.normalizeWebTierAuth?b.generateToken(a.sinfo_,
null,{ssl:d.allSSL}).always(function(a){d.portalToken=a&&a.token;d.tokenExpiration=a&&a.expires;return d}):!e&&f&&4.4<=parseFloat(h)&&!b._doPortalSignIn(a.resUrl_)?b._generateOAuthInfo({portalUrl:a.sinfo_.server,customBaseUrl:g,owningTenant:a.sinfo_._selfReq.owningTenant}).always(function(){return d}):d}).always(function(b){a.sinfo_._selfReq=null;b?e(b.username,b.allSSL,b.portalToken,b.tokenExpiration):e()}):e()},_generateOAuthInfo:function(a){var b=this,c,d=a.portalUrl,e=a.customBaseUrl,g=a.owningTenant;
if(a=!this.defaultOAuthInfo&&this._createDefaultOAuthInfo&&!this._hasTestedIfAppIsOnPortal){c=window.location.href;var f=c.indexOf("?");-1<f&&(c=c.slice(0,f));f=c.search(/\/(apps|home)\//);c=-1<f?c.slice(0,f):null}a&&c?(this._hasTestedIfAppIsOnPortal=!0,a=x(c+"/sharing/rest",{query:{f:"json"},responseType:"json"}).then(function(){b.defaultOAuthInfo=new K({appId:"arcgisonline",popup:!0,popupCallbackUrl:c+"/home/oauth-callback.html"})})):(a=new N,a.resolve(),a=a.promise);return a.then(function(){if(b.defaultOAuthInfo)return d=
d.replace(/^http:/i,"https:"),x(d+"/sharing/rest/oauth2/validateRedirectUri",{query:{accountId:g,client_id:b.defaultOAuthInfo.appId,redirect_uri:p.makeAbsolute(b.defaultOAuthInfo.popupCallbackUrl),f:"json"},responseType:"json",callbackParamName:"callback"}).then(function(a){if(a.data.valid){var c=b.defaultOAuthInfo.clone();c.portalUrl=a.data.urlKey&&e?"https://"+a.data.urlKey+"."+e:d;b.oAuthInfos.push(c)}})})}});r=E([Q,I],{declaredClass:"esri.Credential",tokenRefreshBuffer:2,constructor:function(a){n.mixin(this,
a);this.resources=this.resources||[];u.isDefined(this.creationTime)||(this.creationTime=(new Date).getTime())},_oAuthCred:null,refreshToken:function(){var a=this,b=this.resources&&this.resources[0],c=k.id.findServerInfo(this.server),d=c&&c.owningSystemUrl,e=!!d&&"server"===this.scope,n=e&&D(c,k.id._legacyFed),f=e&&k.id.findServerInfo(d),h,p=(h=c.webTierAuth)&&k.id.normalizeWebTierAuth,s=y[this.server],s=s&&s[this.userId],q={username:this.userId,password:s},t;if(!h||p)if(e&&!f&&g.some(k.id.serverInfos,
function(a){k.id._isIdProvider(d,a.server)&&(f=a);return!!f}),h=f&&k.id.findCredential(f.server,this.userId),!e||h)if(n)h.refreshToken();else{if(e)t={serverUrl:b,token:h&&h.token,ssl:h&&h.ssl};else if(p)q=null,t={ssl:this.ssl};else if(s)this.isAdmin&&(t={isAdmin:!0});else{var r;b&&(b=k.id._sanitizeUrl(b),this._enqueued=1,r=k.id._enqueue(b,c,null,null,this.isAdmin,this),r.then(function(){a._enqueued=0;a.refreshServerTokens()}).then(null,function(){a._enqueued=0}));return r}return k.id.generateToken(e?
f:c,e?null:q,t).then(function(b){a.token=b.token;a.expires=u.isDefined(b.expires)?Number(b.expires):null;a.creationTime=(new Date).getTime();a.validity=b.validity;a.emitTokenChange();a.refreshServerTokens()}).then(null,function(){})}},refreshServerTokens:function(){"portal"===this.scope&&g.forEach(k.id.credentials,function(a){var b=k.id.findServerInfo(a.server),c=b&&b.owningSystemUrl;if(a!==this&&a.userId===this.userId&&c&&"server"===a.scope&&(k.id._hasSameServerInstance(this.server,c)||k.id._isIdProvider(c,
this.server)))D(b,k.id._legacyFed)?(a.token=this.token,a.expires=this.expires,a.creationTime=this.creationTime,a.validity=this.validity,a.emitTokenChange()):a.refreshToken()},this)},emitTokenChange:function(a){clearTimeout(this._refreshTimer);var b=this.server&&k.id.findServerInfo(this.server),c=(b=b&&b.owningSystemUrl)&&k.id.findServerInfo(b);!1!==a&&((!b||"portal"===this.scope||c&&c.webTierAuth&&!k.id.normalizeWebTierAuth)&&(u.isDefined(this.expires)||u.isDefined(this.validity)))&&this._startRefreshTimer();
this.emit("token-change")},destroy:function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);var a=g.indexOf(k.id.credentials,this);-1<a&&k.id.credentials.splice(a,1);this.emitTokenChange();this.emit("destroy")},toJSON:function(){var a=u.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,
scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b);return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);var a=6E4*this.tokenRefreshBuffer,b=(this.validity?this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>b&&(b=0);this._refreshTimer=setTimeout(n.hitch(this,this.refreshToken),b>a?b-a:b)}});M.Credential=r;return M});