// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/Error ../../core/HandleRegistry ../../core/lang ../../core/urlUtils ../../core/promiseList ../../core/promiseUtils ../../core/watchUtils ../../request ../../tasks/support/StatisticDefinition ../../tasks/support/Query ../../tasks/QueryTask dojo/_base/lang dojo/promise/all dojo/i18n!dojo/cldr/nls/number".split(" "),function(B,v,C,k,D,E,r,x,y,F,z,G,q,w,A){var H=/\'/g,I=/href\s*=\s*(?:\"([^\"]+)\"|\'([^\']+)\')/ig,J=/(\{([^\{\r\n]+)\})/g,m={attachments:"attachments",
fields:"fields",media:"media",text:"text"},t={"short-date":"(datePattern: 'M/d/y', selector: 'date')","short-date-le":"(datePattern: 'd/M/y', selector: 'date')","long-month-day-year":"(datePattern: 'MMMM d, y', selector: 'date')","day-short-month-year":"(datePattern: 'd MMM y', selector: 'date')","long-date":"(datePattern: 'EEEE, MMMM d, y', selector: 'date')","short-date-short-time":"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')","short-date-le-short-time":"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",
"short-date-short-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')","short-date-le-short-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')","short-date-long-time":"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-le-long-time":"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-long-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",
"short-date-le-long-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')","long-month-year":"(datePattern: 'MMMM y', selector: 'date')","short-month-year":"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"};return B.createSubclass({declaredClass:"esri.widgets.Popup.PopupRendererViewModel",properties:{content:{readOnly:!0},contentEnabled:!0,contentTypes:{readOnly:!0},formattedAttributes:{readOnly:!0},graphic:{},title:{readOnly:!0},
waitingForContent:{readOnly:!0}},constructor:function(){this._handles=new C},initialize:function(){this._handles.add([x.init(this,"graphic",function(a){this._updateGraphic(a,this.contentEnabled)}.bind(this)),x.init(this,"contentEnabled",function(a){this._updateGraphic(this.graphic,a)}.bind(this))])},destroy:function(){this._handles.destroy();this._handles=null;this._clearRelatedInfo();this._cancelPromises();this.graphic=null;this._set("title",null);this._set("content",null);this._set("waitingForContent",
null)},content:null,contentEnabled:!0,contentTypes:m,formattedAttributes:null,graphic:null,title:"",waitingForContent:!1,_handles:null,_contentPromise:null,_contentPromiseLookup:null,_relatedRecordsPromise:null,_relatedRecordsQueryPromises:[],_relatedRecordsLayerPromises:[],_relatedLayersInfo:null,_relatedInfo:null,_dateFormats:t,_addValuesToHref:function(a,b,c,d){b=this._trimString(b);return k.substitute(b&&0===b.indexOf("${")?c:d,a)},_cancelPromises:function(){this._contentPromiseLookup&&(Object.keys(this._contentPromiseLookup).forEach(function(a){this._contentPromiseLookup[a].cancel()},
this),this._contentPromiseLookup=null);this._contentPromise&&(this._contentPromise.cancel(),this._contentPromise=null);this._relatedRecordsQueryPromises.forEach(function(a){a.cancel()});this._relatedRecordsQueryPromises.length=0;this._relatedRecordsLayerPromises.length&&(this._relatedRecordsLayerPromises.forEach(function(a){a.cancel()}),this._relatedRecordsLayerPromises.length=0);this._relatedRecordsPromise&&(this._relatedRecordsPromise.cancel(),this._relatedRecordsPromise=null)},_clearRelatedInfo:function(){this._relatedInfo=
this._relatedLayersInfo=null},_compileContent:function(a,b){var c=a.content;if("function"===typeof c&&(c=c.call(null,{graphic:a.graphic}))&&c.nodeName)return c;if("string"===typeof c)return this._compileText(a,{type:m.text,text:c}).text;if(Array.isArray(c))return c.map(function(c,d){switch(c.type){case m.attachments:return this._proxyAttachments(c,b&&b[d]);case m.fields:return c;case m.media:return this._compileMedia(a,c);case m.text:return this._compileText(a,c)}},this);if(c)try{throw new v(this.declaredClass+
"::invalid content type.");}catch(d){console.warn(d.stack)}},_compileMedia:function(a,b){var c=q.clone(b),d=c.mediaInfos,f=a.attributes,e=a.layer,g=this.formattedAttributes.global,h=a.substOptions,n,l;d&&(n=[],d.forEach(function(c){l=0;var b=c.value;switch(c.type){case "image":var d=b.sourceURL,d=d&&this._trimString(k.substitute(f,this._fixTokens(d,e)));l=!!d;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var s,d=b.normalizeField;b.fields=b.fields.map(function(a){return(s=
this._getLayerFieldInfo(e,a))?s.name:a},this);d&&(s=this._getLayerFieldInfo(e,d),b.normalizeField=s?s.name:d);l=b.fields.some(function(a){return k.isDefined(f[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(l){c=q.clone(c);var b=c.value,d=c.title?this._processFieldsInLinks(this._fixTokens(c.title,e),f):"",p=c.caption?this._processFieldsInLinks(this._fixTokens(c.caption,e),f):"";c.title=d?this._trimString(k.substitute(g,d,h)):"";c.caption=p?this._trimString(k.substitute(g,
p,h)):"";if("image"===c.type)b.sourceURL=k.substitute(f,this._fixTokens(b.sourceURL,e)),b.linkURL&&(b.linkURL=this._trimString(k.substitute(f,this._fixTokens(b.linkURL,e))));else{var u,m=(d=a.template)&&d.fieldInfos;b.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/")){var d=this._getRelatedChartInfos(e,m,a,b,f,h);Array.isArray(d)?b.fields=d:b.fields[c]=d}else{d=f[a];d=void 0===d?null:d;u=f[b.normalizeField]||0;d&&u&&(d/=u);var g=m&&this._getFieldInfo(m,a);b.fields[c]={y:d,tooltip:(g&&
g.label||a)+":"+this._formatValue(d,{fieldInfos:m,fieldName:a,layer:e,substOptions:h,preventPlacesFormatting:!!u})}}},this)}n.push(c)}},this));c.mediaInfos=n;return c},_compileText:function(a,b){var c=q.clone(b);if(c&&c.text){var d=a.attributes,f=this.formattedAttributes.global,e=a.substOptions,d=this._processFieldsInLinks(this._fixTokens(c.text,a.layer),d);c.text=this._trimString(k.substitute(f,d,e))}return c},_compileTitle:function(a){var b="",c=a.title,d=a.layer,f=a.attributes,e=a.substOptions,
g=this.formattedAttributes.global;c&&("function"===typeof c&&(c=c.call(null,{graphic:a.graphic})),"string"===typeof c&&-1===c.indexOf("{relationships/")&&(a=this._processFieldsInLinks(this._fixTokens(c,d),f),b=this._trimString(k.substitute(g,a,e))));return b},_createGraphicInfo:function(a,b){var c=a.getEffectivePopupTemplate(),d=c&&c.title,f=c&&c.content,e=a.layer,g=e&&e._getDateOpts&&e._getDateOpts().properties,h=q.clone(a.attributes)||{};return{graphic:a,template:c,title:d,content:f,contentEnabled:b,
layer:e,attributes:h,properties:g,substOptions:{dateFormat:{properties:g,formatter:"DateFormat"+t["short-date-short-time"]}}}},_fixTokens:function(a,b){return a.replace(J,function(a,d,f){return(a=this._getLayerFieldInfo(b,f))?"{"+a.name+"}":d}.bind(this))},_encodeAttributes:function(a){var b=q.clone(a)||{};Object.keys(b).forEach(function(a){var d=b[a];"string"===typeof d&&(d=encodeURIComponent(d).replace(H,"\x26apos;"),b[a]=d)});return b},_formatAttributesToFieldInfos:function(a,b,c,d,f){a.forEach(function(e){var g=
e.fieldName,h=this._getLayerFieldInfo(b,g);h&&(g=e.fieldName=h.name);f[g]=this._formatValue(f[g],{fieldInfos:a,fieldName:g,layer:b,substOptions:c});d&&(e.format&&e.format.dateFormat)&&(e=d.indexOf(g),-1<e&&d.splice(e,1))},this)},_formatAttributes:function(a,b,c,d,f,e){var g=q.clone(f);this._relatedInfo&&Object.keys(this._relatedInfo).forEach(function(a){var c=this._relatedInfo[a];a=this._relatedLayersInfo[a];c&&(c.relatedFeatures.forEach(this._relatedFeaturesAttributes.bind(this,a,f,g)),c.relatedStatsFeatures.forEach(this._relatedStatsAttributes.bind(this,
a,f,g)))},this);a&&this._formatAttributesToFieldInfos(a,b,c,d,g);if(b){var h=b.typeIdField;Object.keys(f).forEach(function(a){if(-1===a.indexOf("relationships/")){var c=f[a];if(k.isDefined(c)){var d=this._getDomainName(b,e,a,c);k.isDefined(d)?g[a]=d:a===h&&(c=this._getTypeName(b,e,c),k.isDefined(c)&&(g[a]=c))}}},this)}return g},_formatValue:function(a,b){var c=b.fieldInfos,d=b.fieldName,f=b.substOptions,c=c&&this._getFieldInfo(c,d),e=q.clone(c),c=b.preventPlacesFormatting,g=this._getLayerFieldInfo(b.layer,
d);g&&"date"===g.type&&(g=e.format||{},g.dateFormat=g.dateFormat||"short-date-short-time",e.format=g);g=e&&e.format;d="number"===typeof a&&f.dateFormat.properties&&-1===f.dateFormat.properties.indexOf(d)&&(!g||!g.dateFormat);if(!k.isDefined(a)||!e||!k.isDefined(g))return d?this._forceLTR(a):a;var h="",n=[],e=g.hasOwnProperty("places")||g.hasOwnProperty("digitSeparator"),l=g.hasOwnProperty("digitSeparator")?g.digitSeparator:!0;if(e){if(h="NumberFormat",k.isDefined(g.places)&&(!c||0<g.places))n.push("places: "+
Number(g.places)),h+="("+n.join(",")+")"}else if(g.dateFormat)h="DateFormat"+t[g.dateFormat]||t["short-date-short-time"];else return d?this._forceLTR(a):a;f=k.substitute({myKey:a},"{myKey:"+h+"}",f)||"";e&&!l&&A.group&&(f=f.replace(RegExp("\\"+A.group,"g"),""));return d?this._forceLTR(f):f},_forceLTR:function(a){return"\x26lrm;"+a},_getDomainName:function(a,b,c,d){return(a=a.getDomain&&a.getDomain(c,{feature:b}))&&a.codedValues?a.getName(d):null},_getFieldInfo:function(a,b){for(var c=b.toLowerCase(),
d,f=0;f<a.length;f++){var e=a[f];if(e.fieldName&&e.fieldName.toLowerCase()===c){d=e;break}}return d},_getLayerFieldInfo:function(a,b){return a&&a.getField?a.getField(b):null},_getTypeName:function(a,b){var c=a.getType&&a.getType(b);return c&&c.name},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b);a&&(a=a.replace(I,function(a,f){return this._addValuesToHref(a,f,b,c)}.bind(this)));return a},_proxyAttachments:function(a,b){var c=q.clone(a);if(b&&!(b instanceof v)&&b.attachmentInfos&&
b.attachmentInfos.length){var d=b.attachmentInfos.map(function(a){a.url=D.addProxy(a.url);return a},this);c.attachmentInfos=d}return c},_queryAttachments:function(a){var b=a.layer,c=a.attributes;a=b&&b.objectIdField;c=c&&a&&c[a];if(a&&b.hasAttachments&&c)return this._queryAttachmentInfos(b,c)},_queryAttachmentInfos:function(a,b){var c=a.url+"/"+a.layerId+"/"+b+"/attachments",d=a.token||"";return y(c,{query:{f:"json",token:d},callbackParamName:"callback"}).then(function(a){a=a.data;a.attachmentInfos.forEach(function(a){a.url=
c+"/"+a.id;d&&(a.url+="?token\x3d"+d);a.objectId=b});return a})},_queryContent:function(a){var b=a.template,b=b&&b.content;if(!b||"string"===typeof b||"function"===typeof b)return r.resolve();if(!Array.isArray(b))return r.reject(new v(this.declaredClass+"::Invalid content type."));var c={};b.forEach(function(b,f){b.type===m.attachments&&(c[f]=this._queryAttachments(a))},this);if(0===Object.keys(c).length)return r.resolve();this._contentPromiseLookup=c;return E(c).always(function(a){this._contentPromiseLookup=
null;return a}.bind(this))},_trimString:function(a){return(a||"").trim()},_updateContent:function(a){if(a.contentEnabled){var b=this._queryContent(a).then(function(c){this._set("content",this._compileContent(a,c))}.bind(this),function(a){console.log(this.declaredClass+"::error loading template",a)}.bind(this)).always(function(){this._contentPromise=null}.bind(this));return this._contentPromise=b}return r.resolve()},_createFormattedAttributes:function(a){var b=a.graphic,c=a.attributes,d=a.layer,f=
a.template,e=a.substOptions,g=a.properties,h={global:this._formatAttributes(f&&f.fieldInfos,d,e,g,c,b),content:[]};a=f&&f.content;Array.isArray(a)&&a.forEach(function(a,f){a.type===m.fields&&a.fieldInfos&&(h.content[f]=this._formatAttributes(a.fieldInfos,d,e,g,c,b))},this);return h},_updateGraphic:function(a,b){if(this._handles&&(this._clearRelatedInfo(),this._cancelPromises(),this._set("title",""),this._set("content",null),this._set("formattedAttributes",null),this._set("waitingForContent",!1),a)){this._set("waitingForContent",
!0);var c=this._createGraphicInfo(a,b);this._relatedRecordsPromise=this._checkForRelatedRecords(c).then(function(){this._set("formattedAttributes",this._createFormattedAttributes(c));this._set("title",this._compileTitle(c));return this._updateContent(c)}.bind(this)).always(function(){this._relatedRecordsPromise=null;this._relatedRecordsLayerPromises.length=0;this._relatedRecordsQueryPromises.length=0;this._set("waitingForContent",!1)}.bind(this))}},_getAllFieldInfos:function(a){var b=[],c=a.template,
d=c&&c.fieldInfos;a=a.contentEnabled;d&&(b=b.concat(d));a&&(c=c&&c.content,Array.isArray(c)&&c.forEach(function(a){b=b.concat(a&&a.fieldInfos)},this));return b},_checkForRelatedRecords:function(a){var b=this._getAllFieldInfos(a).filter(function(a){return a&&a.fieldName&&-1!==a.fieldName.indexOf("relationships/")},this);return a.layer&&b&&0<b.length?this._getRelatedRecords({graphic:a.graphic,fieldsInfo:b}):r.resolve()},_relatedFeaturesAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){if("esriRelCardinalityOneToOne"===
a.relation.cardinality){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]}},this)},_relatedStatsAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]},this)},_getRelatedChartInfos:function(a,b,c,d,f,e){var g,h,n,l,k,m;g=[];m=this._fromRelatedFieldName(c);k=m[0];h=this._relatedInfo[k];k=this._relatedLayersInfo[k];h&&h.relatedFeatures.forEach(function(h){var k=h.attributes,p;Object.keys(k).forEach(function(h){if(h===
m[1]){p={};l=k[h];d.normalizeField&&(n=-1!==d.normalizeField.indexOf("relationships/")?k[this._fromRelatedFieldName(d.normalizeField)[1]]:f[d.normalizeField]);l&&n&&(l/=n);if(d.tooltipField)if(-1!==d.tooltipField.indexOf("relationships/"))h=this._fromRelatedFieldName(d.tooltipField)[1],h=k[h],p.tooltip=h+": "+this._formatValue(l,{fieldInfos:b,fieldName:h,layer:a,substOptions:e,preventPlacesFormatting:!!n});else{if(h=this._getLayerFieldInfo(a,c))c=h.name;p.tooltip=c+": "+this._formatValue(l,{fieldInfos:b,
fieldName:d.tooltipField,layer:a,substOptions:e,preventPlacesFormatting:!!n})}else p.tooltip=l;p.y=l;g.push(p)}},this)},this);return"esriRelCardinalityOneToMany"===k.relation.cardinality||"esriRelCardinalityManyToMany"===k.relation.cardinality?g:g[0]},_getRelatedRecords:function(a){var b=a.graphic;return this._relatedLayersInfo?this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this)):this._getRelatedLayersInfo(a).then(function(a){Object.keys(a).forEach(function(b){a[b]&&
(this._relatedLayersInfo[b].relatedLayerInfo=a[b].data)},this);return this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this))}.bind(this))},_getRelatedLayersInfo:function(a){var b=a.fieldsInfo,c,d={};c=a.graphic.layer;this._relatedLayersInfo||(this._relatedLayersInfo={});b.forEach(function(a){var b,d,h;b=this._fromRelatedFieldName(a.fieldName);d=b[0];b=b[1];if(d){if(!this._relatedLayersInfo[d]){var k=c&&c.relationships;k&&k.some(function(a){if(a.id==d)return h=
a,!0});h&&(this._relatedLayersInfo[d]={relation:h,relatedFields:[],outStatistics:[]})}this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),a.statisticType&&(a=new F({statisticType:a.statisticType,onStatisticField:b,outStatisticFieldName:b}),this._relatedLayersInfo[d].outStatistics.push(a)))}},this);Object.keys(this._relatedLayersInfo).forEach(function(a){var b;this._relatedLayersInfo[a]&&(b=this._relatedLayersInfo[a].relation,b=c.url+"/"+b.relatedTableId,this._relatedLayersInfo[a].relatedLayerUrl=
b,d[a]=y(b,{query:{f:"json"},callbackParamName:"callback"}))},this);Object.keys(d).forEach(function(a){this._relatedRecordsLayerPromises.push(d[a])},this);return w(d)},_queryRelatedLayers:function(a){var b={};Object.keys(this._relatedLayersInfo).forEach(function(c){b[c]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[c]})},this);return w(b)},_queryRelatedLayer:function(a){var b,c,d,f,e,g,h,k,l;b=a.graphic;c=b.layer.layerId;h=a.relatedInfo;a=h.relatedLayerInfo;k=h.relatedLayerUrl;
l=h.relation;a&&a.relationships&&a.relationships.some(function(a){if(a.relatedTableId===parseInt(c,10))return d=a,!0});d&&(a.fields.some(function(a){if(a.name===d.keyField)return f=-1!==["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(a.type)?"number":"string",!0}),e="string"===f?d.keyField+"\x3d'"+b.attributes[l.keyField]+"'":d.keyField+"\x3d"+b.attributes[l.keyField],e=new z({where:e,outFields:h.relatedFields}),h.outStatistics&&(0<h.outStatistics.length&&
a.supportsStatistics)&&(g=new z({where:e.where,outFields:e.outFields,outStatistics:h.outStatistics})),a=new G({url:k}),e=[a.execute(e)],g&&e.push(a.execute(g)));this._relatedRecordsQueryPromises=this._relatedRecordsQueryPromises.concat(e);return w(e)},_setRelatedRecords:function(a){this._relatedInfo=[];Object.keys(a).forEach(function(b){if(a[b]){var c=a[b];this._relatedInfo[b]={relatedFeatures:c[0].features};k.isDefined(c[1])&&(this._relatedInfo[b].relatedStatsFeatures=c[1].features)}},this)},_fromRelatedFieldName:function(a){return-1!==
a.indexOf("relationships/")?a.split("/").slice(1):[]},_toRelatedFieldName:function(a){return a&&0<a.length?"relationships/"+a[0]+"/"+a[1]:""}})});