// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper dojo/_base/lang dojo/when ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./Graphics3DDrapedGraphicLayer ./ElevationAligners ./Graphics3DSymbolCommonCode ./SignedDistanceFunctions ./FastSymbolUpdates ../../../../core/urlUtils ../../../../core/screenUtils ../../../../config ../../../../Color ../../../../geometry/Polygon ../../support/projectionUtils ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/lib/Texture ../../webgl-engine/materials/HUDMaterial".split(" "),
function(B,aa,L,C,D,v,E,M,w,g,k,t,x,r,F,N,O,P,y,s,Q,G,R,S,H){function z(g){return"cross"===g||"x"===g}function T(g){var b,a=n,c=a*u;"primitive:"===g.substring(0,10)&&(g=g.substring(10));switch(g){case p.PRIM_CIRCLE:b=k.computeSignedDistancefieldCicle(a,c);break;case p.PRIM_SQUARE:b=k.computeSignedDistancefieldSquare(a,c,!1);break;case p.PRIM_KITE:b=k.computeSignedDistancefieldSquare(a,c,!0);break;case p.PRIM_CROSS:b=k.computeSignedDistancefieldCrossAndX(a,c,!1);break;case p.PRIM_X:b=k.computeSignedDistancefieldCrossAndX(a,
c,!0)}return new S(b,"sdf_"+g,{mipmap:!1,wrapClamp:!0,width:n,height:n,components:4})}var U=y.vec3d;B=y.vec4d;var A=y.mat4d.identity(),I=[0,0,1],V=[0,0,0,0],W=[0,0,0],X=[1,1,1],J="center bottom top left right bottom-left bottom-right top-left top-right".split(" "),n=128,u=0.5,p={PRIM_CIRCLE:"circle",PRIM_SQUARE:"square",PRIM_CROSS:"cross",PRIM_X:"x",PRIM_KITE:"kite"},Y=[n*u,n*u];v=function(k){function b(){k.apply(this,arguments)}L(b,k);b.prototype._prepareResources=function(){var a=this.symbol,c=
null!=a.size?r.pt2px(a.size):16;this._size=null;this._symbolTextureRatio=1;this._primitive=null;var K=this._getStageIdHint();this._isPropertyDriven("size")&&64>c&&(c=64);var e=a.resource||{primitive:"circle",href:void 0},d={anchorPos:this._getAnchorPos(a)};if(e.href)d.color=this._getFillColor(a,null),d.outlineColor=this._getOutlineColor(a),d.outlineSize=this._getOutlineSize(a,null),d.textureIsSignedDistanceField=!1,this._prepareImageResources(e.href,c,d,K);else{var e=e.primitive||"circle",b="primitive:"+
e;this._primitive=e;d.color=this._getFillColor(a,e);d.outlineColor=this._getOutlineColor(a);d.outlineSize=this._getOutlineSize(a,e);z(e)&&0===d.outlineSize?this.reject():(this.texture=this._context.sharedResources.textures.acquire(b,T),this._textureURI=b,d.textureIsSignedDistanceField=!0,d.textureId=this.texture.getId(),this._size=[c,c],this._symbolTextureRatio=1/u,this._createMaterialsAndAddToStage(d,this._context.stage,K),this.resolve())}};b.prototype._getOutlineDefaultSize=function(a){return z(a)?
1.5:0};b.prototype._getOutlineSize=function(a,c){return a.outline?null!=a.outline.size?r.pt2px(a.outline.size):this._getOutlineDefaultSize(c):this._getOutlineDefaultSize(c)};b.prototype._getOutlineColor=function(a){var c=this._getLayerOpacity();if(a.outline&&null!=a.outline.color){var b=N.toUnitRGB(a.outline.color);return[b[0],b[1],b[2],a.outline.color.a*c]}return[0,0,0,c]};b.prototype._getFillColor=function(a,c){return z(c)?V:this._getMaterialOpacityAndColor()};b.prototype._getAnchorPos=function(a){return-1<
J.indexOf(a.anchor)?a.anchor:"center"};b.prototype._prepareImageResources=function(a,c,b,e){var d=this,f=function(a){if(!d.isRejected()){var f=a.params,g=f.width/f.height;d._size=c?1<g?[c,c/g]:[c*g,c]:[f.width,f.height];b.textureId=a.getId();d._createMaterialsAndAddToStage(b,d._context.stage,e);d.resolve()}},g="data:image/svg"===a.substring(0,14),q=".svg"===a.substring(a.length-4,a.length);if(!g&&!q)D(this._context.sharedResources.textures.acquire(a),f,function(){d.reject()}),this._textureURI=a;else{a=
x.normalize(a);var h=new Image,q=!g&&x.hasSameOrigin(a,window.location.href);g||(q||x.canUseXhr(a)?q||(h.crossOrigin="anonymous"):F.request.proxyUrl&&(a=F.request.proxyUrl+"?"+a));h.src=a;h.onerror=function(){d.reject()};h.onload=function(){var a=h.width,b=h.height,e=1;a&&b&&(e=a/b);null!=c&&(1<e?(a=c,b=Math.round(c/e)):(b=c,a=Math.round(c*e)));e=document.createElement("canvas");e.width=a;e.height=b;e.getContext("2d").drawImage(h,0,0,a,b);a=e.toDataURL();D(d._context.sharedResources.textures.acquire(a),
f,function(){d.reject()});d._textureURI=a};h.onerror=function(){console.warn("Failed to create Icon primitive");d.reject()}}};b.prototype._createMaterialsAndAddToStage=function(a,c,b){this._fastUpdates=t.initFastSymbolUpdatesState(this._context.renderer,this._supportsShaderVisualVariables(),this._fastVisualVariableConvertOptions());this._fastUpdates.enabled&&C.mixin(a,this._fastUpdates.materialParameters);var e=C.clone(a);e.occlusionTest=!1;e.shaderPolygonOffset=0;this._drapedMaterial=new H(e,b+"_iconDraped");
c.add(s.ModelContentType.MATERIAL,this._drapedMaterial);a.occlusionTest=!0;this._material=new H(a,b+"_icon");c.add(s.ModelContentType.MATERIAL,this._material)};b.prototype.destroy=function(){this.isFulfilled()||this.reject();this._material&&(this._context.stage.remove(s.ModelContentType.MATERIAL,this._material.getId()),this._material=null);this._drapedMaterial&&(this._context.stage.remove(s.ModelContentType.MATERIAL,this._drapedMaterial.getId()),this._drapedMaterial=null);this._textureURI&&(this._context.sharedResources.textures.release(this._textureURI),
this._textureURI=null)};b.prototype._getGeometry=function(a){a=a.geometry;if("extent"===a.type)return g.placePointOnPolygon(O.fromExtent(a));if("polyline"===a.type)return g.placePointOnPolyline(a);if("polygon"===a.type)return g.placePointOnPolygon(a);if("point"===a.type)return a;this._logWarning("unsupported geometry type for icon symbol: "+a.type);return null};b.prototype._getScaleFactor=function(a){if(this._isPropertyDriven("size")){if(a.size){for(var c=0;3>c;c++)a.size[c]&&"symbolValue"!==a.size[0]&&
(a.size[c]=r.pt2px(a.size[c]));c=this._size[0]>this._size[1]?this._size[0]:this._size[1];if("symbolValue"===a.size[0])return 1;if(isFinite(a.size[0]))return a.size[0]/c;if(isFinite(a.size[2]))return a.size[2]/c}}else return 1};b.prototype.createGraphics3DGraphic=function(a,c){var b=this._getGeometry(a);if(null===b)return null;var e="graphic"+a.uid,d=this._getVertexOpacityAndColor(c),f=1;if(!this._fastUpdates.enabled||!this._fastUpdates.visualVariables.size)f=this._getScaleFactor(c);var f=f*this._symbolTextureRatio,
f=[this._size[0]*f,this._size[1]*f],l=this._getGraphicElevationInfo(a);return l.mode===g.ELEV_MODES.ON_THE_GROUND?this._createAsOverlay(a,b,d,f,l,e,a.uid):this._createAs3DShape(a,b,d,f,l,e,a.uid)};b.prototype.layerPropertyChanged=function(a,c,b){if("opacity"===a)return c=this._getFillColor(this.symbol,this._primitive),this._drapedMaterial.setParameterValues({color:c}),this._material.setParameterValues({color:c}),c=this._getOutlineColor(this.symbol),this._drapedMaterial.setParameterValues({outlineColor:c}),
this._material.setParameterValues({outlineColor:c}),!0;if("elevationInfo"===a){var e=this._elevationInfo.mode;this._updateElevationInfo();a=this._elevationInfo.mode;var d=g.ELEV_MODES;if(e===d.ON_THE_GROUND&&a===d.ON_THE_GROUND)return!0;if(e!==a&&(e===d.ON_THE_GROUND||a===d.ON_THE_GROUND))return!1;var e=this._context.elevationProvider,f=this._context.renderCoordsHelper,l=w.perObjectElevationAligner,q;for(q in c){var h=c[q],m=h._graphics[b];m&&m instanceof E&&(h=this._getGraphicElevationInfo(h.graphic),
m.elevationAligner=a===d.RELATIVE_TO_GROUND?l:null,m.elevationInfo.set(h),l(m,e,f))}return!0}return!1};b.prototype.applyRendererDiff=function(a,c,b,e){for(var d in a.diff)switch(d){case "visualVariables":if(t.updateFastSymbolUpdatesState(this._fastUpdates,c,this._fastVisualVariableConvertOptions()))this._material.setParameterValues(this._fastUpdates.materialParameters),this._drapedMaterial.setParameterValues(this._fastUpdates.materialParameters);else return!1;break;default:return!1}return!0};b.prototype.setDrawOrder=
function(a,c,b){this._drapedMaterial&&(this._drapedMaterial.setRenderPriority(a),b[this._drapedMaterial.getId()]=!0)};b.prototype._defaultElevationInfoNoZ=function(){return Z};b.prototype._getGraphicElevationInfo=function(a){var c=k.prototype._getGraphicElevationInfo.call(this,a);c.mode===g.ELEV_MODES.RELATIVE_TO_GROUND&&(0===c.offset&&!a.geometry.get("hasZ"))&&(c.offset=1/this._context.renderCoordsHelper.unitInMeters);return c};b.prototype._createAs3DShape=function(a,c,b,e,d,f,l){var q=this,h=this._getFastUpdateAttrValues(a),
m=h?function(a){return t.evaluateModelTransform(q._fastUpdates.materialParameters,h,a)}:null;a=G.createPointGeometry(I,null,b,e,null,$,null,h);a=[new Q(a,f)];f=g.createStageObjectForPoint.call(this,c,a,[[this._material]],null,null,d,f,this._context.layer.id,l,!0,m);if(null===f)return null;l=null;d.mode===g.ELEV_MODES.RELATIVE_TO_GROUND?l=w.perObjectElevationAligner:d.mode===g.ELEV_MODES.ABSOLUTE_HEIGHT&&(l=w.perObjectVerticalDistanceToGroundAligner);d=new E(this,f,a,null,null,l,d);if(this._fastUpdates.enabled){var k=
e[0]/this._symbolTextureRatio,n=e[1]/this._symbolTextureRatio;d.getScreenSize=function(){var a=m(A);return[a[0]*k,a[5]*n]}}else{var p=e[0]/this._symbolTextureRatio,r=e[1]/this._symbolTextureRatio;d.getScreenSize=function(){return[p,r]}}g.extendPointGraphicElevationInfo(d,c,this._context.elevationProvider);return d};b.prototype._createAsOverlay=function(a,c,b,e,d,f,l){var k=this;this._drapedMaterial.setRenderPriority(this._symbolLayerOrder);d=U.create();P.pointToVector(c,d,this._context.overlaySR);
d[2]=this._getDrapedZ();if((c=this._context.clippingExtent)&&!g.pointInBox2D(d,c))return null;var h=this._getFastUpdateAttrValues(a),m=h?function(a){return t.evaluateModelTransform(k._fastUpdates.materialParameters,h,a)}:null;a=G.createPointGeometry(I,d,b,e,!0,null,null,h);b=new R(a);b.material=this._drapedMaterial;b.center=d;b.bsRadius=0;b.transformation=A;b.name=f;b.uniqueName=f+"#"+a.id;f=new M(this,[b],null,null,null);if(this._fastUpdates.enabled){var n=e[0]/this._symbolTextureRatio,p=e[1]/this._symbolTextureRatio;
f.getScreenSize=function(){var a=m(A);return[a[0]*n,a[5]*p]}}else{var r=e[0]/this._symbolTextureRatio,s=e[1]/this._symbolTextureRatio;f.getScreenSize=function(){return[r,s]}}return f};b.prototype._supportsShaderVisualVariables=function(){return!0};b.prototype._fastVisualVariableConvertOptions=function(){var a=this._size[0]>this._size[1]?this._size[0]:this._size[1];return{modelSize:[a,a,a],unitInMeters:r.px2pt(1),transformation:{anchor:W,scale:X}}};b.PRIMITIVE_SIZE=Y;b.VALID_ANCHOR_STRINGS=J;return b}(v);
var Z={mode:g.ELEV_MODES.RELATIVE_TO_GROUND,offset:0},$=B.createFrom(0,0,0,1);return v});