// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper dojo/_base/lang ../../support/PromiseLightweight ./ElevationInfo ./graphicUtils ../../../../core/Logger ../../../../Color".split(" "),function(h,v,n,l,p,k,m,q,r){var g=new k,s=q.getLogger("esri.symbols.Symbol3D");h=function(h){function b(a,d,b){h.call(this);this.symbol=a;this._context=d;this._symbolLayerOrder=d.layerOrder;this._symbolLayerOrderDelta=d.layerOrderDelta;this._elevationInfo=new k;this._material=null;this._updateDrivenProperties(b);
this._updateElevationInfo();this._prepareResources()}n(b,h);b.prototype._logWarning=function(a){s.warn(a)};b.prototype._prepareResources=function(a){throw Error("This is an abstract base class");};b.prototype._defaultElevationInfoNoZ=function(){return t};b.prototype._defaultElevationInfoZ=function(){return u};b.prototype._updateElevationInfo=function(){for(var a in this._elevationInfo)this._elevationInfo[a]=void 0;if(a=this._context.layer.elevationInfo)this._elevationInfo=l.mixin(this._elevationInfo,
a);this.symbol.elevationInfo&&(this._elevationInfo=l.mixin(this._elevationInfo,this.symbol.elevationInfo))};b.prototype._getGraphicElevationInfo=function(a){a=a.geometry.hasZ?this._defaultElevationInfoZ():this._defaultElevationInfoNoZ();g.mode=this._elevationInfo.mode||a.mode;g.offset=null!=this._elevationInfo.offset?this._elevationInfo.offset:a.offset;g.featureExpression=this._elevationInfo.featureExpression;g.offset/=this._context.renderCoordsHelper.unitInMeters;return g};b.prototype._getDrapedZ=
function(){return-2};b.prototype._updateDrivenProperties=function(a){var d={color:!1,opacity:!1,size:!1};if(!a&&(a=this._context.renderer))d.color=!!a.colorInfo,d.size=!!a.sizeInfo,a.visualVariables&&a.visualVariables.forEach(function(a){switch(a.type){case "color":d.color=!0;if(a.colors)for(var b=0;b<a.colors.length;b++){var f=a.colors[b];if(f&&(Array.isArray(f)&&3<f.length&&255!==f[3]||void 0!==f.a&&255!==f.a))d.opacity=!0}if(a.stops)for(b=0;b<a.stops.length;b++)if((f=a.stops[b].color)&&(Array.isArray(f)&&
3<f.length&&255!==f[3]||void 0!==f.a&&255!==f.a))d.opacity=!0;break;case "opacity":d.opacity=!0;break;case "size":d.size=!0}});this._drivenProperties=d};b.prototype._isPropertyDriven=function(a){return this._drivenProperties[a]};b.prototype._getLayerOpacity=function(){if(this._context.layerView&&"fullOpacity"in this._context.layerView)return this._context.layerView.fullOpacity;var a=this._context.layer.opacity;return null==a?1:a};b.prototype._getMaterialOpacity=function(){var a;a=1*this._getLayerOpacity();
var b=this.symbol.material;b&&!this._isPropertyDriven("opacity")&&(a*=b.color.a);return a};b.prototype._getMaterialOpacityAndColor=function(){var a=this.symbol.material,b=this._getMaterialOpacity(),a=this._isPropertyDriven("color")||!a?null:r.toUnitRGB(a.color);return m.mixinColorAndOpacity(a,b)};b.prototype._getVertexOpacityAndColor=function(a,b,e){var c=this._isPropertyDriven("color")?a.color:null;a=this._isPropertyDriven("opacity")?a.opacity:null;c=m.mixinColorAndOpacity(c,a);e&&(c[0]*=e,c[1]*=
e,c[2]*=e,c[3]*=e);return b?new b(c):c};b.prototype._getStageIdHint=function(){return this._context.layer.id+"_symbol"};b.prototype.setDrawOrder=function(a,b,e){this._material&&(this._material.setRenderPriority(a),e[this._material.getId()]=!0)};b.prototype.createGraphics3DGraphic=function(a,b){for(var e=2;e<arguments.length;e++);throw Error("This is an abstract base class");};b.prototype.destroy=function(){throw Error("This is an abstract base class");};b.prototype.layerPropertyChanged=function(a,
b,e){return!1};b.prototype.applyRendererDiff=function(a,b,e,c){return!1};b.prototype._getFastUpdateAttrValues=function(a){if(!this._fastUpdates.enabled)return null;var b=this._fastUpdates.visualVariables.field;a=null!=b?a.attributes[b]:0;if(null==a||!isFinite(a))a=0;return[a,0,0,0]};return b}(p.Promise);var t={mode:k.MODES.ON_THE_GROUND,offset:0},u={mode:k.MODES.ABSOLUTE_HEIGHT,offset:0};return h});