// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["require","exports"],function(q,r){function h(a){var b=!1;a.labelingInfo&&(b=b||a.labelingInfo.some(function(b){return b&&(null!==b.minScale&&0<b.minScale&&8E7>b.minScale||1E3<b.maxScale)}));return b=b||null!==a.minScale&&0<a.minScale&&8E7>a.minScale||1E3<a.maxScale}return function(){function a(){this._scaleRangeActive=!1;this.layerScaleRangeVisibilityDirty=this.layerScaleRangeVisibility=!0;this.layerScaleRangeVisibilityQuery=!1;this.basemapTerrain=this.graphicsCore=this.extent=this.spatialIndex=
this.layer=this.layerView=this.scaleChangeEventHandle=null}a.prototype.initialize=function(b,c,d,a,l){this.layerView=b;this.layer=c;this.spatialIndex=d;this.graphicsCore=a;this._scaleRangeActive=h(c);this.basemapTerrain=l;this.layerMinMaxScaleChangeHandler(!1)};a.prototype.destroy=function(){this.scaleChangeEventHandle&&(this.scaleChangeEventHandle.remove(),this.scaleChangeEventHandle=null);this.graphicsCore=this.spatialIndex=this.extent=this.layerView=null};a.prototype.needsIdleUpdate=function(){return this.layerView.view.basemapTerrain&&
this.layerScaleRangeVisibilityDirty};a.prototype.canResume=function(){return this.layerScaleRangeVisibility};a.prototype.setExtent=function(b){this.extent=b;this.layerScaleRangeVisibilityDirty=!0};a.prototype.idleUpdate=function(b){this.layerView.view.basemapTerrain&&(!b.done()&&this.layerScaleRangeVisibilityDirty)&&(this.updateSuspendScaleVisible(),this.layerScaleRangeVisibilityDirty=!1)};a.prototype.scaleRangeActive=function(){return this._scaleRangeActive};a.prototype.updateSuspendScaleVisibleFinish=
function(b){this.layerScaleRangeVisibilityQuery=!1;this.layerScaleRangeVisibility!==b&&(this.layerScaleRangeVisibility=b,this.layerView._notifySuspendedChange())};a.prototype.updateSuspendScaleVisible=function(){var b=this,c=this.layerView.view.basemapTerrain;!this.extent||!c||!this._scaleRangeActive?this.updateSuspendScaleVisibleFinish(!0):this.layerScaleRangeVisibilityQuery||(this.layerScaleRangeVisibilityQuery=!0,c.queryVisibleScaleRange(this.extent,this.layer.minScale,this.layer.maxScale,function(c){return b.updateSuspendScaleVisibleFinish(c)}))};
a.prototype.visibleAtScale=function(b,c,a){return null==b?!0:b>a&&(!c||b<c)};a.prototype.visibleAtLayerScale=function(b){return this.visibleAtScale(b,this.layer.minScale,this.layer.maxScale)};a.prototype.visibleAtLabelScale=function(b,c){return this.visibleAtScale(b,c.minScale,c.maxScale)};a.prototype.graphicScale=function(b,c){var a;c.centroid?a=c.centroid:"point"===b.geometry.type&&(a=b.geometry);return a?this.layerView.view.basemapTerrain?this.layerView.view.basemapTerrain.getScale(a):1:null};
a.prototype.graphicVisible=function(b,c){var a=this.graphicScale(b,c);return this.visibleAtLayerScale(a)};a.prototype.updateGraphicScaleVisibility=function(b,a){if(this._scaleRangeActive&&a.addedToSpatialIndex){var d=this.graphicVisible(b,a);return a.setVisibilityFlag("VISIBILITY_SCALERANGE",d)}return!1};a.prototype.updateGraphicLabelScaleVisibility=function(b,a){if(!this._scaleRangeActive||!a.addedToSpatialIndex||!a._labelGraphics||0===a._labelGraphics.length)return!1;var d=this.graphicScale(b,a);
(d=this.updateLabelScaleVisibility(a,d))&&this.layerView.view.labelManager.setDirty();return d};a.prototype.updateLabelScaleVisibility=function(b,a){if(!b._labelGraphics||0===b._labelGraphics.length)return!1;for(var d=!1,g=0,l=b._labelGraphics;g<l.length;g++){var n=l[g],f=n._labelClass;f&&(null!=f.minScale&&null!=f.maxScale)&&(f=this.visibleAtLabelScale(a,f),n.setVisibilityFlag("VISIBILITY_SCALERANGE_LABEL",f)&&(d=!0))}return d};a.prototype.scaleUpdateHandler=function(a){var c=this;if(!this.layerView.suspended&&
this.spatialIndex.hasGraphics()){var d=a.extent,g=a.scale;this.spatialIndex.intersects(d,a.spatialReference,function(a,b){for(var f=c.visibleAtLayerScale(g),h=!1,p=!1,m=0;m<b;m++){var k=c.graphicsCore.getGraphics3DGraphicById(a[m]);if(k){var e=k.centroid;if(!e||!(d[0]>e.x||d[1]>e.y||d[2]<e.x||d[3]<e.y))e=!1,k.setVisibilityFlag("VISIBILITY_SCALERANGE",f)&&(e=!0),c.updateLabelScaleVisibility(k,g)&&(e=!0),e&&(p=!0,k.isDraped()&&(h=!0))}}p&&c.layerView.view.labelManager.setDirty();h&&c.layerView._notifyDrapedDataChange()})}this.layerScaleRangeVisibilityDirty=
!0};a.prototype.layerMinMaxScaleChangeHandler=function(a){var c=this;void 0===a&&(a=!0);(this._scaleRangeActive=h(this.layer))&&!this.scaleChangeEventHandle?(this.scaleChangeEventHandle=this.basemapTerrain.on("scale-change",function(a){return c.scaleUpdateHandler(a)}),this.layerView.suspended||this.spatialIndex.addGraphicsToSpatialIndex(this._scaleRangeActive)):!this._scaleRangeActive&&this.scaleChangeEventHandle&&(this.scaleChangeEventHandle.remove(),this.scaleChangeEventHandle=null);!this.layerView.suspended&&
a&&this.graphicsCore.updateAllGraphicsVisibility();this.layerScaleRangeVisibilityDirty=!0};return a}()});