// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/watchUtils ../../../../core/arrayUtils ../../../../core/Error ../../../../core/Logger ../../../../core/promiseUtils ../../support/projectionUtils ../../../../renderers/support/rendererConversion ../../../../renderers/support/diffUtils ../../../../geometry/Point ../../../../geometry/Extent ../../webgl-engine/Stage ../../webgl-engine/lib/Util ../../webgl-engine/lib/Layer ../../webgl-engine/lib/FloatingBoxLocalOriginFactory ../../../../symbols/WebStyleSymbol ../../../../symbols/support/symbolConversion ../../lib/glMatrix ./Graphics3DGraphic ./Graphics3DSymbol ./Graphics3DWebStyleSymbol ./graphicUtils ./Graphics3DOwner ../../support/aaBoundingBox ../../support/mathUtils dojo/Deferred".split(" "),
function(u,R,r,B,v,C,D,p,E,F,G,H,s,w,x,I,J,y,z,K,L,M,N,O,A,n,P){u=z.vec3d;var q=new G,t=u.create(),Q=C.getLogger("esri.views.3d.LayerView3D");return function(){function c(){this.graphics={};this.graphicsDrapedIds={};this.graphicsBySymbol={};this.graphicsKeys=[];this.symbols={};this.graphicsWithoutSymbol={};this.computedExtent=null;this.symbolCreationContext=new O.Graphics3DSymbolCreationContext;this.hasDraped=!1;this.updatingGraphicIds={};this.graphicTransformFunc=this.onComputedExtentChange=this.stage=
this.labelStageLayer=this.stageLayer=this.tilingSchemeHandle=this.lastFastUpdate=null;this.eventHandles=[];this.labeling=this.spatialIndex=this.scaleVisibility=this.elevation=this.layer=this.layerView=this.viewSR=null;this.whenGraphics3DGraphicRequests={}}c.prototype.initialize=function(a,b,d,k,e,f,h,g,l){var m=this;this.layerView=a;this.layer=b;this.viewSR=a.view.spatialReference;this.elevation=d;this.scaleVisibility=k;this.spatialIndex=e;this.labeling=f;this.onComputedExtentChange=h;this.graphicTransformFunc=
g;this.initializeStage(this.layerView.view,this.layer.id);this.symbolCreationContext.sharedResources=this.layerView.view.sharedSymbolResources;this.symbolCreationContext.renderer=this.layer.renderer;this.symbolCreationContext.stage=this.stage;this.symbolCreationContext.streamDataSupplier=this.layerView.view.sharedSymbolResources.streamDataSupplier;this.symbolCreationContext.renderSpatialReference=this.layerView.view.renderSpatialReference;this.symbolCreationContext.renderCoordsHelper=this.layerView.view.renderCoordsHelper;
this.symbolCreationContext.layer=this.layer;this.symbolCreationContext.layerView=this.layerView;this.symbolCreationContext.layerOrder=0;this.symbolCreationContext.localOriginFactory=c.createLocalOriginFactory();this.symbolCreationContext.elevationProvider=l;this.tilingSchemeHandle=r.when(l,"tilingScheme",function(a){a.spatialReference.equals(m.symbolCreationContext.overlaySR)||(m.symbolCreationContext.overlaySR=l.spatialReference,m.recreateAllGraphics())});this.eventHandles.push(this.layerView.watch("suspended",
function(){return m.suspendedChange()}));this.eventHandles.push(r.on(a,"loadedGraphics","change",function(a){return m.graphicsCollectionChanged(a)},function(){m.clearSymbolsAndGraphics();m.graphicsCollectionChanged({added:m.layerView.loadedGraphics.toArray(),removed:[]})}));this.validateRenderer(this.layer.renderer)};c.prototype.destroy=function(){var a=this;this.clear();if(this.stage){var b=[this.stageLayer.getId()];this.labelStageLayer&&b.push(this.labelStageLayer.getId());this.stage.removeFromViewContent(b);
b.forEach(function(b){return a.stage.remove(s.ModelContentType.LAYER,b)});this.stage=this.labelStageLayer=this.stageLayer=null}this.tilingSchemeHandle&&(this.tilingSchemeHandle.remove(),this.tilingSchemeHandle=null);this.eventHandles.forEach(function(a){return a.remove()});this.layerView=this.labeling=this.scaleVisibility=this.viewSR=this.onComputedExtentChange=this.eventHandles=null;for(var d in this.whenGraphics3DGraphicRequests)this.whenGraphics3DGraphicRequests[d].reject(new v("graphic:layer-destroyed",
"Layer has been destroyed"));this.whenGraphics3DGraphicRequests=null};c.prototype.clear=function(){var a=!1,b;for(b in this.graphics){var d=this.graphics[b];d&&(a=a||d.isDraped(),d.destroy())}this.graphics={};this.graphicsKeys=null;for(var k in this.symbols)(b=this.symbols[k])&&b.destroy();this.symbols={};this.graphicsBySymbol={};this.graphicsWithoutSymbol={};this.hasDraped=!1;a&&this.layerView._notifyDrapedDataChange()};c.prototype.initializeStage=function(a,b){this.stage=a._stage;this.stageLayer=
new x(b,{state:this.layerView.suspended?"HIDDEN":"VISIBLE"},b);this.stage.add(s.ModelContentType.LAYER,this.stageLayer);var d=[this.stageLayer.getId()];this.labeling&&(this.labelStageLayer=new x(b,{state:this.layerView.suspended?"HIDDEN":"IGNORED"},b+"_labels"),this.stage.add(s.ModelContentType.LAYER,this.labelStageLayer),d.push(this.labelStageLayer.getId()));this.stage.addToViewContent(d)};c.prototype.setDrawingOrder=function(a){this.symbolCreationContext.layerOrder=a;var b={},d={},k;for(k in this.graphics){var e=
this.graphics[k];e&&e.setDrawOrder(a,b,d)}for(var f in d)(d=this.symbols[f])&&d.setDrawOrder(a,b);w.objectEmpty(b)||(this.stage.getTextureGraphicsRenderer().updateRenderOrder(b),this.layerView._notifyDrapedDataChange())};c.prototype.suspendedChange=function(){!0===this.layerView.suspended?(this.stageLayer.setState("HIDDEN"),this.labelStageLayer&&this.labelStageLayer.setState("HIDDEN"),this.hideAllGraphics()):!1===this.layerView.suspended&&(this.stageLayer.setState("VISIBLE"),this.labelStageLayer&&
this.labelStageLayer.setState("IGNORED"),this.updateAllGraphicsVisibility())};c.prototype.getGraphics3DGraphics=function(){return this.graphics};c.prototype.getGraphics3DGraphicById=function(a){return this.graphics[a]};c.prototype.getGraphics3DGraphicsKeys=function(){null===this.graphicsKeys&&(this.graphicsKeys=Object.keys(this.graphics));return this.graphicsKeys};c.prototype.numNodesUpdating=function(){return Object.keys(this.updatingGraphicIds).length};c.prototype.needsIdleUpdate=function(){return this.lastFastUpdate&&
500<performance.now()-this.lastFastUpdate};c.prototype.idleUpdate=function(a){a.done()||(this.lastFastUpdate&&(this.labeling&&this.labeling.updateLabelingInfo(),this.lastFastUpdate=null),this.layerView._evaluateUpdatingState())};c.prototype.whenGraphics3DGraphic=function(a){var b=this.graphics[a.uid];if(b)return D.resolve(b);b=this.whenGraphics3DGraphicRequests[a.uid];b||(b=new P,this.whenGraphics3DGraphicRequests[a.uid]=b);return b.promise};c.prototype.boundsForGraphics3DGraphic=function(a,b){void 0===
b&&(b=A.create());var d=this.layerView.view.spatialReference,k=this.layerView.view.renderSpatialReference,e=this.layerView.view.basemapTerrain.spatialReference,f=a.getProjectedBoundingBox(function(a,b,e){return p.bufferToBuffer(a,k,b,a,d,b,e)},function(a,b,k){return p.bufferToBuffer(a,e,b,a,d,b,k)},b);if(!f)return null;var c=a.isDraped(),g=this.symbolCreationContext.elevationProvider;c&&g&&(A.center(f,t),q.x=t[0],q.y=t[1],q.z=void 0,q.spatialReference=d,c=g.getElevation(q)||0,f[2]=Math.min(f[2],c),
f[5]=Math.max(f[5],c));return f};c.prototype.whenGraphicBounds=function(a){var b=this;return r.whenOnce(this.layerView,"loadedGraphics").then(function(){if(b.layerView.loadedGraphics.some(function(b){return b===a}))return b.whenGraphics3DGraphic(a);throw new v("internal:graphic-not-part-of-view","Graphic is not part of this view");}).then(function(a){return b.boundsForGraphics3DGraphic(a)})};c.prototype.graphicsCollectionChanged=function(a){var b=this.graphicTransformFunc?this.graphicTransformFunc(a.added):
a.added;this.add(b);this.remove(a.removed)};c.prototype.graphicUpdateHandler=function(a){var b=this.graphics[a.graphic.uid];if(b)switch(a.property){case "visible":b.setVisibilityFlag("VISIBILITY_GRAPHIC",a.newValue)&&(b.isDraped()&&this.layerView._notifyDrapedDataChange(),this.labeling&&this.layerView.view.labelManager.setDirty())}};c.prototype.beginGraphicUpdate=function(a){this.updatingGraphicIds[a.uid]=!0;this.layerView.get("symbols-updating")||this.layerView.set("symbols-updating",!0);this.layerView._evaluateUpdatingState()};
c.prototype.endGraphicUpdate=function(a){a&&delete this.updatingGraphicIds[a.uid];this.layerView.get("symbols-updating")&&w.objectEmpty(this.updatingGraphicIds)&&(this.layerView.view.flushDisplayModifications(),this.layerView.set("symbols-updating",!1));this.layerView._evaluateUpdatingState()};c.prototype.expandComputedExtent=function(a){var b,d,k,e,f,h;if("point"===a.type)b=d=a.x,k=e=a.y,a.z&&(f=h=a.z);else if("polygon"===a.type||"polyline"===a.type||"multipoint"===a.type){h=a.extent;if(!h)return;
b=h.xmin;d=h.xmax;k=h.ymin;e=h.ymax;f=h.zmin;h=h.zmax}var g=this.viewSR,l=c.tmpVec;!a.spatialReference.equals(g)&&p.xyzToVector(b,k,0,a.spatialReference,l,g)&&(b=l[0],k=l[1],p.xyzToVector(d,e,0,a.spatialReference,l,g),d=l[0],e=l[1]);n.isFinite(b)&&(n.isFinite(d)&&n.isFinite(k)&&n.isFinite(e))&&((g=this.computedExtent)?(g.xmin=Math.min(b,g.xmin),g.xmax=Math.max(d,g.xmax),g.ymin=Math.min(k,g.ymin),g.ymax=Math.max(e,g.ymax)):this.computedExtent=g=new H(b,k,d,e,a.spatialReference),n.isFinite(f)&&!n.isFinite(h)&&
(g.zmin=null!=g.zmin?Math.min(f,g.zmin):f,g.zmax=null!=g.zmax?Math.max(h,g.zmax):h),this.onComputedExtentChange&&this.onComputedExtentChange())};c.prototype.updateHasDraped=function(){this.hasDraped=!1;for(var a in this.graphicsDrapedIds)if(this.graphicsDrapedIds.hasOwnProperty(a)){this.hasDraped=!0;break}};c.prototype.elevationInfoChange=function(){this.labeling&&this.labeling.elevationInfoChange();for(var a in this.graphicsBySymbol){var b=this.symbols[a],d=this.graphicsBySymbol[a];if(!b||!b.layerPropertyChanged("elevationInfo",
d))this.recreateSymbol(a);else for(var k in d)for(var e=d[k],b=e.graphic,e=e._labelGraphics,c=0;c<e.length;c++){var h=e[c];h.graphics3DSymbolLayer.updateGraphicElevationInfo(b,h)}}};c.prototype.clearSymbolsAndGraphics=function(){this.clear();this.elevation&&this.elevation.clear();this.labeling&&this.labeling.clear()};c.prototype.recreateAllGraphics=function(){this.clearSymbolsAndGraphics();this.computedExtent=null;this.onComputedExtentChange&&this.onComputedExtentChange();this.layerView.loadedGraphics&&
this.layerView.view.basemapTerrain.tilingScheme&&this.add(this.layerView.loadedGraphics.toArray())};c.prototype.recreateSymbol=function(a){var b=this.graphicsBySymbol[a],d=[],k=!1,e;for(e in b){var c=b[e];c.isDraped()&&(delete this.graphicsDrapedIds[e],k=!0);d.push(c.graphic);c.destroy();this.graphics[e]=null}this.graphicsBySymbol[a]={};(b=this.symbols[a])&&b.destroy();this.symbols[a]=void 0;this.updateHasDraped();k&&this.layerView._notifyDrapedDataChange();this.add(d)};c.prototype.add=function(a){if(this.layerView.view.basemapTerrain&&
this.layerView.view.basemapTerrain.tilingScheme){for(var b=a.length,d=Array(b),c=Array(b),e=Array(b),f=0;f<b;f++){var h=a[f],g=h.geometry;g&&(this.expandComputedExtent(g),(g=this.layerView.getRenderingInfo?this.layerView.getRenderingInfo(h):{symbol:h.symbol})&&g.symbol?(c[f]=g.symbol,e[f]=g,(g=this.getOrCreateGraphics3DSymbol(c[f],g.renderer))?(d[f]=g,this.beginGraphicUpdate(h)):this.graphicsWithoutSymbol[h.uid]=!0):this.graphicsWithoutSymbol[h.uid]=!0)}for(f=0;f<b;f++)this.waitForSymbol(d[f],c[f],
a[f],e[f])}};c.prototype.waitForSymbol=function(a,b,d,c){var e=this;a&&a.then(function(){e.graphicsBySymbol[b.id]||(e.graphicsBySymbol[b.id]={});e.createGraphics3DGraphic(a,d,c);e.endGraphicUpdate(d);e.labeling&&e.layerView.view.labelManager.setDirty()},function(){e.endGraphicUpdate(d)})};c.prototype.remove=function(a){for(var b=!1,d=a.length,c=0;c<d;c++){var e=a[c].uid,f=this.graphics[e];if(f){f.isDraped()&&(delete this.graphicsDrapedIds[e],b=!0);var h=f.graphics3DSymbol.symbol.id;f.destroy();delete this.graphics[e];
delete this.graphicsBySymbol[h][e];delete this.graphicsWithoutSymbol[e];this.graphicsKeys=null}}this.updateHasDraped();b&&this.layerView._notifyDrapedDataChange();this.labeling&&this.layerView.view.labelManager.setDirty()};c.prototype.createGraphics3DSymbol=function(a,b){var d=y.to3D(a,!0,!1);if(d.symbol){var c=void 0;if(b&&b.backgroundFillSymbol){var e=y.to3D(b.backgroundFillSymbol,!1,!0);e.symbol&&(c=e.symbol.symbolLayers)}return new L(d.symbol,this.symbolCreationContext,c)}return null};c.prototype.getOrCreateGraphics3DSymbol=
function(a,b){var d=this,c=this.symbols[a.id];void 0===c&&(c=a instanceof J?new M(a,function(a){return d.createGraphics3DSymbol(a,b)}):this.createGraphics3DSymbol(a,b),this.symbols[a.id]=c);return c};c.prototype.createGraphics3DGraphic=function(a,b,d){if(!this.graphics[b.uid]&&(d=a.createGraphics3DGraphic(b,d),this.labeling&&this.labeling.layerLabelsEnabled()&&this.labeling.createLabelsForGraphic(b,d),this.graphics[b.uid]=d,this.graphicsKeys=null,this.graphicsBySymbol[a.symbol.id][b.uid]=d,d.initialize(this.stageLayer,
this.stage),d.isDraped()&&(this.hasDraped=this.graphicsDrapedIds[b.uid]=!0,this.layerView._notifyDrapedDataChange()),d.centroid=null,"point"!==b.geometry.type&&d instanceof K&&(d.centroid=N.computeCentroid(b.geometry,this.viewSR)),a=this.scaleVisibility&&this.scaleVisibility.scaleRangeActive(),this.spatialIndex&&this.spatialIndex.shouldAddToSpatialIndex(b,d,a)&&this.spatialIndex.addGraphicToSpatialIndex(b,d),a&&this.scaleVisibility.updateGraphicScaleVisibility(b,d),d.setVisibilityFlag("VISIBILITY_GRAPHIC",
b.visible&&!this.layerView.suspended),a=this.whenGraphics3DGraphicRequests[b.uid]))a.resolve(d),delete this.whenGraphics3DGraphicRequests[b.uid]};c.prototype.rendererChange=function(a){var b=this.symbolCreationContext.renderer;this.validateRenderer(a);this.symbolCreationContext.renderer=a;(b=F.diff(b,a))&&("complete"===b.type?this.recreateAllGraphics():"partial"===b.type&&(this.applyRendererDiff(b,a)?this.volatileGraphicsUpdated():this.recreateAllGraphics()))};c.prototype.diffHasSymbolChange=function(a){for(var b in a.diff)switch(b){case "visualVariables":break;
default:return!0}return!1};c.prototype.applyRendererDiff=function(a,b){var d=!1;if(this.diffHasSymbolChange(a))return!1;for(var c in this.graphicsBySymbol){var e=this.symbols[c];if(e){var f=this.graphicsBySymbol[c];if(!e.applyRendererDiff(a,b,f))return!1;if(!d)for(var h in f)if(f[h].isDraped()){this.layerView._notifyDrapedDataChange();d=!0;break}}}return!0};c.prototype.opacityChange=function(){var a=!1,b;for(b in this.graphicsBySymbol){var d=this.symbols[b];if(d){var c=this.graphicsBySymbol[b];d.layerPropertyChanged("opacity");
if(!a)for(var e in c)if(c[e].isDraped()){this.layerView._notifyDrapedDataChange();a=!0;break}}}};c.prototype.setClippingExtent=function(a,b){var d=this.symbolCreationContext.clippingExtent,c=[];p.extentToBoundingRect(a,c,b)?this.symbolCreationContext.clippingExtent=[c[0],c[1],-Infinity,c[2],c[3],Infinity]:this.symbolCreationContext.clippingExtent=null;return!B.equals(this.symbolCreationContext.clippingExtent,d)};c.prototype.updateAllGraphicsVisibility=function(){var a=this;if(this.layerView.loadedGraphics){var b=
!1;this.layerView.loadedGraphics.forEach(function(c){var k=a.getGraphics3DGraphicById(c.uid);if(k){var e=k.setVisibilityFlag("VISIBILITY_GRAPHIC",c.visible);a.scaleVisibility&&(c=a.scaleVisibility.updateGraphicScaleVisibility(c,k),e=e||c);e&&k.isDraped()&&(b=!0)}});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};c.prototype.hideAllGraphics=function(){var a=this;if(this.layerView.loadedGraphics){var b=!1;this.layerView.loadedGraphics.forEach(function(c){(c=
a.getGraphics3DGraphicById(c.uid))&&c.setVisibilityFlag("VISIBILITY_GRAPHIC",!1)&&c.isDraped()&&(b=!0)});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};c.prototype.validateRenderer=function(a){(a=E.validateTo3D(a))&&Q.warn("Renderer for layer '"+(this.layer.title?this.layer.title+", ":"")+", id:"+this.layer.id+"' is not supported in a SceneView",a.message)};c.prototype.volatileGraphicsUpdated=function(){this.labeling&&(this.lastFastUpdate=performance.now());
this.stageLayer.invalidateSpatialQueryAccelerator();this.layerView._evaluateUpdatingState()};c.createLocalOriginFactory=function(){return new I(5E6,16)};c.tmpVec=z.vec3d.create();return c}()});