// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../support/earthUtils ../../support/projectionUtils ../../support/intersectionUtils ../../lib/glMatrix".split(" "),function(k,w,l,q,m,n){var d=n.vec3d,p=n.vec4d,r=-0.3*l.earthRadius;k=0.5*Math.PI;var s=180*(k/Math.PI),t=k*l.earthRadius,u=0.9*l.earthRadius,v=function(){function b(){this.extent=Array(4);this.planes=Array(4);this.maxSpan=0;this.center={origin:d.create(),direction:d.create()};for(var a=0;4>a;a++)this.extent[a]={origin:d.create(),originLength:0,direction:d.create(),
cap:{next:null,direction:d.create()}},this.planes[a]=p.create();this.planes[4]=p.create()}b.prototype.update=function(a,b,c,g,e,h){var f=this.extent;d.set3(a[0],a[1],h,f[0].origin);d.set3(a[2],a[1],h,f[1].origin);d.set3(a[2],a[3],h,f[2].origin);d.set3(a[0],a[3],h,f[3].origin);if(!e)for(e=0;4>e;e++)q.vectorToVector(f[e].origin,g,f[e].origin,c);d.add(f[0].origin,f[2].origin,this.center.origin);d.scale(this.center.origin,0.5);b(this.center.origin,this.center.direction);for(e=0;4>e;e++)c=f[e],b(c.origin,
c.direction),c.originLength=d.length(c.origin),g=f[3===e?0:e+1],c.cap.next=g.origin,d.direction(g.origin,c.origin,c.cap.direction),this._computePlane(c.cap.direction,c.direction,c.origin,this.planes[e]);this._computePlane(f[1].cap.direction,f[0].cap.direction,f[0].origin,this.planes[4]);this.maxSpan=Math.max(Math.abs(a[0]-a[2]),Math.abs(a[1]-a[3]))};b.prototype.isVisibleInFrustumGlobal=function(a){if(0>d.dot(this.center.direction,a.direction))return!0;for(var b=0;4>b;b++)if(0>d.dot(this.extent[b].direction,
a.direction))return!0;return!1};b.prototype.isVisibleInFrustum=function(a,b,c){if("global"===a.viewingMode){if(this.maxSpan>(a.spatialReference.isWGS84?s:t))return!0;if(b.altitude()>=u)return this.isVisibleInFrustumGlobal(b)}for(a=0;a<this.extent.length;a++)if(c=this.extent[a],m.frustumRay(b.planes,c.origin,null,c.direction)||m.frustumLineSegment(b.planes,c.origin,c.cap.next,c.cap.direction))return!0;for(a=0;a<b.lines.length;a++)if(c=b.lines[a],m.frustumLineSegment(this.planes,c.origin,c.endpoint,
c.direction))return!0;return!1};b.prototype._computePlane=function(a,b,c,g){d.cross(a,b,g);g[3]=-d.dot(g,c)};return b}();return function(){function b(){this.frustumVisibilityDirty=this.frustumVisibility=!0;this.extent=null;this.extentEngine=new v;this.extentEngineDirty=!0;this.renderSREqualsViewSR=null;this._isVisibleBelowSurface=!1;this.layerView=null}b.prototype.initialize=function(a){this.layerView=a;this.renderSREqualsViewSR=a.view.renderSpatialReference.equals(a.view.spatialReference)};b.prototype.destroy=
function(){this.extentEngine=this.extent=this.layerView=null};b.prototype.needsIdleUpdate=function(){return this.frustumVisibilityDirty};b.prototype.canResume=function(){return this.frustumVisibility};b.prototype.setExtent=function(a){this.extent=a;this.frustumVisibilityDirty=this.extentEngineDirty=!0};b.prototype.viewChange=function(){this.frustumVisibilityDirty=!0};b.prototype.elevationBoundsChange=function(){this.extentEngineDirty=this.frustumVisibilityDirty=!0};Object.defineProperty(b.prototype,
"isVisibleBelowSurface",{set:function(a){this._isVisibleBelowSurface=a;this.extentEngineDirty=this.frustumVisibilityDirty=!0},enumerable:!0,configurable:!0});b.prototype.idleUpdate=function(a){!a.done()&&this.frustumVisibilityDirty&&(this.updateSuspendFrustumVisible(),this.frustumVisibilityDirty=!1)};b.prototype.updateExtentEngine=function(){if(this.extentEngineDirty){this.extentEngineDirty=!1;var a=this.layerView.view,b=a.renderCoordsHelper.worldUpAtPosition,c;if(this._isVisibleBelowSurface)c=r;
else{var d=a.basemapTerrain.getElevationBounds();c=d[0];d=Math.max(1,(d[1]-c)*(1.2-1));c-=d}this.extentEngine.update(this.extent,b,a.renderSpatialReference,a.spatialReference,this.renderSREqualsViewSR,c)}};b.prototype.updateSuspendFrustumVisible=function(){if(this.extent){this.updateExtentEngine();var a=this.layerView.view.getFrustum(),a=this.extentEngine.isVisibleInFrustum(this.layerView.view,a,this._isVisibleBelowSurface);a!==this.frustumVisibility&&(this.frustumVisibility=a,this.layerView._notifySuspendedChange())}else this.frustumVisibility=
!0};return b}()});