// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/promise/all ../../webgl-engine/lib/TextTextureAtlas ../../webgl-engine/lib/MaterialCollection ../../webgl-engine/materials/HUDMaterial ./Graphics3DWebStyleSymbol ../../../../layers/support/LabelClass ../../../../core/HandleRegistry ../../../../core/watchUtils ../../lib/glMatrix".split(" "),function(n,k,t,u,v,w,p,q,x,y,l){var r=l.vec3d;n=function(){function a(){this.hudMaterialCollection=this.textTextureAtlas=null;this.labelVisibilityDirty=!1;this.labelClasses=[];this.eventHandles=
new x;this.graphicsCore=this.layer=this.layerView=null}a.prototype.initialize=function(f,b,e,c){var d=this;this.layerView=f;this.layer=b;this.graphicsCore=c;this.labelGraphicsCreated=e;this.layerView.view.labelManager.addSceneServiceLayerView(this);this.eventHandles.add(y.whenNot(this.layerView,"suspended",function(){return d.resume()}))};a.prototype.destroy=function(){this.layerView.view.labelManager.removeSceneServiceLayerView(this);this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=
null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null);this.labelClasses=null;this.eventHandles.destroy();this.graphicsCore=this.layer=this.layerView=this.eventHandles=null};a.prototype.clear=function(){this.layerView.view.labelManager.setDirty();this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null)};a.prototype.updateLabelingInfo=
function(){var f=this;this.removeLabels();return this.layer.then(function(){var b=f.layer.labelingInfo&&f.layer.labelingInfo.filter(function(c){return!!c.symbol});if(b&&0<b.length){var e=Array(b.length),b=b.map(function(c,d){var b=f.graphicsCore.getOrCreateGraphics3DSymbol(c.symbol),a;a=b instanceof p?b.graphics3DSymbol:b;e[d]={labelClass:c,graphics3DSymbolLayer:a};return b});return t(b).then(function(){return e})}return null}).then(function(b){f.labelClasses=b;f.labelVisibilityChanged()})};a.prototype.createLabelsForGraphic=
function(f,b){var e=!1;if(this.labelClasses&&0!==this.labelClasses.length&&b._graphics[0]){for(var c=0;c<this.labelClasses.length;c++){var d=this.labelClasses[c];if(q.evaluateWhere(d.labelClass.where,f.attributes)){var a=d.labelClass.getLabelExpression();if(a&&(a=q.buildLabelText(a,f.attributes,this.layer.fields))){var c=d.graphics3DSymbolLayer.childGraphics3DSymbols[0],g=this.evalLabelPlacementParams(f,b);null==this.textTextureAtlas&&(this.textTextureAtlas=new u(this.layer.id,this.layerView.view._stage),
this.hudMaterialCollection=new v(this.layerView.view._stage));if(a=c.createGraphics3DGraphic(f,{text:a,centerOffset:g.centerOffset,translation:g.translation,screenOffset:g.screenOffset,anchor:g.anchor},this.hudMaterialCollection,this.textTextureAtlas))a._labelClass=d.labelClass,b.addLabelGraphic(a,this.graphicsCore.labelStageLayer,this.graphicsCore.stage),a.setVisibilityFlag("VISIBILITY_LABEL_SHOW",this.layerLabelsEnabled()),this.layerView.view.labelManager.setInitialLabelGraphicState(a),e=!0;break}}}e&&
this.labelGraphicsCreated&&this.labelGraphicsCreated(f,b)}};a.prototype.evalLabelPlacementParams=function(a,b){var e=g[this.layer.labelingInfo[0].labelPlacement]||g["default"];if("polygon"===a.geometry.type||"polyline"===a.geometry.type||"extent"===a.geometry.type)return{anchor:"center"};if("point"!==a.geometry.type)return{anchor:e.anchor};var c=b.graphics3DSymbol,d=(c instanceof p?c.graphics3DSymbol:c).symbol.symbolLayers.getItemAt(0),c={screenOffset:[0,0],centerOffset:[0,0,0,-1],translation:r.create(b.getCenterObjectSpace()),
anchor:e.anchor},h=b._graphics[0];"Icon"===d.type?(d=h.getScreenSize(),b.isDraped()?c.anchor="center":(h=h.stageObject.getGeometryRecords()[0].materials[0],h instanceof w?(h=h.getParams(),c.screenOffset=[d[0]/2*(e.normalizedOffset[0]-2*(h.anchorPos[0]-0.5)),d[1]/2*(e.normalizedOffset[1]-2*(h.anchorPos[1]-0.5))]):c.screenOffset=[d[0]/2*e.normalizedOffset[0],d[1]/2*e.normalizedOffset[1]])):"Object"===d.type&&(d=h.getBoundingBoxObjectSpace(),d=[d[3]-d[0],d[4]-d[1],d[5]-d[2]],h=Math.max(d[0],d[1]),c.centerOffset[0]=
1.1*h/2*e.normalizedOffset[0],c.translation[2]+=1.1*d[2]/2*e.normalizedOffset[1],d=r.length(d),c.centerOffset[2]=1.1*d/2*e.normalizedOffset[2]);return c};a.prototype.layerLabelsEnabled=function(){return this.layer.labelsVisible};a.prototype.getGraphics3DGraphics=function(){return this.graphicsCore.getGraphics3DGraphics()};a.prototype.getGraphics3DGraphicsKeys=function(){return this.graphicsCore.getGraphics3DGraphicsKeys()};a.prototype.labelVisibilityChanged=function(){var a=this;if(this.layerView.suspended)this.labelVisibilityDirty=
!0;else if(this.layerView.loadedGraphics){var b=this.layerLabelsEnabled();this.layerView.loadedGraphics.forEach(function(e){var c=a.graphicsCore.getGraphics3DGraphicById(e.uid);if(c){b&&0===c._labelGraphics.length&&a.createLabelsForGraphic(e,c);for(e=0;e<c._labelGraphics.length;e++)c._labelGraphics[e].setVisibilityFlag("VISIBILITY_LABEL_SHOW",b)}});this.layerView.view.labelManager.setDirty();this.labelVisibilityDirty=!1}};a.prototype.elevationInfoChange=function(){this.labelClasses&&this.labelClasses.forEach(function(a){a.graphics3DSymbolLayer.layerPropertyChanged("elevationInfo",
{})})};a.prototype.resume=function(){this.labelVisibilityDirty&&this.labelVisibilityChanged()};a.prototype.removeLabels=function(){var a=this;this.layerView.loadedGraphics&&(this.layerView.loadedGraphics.forEach(function(b){if(b=a.graphicsCore.getGraphics3DGraphicById(b.uid))b._labelGraphics&&b._labelGraphics.forEach(function(a){return a._labelClass=null}),b.clearLabelGraphics()}),this.labelClasses=null,this.layerView.view.labelManager.setDirty())};return a}();var g={"above-center":{normalizedOffset:[0,
1,0],anchor:"bottom"},"above-left":{normalizedOffset:[-1,1,0],anchor:"bottom-right"},"above-right":{normalizedOffset:[1,1,0],anchor:"bottom-left"},"below-center":{normalizedOffset:[0,-1,2],anchor:"top"},"below-left":{normalizedOffset:[-1,-1,0],anchor:"top-right"},"below-right":{normalizedOffset:[1,-1,0],anchor:"top-left"},"center-center":{normalizedOffset:[0,0,1],anchor:"center"},"center-left":{normalizedOffset:[-1,0,0],anchor:"right"},"center-right":{normalizedOffset:[1,0,0],anchor:"left"}};k={"above-center":["default",
"esriServerPointLabelPlacementAboveCenter"],"above-left":["esriServerPointLabelPlacementAboveLeft"],"above-right":["esriServerPointLabelPlacementAboveRight"],"below-center":["esriServerPointLabelPlacementBelowCenter"],"below-left":["esriServerPointLabelPlacementBelowLeft"],"below-right":["esriServerPointLabelPlacementBelowRight"],"center-center":["esriServerPointLabelPlacementCenterCenter"],"center-left":["esriServerPointLabelPlacementCenterLeft"],"center-right":["esriServerPointLabelPlacementCenterRight"]};
var s,m;for(m in k)l=k[m],s=g[m],l.forEach(function(a){g[a]=s});Object.freeze&&(Object.freeze(g),Object.keys(g).forEach(function(a){Object.freeze(g[a]);Object.freeze(g[a].normalizedOffset)}));return n});