// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper dojo/_base/lang dojox/gfx/_base dojox/gfx/matrix ./Shape".split(" "),function(k,l,n,m,h,p,q){k=function(g){function f(d){g.call(this);this.segments=[];this.tbbox=null;this.absolute=!0;this.last={};this.segmented=!1;this._validSegments={m:2,l:2,h:1,v:1,c:6,s:4,q:4,t:2,a:7,z:0};this._2PI=2*Math.PI;this.rawNode=d;this.shape=m.clone(h.defaultPath)}n(f,g);f.prototype.setAbsoluteMode=function(d){this._confirmSegmented();this.absolute="string"===
typeof d?"absolute"===d:d;return this};f.prototype.getAbsoluteMode=function(){this._confirmSegmented();return this.absolute};f.prototype.getBoundingBox=function(){this._confirmSegmented();return this.bbox&&"l"in this.bbox?{x:this.bbox.l,y:this.bbox.t,width:this.bbox.r-this.bbox.l,height:this.bbox.b-this.bbox.t}:null};f.prototype._getRealBBox=function(){this._confirmSegmented();if(this.tbbox)return this.tbbox;var d=this.bbox,c=this._getRealMatrix();this.bbox=null;for(var b=0,e=this.segments.length;b<
e;++b)this._updateWithSegment(this.segments[b],c);c=this.bbox;this.bbox=d;return this.tbbox=c?[{x:c.l,y:c.t},{x:c.r,y:c.t},{x:c.r,y:c.b},{x:c.l,y:c.b}]:null};f.prototype.getLastPosition=function(){this._confirmSegmented();return"x"in this.last?this.last:null};f.prototype._applyTransform=function(){this.tbbox=null;g.prototype._applyTransform.call(this);return this};f.prototype._updateBBox=function(d,c,b){b&&(c=p.multiplyPoint(b,d,c),d=c.x,c=c.y);this.bbox&&"l"in this.bbox?(this.bbox.l>d&&(this.bbox.l=
d),this.bbox.r<d&&(this.bbox.r=d),this.bbox.t>c&&(this.bbox.t=c),this.bbox.b<c&&(this.bbox.b=c)):this.bbox={l:d,b:c,r:d,t:c}};f.prototype._updateWithSegment=function(d,c){var b=d.args,e=b.length,a;switch(d.action){case "M":case "L":case "C":case "S":case "Q":case "T":for(a=0;a<e;a+=2)this._updateBBox(b[a],b[a+1],c);this.last.x=b[e-2];this.last.y=b[e-1];this.absolute=!0;break;case "H":for(a=0;a<e;++a)this._updateBBox(b[a],this.last.y,c);this.last.x=b[e-1];this.absolute=!0;break;case "V":for(a=0;a<
e;++a)this._updateBBox(this.last.x,b[a],c);this.last.y=b[e-1];this.absolute=!0;break;case "m":a=0;"x"in this.last||(this._updateBBox(this.last.x=b[0],this.last.y=b[1],c),a=2);for(;a<e;a+=2)this._updateBBox(this.last.x+=b[a],this.last.y+=b[a+1],c);this.absolute=!1;break;case "l":case "t":for(a=0;a<e;a+=2)this._updateBBox(this.last.x+=b[a],this.last.y+=b[a+1],c);this.absolute=!1;break;case "h":for(a=0;a<e;++a)this._updateBBox(this.last.x+=b[a],this.last.y,c);this.absolute=!1;break;case "v":for(a=0;a<
e;++a)this._updateBBox(this.last.x,this.last.y+=b[a],c);this.absolute=!1;break;case "c":for(a=0;a<e;a+=6)this._updateBBox(this.last.x+b[a],this.last.y+b[a+1],c),this._updateBBox(this.last.x+b[a+2],this.last.y+b[a+3],c),this._updateBBox(this.last.x+=b[a+4],this.last.y+=b[a+5],c);this.absolute=!1;break;case "s":case "q":for(a=0;a<e;a+=4)this._updateBBox(this.last.x+b[a],this.last.y+b[a+1],c),this._updateBBox(this.last.x+=b[a+2],this.last.y+=b[a+3],c);this.absolute=!1;break;case "A":for(a=0;a<e;a+=7)this._updateBBox(b[a+
5],b[a+6],c);this.last.x=b[e-2];this.last.y=b[e-1];this.absolute=!0;break;case "a":for(a=0;a<e;a+=7)this._updateBBox(this.last.x+=b[a+5],this.last.y+=b[a+6],c);this.absolute=!1}var f=[d.action];for(a=0;a<e;++a)f.push(h.formatNumber(b[a],!0));if("string"===typeof this.shape.path)this.shape.path+=f.join("");else{a=0;for(e=f.length;a<e;++a)this.shape.path.push(f[a])}"string"===typeof this.shape.path&&this.rawNode.setAttribute("d",this.shape.path)};f.prototype._pushSegment=function(d,c){this.tbbox=null;
var b=this._validSegments[d.toLowerCase()];"number"===typeof b&&(b?c.length>=b&&(b={action:d,args:c.slice(0,c.length-c.length%b)},this.segments.push(b),this._updateWithSegment(b)):(b={action:d,args:[]},this.segments.push(b),this._updateWithSegment(b)))};f.prototype._collectArgs=function(d,c){for(var b=0;b<c.length;++b){var e=c[b];"boolean"===typeof e?d.push(e?1:0):"number"===typeof e?d.push(e):e instanceof Array?this._collectArgs(d,e):"x"in e&&"y"in e&&d.push(e.x,e.y)}};f.prototype._confirmSegmented=
function(){if(!this.segmented){var d=this.shape.path;this.shape.path=[];this._setPath(d);this.shape.path=this.shape.path.join("");this.segmented=!0}};f.prototype._setPath=function(d){d=m.isArray(d)?d:d.match(h.pathSvgRegExp);this.segments=[];this.absolute=!0;this.bbox={};this.last={};if(d){for(var c="",b=[],e=d.length,a=0;a<e;++a){var f=d[a],g=parseFloat(f);isNaN(g)?(c&&this._pushSegment(c,b),b=[],c=f):b.push(g)}this._pushSegment(c,b)}};f.prototype.setShape=function(d){g.prototype.setShape.call(this,
"string"===typeof d?{path:d}:d);this.segmented=!1;this.segments=[];this.shape.path?this.rawNode.setAttribute("d",this.shape.path):this.rawNode.removeAttribute("d");return this};f.nodeType="path";return f}(q.default);Object.defineProperty(l,"__esModule",{value:!0});l.default=k});