// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./parts/Model ./parts/View ./lib/Selector ./lib/Camera ./lib/gl-matrix ./lib/Util ./lib/ModelContentType".split(" "),function(t,u,r,w,s,x,p,g,v){t=p.vec2d;u=p.vec2;var k=p.vec3d;p=function(){function b(a,d){this._intersectTolerance=s.DEFAULT_TOLERANCE;this._viewContent=[];this._externalIntersectionHandlers=[];this.onSelectionChange=function(){};this.container=a;this.model=new r;this.view=new w(a,this,this.model.getDirtySet(),d);this.view.setLights(this.model.getAmbientLight(),
this.model.getDirectionalLight())}b.prototype.setNeedsRender=function(){this.view.setNeedsRender()};b.prototype.dispose=function(){this.view.dispose();this.model=this.view=null};b.prototype.setSelectionObject=function(a,d,c){this.model.setSelection(a,c);this.view.setSelectionObject(void 0!==a?a.getId():void 0,c);if(!d)this.onSelectionChange(a,c)};b.prototype.getSelectionObject=function(){return this.model.getSelection()};b.prototype.frame=function(a,d){void 0===d&&(d=0);var c=Math.max(1E-6,a.getBSRadius());
d=Math.max(2,d+2);var b=c*d,c=this.getCamera(),e=k.create(c.viewForward),b=1.5*b/Math.tan(c.fov);k.scale(e,-b);k.set(a.getCenter(),c.center);k.add(c.center,e,c.eye);c=new x(c.eye,c.center,c.up);this.setCamera(c)};b.prototype.beginMod=function(){b.DebugSettings.fineGrainedContentValidation&&this.model.validateContent()};b.prototype.endMod=function(a){void 0===a&&(a=!1);b.DebugSettings.fineGrainedContentValidation&&!a&&this.model.validateContent()};b.prototype.add=function(a,d){this.model.add(a,d);
"function"===typeof d.addParentStage&&d.addParentStage(this)};b.prototype.remove=function(a,d){var c=this.model.remove(a,d);"function"===typeof c.removeParentStage&&c.removeParentStage(this);return c};b.prototype.notifyDirty=function(a,d,c,b){this.model.notifyDirty(a,d,c,b)};b.prototype.processDirty=function(){var a=this.model.getDirtySet(),d=a.getDirtyMaterials();if(a.hasDirtyGeometryRecords()||d){b.DebugSettings.endFrameContentValidation&&this.model.validateContent();b.DebugSettings.logDirtySet&&
console.log("Dirty set: "+this.model.getDirtySet().formatDebugInfo(!1));var c=a.getAddRemoveUpdateListFilteredByLayers(this._viewContent,!0);(0<c[0].length+c[1].length+c[2].length||d)&&this.view.modify(c[0],c[1],c[2],d);b.DebugSettings.logDirtySet&&(console.log("RGs add: "+c[0].map(function(a){return a.uniqueName})),console.log("RGs remove: "+c[1].map(function(a){return a.uniqueName})));a.getAddRemoveUpdateList(!0);a.clearDirtyMaterials();this.view.setNeedsRender()}};b.prototype.processDirtyLayer=
function(a){var d=this.model.getDirtySet(),c=d.getDirtyMaterials();a=d.getAddRemoveUpdateListFilteredByLayers([a],!0);(0<a[0].length+a[1].length+a[2].length||c)&&this.view.modify(a[0],a[1],a[2],c);d.clearDirtyMaterials()};b.prototype.get=function(a,d){return this.model.get(a,d)};b.prototype.getAll=function(a){return this.model.getAll(a)};b.prototype.addTextureListener=function(a){this.view.addTextureListener(a)};b.prototype.removeTextureListener=function(a){this.view.removeTextureListener(a)};b.prototype.getContainer=
function(){return this.container};b.prototype.getCamera=function(){return this.view.getCamera()};b.prototype.setCamera=function(a){this.view.setCamera(a)};b.prototype.getViewParams=function(a){return this.view.getViewParams(a)};b.prototype.setViewParams=function(a){this.view.setViewParams(a)};b.prototype.getLayers=function(){return this.model.getAll(v.LAYER)};b.prototype.getAmbientLight=function(){return this.model.getAmbientLight()};b.prototype.getDirectionalLight=function(){return this.model.getDirectionalLight()};
b.prototype.setAmbientLight=function(a){this.model.setAmbientLight(a);this.view.setLights(this.model.getAmbientLight(),this.model.getDirectionalLight())};b.prototype.setDirectionalLight=function(a){this.model.setDirectionalLight(a);this.view.setLights(this.model.getAmbientLight(),this.model.getDirectionalLight())};b.prototype.getCanvas=function(){return this.view.getCanvas()};b.prototype.setRenderParams=function(a){this.view.setRenderParams(a)};b.prototype.getRenderParams=function(){return this.view.getRenderParams()};
b.prototype.has=function(a){return this.view.has(a)};b.prototype.getViewContent=function(){return this._viewContent.slice(0)};b.prototype.setViewContent=function(a){var d=g.array2object(this._viewContent),c=g.array2object(a),b=g.subtractObjects(c,d),d=g.subtractObjects(d,c);this.processDirty();c=this.model.getDirtySet();b=c.getResidentRenderGeometriesFilteredByLayers(g.object2array(b));d=c.getResidentRenderGeometriesFilteredByLayers(g.object2array(d));this.view.modify(b,d,[]);this._viewContent=a.slice(0)};
b.prototype.addToViewContent=function(a){for(var d=[],c=0;c<a.length;c++)-1===this._viewContent.indexOf(a[c])&&d.push(a[c]);0<a.length&&(this.processDirty(),a=this.model.getDirtySet().getResidentRenderGeometriesFilteredByLayers(d),this.view.modify(a,[],[]),this._viewContent.push.apply(this._viewContent,d))};b.prototype.removeFromViewContent=function(a){this.processDirty();for(var d=this.model.getDirtySet(),c=this._viewContent,b=[],e=0;e<a.length;e++){var l=c.indexOf(a[e]);-1<l&&(c[l]=c[c.length-1],
c.pop(),b.push(a[e]))}a=d.getResidentRenderGeometriesFilteredByLayers(b);this.view.modify([],a,[])};b.prototype.getViewFrustumObjects=function(){return this.view.getFrustumObjects()};b.prototype.getLocalOrigin=function(a,d,c){return this.model.getOrigin(a,d,c)};b.prototype.getFrameTask=function(){return this.view.getFrameTask()};b.prototype.requestScreenCapture=function(a,d){this.view.requestScreenCapture(a,d)};b.prototype.getAllTexturesLoaded=function(){return this.view.getAllTexturesLoaded()};b.prototype.getTextureLoaded=
function(a){return this.view.getTextureLoaded(a)};b.prototype.addExternalRenderer=function(a,d){"function"===typeof d.intersect&&this._externalIntersectionHandlers.push(d);return this.view.addExternalRenderer(a,d)};b.prototype.removeExternalRenderer=function(a){var d=this._externalIntersectionHandlers.indexOf(a);-1<d&&this._externalIntersectionHandlers.splice(d,1);return this.view.removeExternalRenderer(a)};b.prototype.getContentDebugStrings=function(a){return this.model.formatDebugInfo(a)};b.prototype.getRenderStats=
function(){return this.view.getCombinedStats()};b.prototype.getRenderStatString=function(a){var d=this.getRenderStats(),c="";if(a){var c=c+"\x3ctable\x3e",b;for(b in d)c+="\x3ctr\x3e\x3ctd\x3e"+b+'\x3c/td\x3e\x3ctd style\x3d"text-align: right"\x3e'+Math.round(d[b])+"\x3c/td\x3e\x3c/tr\x3e";c+="\x3c/table\x3e"}else for(b in d)c+=b+": "+d[b]+"\n";return c};b.prototype.pick=function(a,b,c,h){var e=k.create(),l=k.create();this.view.getPickRay(a,e,l);return this.pickRay(e,l,a,a,b,c,h)};b.prototype.pickRayWithBeginPoint=
function(a,b,c,h,e){this.view.pickRayWithBeginPoint(a,b,c,h,e)};b.prototype.pickRay=function(a,b,c,h,e,l,m){h=this.view.getCamera();c||(c=y,h.projectPoint(b,c));var n;if(e){n=Array(e.length);for(var f=0;f<n.length;f++)n[f]=this.model.get(r.ContentType.LAYER,e[f])}else{n=[];e=this.getViewContent();for(var k=this.model.getAll(r.ContentType.LAYER),f=0;f<e.length;f++){var g=k[e[f]];g&&"VISIBLE"===g.getState()&&n.push(g)}}m?m.init(n,a,b,c,h,this._intersectTolerance,l):m=new s(n,a,b,c,h,this._intersectTolerance,
l);for(f=0;f<this._externalIntersectionHandlers.length;f++)this._externalIntersectionHandlers[f].intersect(m,a,b,c);if(m.getHudResults().length){f=m.getHudResults();f.sort(function(a,b){return b.dist-a.dist});b=f[f.length-1];c=z;h.projectPoint(b.center,c);c[0]=Math.round(c[0]);c[1]=Math.round(c[1]);e=A;this.view.getPickRay(c,a,e);q.init(n,a,e,c,h,this._intersectTolerance,l);for(f=0;f<this._externalIntersectionHandlers.length;f++)this._externalIntersectionHandlers[f].intersect(q,a,e,c);if(null==q.getMinResult().dist||
b.dist<=q.getMinResult().dist)m.getMinResult().set(b.object,b.name,b.dist,b.normal,b.priority),m.getMinResult().setIntersector("stage")}return m};b.prototype.getIntersectTolerance=function(){return this._intersectTolerance};b.prototype.setIntersectTolerance=function(a){void 0===a&&(a=1E-5);this._intersectTolerance=a};b.prototype.getTextureGraphicsRenderer=function(){return this.view.getTextureGraphicsRenderer()};b.prototype.debugHideFaceRange=function(a,b){var c=this.getAll("objects")[a];c.hideFaceRange(c.getGeometryRecords()[0],
[c.getMetadata().faceRanges[b]])};b.prototype.debugHideAllFaceRange=function(a){a=this.getAll("objects")[a];for(var b in a.getMetadata().faceRanges)a.hideFaceRange(a.getGeometryRecords()[0],[a.getMetadata().faceRanges[b]])};b.prototype.debugUnhideFaceRange=function(a,b){this.getAll("objects")[a].unhideAllFaceRange()};b.DebugSettings={fineGrainedContentValidation:!1,endFrameContentValidation:!1,logDirtySet:!1};b.ModelContentType=v;return b}();var y=t.create(),z=u.create(),A=k.create(),q=new s;q.enableHUDSelection=
!1;return p});