// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators dojo/_base/lang ../../core/Accessor ./sublayerUtils".split(" "),function(n,p,f,d,c,h,k,l){var m={visible:"visibleSublayers",definitionExpression:"layerDefs",labelsVisible:"hasDynamicLayers",labelingInfo:"hasDynamicLayers",opacity:"hasDynamicLayers",renderer:"hasDynamicLayers",source:"hasDynamicLayers"};return function(e){function b(){e.apply(this,arguments);this.scale=
0}f(b,e);Object.defineProperty(b.prototype,"dynamicLayers",{get:function(){if(!this.hasDynamicLayers)return null;var a=this.visibleSublayers.map(function(a){return a.toExportImageJSON()});return!a.length?null:JSON.stringify(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasDynamicLayers",{get:function(){return l.isExportDynamic(this.visibleSublayers,this.layer.serviceSublayers,this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layer",{set:function(a){var b=
this;this._get("layer")!==a&&(this._set("layer",a),this._layerHandles&&(this._layerHandles.forEach(function(a){return a.remove()}),this._layerHandles.length=0),a&&(this._layerHandles=[a.allSublayers.on("change",function(){return b.notifyChange("visibleSublayers")}),a.on("sublayer-update",function(a){return b.notifyChange(m[a.propertyName])})]))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layers",{get:function(){var a=this.visibleSublayers;return a?a.length?"show:"+a.map(function(a){return a.id}).join(","):
"show:-1":null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layerDefs",{get:function(){var a=this.visibleSublayers.filter(function(a){return null!=a.definitionExpression});if(!a.length)return null;var b=/[:;]/;return a.some(b.test.bind(b))?JSON.stringify(a.reduce(function(a,b){a[b.id]=b.definitionExpression;return a},{})):a.map(function(a){return a.id+":"+a.definitionExpression}).join(";")},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"version",{get:function(){return(this._get("version")||
0)+1},set:function(a){this._set("version",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visibleSublayers",{get:function(){var a=this,b=this.layer.sublayers,c=[],d=function(b){var g=a.scale,e=0===b.minScale||g<=b.minScale,f=0===b.maxScale||g>=b.maxScale;if(b.visible&&(0===g||e&&f))b.sublayers?b.sublayers.forEach(d):c.unshift(b)};b&&b.forEach(d);return c},enumerable:!0,configurable:!0});b.prototype.toJSON=function(){var a=this.layer,a={dpi:a.dpi,format:a.imageFormat,transparent:a.imageTransparency,
gdbVersion:a.gdbVersion||null};this.hasDynamicLayers&&this.dynamicLayers?a.dynamicLayers=this.dynamicLayers:h.mixin(a,{layers:this.layers,layerDefs:this.layerDefs});return a};d([c.property({readOnly:!0,dependsOn:["hasDynamicLayers","visibleSublayers"]})],b.prototype,"dynamicLayers",null);d([c.property({readOnly:!0,dependsOn:["visibleSublayers","layer.serviceSublayers","layer.capabilities"]})],b.prototype,"hasDynamicLayers",null);d([c.property()],b.prototype,"layer",null);d([c.property({readOnly:!0,
dependsOn:["visibleSublayers"]})],b.prototype,"layers",null);d([c.property({readOnly:!0,dependsOn:["visibleSublayers"]})],b.prototype,"layerDefs",null);d([c.property({type:Number})],b.prototype,"scale",void 0);d([c.property({dependsOn:"layers layerDefs dynamicLayers layer.dpi layer.imageFormat layer.imageTransparency layer.gdbVersion".split(" ")})],b.prototype,"version",null);d([c.property({readOnly:!0,dependsOn:["layer.sublayers","scale"]})],b.prototype,"visibleSublayers",null);return b=d([c.subclass("esri.layers.mixins.ExportImageParameters")],
b)}(c.declared(k))});