// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper dojo/_base/lang dojo/io-query ../../request ../../core/Accessor ../../core/LRUMap ../../core/promiseUtils ../../core/watchUtils ../../core/Error ../../core/HandleRegistry ../../core/Logger ../../core/accessorSupport/decorators ./Tilemap".split(" "),function(z,A,q,h,n,r,s,t,u,k,v,m,w,x,f,l){var y=x.getLogger("esri.layers.support.TilemapCache");return function(p){function d(){p.apply(this,arguments);
this._handles=new w;this._pendingTilemapRequests={};this._availableLevels={};this.levels=5;this.cacheByteSize=2097152;this.request=s}q(d,p);d.prototype.normalizeCtorArgs=function(a){var b=this;a=n.mixin({},a);this._constructOnly={};["cacheByteSize","layer","levels","request"].forEach(function(e){e in a&&("levels"===e&&2>=a[e]?y.error("Minimum levels for Tilemap is 3, but got ",a[e]):b._constructOnly[e]=a[e],delete a[e])});return a};d.prototype.initialize=function(){var a=this,b;for(b in this._constructOnly)this._set(b,
this._constructOnly[b]);this._constructOnly=null;this._tilemapCache=new u(this.cacheByteSize,{sizeOfFunction:function(a){return a.byteSize}});this._handles.add([this.watch(["layer.parsedUrl","layer.tileServers"],function(){return a._initializeTilemapDefinition()}),v.init(this,"layer.tileInfo.lods",function(b){return a._initializeAvailableLevels(b)},!0)]);this._initializeTilemapDefinition()};d.prototype.destroy=function(){this._handles&&(this._handles.destroy(),this._handles=null)};Object.defineProperty(d.prototype,
"size",{get:function(){return 1<<this.levels},enumerable:!0,configurable:!0});d.prototype.getTilemap=function(a,b,e){return this._tilemapFromCache(a,b,e,this._tmpTilemapDefinition)};d.prototype.fetchTilemap=function(a,b,e,c){var d=this;if(!this._availableLevels[a])return k.reject(new m("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service"));var f=this._tmpTilemapDefinition;if(a=this._tilemapFromCache(a,b,e,f))return k.resolve(a);var g=l.tilemapDefinitionId(f);a=this._pendingTilemapRequests[g];
a||(a=l.Tilemap.fromDefinition(f,c).then(function(a){d._tilemapCache.set(g,a);delete d._pendingTilemapRequests[g];return a}).otherwise(function(a){delete d._pendingTilemapRequests[g];return k.reject(a)}),this._pendingTilemapRequests[g]=a);return a};d.prototype.getAvailability=function(a,b,e){return!this._availableLevels[a]?"unavailable":(a=this.getTilemap(a,b,e))?a.getAvailability(b,e):"unknown"};d.prototype.getAvailabilityUpsample=function(a,b,e,c){c.level=a;c.row=b;c.col=e;a=this.layer.tileInfo;
for(a.updateTileInfo(c);;)if(b=this.getAvailability(c.level,c.row,c.col),"unavailable"===b){if(!a.upsampleTile(c))return"unavailable"}else return b};d.prototype.fetchAvailability=function(a,b,e,c){return!this._availableLevels[a]?k.reject(new m("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service")):this.fetchTilemap(a,b,e,c).always(function(c){return c instanceof l.Tilemap?(c=c.getAvailability(b,e),"unavailable"===c?k.reject(new m("tile-map:tile-unavailable","Tile is not available",
{level:a,row:b,col:e})):c):"unknown"})};d.prototype.fetchAvailabilityUpsample=function(a,b,e,c,d){var f=this;c.level=a;c.row=b;c.col=e;var g=this.layer.tileInfo;g.updateTileInfo(c);return this.fetchAvailability(a,b,e,d).otherwise(function(a){return g.upsampleTile(c)?f.fetchAvailabilityUpsample(c.level,c.row,c.col,c):k.reject(a)})};d.prototype._initializeTilemapDefinition=function(){if(this.layer.parsedUrl){var a=this.layer.parsedUrl,b=a.query;if((!b||!b.token)&&this.layer.token)b=n.mixin(b,{token:this.layer.token});
this._tilemapCache.clear();this._tmpTilemapDefinition={service:{url:a.path,query:b?r.objectToQuery(b):null,tileServers:this.layer.tileServers,request:this.request},width:this.size,height:this.size,level:0,row:0,col:0}}};d.prototype._tilemapFromCache=function(a,b,e,c){a=this._getTilemapDefinition(a,b,e,c);a=l.tilemapDefinitionId(a);return this._tilemapCache.get(a)};d.prototype._getTilemapDefinition=function(a,b,e,c){c.level=a;c.row=b-b%this.size;c.col=e-e%this.size;return c};d.prototype._initializeAvailableLevels=
function(a){var b=this;this._availableLevels={};a&&a.forEach(function(a){return b._availableLevels[a.level]=!0})};h([f.property({readOnly:!0})],d.prototype,"levels",void 0);h([f.property({readOnly:!0,dependsOn:["levels"]})],d.prototype,"size",null);h([f.property({readOnly:!0})],d.prototype,"cacheByteSize",void 0);h([f.property({readOnly:!0})],d.prototype,"layer",void 0);h([f.property({readOnly:!0})],d.prototype,"request",void 0);return d=h([f.subclass("esri.layers.support.TilemapCache")],d)}(f.declared(t))});