// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/has dojo/_base/lang ../../core/promiseUtils ../../core/urlUtils ../../config ../../request".split(" "),function(y,t,z,u,l,d,m,n){function k(a){if(a){var b=d.getOrigin(a);!d.canUseXhr(b)&&-1===p.indexOf(b)&&p.push(b);return a}}function q(a,b,c){if(null!=b.sources){c&&-1!==c.path.indexOf("root.json")&&(c.path=c.path.substr(0,c.path.indexOf("root.json")),a.styleUrl=c.path);var e=r(b,c),g=b.sprite,f=b.glyphs;e&&e.url&&(e=c&&c.path?c.path:e.url,b.sprite&&!d.isAbsolute(b.sprite)&&
(g=d.join(e,b.sprite)),b.glyphs&&!d.isAbsolute(b.glyphs)&&(f=d.join(e,b.glyphs)));a.style=b;a.spriteUrl=g;a.glyphsUrl=f;return v(a,b,c)}if(b.hasOwnProperty("tileInfo"))return a.layerDefinition=b,a.serviceUrl=c.path,w(a,b,c)}function w(a,b,c){if(x&&!b.hasOwnProperty("defaultStyles"))throw Error("Service definition must have 'defaultStyles' element!");b=b.defaultStyles;d.isAbsolute(b)?a.styleUrl=d.normalize(b):a.styleUrl=d.normalize(d.join(c.path,b));k(a.styleUrl);return n(d.join(a.styleUrl,"root.json"),
{responseType:"json"}).then(function(b){var c=b.data.sprite,f=b.data.glyphs;c&&!d.isAbsolute(c)&&(c=d.join(a.styleUrl,c));f&&!d.isAbsolute(f)&&(f=d.join(a.styleUrl,f));a.spriteUrl=c;a.glyphsUrl=f;return a.style=b.data})}function v(a,b,c){(b=r(b,c))||l.reject("Source isn't available in the syle object!");if(b.url)return a.serviceUrl=b.url,d.isAbsolute(a.serviceUrl)||(a.serviceUrl=d.join(c.path,a.serviceUrl)),k(a.serviceUrl),n(a.serviceUrl,{query:{f:"json"},responseType:"json"}).then(function(b){a.layerDefinition=
s(b.data);return a});a.layerDefinition=s(b);return l.resolve(a)}function r(a,b){if(!a.sources)return null;var c=a.sources,e=null;if(c.esri)e=c.esri,b&&(e.url&&!d.isAbsolute(e.url))&&(c=b.path.substring(0,b.path.lastIndexOf("/")),e.url=d.join(c,e.url));else{for(var g=0,f=Object.keys(c);g<f.length;g++){var h=f[g];if(-1!==h.toLocaleLowerCase().indexOf("street")&&"vector"===e.type){e=c[h];break}}if(!e){g=0;for(f=Object.keys(c);g<f.length&&!(h=f[g],e=c[h],"vector"===e.type);g++);}}return e}function s(a){if(a.hasOwnProperty("tileInfo"))return a;
for(var b={xmin:-2.0037507067161843E7,ymin:-2.0037507067161843E7,xmax:2.0037507067161843E7,ymax:2.0037507067161843E7,spatialReference:{wkid:102100}},c=(b.xmax-b.xmin)/512,e=[],d=a.hasOwnProperty("minzoom")?parseFloat(a.minzoom):0,f=a.hasOwnProperty("maxzoom")?parseFloat(a.maxzoom):16;d<f;d++){var h=c/Math.pow(2,d);e.push({level:d,scale:Math.floor(3779.527559055118*h),resolution:h})}a.tiles.forEach(k);return{capabilities:"TilesOnly",initialExtent:b,fullExtent:b,minScale:e[0].scale,maxScale:e[e.length-
1].scale,tiles:a.tiles,tileInfo:{rows:512,cols:512,dpi:96,format:"pbf",origin:{x:-2.0037508342787E7,y:2.0037508342787E7},lods:e,spatialReference:{wkid:102100}}}}var x=0,p=m.defaults&&m.defaults.io.corsEnabledServers||m.request.corsEnabledServers;t.loadMetadata=function(a){if(!a)return l.reject("invalid input URL!");var b={layerDefinition:null,parsedUrl:null,serviceUrl:null,style:null,styleUrl:null,url:null,spriteUrl:null,glyphsUrl:null};if("string"!==typeof a)return q(b,a,null).then(function(){return b});
a=b.url=d.normalize(a);var c=b.parsedUrl=d.urlToObject(a);k(a);return n(c.path,{responseType:"json",query:u.mixin({f:"json"},c.query)}).then(function(a){return q(b,a.data,c)}).then(function(){return b})}});