// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/Deferred ../../config ../Polyline ../Polygon ./webMercatorUtils ./spatialReferenceUtils ./jsonUtils".split(" "),function(g,G,H,q,z,y,D,I){function v(a,c){return Math.ceil((a-c)/(2*c))}function A(a,c){var b=a.paths||a.rings,d,f,m=b.length,n;for(d=0;d<m;d++){n=b[d].length;for(f=0;f<n;f++){var k=a.getPoint(d,f);a.setPoint(d,f,k.clone().offset(c,0))}}return a}function w(a,c){if(!(a instanceof q||a instanceof z))throw console.error("_straightLineDensify: the input geometry is neither polyline nor polygon"),
Error("_straightLineDensify: the input geometry is neither polyline nor polygon");var b=a instanceof q,d=[],f;g.forEach(b?a.paths:a.rings,function(a){d.push(f=[]);f.push([a[0][0],a[0][1]]);var b,k,e,h,l,r,g,p,q,s,t,u;for(l=0;l<a.length-1;l++){b=a[l][0];k=a[l][1];e=a[l+1][0];h=a[l+1][1];g=Math.sqrt((e-b)*(e-b)+(h-k)*(h-k));p=(h-k)/g;q=(e-b)/g;s=g/c;if(1<s){for(r=1;r<=s-1;r++)u=r*c,t=q*u+b,u=p*u+k,f.push([t,u]);r=(g+Math.floor(s-1)*c)/2;t=q*r+b;u=p*r+k;f.push([t,u])}f.push([e,h])}});return b?new q({paths:d,
spatialReference:a.spatialReference}):new z({rings:d,spatialReference:a.spatialReference})}function B(a,c,b){c&&(a=w(a,1E6),a=y.webMercatorToGeographic(a,!0));b&&(a=A(a,b));return a}function C(a,c,b){var d=a.x||a[0],f;d>c?(f=v(d,c),a.x?a=a.clone().offset(f*-2*c,0):a[0]=d+f*-2*c):d<b&&(f=v(d,b),a.x?a=a.clone().offset(f*-2*b,0):a[0]=d+f*-2*b);return a}function E(a,c){var b=-1;g.forEach(c.cutIndexes,function(d,f){var m=c.geometries[f];g.forEach(m.rings||m.paths,function(a,d){g.some(a,function(b){if(!(180>
b[0])){b=0;var c,f=a.length,g;for(c=0;c<f;c++)g=a[c][0],b=g>b?g:b;b=Number(b.toFixed(9));b=-360*v(b,180);f=a.length;for(c=0;c<f;c++)g=m.getPoint(d,c),m.setPoint(d,c,g.clone().offset(b,0))}return!0})});d===b?m.rings?g.forEach(m.rings,function(b){a[d]=a[d].addRing(b)}):g.forEach(m.paths,function(b){a[d]=a[d].addPath(b)}):(b=d,a[d]=m)});return a}function x(a){for(var c=[],b=0,d=0,f=Math.min,g=Math.max,n=0;n<a.length;n++){for(var k=a[n],e=null,h=0;h<k.length;h++)e=k[h],c.push(e),0===h?d=b=e[0]:(b=f(b,
e[0]),d=g(d,e[0]));e&&c.push([(b+d)/2,0])}return c}return{normalizeCentralMeridian:function(a,c){var b=new G;c=c||H.geometryService;var d=[],f=[],m,n,k,e,h,l,r,w,p=0;g.forEach(a,function(a){if(a)if(m||(m=a.spatialReference,n=D.getInfo(m),e=(k=m.isWebMercator)?2.0037508342788905E7:180,h=k?-2.0037508342788905E7:-180,l=k?102100:4326,r=new q({paths:[[[e,h],[e,e]]],spatialReference:{wkid:l}}),w=new q({paths:[[[h,h],[h,e]]],spatialReference:{wkid:l}})),n){var b=I.fromJSON(a.toJSON()),c=a.extent;"point"===
a.type?d.push(C(b,e,h)):"multipoint"===a.type?(b.points=g.map(b.points,function(a){return C(a,e,h)}),d.push(b)):"extent"===a.type?(b=c.clone()._normalize(null,null,n),d.push(b.rings?new z(b):b)):c?(a=v(c.xmin,h)*2*e,b=0===a?b:A(b,a),c=c.clone().offset(a,0),c.intersects(r)&&c.xmax!==e?(p=c.xmax>p?c.xmax:p,b=B(b,k),f.push(b),d.push("cut")):c.intersects(w)&&c.xmin!==h?(p=c.xmax*2*e>p?c.xmax*2*e:p,b=B(b,k,360),f.push(b),d.push("cut")):d.push(b)):d.push(b)}else d.push(a);else d.push(a)});for(var x=new q,
s=v(p,e),t=-90,u=s;0<s;){var F=-180+360*s;x.addPath([[F,t],[F,-1*t]]);t*=-1;s--}0<f.length&&0<u?c?c.cut(f,x,function(e){f=E(f,e);var h=[];g.forEach(d,function(b,c){if("cut"===b){var e=f.shift();a[c].rings&&1<a[c].rings.length&&e.rings.length>=a[c].rings.length?(d[c]="simplify",h.push(e)):d[c]=!0===k?y.geographicToWebMercator(e):e}});0<h.length?c.simplify(h,function(a){g.forEach(d,function(b,c){"simplify"===b&&(d[c]=!0===k?y.geographicToWebMercator(a.shift()):a.shift())});b.resolve(d)},function(a){b.reject(a)}):
b.resolve(d)},function(a){b.reject(a)}):b.reject(Error("esri.geometry.normalizeCentralMeridian: 'geometryService' argument is missing.")):(g.forEach(d,function(a,b){if("cut"===a){var c=f.shift();d[b]=!0===k?y.geographicToWebMercator(c):c}}),b.resolve(d));return b.promise},_foldCutResults:E,_prepareGeometryForCut:B,_offsetMagnitude:v,_pointNormalization:C,_updatePolyGeometry:A,_straightLineDensify:w,getDenormalizedExtent:function(a){if(!a)return null;var c=a.extent;if(!c)return null;var b=a.spatialReference&&
D.getInfo(a.spatialReference);if(!b)return c;var d=b.valid[0],b=b.valid[1],f=c.width,g=c.xmax,n=c.xmin;if("extent"===a.type||0===f||f<=b||f>2*b||g<d||n>b)return c;var k;switch(a.type){case "polygon":if(1<a.rings.length)k=x(a.rings);else return c;break;case "polyline":if(1<a.paths.length)k=x(a.paths);else return c;break;case "multipoint":k=a.points}a=Math.min;for(var d=Math.max,e=c.clone(),h=0;h<k.length;h++){var l=k[h][0];0>l?(l+=b,n=d(l,n)):(l-=b,g=a(l,g))}e.xmin=g;e.xmax=n;return e.width<f?(e.xmin-=
b,e.xmax-=b,e):c}}});