// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/promiseUtils ../../symbols/support/jsonUtils ../../symbols/support/gfxUtils ../../core/accessorSupport/decorators dojo/promise/all ../../symbols/WebStyleSymbol ../../symbols/support/symbolUtils dojo/i18n!./nls/SymbolStyler".split(" "),function(e,h,f,c,g,l,n,p,b,q,r,s,m){function t(b,a){return q(b.map(function(b){var d=s.styleNameFromItem(a);return(new r({styleName:d,
name:b.name,portal:a.portal})).fetchSymbol()}))}function k(b){return b.map(function(a){return n.fromJSON(a)})}e=function(d){function a(){d.apply(this,arguments)}f(a,d);a.prototype._fetchData=function(){return this.portalItem.fetchData()};c([b.property({aliasOf:"portalItem.id"})],a.prototype,"id",void 0);c([b.property({aliasOf:"portalItem.title"})],a.prototype,"name",void 0);c([b.property()],a.prototype,"portalItem",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.PortalItemSymbolSource")],
a)}(b.declared(g));var u=function(d){function a(){d.apply(this,arguments);this.type="symbol-set"}f(a,d);a.prototype.getSymbols=function(){return this._fetchData().then(function(a){return k(a)})};c([b.property({readOnly:!0})],a.prototype,"type",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.SymbolSetSymbolSource")],a)}(b.declared(e));h.SymbolSetSymbolSource=u;e=function(d){function a(){d.apply(this,arguments);this.type="web-style"}f(a,d);a.prototype.getSymbols=function(){var a=this;return this._fetchData().then(function(b){return t(b.items,
a.portalItem)})};c([b.property({readOnly:!0})],a.prototype,"type",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.WebStyleSymbolSource")],a)}(b.declared(e));h.WebStyleSymbolSource=e;var v=[{name:"Circle",type:"esriSMS",style:"esriSMSCircle",color:[0,0,128,128],size:18,outline:{color:[0,0,128,255],width:1}},{name:"Square",type:"esriSMS",style:"esriSMSSquare",color:[0,0,128,128],size:18,outline:{color:[0,0,128,255],width:1}},{name:"Diamond",type:"esriSMS",style:"esriSMSDiamond",color:[0,0,
128,128],size:18,outline:{color:[0,0,128,255],width:1}},{name:"Cross",type:"esriSMS",style:"esriSMSCross",color:[0,0,128,128],size:18,outline:{color:[0,0,128,255],width:1}},{name:"X",type:"esriSMS",style:"esriSMSX",color:[0,0,128,128],size:18,outline:{color:[0,0,128,255],width:1}}],w=["circle","square","cross","x","kite"].map(function(b){return{type:"PointSymbol3D",symbolLayers:[{type:"Icon",resource:{primitive:b},material:{color:p.defaultThematicColor},outline:{color:[0,0,0]}}]}}),x="sphere cylinder cube cone inverted-cone diamond tetrahedron".split(" ").map(function(b){return{type:"PointSymbol3D",
symbolLayers:[{type:"Object",resource:{primitive:b}}]}});e=function(d){function a(){d.apply(this,arguments);this.name=m.basic;this.type="symbol-set"}f(a,d);a.prototype.getSymbols=function(){return l.resolve(k(v))};c([b.property()],a.prototype,"id",void 0);c([b.property()],a.prototype,"name",void 0);c([b.property({readOnly:!0})],a.prototype,"type",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.BasicSymbolSetSource")],a)}(b.declared(g));h.BasicSymbolSetSource=e;e=function(d){function a(){d.apply(this,
arguments);this.id="basic-web-style:flat";this.name=m.basic;this.type="web-style"}f(a,d);a.prototype.getSymbols=function(){return l.resolve(k(w))};c([b.property()],a.prototype,"id",void 0);c([b.property()],a.prototype,"name",void 0);c([b.property({readOnly:!0})],a.prototype,"type",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.IconPrimitiveWebStyleSource")],a)}(b.declared(g));h.IconPrimitiveWebStyleSource=e;g=function(d){function a(){d.apply(this,arguments);this.id="basic-web-style:volumetric";
this.name=m.basic;this.type="web-style"}f(a,d);a.prototype.getSymbols=function(){return l.resolve(k(x))};c([b.property()],a.prototype,"id",void 0);c([b.property()],a.prototype,"name",void 0);c([b.property({readOnly:!0})],a.prototype,"type",void 0);return a=c([b.subclass("esri.widgets.SymbolStyler.ObjectPrimitiveWebStyleSource")],a)}(b.declared(g));h.ObjectPrimitiveWebStyleSource=g});