// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/promise/all ../../../views/3d/support/ResourceController ../../../views/3d/layers/i3s/I3SNodeLoader ../../../views/3d/layers/i3s/I3SIndexTraversal ../../../views/3d/layers/i3s/I3SUtil ../../../views/3d/layers/i3s/I3SLodHandling ../../../views/3d/layers/i3s/I3SViewportQueries ../../../layers/SceneLayer ../../../layers/IntegratedMeshLayer ../../../core/accessorSupport/decorators ../../../core/Accessor ../../../core/Evented ../../../core/Promise ../../../core/Logger ../../../core/watchUtils ../../../core/HandleRegistry ../../../views/3d/support/PromiseLightweight ../../../views/3d/support/projectionUtils ../../../views/3d/lib/glMatrix".split(" "),
function(H,I,p,g,q,r,s,t,k,u,v,w,x,d,y,z,A,B,C,D,E,F,G){function l(d,c){for(var a=0;a<d.length;a++)if(d[a].name===c)return[a,d[a]];return[-1,void 0]}var h=G.vec3d,n=B.getLogger("esri.layers.SceneService");return function(m){function c(a){m.call(this);this.nodeIndex={};this.screenSizeFactor=0;this.updating=!1;this.updatingPercentage=0;this._lodFactorProperty=null;this._numNodesLoading=0;this._progressMaxNumNodes=1;this._animFrameFunctionQueue=[[],[]];this._requiredAttributesDirty=!0;this._restartNodeLoading=
this._updatesDisabled=!1;this._handles=new D}p(c,m);Object.defineProperty(c.prototype,"isMeshPyramid",{get:function(){return"mesh-pyramids"===this.layer.profile||"MeshPyramid"===this.layer.store.lodType},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"streamDataSupplier",{get:function(){return this.layerView.view.resourceController.registerClient(this.layerView,r.ClientType.SCENE,{addUrlToken:this.addUrlToken,trackRequests:!0})},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"crsVertex",{get:function(){return k.getVertexCrs(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"crsIndex",{get:function(){return k.getIndexCrs(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"rootNodeVisible",{get:function(){var a=this._rootNodeId&&this.nodeIndex[this._rootNodeId];return a&&this._viewportQueries?this._viewportQueries.isNodeVisible(a):!0},enumerable:!0,configurable:!0});c.prototype.initialize=function(){var a=this;this.updateEventListener=
{needsUpdate:function(){return a._needsAnimationFrameHandler()},idleFrame:function(b){return a._animationFrameHandler(b)},idleBegin:function(){return a._startNodeLoading()},idleEnd:function(){return a.cancelNodeLoading()}};this.updateEventListenerWhileSuspended={idleBegin:function(){return a._startNodeLoadingWhileSuspended()}};this._lodHandling=new u(this.layerViewRequiredFunctions,this.layerViewOptionalFunctions);this.layerView._controller=this;var b=this.layer;this._defaultGeometrySchema=b.store.defaultGeometrySchema;
this._fields=b.fields;this._attributeStorageInfo=b.attributeStorageInfo;this._rootNodeUrl=b.store.rootNode;b=this._rootNodeUrl.split("/");this._rootNodeId=b[b.length-1];this.layer instanceof w?"mesh"===this.layer.geometryType?this._lodFactorProperty="qualitySettings.sceneService.3dObject.lodFactor":"point"===this.layer.geometryType&&(this._lodFactorProperty="qualitySettings.sceneService.point.lodFactor"):this.layer instanceof x&&(this._lodFactorProperty="qualitySettings.sceneService.integratedMesh.lodFactor");
b=q([this.layer,this.layerView]).then(function(){if(!a.destroyed&&a.layerView&&!a.layerView.destroyed){a.setClippingArea(a.layerView.view.clippingArea);var b=a.layerView.view.resourceController,c=!1;a._handles.add(C.init(a.layerView,"suspended",function(f){null!=a.layerView.setVisibility&&a.layerView.setVisibility(!f);c&&b.deregisterIdleFrameWorker(a);f?b.registerIdleFrameWorker(a,a.updateEventListenerWhileSuspended):b.registerIdleFrameWorker(a,a.updateEventListener);c=!0}),"layerview");a._lodFactorProperty&&
a._handles.add(a.layerView.view.watch(a._lodFactorProperty,function(){return a._qualityChanged()}),"quality")}});this.addResolvingPromise(b)};c.prototype.destroy=function(){this.layerView.view.resourceController.deregisterIdleFrameWorker(this);this.layerView.view.resourceController.deregisterClient(this.layerView);this._handles.destroy();this._nodeLoader=null};c.prototype._modifyNumNodesLoading=function(a){this._numNodesLoading+=a};c.prototype._getRequiredAttributes=function(){if(null==this._attributeStorageInfo||
!this._fields)return[];var a=Object.create(null);this.layer.renderer&&this.layer.renderer.collectRequiredFields(a);this.layer.labelsVisible&&this.layer.labelingInfo&&this.layer.labelingInfo.forEach(function(b){b._collectRequiredFields(a)});var b=this._attributeStorageInfo,c=this._fields;return Object.keys(a).map(function(a){var f=l(b,a)[0],d=l(c,a)[1];return{index:f,name:a,field:d,attributeStorageInfo:b[f]}}).filter(function(a){return-1!==a.index&&null!=a.field})};c.prototype._rendererChanged=function(){this._restartNodeLoading=
this._requiredAttributesDirty=!0};c.prototype._labelsVisibleChanged=function(){var a=this._getRequiredAttributes(),b=!0;a.length===this._requiredAttributes.length&&(b=this._requiredAttributes.every(function(b){return-1!==l(a,b.name)[0]}));b&&(this._restartNodeLoading=this._requiredAttributesDirty=!0)};c.prototype._labelingInfoChanged=function(){};c.prototype.setClippingArea=function(a){var b=[];F.extentToBoundingBox(a,b,this.layerView.view.renderSpatialReference)?this._clippingArea=b:this._clippingArea=
null};c.prototype._qualityChanged=function(){this._restartNodeLoading=!0};c.prototype.updateClippingArea=function(a){this.setClippingArea(a);this._restartNodeLoading=!0};c.prototype.queueAnimationFrameFunctionCall=function(a,b,c,e,f){null!=this._nodeLoader&&this._animFrameFunctionQueue[f||0].push({fct:a,that:b,args:c,cancelFunc:e})};c.prototype.getBaseUrl=function(){return k.addTrailingSlash(this.layer.parsedUrl.path)};c.prototype.updateElevationChanged=function(a,b,c){k.findIntersectingNodes(a,b,
this.nodeIndex.root,this.crsIndex,this.nodeIndex,c);for(a=0;a<c.length;a++)b=c.data[a],b.computedMbs&&(b.computedMbs[3]=-1);c.length&&this.restartNodeLoading()};c.prototype.restartNodeLoading=function(){this._restartNodeLoading=!0};c.prototype._needsAnimationFrameHandler=function(){return!0};c.prototype._animationFrameHandler=function(a){this._restartNodeLoading&&(this.cancelNodeLoading(),this._startNodeLoading());if(null!=this._nodeLoader){for(var b;0<this._animFrameFunctionQueue[0].length&&!a.done();)b=
this._animFrameFunctionQueue[0].shift(),b.fct.apply(b.that,b.args);b=5-this._numNodesLoading;for(null!=this._indexLoader&&0<b&&this._indexLoader.continueTraversal(b);0<this._animFrameFunctionQueue[1].length&&!a.done();)b=this._animFrameFunctionQueue[1].shift(),b.fct.apply(b.that,b.args);this._evaluateUpdatingState();this._lodHandling.lodGlobalHandling()}};c.prototype._evaluateUpdatingState=function(){var a=null!=this._indexLoader?this._indexLoader.getQueueSize()+3*this._numNodesLoading:0,b=0<a;0===
a&&(this._progressMaxNumNodes=1);this._progressMaxNumNodes=Math.max(a,this._progressMaxNumNodes);b!==this._get("updating")&&this._set("updating",b);a=100*a/this._progressMaxNumNodes;a!==this._get("updatingPercentage")&&this._set("updatingPercentage",a)};c.prototype._initViewData=function(){var a=this.layerView.view,b=a.navigation.targetCamera,c=a.renderCoordsHelper;this.camPos=b.eye;this.screenSizeFactor=1/b.perPixelRatio;this._poi=h.create();var e=h.create(),f=h.create();h.subtract(b.center,b.eye,
e);h.normalize(e);c.worldUpAtPosition(b.center,f);e=Math.acos(h.dot(f,e))-0.5*Math.PI;h.lerp(b.eye,b.center,Math.max(0,Math.min(1,e/(0.5*Math.PI))),this._poi);e=this._lodFactorProperty&&this.layerView.view.get(this._lodFactorProperty)||1;f=this.layerViewOptionalFunctions.traversalOptions.elevationInfo;this._viewportQueries=new v(this.crsIndex,c,b,this._clippingArea,null!=this.layerViewOptionalFunctions.traversalOptions?this.layerViewOptionalFunctions.traversalOptions.errorMetricPreference:null,f?
a.basemapTerrain:null,f,{screenspaceErrorBias:e,maxDistance:25E7,angleDependentLoD:0.5>e});this.notifyChange("rootNodeVisible")};c.prototype._startNodeLoadingWhileSuspended=function(){var a=this;this._initViewData();this._removeInvisibleNodes(function(b){return a._viewportQueries.isNodeVisible(b)})};c.prototype._startNodeLoading=function(){var a=this;this._restartNodeLoading=!1;if(!this._updatesDisabled&&null!=this.streamDataSupplier){this._initViewData();var b=null!=this.layerViewOptionalFunctions.getTexturePrefetchFunctions?
this.layerViewOptionalFunctions.getTexturePrefetchFunctions():void 0,c=this.isMeshPyramid&&null!=this._defaultGeometrySchema&&null!=this._defaultGeometrySchema.ordering;null!=this.layerViewOptionalFunctions.getLoadedAttributes&&this._requiredAttributesDirty&&(this._requiredAttributes=this._getRequiredAttributes(),this._requiredAttributesDirty=!1,this._handles.add([this.layer.watch("renderer",function(){return a._rendererChanged()}),this.layer.watch("labelsVisible",function(){return a._labelsVisibleChanged()}),
this.layer.watch("labelingInfo",function(){return a._labelingInfoChanged()})],"requiredAttributes"));this._nodeLoader=new s(this.streamDataSupplier,this._bundleLoadedCallback.bind(this),this.queueAnimationFrameFunctionCall.bind(this),void 0,this.layerView.view.renderCoordsHelper,this.crsIndex,b?b._calcDesiredTextureLOD:void 0,b?b._imageIsPartOfTextureBundle:void 0,b?b._matId2Meta:void 0,b?b._texId2Meta:void 0,b?b.useCompressedTextures:void 0,n,this._defaultGeometrySchema,this._requiredAttributes,
c);this._indexLoader=new t(this.getBaseUrl(),this._rootNodeUrl,this._rootNodeId,this._poi,this.nodeIndex,this.streamDataSupplier,this._viewportQueries,function(b,c){return a._processNodeIndexDocument(b,c)},function(b){return a._lodHandling.finishedLevel(b)},this.layerViewOptionalFunctions._nodeDebugVisualizer,n,this.layerViewOptionalFunctions.traversalOptions);this._indexLoader.start();b=this._removeInvisibleNodes(function(b){return a._indexLoader.nodeIsVisible(b)});c=null!=this.layerViewOptionalFunctions.traversalOptions&&
!0===this.layerViewOptionalFunctions.traversalOptions.perLevelTraversal?"perLevel":this.isMeshPyramid?"global":"swap";this._lodHandling.startNodeLoading(this._indexLoader.nodeIsVisible.bind(this._indexLoader),this._indexLoader.nodeTraversalState.bind(this._indexLoader),c,this.nodeIndex,b,this._rootNodeId);this.layerViewOptionalFunctions.additionalStartNodeLoadingHandler&&this.layerViewOptionalFunctions.additionalStartNodeLoadingHandler();this._evaluateUpdatingState()}};c.prototype.isNodeLoading=function(){return null!=
this._nodeLoader&&null!=this._indexLoader};c.prototype.cancelNodeLoading=function(){if(this.isNodeLoading()){this._indexLoader.cancel();this._nodeLoader.cancel();this.streamDataSupplier.cancelAll();for(var a=0;a<this._animFrameFunctionQueue.length;a++)for(var b=0;b<this._animFrameFunctionQueue[a].length;b++)void 0!==this._animFrameFunctionQueue[a][b].cancelFunc&&this._animFrameFunctionQueue[a][b].cancelFunc();this._numNodesLoading=0;this._animFrameFunctionQueue=[[],[]];this._indexLoader=this._nodeLoader=
void 0;this._lodHandling.cancelNodeLoading();this.layerViewOptionalFunctions.additionalCancelNodeLoadingHandler&&this.layerViewOptionalFunctions.additionalCancelNodeLoadingHandler();this._evaluateUpdatingState()}};c.prototype._removeInvisibleNodes=function(a){for(var b={},c=this.layerViewRequiredFunctions.getAddedNodeIDs(),e=0;e<c.length;e++){var f=c[e],d=this.nodeIndex[f];this._isNodeVisibleWithParents(d,a)?b[f]=d:this._removeNodeData(d)}return b};c.prototype._isNodeVisibleWithParents=function(a,
b){var c,e=a;do c=b(e),e=e.parentNode,e=null!=e?this.nodeIndex[e.id]:null;while(c&&null!=e);return c};c.prototype._removeNodeData=function(a){this._lodHandling.setLodGlobalDirty();this.layerViewRequiredFunctions.removeNodeData(a)};c.prototype._processNodeIndexDocument=function(a,b){var c=this,e=new E.Promise;if(null!=a.featureData&&0<a.featureData.length)if(this.layerViewRequiredFunctions.areAllBundlesLoaded(a,!0)){var f=this.layerViewOptionalFunctions.getLoadedAttributes,f=null!=f?f(a):void 0;null!=
f&&f!==this._requiredAttributes&&this._nodeLoader.loadAttributes(a,a.baseUrl,this._requiredAttributes).then(function(b){c.layerViewOptionalFunctions.setAttributeData(a,c._requiredAttributes,b)}).catch(function(b){c.layerViewOptionalFunctions.setAttributeData(a,c._requiredAttributes,{})});this._lodHandling.shouldLoadNode(a,b)&&(f=this._lodHandling.lodSwapBuildInfoForNode(a))&&null==f.swapPairs&&this._lodHandling.lodSwapBundleLoaded(a,null,f)}else if(this._lodHandling.shouldLoadNode(a,b)){f=this._lodHandling.lodSwapBuildInfoForNode(a);
if(this.layerViewRequiredFunctions.isOverMemory())return e.done(),e;this._modifyNumNodesLoading(1);for(var d=[],g=0;g<a.featureData.length;g++){var h=this.layerViewRequiredFunctions.isBundleAlreadyAddedToStage(a,g),k=h.wasPartiallyHidden;(!h.alreadyLoaded||k)&&d.push(g)}this.queueAnimationFrameFunctionCall(this._nodeLoader.loadNodeData,this._nodeLoader,[a,d,e,null!=this.layerViewOptionalFunctions.getTexturePrefetchFunctions,f],void 0,1);e.then(function(){return c._modifyNumNodesLoading(-1)},function(){return c._modifyNumNodesLoading(-1)});
return e}e.done();return e};c.prototype._bundleLoadedCallback=function(a,b,c,e,d,g,h,k){this._lodHandling.lodSwapBundleLoaded(a,b,k);this.layerViewRequiredFunctions.addBundle(a,b,c,e,d,g,h);null!=this.layerViewOptionalFunctions.setPolygonOffset&&(b=this._lodHandling.shouldSetPolygonOffset(a))&&this.layerViewOptionalFunctions.setPolygonOffset(a,b)};g([d.property({readOnly:!0})],c.prototype,"isMeshPyramid",null);g([d.property({readOnly:!0})],c.prototype,"streamDataSupplier",null);g([d.property({readOnly:!0})],
c.prototype,"crsVertex",null);g([d.property({readOnly:!0})],c.prototype,"crsIndex",null);g([d.property({readOnly:!0})],c.prototype,"nodeIndex",void 0);g([d.property()],c.prototype,"camPos",void 0);g([d.property()],c.prototype,"screenSizeFactor",void 0);g([d.property()],c.prototype,"layerView",void 0);g([d.property()],c.prototype,"layerViewRequiredFunctions",void 0);g([d.property()],c.prototype,"layerViewOptionalFunctions",void 0);g([d.property()],c.prototype,"layer",void 0);g([d.property()],c.prototype,
"addUrlToken",void 0);g([d.property({readOnly:!0})],c.prototype,"updating",void 0);g([d.property({readOnly:!0})],c.prototype,"updatingPercentage",void 0);g([d.property({readOnly:!0})],c.prototype,"rootNodeVisible",null);return c=g([d.subclass("esri.layers.graphics.controllers.I3SOnDemandController")],c)}(d.declared(y,A,z))});