// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ./Bucket ./style/StyleLayer".split(" "),function(L,M,E,N,F,J){return function(D){function h(k,K,m,l,h){D.call(this,k,K);this.lineVertexBuffer=m;this.lineIndexBuffer=l;this.joinsVertexBuffer=h}E(h,D);Object.defineProperty(h.prototype,"triangleIndexStart",{get:function(){return this.triangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"triangleIndexCount",{get:function(){return this.triangleElementsCount},
enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"connectorStart",{get:function(){return this.pointConnectorStart},enumerable:!0,configurable:!0});Object.defineProperty(h.prototype,"connectorCount",{get:function(){return this.pointConnectorCount},enumerable:!0,configurable:!0});h.prototype.assignBufferInfo=function(k){k.triangleElementsStart=this.triangleElementsStart;k.triangleElementsCount=this.triangleElementsCount;k.pointConnectorStart=this.pointConnectorStart;k.pointConnectorCount=
this.pointConnectorCount};h.prototype.processFeatures=function(k,h){this.triangleElementsStart=this.lineIndexBuffer.index;this.triangleElementsCount=0;this.pointConnectorStart=this.joinsVertexBuffer.index;this.pointConnectorCount=0;k&&k.setExtent(this.layerExtent);for(var m=new J.LineLayout(this.layer,this.zoom),l=0,w=this._features;l<w.length;l++){var z=w[l].getGeometry(k);this._processFeature(m,z)}};h.prototype._processFeature=function(k,h){if(h)for(var m=h.length,l=0;l<m;l++)this._processGeometry(h[l],
k)};h.prototype._processGeometry=function(k,h){for(var m=k.length;2<=m&&k[m-1].isEqual(k[m-2]);)m--;if(!(2>m)){var l=k[m-1],w=k[0].isEqual(l);if(!(w&&2===m)){var z=h.cap,D=h.join,G=Math.min(h.miterLimit,4),B=Math.min(h.roundLimit,1.4142),B=2/B*Math.sqrt(1-1/B/B),b,x,n,I,y,p,r,f,g,d=-1,c=-1,a=-1,e=1,q=0;w&&(b=k[m-2],f=l.x-b.x,g=l.y-b.y,y=Math.sqrt(f*f+g*g),f/=y,g/=y);for(var s=this.lineVertexBuffer,t=this.lineIndexBuffer,C=this.joinsVertexBuffer,E=t.index,F=C.index,A=0;A<m;A++)if(void 0!==f&&(p=-f,
r=-g),b&&(x=b,I=y),b=k[A],l=D,x&&(q+=I),n=A+1<m?k[A+1]:void 0,w&&!n&&(n=k[1]),!n||!b.isEqual(n)){n?(f=n.x-b.x,g=n.y-b.y,y=Math.sqrt(f*f+g*g),f/=y,g/=y):(f=-p,g=-r);void 0===p&&(p=-f,r=-g);var u=p+f,v=r+g,a=f*v-g*u,u=u/a,v=v/a,H=Math.sqrt(u*u+v*v);2!==l&&Math.abs(a)<B&&H<G&&(l=2);if(!x&&2===z)c=a=s.add(b.x,b.y,p+e*r,r-p*e,0,0,q),a=s.add(b.x,b.y,p-r*e,r+p*e,0,1,q),d=c,c=a;else if(!n&&2===z)a=s.add(b.x,b.y,f-g*e,g+f*e,0,0,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a,a=s.add(b.x,b.y,f+g*e,g-f*e,0,1,q),
0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a;else if(2===l)0.01>Math.abs(a)?(u=-g,v=f):H>G&&(u=(p-f)/a,v=(r-g)/a),H>G&&(e=-e),a=s.add(b.x,b.y,u*e,v*e,0,0,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a,a=s.add(b.x,b.y,-u*e,-v*e,0,1,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a,(!x||!n)&&1===z&&C.add(b.x,b.y);else{x&&(a=s.add(b.x,b.y,r*e,-p*e,0,0,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a,a=s.add(b.x,b.y,-r*e,p*e,0,1,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a);if((!x||!n)&&1===z)d=s.add(b.x,b.y,r*e,-p*e,0,
0,q),C.add(b.x,b.y);e=1;1===l&&(x&&(n&&(!w||0<A))&&C.add(b.x,b.y),c=d=-1);n&&(a=s.add(b.x,b.y,-g*e,f*e,0,0,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a,a=s.add(b.x,b.y,g*e,-f*e,0,1,q),0<=d&&(0<=c&&0<=a)&&t.add(d,c,a),d=c,c=a)}}this.triangleElementsCount+=3*(t.index-E);this.pointConnectorCount+=C.index-F}}};return h}(F)});