// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper dojo/_base/lang ../../core/accessorSupport/decorators ../../core/accessorSupport/PropertyOrigin ./ArcGISMapService ../support/Sublayer ../support/sublayerUtils ../../core/Collection ../../core/CollectionFlattener ../support/ExportImageParameters ../../geometry/support/scaleUtils".split(" "),function(z,A,t,d,k,c,l,u,h,m,n,v,w,x){function p(c,b,a){var e=[],s={};c.forEach(function(g){var f=new h;f.read(g,
b);a&&-1===a.indexOf(f.id)&&(f.visible=!1);s[f.id]=f;null!=g.parentLayerId&&-1!==g.parentLayerId?(g=s[g.parentLayerId],g.sublayers||(g.sublayers=[]),g.sublayers.unshift(f)):e.unshift(f)});return e}function q(c,b){var a=b.get(c.id);a?(k.mixin(c.__accessor__.store._values,a.__accessor__.store._values),a.sublayers&&(c.sublayers=a.sublayers.map(function(a){return q(a,b)}))):c.sublayers&&c.sublayers.forEach(function(a){return q(a,b)});return c}return function(r){function b(){var a=this;r.call(this);this.allSublayers=
new v({root:this,rootCollectionNames:["sublayers"],getChildrenFunction:function(a){return a.sublayers}});this.dpi=96;this.gdbVersion=null;this.imageFormat="png24";this.imageTransparency=!0;this.loaded=!1;this.sublayers=null;this.watch("sublayers",function(e,b){b&&(b.forEach(function(a){a.parent=null;a.layer=null}),a._sublayersHandles.forEach(function(a){return a.remove()}),a._sublayersHandles=null);e&&(e.forEach(function(e){e.parent=a;e.layer=a}),a._sublayersHandles=[e.on("after-add",function(e){e=
e.item;e.parent=a;e.layer=a}),e.on("after-remove",function(a){a=a.item;a.parent=null;a.layer=null})])},!0)}t(b,r);b.prototype.readCapabilities=function(a,e){var b=a&&a.split(",").map(function(a){return a.trim()}),b=b||[];e.supportsDynamicLayers&&b.push("DynamicLayers");return b};b.prototype.readImageFormat=function(a,e){var b=e.supportedImageFormatTypes;return b&&-1<b.indexOf("PNG32")?"png32":"png24"};b.prototype.readServiceSublayers=function(a,e,b){return p(e.layers,b)};b.prototype.readSublayersFromItemOrWebMap=
function(a,e,b){return!e.layers&&e.visibleLayers?e.visibleLayers.map(function(a){return{id:a}}):p(e.layers,b,e.visibleLayers)};b.prototype.readSublayers=function(a,b,c){a=p(b.layers,c);this._updateSublayersForOrigin(l.OriginId.PORTAL_ITEM,a);this._updateSublayersForOrigin(l.OriginId.WEB_MAP,a);this._updateSublayersForOrigin(l.OriginId.WEB_SCENE,a);return a};b.prototype.writeSublayers=function(a,b,c){a=a.flatten(function(a){return(a=a.sublayers)&&a.toArray().reverse()}).toArray().reverse();var g=this.serviceSublayers.flatten(function(a){return(a=
a.sublayers)&&a.toArray().reverse()}).toArray().reduce(function(a,b){return a.set(b.id,b)},new Map),f=!1,d=!0;this.capabilities&&-1!==this.capabilities.indexOf("DynamicLayers")?(f=m.isExportDynamic(a,this.serviceSublayers,this),d=!f&&m.sameStructureAsService(a,this.serviceSublayers)):d=m.sameStructureAsService(a,this.serviceSublayers);b.layers=[];a.forEach(function(a){var h=g.get(a.id),h=k.mixin({writeAsDynamic:f,writeOverridesOnly:d,serviceSublayer:h},c);a=a.write({},h);(!d||d&&1<Object.keys(a).length)&&
b.layers.push(a)});b.visibleLayers=a.filter(function(a){return a.visible}).map(function(a){return a.id})};b.prototype.findSublayerById=function(a){return this.allSublayers.find(function(b){return b.id===a})};b.prototype.createServiceSublayers=function(){return this.serviceSublayers.map(function(a){return a.clone()})};b.prototype.createExportImageParameters=function(a){var b=a.extent,c=a.width,d=a.height,f=a.exportImageParameters;b&&10<=this.version&&(b=a.extent.clone().shiftCentralMeridian());f||
(f=new w({layer:this,scale:x.getScale({extent:b,width:c})}));var y=f.toJSON();a.exportImageParameters||(f.layer=null,f.destroy());a=null==a.rotation||0===a.rotation||10.3>this.version?{}:{rotation:-a.rotation};f=b&&b.spatialReference;f=f.wkid||JSON.stringify(f.toJSON());return k.mixin({bbox:b&&b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,bboxSR:f,imageSR:f,size:c+","+d},a,y)};b.prototype._updateSublayersForOrigin=function(a,b){var c=this.__accessor__.store;if(c.has("sublayers",a)){var d=c.get("sublayers",
a).flatten(function(a){return a.sublayers});if(d.every(function(a){return!a.__accessor__.store._values.hasOwnProperty("minScale")})){var f=d.reduce(function(a,b){return a.set(b.id,b)},new Map),d=b.map(function(a){return q(a.clone(),f)});c.set("sublayers",new (n.ofType(h))(d),a)}}};d([c.property({readOnly:!0})],b.prototype,"allSublayers",void 0);d([c.property({readOnly:!0})],b.prototype,"capabilities",void 0);d([c.read("service","capabilities",["supportsDynamicLayers"])],b.prototype,"readCapabilities",
null);d([c.property()],b.prototype,"dpi",void 0);d([c.property()],b.prototype,"gdbVersion",void 0);d([c.property()],b.prototype,"imageFormat",void 0);d([c.read("imageFormat",["supportedImageFormatTypes"])],b.prototype,"readImageFormat",null);d([c.property()],b.prototype,"imageTransparency",void 0);d([c.property()],b.prototype,"loaded",void 0);d([c.property({readOnly:!0,type:n.ofType(h)})],b.prototype,"serviceSublayers",void 0);d([c.read("service","serviceSublayers",["layers"])],b.prototype,"readServiceSublayers",
null);d([c.property({type:n.ofType(h)})],b.prototype,"sublayers",void 0);d([c.read(["web-map","web-scene","portal-item"],"sublayers",["layers","visibleLayers"])],b.prototype,"readSublayersFromItemOrWebMap",null);d([c.read("service","sublayers",["layers"])],b.prototype,"readSublayers",null);d([c.write(["web-map","web-scene","portal-item"],"sublayers")],b.prototype,"writeSublayers",null);return b=d([c.subclass("esri.layers.mixins.ArcGISDynamicMapService")],b)}(c.declared(u))});