// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../Layer ../../core/MultiOriginJSONSupport ./ArcGISService ./OperationalLayer ./PortalLayer ../../core/Error ../../core/urlUtils ../../core/promiseUtils ../../core/requireUtils ../../request dojo/_base/lang dojo/io-query ../../geometry/SpatialReference ../../geometry/Extent ../support/arcgisLayerUrl".split(" "),function(q,A,r,d,b,s,t,u,v,w,x,f,m,y,h,z,k,l,n,g){return function(p){function a(){p.apply(this,
arguments);this.fullExtent=this.spatialReference=this.blendMode=null;this.version={major:Number.NaN,minor:Number.NaN,versionString:""};this.copyright=null;this.sublayerTitleMode="item-title";this.layerId=this.title=null}r(a,p);a.prototype.readSpatialReference=function(c,e){return this._readSpatialReference(e)};a.prototype._readSpatialReference=function(c){if(null!=c.spatialReference)return l.fromJSON(c.spatialReference);c=c.store;c=(c=c.indexCRS||c.geographicCRS)&&parseInt(c.substring(c.lastIndexOf("/")+
1,c.length),10);return null!=c?new l(c):null};a.prototype.readFullExtent=function(c,e){var a=e.store,b=this._readSpatialReference(e);return null==b||null==a||null==a.extent?null:new n({xmin:a.extent[0],ymin:a.extent[1],xmax:a.extent[2],ymax:a.extent[3],spatialReference:b})};a.prototype.readVersion=function(c,e){var a=e.store,b=null!=a.version?a.version.toString():"",a={major:Number.NaN,minor:Number.NaN,versionString:b},b=b.split(".");2<=b.length&&(a.major=parseInt(b[0],10),a.minor=parseInt(b[1],10));
return a};a.prototype.readCopyright=function(c,a){return a.copyrightText};a.prototype.readTitlePortalItem=function(c,a){return"item-title"!==this.sublayerTitleMode?void 0:c};a.prototype.readTitleService=function(c,a){var b=this.portalItem&&this.portalItem.title;if("item-title"===this.sublayerTitleMode)return g.titleFromUrlAndName(this.url,a.name);var d=a.name||g.parse(this.url).title;"item-title-and-service-name"===this.sublayerTitleMode&&b&&(d=b+" - "+d);return g.cleanTitle(d)};a.prototype.readLayerId=
function(c,a){return a.id};Object.defineProperty(a.prototype,"url",{set:function(c){var a=f.urlToObject(c),b=g.parse(a.path);b&&null!=b.sublayer&&(this.layerId=b.sublayer,a=k.objectToQuery(a.query),c=b.url.path,a&&(c=c+"?"+a));for(;"/"===c[c.length-1];)c=c.slice(0,-1);this._set("url",c)},enumerable:!0,configurable:!0});a.prototype.writeUrl=function(c,a){c&&f.isProtocolRelative(c)&&(c="https:"+c);var b=f.urlToObject(c);null!=this.layerId&&b?(a.url=b.path+"/layers/"+this.layerId,b.query&&Object.keys(b.query)&&
(a.url+="?"+k.objectToQuery(b.query))):c&&(a.url=c)};Object.defineProperty(a.prototype,"parsedUrl",{get:function(){var c=this._get("url");if(!c)return null;c=f.urlToObject(c);null!=this.layerId&&g.match.test(c.path)&&(c.path=c.path+"/layers/"+this.layerId);return c},enumerable:!0,configurable:!0});a.prototype._addUrlToken=function(c){var a=z.mixin({},this.parsedUrl.query,{token:this.token}),a=k.objectToQuery(a);return c+(a?"?"+a:"")};a.prototype.readRootNode=function(a,b){return b.store.rootNode};
a.prototype._verifyRootNodeAndUpdateExtent=function(){var a=this;return this._fetchRootNode().then(function(b){return a._updateExtentFromRootNode(b)})};a.prototype._updateExtentFromRootNode=function(a){if(!(null==this.fullExtent||this.fullExtent.hasZ)&&null!=a&&Array.isArray(a.mbs)&&4===a.mbs.length){var b=a.mbs[2];a=a.mbs[3];this.fullExtent.zmin=b-a;this.fullExtent.zmax=b+a}};a.prototype._fetchRootNode=function(){if(!this.rootNode)return m.resolve();var a=f.join(this.parsedUrl.path,this.rootNode);
return h(this._addUrlToken(a),{query:{f:"json"},responseType:"json"}).then(function(a){return a.data}).otherwise(function(b){throw new x("sceneservice:root-node-missing","Root node missing.",{error:b,url:a});})};a.prototype._fetchService=function(){var a=this;return(null==this.layerId&&/SceneServer\/*$/i.test(this.url)?this._fetchFirstLayerId().then(function(b){null!=b&&(a.layerId=b)}):m.resolve()).then(function(){return a._fetchServiceLayer()})};a.prototype._fetchFirstLayerId=function(){return h(this._addUrlToken(this.url),
{query:{f:"json"},callbackParamName:"callback",responseType:"json"}).then(function(a){if(a.data&&Array.isArray(a.data.layers)&&0<a.data.layers.length)return a.data.layers[0].id})};a.prototype._fetchServiceLayer=function(){var a=this;return h(this._addUrlToken(this.parsedUrl.path),{query:{f:"json"},responseType:"json"}).then(function(b){b.ssl&&(a.url=a.url.replace(/^http:/i,"https:"));b=b.data;a.read(b,{origin:"service",url:a.parsedUrl});a._validateLayer(b)})};a.prototype._validateLayer=function(a){};
a.prototype.createGraphicsController=function(a){var b=this;a.layer=this;a.addUrlToken=function(a){return b._addUrlToken(a)};var d=y.when(q,"../graphics/controllers/I3SOnDemandController").then(function(b){return new b(a)});d.then(function(a){b.emit("graphics-controller-create",{graphicsController:a})});return d};d([b.shared({id:{json:{origins:{service:{readable:!1},portalItem:{readable:!1}}}}})],a.prototype,"properties",void 0);d([b.property({type:l})],a.prototype,"spatialReference",void 0);d([b.read("spatialReference",
["spatialReference","store.indexCRS","store.geographicCRS"])],a.prototype,"readSpatialReference",null);d([b.property({type:n})],a.prototype,"fullExtent",void 0);d([b.read("fullExtent",["store.extent","spatialReference","store.indexCRS","store.geographicCRS"])],a.prototype,"readFullExtent",null);d([b.property({readOnly:!0})],a.prototype,"version",void 0);d([b.read("version",["store.version"])],a.prototype,"readVersion",null);d([b.property({type:String})],a.prototype,"copyright",void 0);d([b.read("copyright",
["copyrightText"])],a.prototype,"readCopyright",null);d([b.property({type:String})],a.prototype,"sublayerTitleMode",void 0);d([b.property({type:String})],a.prototype,"title",void 0);d([b.read("portal-item","title")],a.prototype,"readTitlePortalItem",null);d([b.read("service","title",["name"])],a.prototype,"readTitleService",null);d([b.property({type:Number})],a.prototype,"layerId",void 0);d([b.read("service","layerId",["id"])],a.prototype,"readLayerId",null);d([b.property()],a.prototype,"url",null);
d([b.write("url")],a.prototype,"writeUrl",null);d([b.property({dependsOn:["layerId"]})],a.prototype,"parsedUrl",null);d([b.property()],a.prototype,"store",void 0);d([b.property({type:String})],a.prototype,"rootNode",void 0);d([b.read("rootNode",["store.rootNode"])],a.prototype,"readRootNode",null);return a=d([b.subclass("esri.layers.mixins.SceneService")],a)}(b.declared(s,u,t,v,w))});