//>>built
define("dgrid1/Keyboard","dojo/_base/declare dojo/aspect dojo/dom-class dojo/on dojo/_base/lang dojo/has ./util/misc dojo/_base/sniff".split(" "),function(s,p,t,q,r,C,D){function u(a){a.preventDefault()}var E={checkbox:1,radio:1,button:1},v=/\bdgrid-cell\b/,w=/\bdgrid-row\b/,d=s(null,{pageSkip:10,tabIndex:0,keyMap:null,headerKeyMap:null,postMixInProperties:function(){this.inherited(arguments);this.keyMap||(this.keyMap=r.mixin({},d.defaultKeyMap));this.headerKeyMap||(this.headerKeyMap=r.mixin({},d.defaultHeaderKeyMap))},
postCreate:function(){function a(a){var b=a.target;return b.type&&(!E[b.type]||32===a.keyCode)}function c(c){function e(){b._focusedHeaderNode&&(b._focusedHeaderNode.tabIndex=-1);if(b.showHeader){if(d)for(var a=b.headerNode.getElementsByTagName("th"),c=0,f;f=a[c];++c){if(k.test(f.className)){b._focusedHeaderNode=l=f;break}}else b._focusedHeaderNode=l=b.headerNode;l&&(l.tabIndex=b.tabIndex)}}function g(){var a=b._focusedNode||l;if(!k.test(a.className)||!c.contains(a)){for(var e=c.getElementsByTagName("*"),
d=0,g;g=e[d];++d)if(k.test(g.className)){a=b._focusedNode=g;break}l.tabIndex=-1;a.tabIndex=b.tabIndex}}var d=b.cellNavigation,k=d?v:w,m=c===b.headerNode,l=c;m?(e(),p.after(b,"renderHeader",e,!0)):(p.after(b,"renderArray",g,!0),p.after(b,"_onNotification",function(a,b){0===b.totalLength?c.tabIndex=0:1===b.totalLength&&"add"===b.type&&g()},!0));b._listeners.push(q(c,"mousedown",function(c){a(c)||b._focusOnNode(c.target,m,c)}));b._listeners.push(q(c,"keydown",function(c){if(!c.metaKey&&!c.altKey){var f=
b[m?"headerKeyMap":"keyMap"][c.keyCode];f&&!a(c)&&f.call(b,c)}}))}this.inherited(arguments);var b=this;this.tabableHeader&&(c(this.headerNode),q(this.headerNode,"dgrid-cellfocusin",function(){b.scrollTo({x:this.scrollLeft})}));c(this.contentNode);this._debouncedEnsureScroll=D.debounce(this._ensureScroll,this)},removeRow:function(a){if(!this._focusedNode)return this.inherited(arguments);var c=this,b=document.activeElement===this._focusedNode,f=this[this.cellNavigation?"cell":"row"](this._focusedNode),
e=f.row||f,d;a=a.element||a;if(a===e.element){d=this.down(e,!0);if(!d||d.element===a)d=this.up(e,!0);this._removedFocus={active:b,rowId:e.id,columnId:f.column&&f.column.id,siblingId:!d||d.element===a?void 0:d.id};setTimeout(function(){c._removedFocus&&c._restoreFocus(e.id)},0);this._focusedNode=null}this.inherited(arguments)},insertRow:function(){var a=this.inherited(arguments);this._removedFocus&&!this._removedFocus.wait&&this._restoreFocus(a);return a},_restoreFocus:function(a){var c=this._removedFocus,
b;if((a=(a=a&&this.row(a))&&a.element&&a.id===c.rowId?a:"undefined"!==typeof c.siblingId&&this.row(c.siblingId))&&a.element){if(!a.element.parentNode.parentNode){c.wait=!0;return}"undefined"!==typeof c.columnId&&(b=this.cell(a,c.columnId))&&b.element&&(a=b);c.active&&0!==a.element.offsetHeight?this._focusOnNode(a,!1,null):(t.add(a.element,"dgrid-focus"),a.element.tabIndex=this.tabIndex,this._focusedNode=a.element)}delete this._removedFocus},addKeyHandler:function(a,c,b){return p.after(this[b?"headerKeyMap":
"keyMap"],a,c,!0)},_ensureRowScroll:function(a){var c=this.getScrollPosition().y;c>a.offsetTop?this.scrollTo({y:a.offsetTop}):c+this.contentNode.offsetHeight<a.offsetTop+a.offsetHeight&&this.scrollTo({y:a.offsetTop-this.contentNode.offsetHeight+a.offsetHeight})},_ensureColumnScroll:function(a){var c=this.getScrollPosition().x,b=a.offsetLeft;if(c>b)this.scrollTo({x:b});else{var f=this.bodyNode.clientWidth;a=a.offsetWidth;var d=b+a;c+f<d&&this.scrollTo({x:f>a?d-f:b})}},_ensureScroll:function(a,c){this.cellNavigation&&
((this.columnSets||1<this.subRows.length)&&!c)&&this._ensureRowScroll(a.row.element);this.bodyNode.clientWidth<this.contentNode.offsetWidth&&this._ensureColumnScroll(a.element)},_focusOnNode:function(a,c,b){var d="_focused"+(c?"Header":"")+"Node",e=this[d],g=this.cellNavigation?"cell":"row",h=this[g](a),k,m,l,p,n;if(a=h&&h.element){if(this.cellNavigation){k=a.getElementsByTagName("input");n=0;for(l=k.length;n<l;n++)if(m=k[n],(-1!==m.tabIndex||"_dgridLastValue"in m)&&!m.disabled){m.focus();p=!0;break}}null!==
b&&(b=r.mixin({grid:this},b),b.type&&(b.parentType=b.type),b.bubbles||(b.bubbles=!0));e&&(t.remove(e,"dgrid-focus"),e.removeAttribute("tabindex"),b&&(b[g]=this[g](e),q.emit(e,"dgrid-cellfocusout",b)));e=this[d]=a;b&&(b[g]=h);d=this.cellNavigation?v:w;!p&&d.test(a.className)&&(a.tabIndex=this.tabIndex,a.focus());t.add(a,"dgrid-focus");b&&q.emit(e,"dgrid-cellfocusin",b);this._debouncedEnsureScroll(h,c)}},focusHeader:function(a){this._focusOnNode(a||this._focusedHeaderNode,!0)},focus:function(a){(a=
a||this._focusedNode)?this._focusOnNode(a,!1):(this._removedFocus&&(this._removedFocus.active=!0),this.contentNode.focus())}}),n=d.moveFocusVertical=function(a,c){var b=this.cellNavigation,d=this[b?"cell":"row"](a),d=b&&d.column.id,e=this.down(this._focusedNode,c,!0);b&&(e=this.cell(e,d));this._focusOnNode(e,!1,a);a.preventDefault()};s=d.moveFocusUp=function(a){n.call(this,a,-1)};var F=d.moveFocusDown=function(a){n.call(this,a,1)},G=d.moveFocusPageUp=function(a){n.call(this,a,-this.pageSkip)},H=d.moveFocusPageDown=
function(a){n.call(this,a,this.pageSkip)},x=d.moveFocusHorizontal=function(a,c){if(this.cellNavigation){var b=!this.row(a);this._focusOnNode(this.right(this["_focused"+(b?"Header":"")+"Node"],c),b,a);a.preventDefault()}},y=d.moveFocusLeft=function(a){x.call(this,a,-1)},z=d.moveFocusRight=function(a){x.call(this,a,1)},A=d.moveHeaderFocusEnd=function(a,c){var b;this.cellNavigation&&(b=this.headerNode.getElementsByTagName("th"),this._focusOnNode(b[c?0:b.length-1],!0,a));a.preventDefault()},I=d.moveHeaderFocusHome=
function(a){A.call(this,a,!0)},B=d.moveFocusEnd=function(a,c){var b=this.cellNavigation,d=this.contentNode,e=d.scrollTop+(c?0:d.scrollHeight),d=d[c?"firstChild":"lastChild"],g=-1<d.className.indexOf("dgrid-preload"),h=g?d[(c?"next":"previous")+"Sibling"]:d,k;a.preventDefault();this.scrollTo({y:e});if(g){for(;h&&0>h.className.indexOf("dgrid-row");)h=h[(c?"next":"previous")+"Sibling"];if(!h)return}!g||1>d.offsetHeight?(b&&(h=this.cell(h,this.cell(a).column.id)),this._focusOnNode(h,!1,a)):(C("dom-addeventlistener")||
(a=r.mixin({},a)),k=p.after(this,"renderArray",function(d){var e=d[c?0:d.length-1];b&&(e=this.cell(e,this.cell(a).column.id));this._focusOnNode(e,!1,a);k.remove();return d}))},J=d.moveFocusHome=function(a){B.call(this,a,!0)};d.defaultKeyMap={32:u,33:G,34:H,35:B,36:J,37:y,38:s,39:z,40:F};d.defaultHeaderKeyMap={32:u,35:A,36:I,37:y,39:z};return d});