//>>built
define("dgrid1/List","dojo/_base/declare dojo/dom-construct dojo/dom-class dojo/on dojo/has ./util/misc dojo/_base/sniff".split(" "),function(t,k,e,n,d,m){function u(a,b){a.className="dgrid-scrollbar-measure";document.body.appendChild(a);var c=a["offset"+b]-a["client"+b];a.className="";a.parentNode&&document.body.removeChild(a);return c}function p(a){e.replace(this.domNode,a,this._class||"");this._class=a}function v(){return this._class}var q=[];d("mozilla")&&q.push("has-mozilla");d("touch")&&q.push("has-touch");
e.add(document.documentElement,q);d.add("pointer",function(a){return"PointerEvent"in a?"pointer":"MSPointerEvent"in a?"MSPointer":!1});var l,r;d.add("dom-scrollbar-width",function(a,b,c){return u(c,"Width")});d.add("dom-scrollbar-height",function(a,b,c){return u(c,"Height")});d.add("dom-rtl-scrollbar-left",function(a,b,c){a=document.createElement("div");c.className="dgrid-scrollbar-measure";c.setAttribute("dir","rtl");c.appendChild(a);document.body.appendChild(c);b=!!d("ie")||!!d("trident")||/\bEdge\//.test(navigator.userAgent)||
a.offsetLeft>=d("dom-scrollbar-width");c.className="";c.parentNode&&document.body.removeChild(c);k.destroy(a);c.removeAttribute("dir");return b});var x=0,y=function(){this._started&&this.resize()},s=t(null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,addUiClasses:!0,highlightDuration:250,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=function(){c.removeRow(this.element)};b&&(this.srcNodeRef=
b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,b){var c=this.domNode=b||document.createElement("div"),d;a&&(this.params=a,t.safeMixin(this,a),d=a["class"]||a.className||c.className);this.sort=this.sort||[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||s.autoIdPrefix+x++;this.buildRendering();d&&p.call(this,d);this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&
this.startup()},buildRendering:function(){var a=this.domNode,b=this.addUiClasses,c=this,w,f,h;h=this.isRTL="rtl"===(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";a.setAttribute("role","grid");e.add(a,"dgrid dgrid-"+this.listType+(b?" ui-widget":""));w=this.headerNode=k.create("div",{className:"dgrid-header dgrid-header-row"+(b?" ui-widget-header":"")+(this.showHeader?"":" dgrid-header-hidden")},a);f=this.bodyNode=k.create("div",{className:"dgrid-scroller"},
a);d("ff")&&(f.tabIndex=-1);this.headerScrollNode=k.create("div",{className:"dgrid-header dgrid-header-scroll dgrid-scrollbar-width"+(b?" ui-widget-header":"")},a);this.footerNode=k.create("div",{className:"dgrid-footer"+(this.showFooter?"":" dgrid-footer-hidden")},a);h&&(a.className+=" dgrid-rtl"+(d("dom-rtl-scrollbar-left")?" dgrid-rtl-swap":""));n(f,"scroll",function(b){c.showHeader&&(w.scrollLeft=b.scrollLeft||f.scrollLeft);b.stopPropagation();n.emit(a,"scroll",{scrollTarget:f})});this.configStructure();
this.renderHeader();this.contentNode=this.touchNode=k.create("div",{className:"dgrid-content"+(b?" ui-widget-content":"")},this.bodyNode);this._listeners.push(this._resizeHandle=n(window,"resize",m.throttleDelayed(y,this)))},postCreate:function(){},startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",this.sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.footerNode,b=this.showFooter?b.offsetHeight:0;this.headerScrollNode.style.height=
a.style.marginTop=this.headerNode.offsetHeight+"px";a.style.marginBottom=b+"px";l||(l=d("dom-scrollbar-width"),r=d("dom-scrollbar-height"),d("ie")&&(l++,r++),m.addCssRule(".dgrid-scrollbar-width","width: "+l+"px"),m.addCssRule(".dgrid-scrollbar-height","height: "+r+"px"),17!==l&&(m.addCssRule(".dgrid-header-row","right: "+l+"px"),m.addCssRule(".dgrid-rtl-swap .dgrid-header-row","left: "+l+"px")))},addCssRule:function(a,b){var c=m.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(c);return c},
on:function(a,b){var c=n(this.domNode,a,b);d("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){for(var a in this._rowIdToObject)if(this._rowIdToObject[a]!==this.columns){var b=document.getElementById(a);b&&this.removeRow(b,!0)}},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();this._listeners=null}this._started=!1;this.cleanup();k.destroy(this.domNode)},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoRowId=
0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},highlightRow:function(a,b){var c="dgrid-highlight"+(this.addUiClasses?" ui-state-highlight":"");a=a.element||a;e.add(a,c);setTimeout(function(){e.remove(a,c)},b||this.highlightDuration)},adjustRowIndices:function(a){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(this.maintainOddEven&&e.contains(a,"dgrid-row")&&e.replace(a,1===b%2?"dgrid-row-odd":"dgrid-row-even",0===b%2?"dgrid-row-odd":"dgrid-row-even"),a.rowIndex=b++);while((a=a.nextSibling)&&
a.rowIndex!==b)}},renderArray:function(a,b,c){c=c||{};var d=c.start||0,f=document.createDocumentFragment(),h=[],g=0,e=a.length;b||(this._lastCollection=a);for(;g<e;)h[g]=this.insertRow(a[g],f,null,d++,c),g++;if((a=b?b.parentNode:this.contentNode)&&a.parentNode&&(a!==this.contentNode||e))a.insertBefore(f,b||null),e&&this.adjustRowIndices(h[e-1]);return h},renderHeader:function(){},_autoRowId:0,insertRow:function(a,b,c,d,f){var h=this.id+"-row-"+(this.collection&&this.collection.getIdentity?this.collection.getIdentity(a):
this._autoRowId++),g=document.getElementById(h),e=g&&g.previousSibling;g&&(g===c&&(c=(c.connected||c).nextSibling),this.removeRow(g,!1,f));g=this.renderRow(a,f);g.className=(g.className||"")+" dgrid-row "+(1===d%2?"dgrid-row-odd":"dgrid-row-even")+(this.addUiClasses?" ui-state-default":"");this._rowIdToObject[g.id=h]=a;b.insertBefore(g,c||null);g.rowIndex=d;e&&e.rowIndex!==g.rowIndex-1&&this.adjustRowIndices(e);return g},renderRow:function(a){var b=document.createElement("div");b.appendChild(document.createTextNode(a));
return b},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||k.destroy(a)},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!==this.domNode)}else return"object"===typeof a?b=this.collection.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+
"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,d){var f,e;e=f=a.element;b=b||1;do if(a=f[0>b?"previousSibling":"nextSibling"]){do if((f=a)&&-1<(f.className+" ").indexOf(c+" ")){e=f;b+=0>b?1:-1;break}while(a=(!d||!f.hidden)&&f[0>b?"lastChild":"firstChild"])}else if(f=f.parentNode,!f||f===this.bodyNode||f===this.headerNode)break;while(b);return e},up:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||
(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,
a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:v,_setClass:p,_getClassName:v,_setClassName:p,_setSort:function(a,b){this.sort="string"!==typeof a?a:[{property:a,descending:b}];this._applySort()},_applySort:function(){this.refresh();if(this._lastCollection){var a=this.sort;if(a&&0<a.length){var b=a[0].property,c=!!a[0].descending;this._lastCollection.sort(function(a,d){var e=a[b],g=
d[b];void 0===e&&(e="");void 0===g&&(g="");return e===g?0:e>g!==c?1:-1})}this.renderArray(this._lastCollection)}},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;e.toggle(b,"dgrid-header-hidden",!a);this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},_setShowFooter:function(a){this.showFooter=a;e.toggle(this.footerNode,"dgrid-footer-hidden",!a);this.resize()}});s.autoIdPrefix="dgrid_";return s});