// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["dojo/_base/lang","./Property","./PropertyNotifier","./merge"],function(w,m,x,r){var n=function(a){return Object.create(void 0===a?null:a)},y=/^_([a-zA-Z0-9]+)(Getter|Setter|Reader)$/,z=/^_(set|get)([a-zA-Z0-9]+)Attr$/,l=function(a){return a._meta?a:a.constructor},p=Object.prototype.hasOwnProperty,B=function(a){if(!(a&&null!=l(a)._meta))return null;var c=k(a),d=c.mixin;if(d)return d;var g=a.prototype,d=p.call(g,"classMetadata")?g.classMetadata:n(),d=c.mixin={declaredClass:g.declaredClass,
properties:d.properties?r(n(),d.properties):n(),reader:d.reader?r(n(),d.reader):n(),notifiers:[]},e=d.properties;Object.getOwnPropertyNames(g).forEach(function(b){var c=g[b],a,d,k;if(a=y.exec(b))d=a[1],k=a[2];else if(a=z.exec(b))d=a[2][0].toLowerCase()+a[2].substr(1),k=a[1]+"ter";d&&k&&(b=d.split(".")[0],e[b]||(e[b]={}),b=e[b],b[k.toLowerCase()]=c)});A(a);Object.getOwnPropertyNames(e).forEach(function(b){t(g,b)&&(e[b].value=g[b])});d.properties=Object.getOwnPropertyNames(e).reduce(function(b,a){b[a]=
new m(a,e[a]);return b},{});return d},A=function(a){var c=k(a).mixin,d=c.properties,g=n(),e,b,f,h,l;if(d){for(b in d)if(e=d[b].dependsOn)for(h=0;f=e[h];h++)g[f]?-1===g[f].indexOf(b)&&g[f].push(b):g[f]=[b];h=[];for(b in g){e=[];l=n();for(h.push(b);h.length;)f=h.shift(),l[f]||(l[f]=!0,e.push(f),(f=g[f])&&Array.prototype.push.apply(h,f));e.shift();-1<b.indexOf(".")&&(c.notifiers||(c.notifiers=[]),c.notifiers.push(new x(b,e)),b=b.split(".")[0]);d[b]?d[b].chain=e:(f=q(a,b))?k(f).mixin.properties[b]||(k(f).mixin.properties[b]=
new m(b,{value:s(a,b),chain:e})):c.properties[b]=new m(b,{chain:e})}}},k=function(a){if(!(a&&null!=l(a)._meta))return null;var c=l(a),d=c._esriMeta;if(d)return d;var d=c._esriMeta={},g=l(a)._meta.bases;a=d.mixins=[];for(var e,b=g.length-1;0<=b;b--)(e=B(g[b]))&&a.unshift(e);var g=d.classMetadata={declaredClass:c.prototype.declaredClass,notifiers:[],properties:{},reader:{}},f=g.properties,h,b;for(b=a.length-1;0<=b;b--){e=a[b];for(h in e.properties)u(c,h),f[h]?f[h].mixIn(e.properties[h]):(f[h]=new m(h,
e.properties[h]),!f[h].hasOwnProperty("value")&&q(c,h)&&(f[h].value=s(c,h)),Object.defineProperty(c.prototype,h,f[h].getDescriptor()));g.notifiers=g.notifiers.concat(d.mixins[b].notifiers);g.reader=r(g.reader,d.mixins[b].reader)}return d},v=function(a,c){if(a){var d=Object.getOwnPropertyDescriptor(a.prototype,c);return d?d.value:a.prototype[c]}},s=function(a,c){if(p.call(a,c))return a[c];var d=q(a,c);return v(d,c)},t=function(a,c){var d;return p.call(a,c)&&(!(d=Object.getOwnPropertyDescriptor(a,c))||
p.call(d,"value"))},q=function(a,c){for(var d=l(a)._meta.bases,g,e,b=0,f=d.length;b<f;b++)if(g=d[b],e=(e=k(g))&&e.mixin.properties[c],t(g.prototype,c)||e&&p.call(e,"value"))return g;return null},u=function(a,c){var d=l(a),g=k(d).classMetadata.properties,e=q(d,c)||d,b=e?k(e).mixin.properties:{},f=b[c];e&&!f&&(f=b[c]=new m(c,{value:v(e,c)}),k(e).mixin.properties[c]=new m(c,f),b=k(e).classMetadata.properties,b[c]?b[c].value=f.value:(b[c]=f,Object.defineProperty(e.prototype,c,f.getDescriptor())));d!==
e&&(g[c]?g[c].value=f.value:(g[c]=new m(c,f),Object.defineProperty(d.prototype,c,f.getDescriptor())));return f};return w.mixin(function(a){return k(a)},{getProperties:function(a){return k(a).classMetadata.properties},isIntrospected:function(a){return null!=l(a)._esriMeta},getPropertyOwnerValue:s,getPropertyOwner:q,installPropertyNotifiers:function(a){var c=k(a).classMetadata.notifiers;return c?c.map(function(a){return a.install(this)},a):[]},defineProperty:u})});