// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../geometry/Extent ../../../../geometry/support/webMercatorUtils ../../../../geometry/support/spatialReferenceUtils ../DisplayObject ./gfxUtils".split(" "),function(x,y,n,p,k,v,w,f){var q=new Set,h=[];return function(l){function b(){l.call(this);this.visible=!0}n(b,l);Object.defineProperty(b.prototype,"graphic",{get:function(){return this._graphic},set:function(a){this._geometry=(this._graphic=a)&&a.geometry||null;this._projected=
null;this.requestRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"geometry",{get:function(){return this._geometry},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isPolygonMarkerSymbol",{get:function(){var a=this.renderingInfo.symbol.type,g=this.geometry;return g&&"polygon"===g.type&&("simple-marker-symbol"===a||"picture-marker-symbol"===a||"text-symbol"===a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"renderingInfo",{get:function(){return this._renderingInfo},
set:function(a){this._renderingInfo=a;this.requestRender()},enumerable:!0,configurable:!0});b.prototype.attach=function(a){return!0};b.prototype.detach=function(){this._removeShape();this._drawInfo=this._projected=null};b.prototype.render=function(a){var g=a.surface,d=a.state,c=a.projector,m=this.visible&&this._projectGeometry(this.geometry,a.state.spatialReference);a=this._getScreenOffsets([],a.state);f.isShapeInvalid(this.renderingInfo.symbol,this._shape)&&this._removeShape();if(a.length){var e=
this._shape,b=m.type;if(!e||this._showRedraw(a,d))"point"===b?(e=f.drawPoint(c,g,m,e,this.renderingInfo,d.rotation,a),f.stylePoint(e,this.renderingInfo)):"multipoint"===b?(e=f.drawMarkers(c,g,m,e,this.renderingInfo,d.rotation,a),f.styleMarkers(e,this.renderingInfo)):(e=f.drawShape(c,g,m,e,a),f.styleShape(e,this.renderingInfo)),this._shape=e,e.getNode().gfxObject=this}else this._removeShape()};b.prototype._getScreenOffsets=function(a,g){var d=g.clippedExtent,c=this._projected.outExtent,b=g.spatialReference;
a.length=0;if(!c)return a;if(b.isWrappable){var b=v.getInfo(b),e=c.cache._partwise,d=d._getParts(b);h.length=0;if(e&&e.length)for(c=0;c<e.length;c++)h.push.apply(h,e[c]._getParts(b));else h.push.apply(h,c._getParts(b));c=g.worldScreenWidth;a.length=0;q.clear();b=0;for(e=h.length;b<e;b++)for(var f=h[b],k=f.extent,f=f.frameIds,l=f.length,r=0,n=d.length;r<n;r++){var u=d[r];if(u.extent.intersects(k))for(var s=0,p=l;s<p;s++){var t=(u.frameIds[0]-f[s])*c;q.has(t)||(a.push(t),q.add(t))}}a.sort()}else d.intersects(c)&&
a.push(0);return a};b.prototype._projectGeometry=function(a,b){var d=this._projected,c=this.isPolygonMarkerSymbol?a.centroid:a;if(d&&d.inGeometry===c&&d.outSpatialReference===b)return d.outGeometry;c&&c.spatialReference.equals(b)?this._projected={inGeometry:c,outGeometry:c,outSpatialReference:b,outExtent:this._getExtent(c)}:k.canProject(c,b)?this._projected={inGeometry:c,outGeometry:k.project(c,b),outSpatialReference:b,outExtent:this._getExtent(c)}:this._projected={inGeometry:c,outGeometry:null,outSpatialReference:b,
outExtent:null};return this._projected.outGeometry};b.prototype._getExtent=function(a){var b=a.extent;if(!b){var d=b=void 0;"esri.geometry.Point"===a.declaredClass?(b=a.x,d=a.y):"esri.geometry.Multipoint"===a.declaredClass&&(b=a.points[0][0],d=a.points[0][1]);b=new p(b,d,b,d,a.spatialReference)}return b};b.prototype._removeShape=function(){var a=this._shape;a&&(a.removeShape(),a.getNode().gfxObject=null,a.destroy());this._shape=this._drawInfo=null};b.prototype._showRedraw=function(a,b){return!0};
return b}(w)});