// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang dojox/gfx/matrix ../../../../core/screenUtils ../../../../geometry/Polygon ../../../../symbols/SimpleMarkerSymbol ../../../../symbols/support/gfxUtils".split(" "),function(L,q,y,t,s,H,r,u){function v(c,a){a.toRgba?(c[0]=a.r,c[1]=a.g,c[2]=a.b,c[3]=a.a):(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3]);return c}function w(c,a,b){null!=b&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=b);return c}function z(c,a){var b=c.width/c.height,e=1,f=1;isNaN(a)||(1<b?(e=a/c.width,f=a/b/c.height):
(f=a/c.height,e=a*b/c.width));return{xx:e,yy:f}}function A(c,a,b,e,f,h,g){var d=f.symbol,l=c.toScreenPoint(I,b,g[0]);b=l.x;g=l.y;var m;c=[];var p=f.rotationAngle;f=f.size&&f.size[0];var k;"number"===typeof f&&(k=isFinite(f)&&f);var n=k&&isFinite(k)&&!isNaN(k);k=n?s.pt2px(k):NaN;h&&c.push(t.rotategAt(h,l));p&&c.push(t.rotategAt(p,l));h=s.pt2px(d.xoffset);p=s.pt2px(d.yoffset);(0!==h||0!==p)&&c.push(t.translate(h,-p));0!==d.angle&&c.push(t.rotategAt(d.angle,l));if("simple-marker-symbol"===d.type)switch(m=
d.style,h=Math.round,k=n?k:s.pt2px(d.size),n=void 0,m){case r.STYLE_SQUARE:case r.STYLE_CROSS:case r.STYLE_X:case r.STYLE_DIAMOND:n=isNaN(k)?16:0.5*k;m=x(a,e,B(m,b,g,h(b-n),h(b+n),h(g-n),h(g+n)));break;case r.STYLE_PATH:m=x(a,e,d.path);d=m.getBoundingBox();a=z(d,f);(1!==a.xx||1!==a.yy)&&c.push(t.scaleAt(a.xx,a.yy,l.x,l.y));c.push(t.translate(-(d.x+0.5*d.width)+b,-(d.y+0.5*d.height)+g));break;default:n=isNaN(k)?16:0.5*k,m=C(a,e,{cx:b,cy:g,r:n})}else if("picture-marker-symbol"===d.type)m=n?k:s.pt2px(d.width),
k=n?k:s.pt2px(d.height),m=D(a,e,{x:b-0.5*m,y:g-0.5*k,width:m,height:k,src:d.url});else if("text-symbol"===d.type){if(l=d.font&&d.font.clone())l.size=n?k:s.pt2px(l.size);m=E(a,e,{type:"text",text:d.text,x:b,y:g,align:u.getSVGAlign(d),decoration:d.decoration||l&&l.decoration,rotated:d.rotated,kerning:d.kerning});l&&m.setFont(l);a=m.getNode();e=u.getSVGBaseline(d);d=u.getSVGBaselineShift(d);a&&(a.setAttribute("dominant-baseline",e),d&&a.setAttribute("baseline-shift",d))}m.setTransform(t.multiply(c));
return m}function D(c,a,b){return a?a.setShape(b):c.createImage(b)}function C(c,a,b){return a?a.setShape(b):c.createCircle(b)}function x(c,a,b){b=Array.isArray(b)?b.join(" "):b;return a?a.setShape(b):c.createPath(b)}function E(c,a,b){return a?a.setShape(b):c.createText(b)}function F(c,a){var b=a&&a.shape&&a.shape.type,e=c&&c.type,f=c&&c.style;e&&(f=J[e]||f);K[f]&&(f="path");return!(!b||!(f&&b!==f))}function B(c,a,b,e,f,h,g,d){switch(c){case r.STYLE_SQUARE:return["M",e+","+h,f+","+h,f+","+g,e+","+
g,"Z"];case r.STYLE_CROSS:return["M",a+","+h,a+","+g,"M",e+","+b,f+","+b];case r.STYLE_X:return["M",e+","+h,f+","+g,"M",e+","+g,f+","+h];case r.STYLE_DIAMOND:return["M",a+","+h,f+","+b,a+","+g,e+","+b,"Z"];case r.STYLE_TARGET:return["M",e+","+h,f+","+h,f+","+g,e+","+g,e+","+h,"M",e-d+","+b,e+","+b,"M",a+","+(h-d),a+","+h,"M",f+d+","+b,f+","+b,"M",a+","+(g+d),a+","+g]}}function G(c,a){var b=a.symbol;if("picture-marker-symbol"!==b.type){var e=u.getFill(b);if("simple-marker-symbol"===b.type){var f=b.style,
h=(b=u.getStroke(b))&&b.color,f=f===r.STYLE_X||f===r.STYLE_CROSS,g=a.opacity,d=a.color||v([0,0,0,0],f?h:e);d&&null!=g&&(d=w([0,0,0,0],d,g));d&&(f?d!==h&&(b=b?y.mixin({},b):{},b.color=d):d!==e&&(e=d));c.setFill(e).setStroke(b)}else"text-symbol"===b.type&&(g=a.opacity,(d=a.color||v([0,0,0,0],e))&&null!=g&&(d=w([0,0,0,0],d,g)),d&&d!==e&&(e=d),c.setFill(e))}}q.getScaleMatrix=z;var I={x:0,y:0};q.drawPoint=A;q.drawMarkers=function(c,a,b,e,f,h,g){var d=f.symbol;b=b.points;a=e||a.createGroup();e=[0];a.children[0]&&
F(d,a.children[0])&&a.clear();for(var l=d=0,m=b.length;l<m;l++)for(var p=b[l],k=0,n=g.length;k<n;k++)e[0]=g[k],a.add(A(c,a,{x:p[0],y:p[1]},a.children[d++],f,h,e));c=a.children.length;if(b.length*g.length<c){l=c-1;for(m=b.length*g.length;l>=m;l--)a.children[l].removeShape()}return a};q.drawShape=function(c,a,b,e,f){var h=[];"extent"===b.type&&(b=H.fromExtent(b));if("polyline"===b.type||"polygon"===b.type){for(var g=0,d=f.length;g<d;g++)h=h.concat(c.toScreenPath(b,f[g]));e=x(a,e,h)}return e};q.drawRect=
function(c,a,b){return a?a.setShape(b):c.createRect(b)};q.drawImage=D;q.drawCircle=C;q.drawPath=x;q.drawText=E;var J={"picture-marker-symbol":"image","picture-fill-symbol":"path","simple-fill-symbol":"path","simple-line-symbol":"path","text-symbol":"text"},K={square:1,cross:1,x:1,diamond:1,target:1};q.isShapeInvalid=F;q.smsToPath=B;q.stylePoint=G;q.styleMarkers=function(c,a){for(var b=0,e=c.children.length;b<e;b++)G(c.children[b],a)};q.styleShape=function(c,a){var b=a.symbol,e=a.size,f=a.color,h=
a.opacity,g=u.getStroke(b),d=u.getFill(b),l=!1,m;"simple-line-symbol"===b.type?(l=!0,m="none"!==b.style):m=b.outline&&"none"!==b.outline.style;var p,k,n;e&&(n=isFinite(e[0])&&e[0]);null!=e&&(n=s.pt2px(n));if((f||null!=h)&&"picture-fill-symbol"!==b.type)l?(p=f||g&&g.color&&v([0,0,0,0],g.color))&&null!=h&&(p=w(p,p,h)):d&&(k=f||v([0,0,0,0],d))&&null!=h&&(k=w(k,k,h));!m||null==e&&!p?c.setStroke(g):c.setStroke(y.mixin({},g,null!=n?{width:n}:null,p&&{color:p}));c.setFill(k||d);c.rawNode.setAttribute("vector-effect",
"non-scaling-stroke")}});