// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/lang ../core/kebabDictionary ../core/Error dojo/_base/array dojo/_base/lang ../symbols/support/jsonUtils ./Renderer ./support/arcadeUtils".split(" "),function(r,e,l,h,s,m,g,t,k){var n=l({esriNormalizeByLog:"log",esriNormalizeByPercentOfTotal:"percent-of-total",esriNormalizeByField:"field"}),p=l({esriClassifyNaturalBreaks:"natural-breaks",esriClassifyEqualInterval:"equal-interval",esriClassifyQuantile:"quantile",esriClassifyStandardDeviation:"standard-deviation",esriClassifyGeometricalInterval:"geometrical-interval"}),
q=r(t,{declaredClass:"esri.renderer.ClassBreaksRenderer",properties:{backgroundFillSymbol:{value:null,json:{read:g.read,write:function(a,c,b){if(a=g.write(a,{},b))c.backgroundFillSymbol=a}}},classBreakInfos:{set:function(a){this._symbols={};a&&a.forEach(this._processCBInfo,this);this._set("classBreakInfos",a)},json:{readFrom:["classBreakInfos","minValue"],read:function(a,c,b){var d=c.minValue;if(a&&Array.isArray(a)){var u=a[0]&&null!=a[0].classMaxValue;return a.map(function(a){a=e.clone(a);if(u){var k=
a.classMaxValue;a.minValue=d;d=a.maxValue=k}a.symbol=g.read(a.symbol,c,b);return a})}return a},write:function(a,c,b){a=this.classBreakInfos||[];var d=a[0]&&a[0].minValue;c.minValue=-Infinity===d?-Number.MAX_VALUE:d;c.classBreakInfos=s.map(a,function(a){a=e.clone(a);a.symbol&&(a.symbol=g.write(a.symbol,{},b));a.classMaxValue=Infinity===a.maxValue?Number.MAX_VALUE:a.maxValue;delete a.minValue;delete a.maxValue;return e.fixJson(a)})}}},classificationMethod:{value:null,json:{read:p.fromJSON,write:function(a,
c){var b=p.toJSON(a);b&&(c.classificationMethod=b)}}},defaultLabel:{value:null,json:{writable:!0}},defaultSymbol:{value:null,json:{read:g.read,write:function(a,c,b){if(a=g.write(a,{},b))c.defaultSymbol=a}}},valueExpression:{value:null,json:{write:function(a,c,b){b&&"web-scene"===b.origin?a&&b.messages&&b.messages.push(new h("property:unsupported",this.declaredClass+".valueExpression is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:"valueExpression",
context:b})):c.valueExpression=a}}},valueExpressionTitle:{value:null,json:{write:function(a,c,b){b&&"web-scene"===b.origin?a&&b.messages&&b.messages.push(new h("property:unsupported",this.declaredClass+".valueExpressionTitle is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:"valueExpressionTitle",context:b})):c.valueExpressionTitle=a}}},compiledFunc:{dependsOn:["valueExpression"],get:function(){return k.createFunction(this.valueExpression)}},
legendOptions:{value:null,json:{write:function(a,c,b){b&&"web-scene"===b.origin?a&&b.messages&&b.messages.push(new h("property:unsupported",this.declaredClass+".legendOptions is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:"legendOptions",context:b})):c.legendOptions=e.clone(a)}}},field:{value:null,json:{writable:!0}},isMaxInclusive:!0,normalizationField:{value:null,json:{writable:!0}},normalizationTotal:{value:null,json:{writable:!0}},
normalizationType:{value:null,dependsOn:["normalizationField","normalizationTotal"],get:function(){var a=this._get("normalizationType"),c=!!this.normalizationField,b=null!=this.normalizationTotal;if(c||b)a=c&&"field"||b&&"percent-of-total",c&&b&&console.warn("warning: both normalizationField and normalizationTotal are set!");else if("field"===a||"percent-of-total"===a)a=null;return a},json:{read:n.fromJSON,write:function(a,c){var b=n.toJSON(a);b&&(c.normalizationType=b)}}},requiredFields:{dependsOn:["field",
"normalizationField"]},type:"classBreaks"},constructor:function(){this._symbols={};this.classBreakInfos=[]},addClassBreakInfo:function(a,c,b){a=m.isObject(a)?a:{minValue:a,maxValue:c,symbol:b};this.classBreakInfos.push(a);this._processCBInfo(a)},removeClassBreakInfo:function(a,c){var b,d,e=this.classBreakInfos.length,f=this._symbols;for(d=0;d<e;d++)if(b=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],b[0]==a&&b[1]==c){delete f[a+"-"+c];this.classBreakInfos.splice(d,1);break}},
getBreakIndex:function(a,c){var b=this.field,d=a.attributes,e=this.classBreakInfos.length,f,g=this.isMaxInclusive;if(this.valueExpression)b=k.executeFunction(this.compiledFunc,k.createExecContext(a,k.getView(c)));else if(m.isFunction(b))b=b(a);else{b=parseFloat(d[b]);f=this.normalizationType;var h;f&&(h=parseFloat(this.normalizationTotal),d=parseFloat(d[this.normalizationField]),"log"===f?b=Math.log(b)*Math.LOG10E:"percent-of-total"===f&&!isNaN(h)?b=100*(b/h):"field"===f&&!isNaN(d)&&(b/=d))}for(d=
0;d<e;d++)if(f=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],f[0]<=b&&(g?b<=f[1]:b<f[1]))return d;return-1},getClassBreakInfo:function(a,c){var b=this.getBreakIndex(a,c);return-1!==b?this.classBreakInfos[b]:null},getSymbol:function(a,c){var b=this.getBreakIndex(a,c);return(b=-1<b&&[this.classBreakInfos[b].minValue,this.classBreakInfos[b].maxValue])?this._symbols[b[0]+"-"+b[1]]:this.defaultSymbol},clone:function(){return new q({field:this.field,backgroundFillSymbol:this.backgroundFillSymbol&&
this.backgroundFillSymbol.clone(),classificationMethod:this.classificationMethod,defaultLabel:this.defaultLabel,defaultSymbol:this.defaultSymbol&&this.defaultSymbol.clone(),valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,classBreakInfos:e.clone(this.classBreakInfos),isMaxInclusive:this.isMaxInclusive,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,normalizationType:this.normalizationType,visualVariables:e.clone(this.visualVariables),
legendOptions:e.clone(this.legendOptions),authoringInfo:e.clone(this.authoringInfo)})},collectRequiredFields:function(a){this.inherited(arguments);[this.field,this.normalizationField].forEach(function(c){c&&(a[c]=!0)})},_processCBInfo:function(a){var c=a.minValue,b=a.maxValue,d=a.symbol;d&&!d.declaredClass&&(a.symbol=g.fromJSON(d));this._symbols[c+"-"+b]=a.symbol}});return q});