// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.19/esri/copyright.txt for details.
//>>built
define("esri/renderers/ClassBreaksRenderer","dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/has ../kernel ../lang ../symbols/jsonUtils ./Renderer ./arcadeUtils".split(" "),function(k,m,f,r,s,q,n,t,p){k=k(t,{declaredClass:"esri.renderer.ClassBreaksRenderer",constructor:function(a,c){this.breaks=[];this._symbols={};this.infos=[];this.isMaxInclusive=!0;if(a&&!a.declaredClass){var b=a;this.attributeField=b.field;this.setValueExpression(b.valueExpression);this.valueExpressionTitle=b.valueExpressionTitle;
this.legendOptions=b.legendOptions;this.defaultSymbol=(a=b.defaultSymbol)&&(a.declaredClass?a:n.fromJson(a));this.backgroundFillSymbol=(a=b.backgroundFillSymbol)&&(a.declaredClass?a:n.fromJson(a));this._copy(["defaultLabel","classificationMethod:rest","normalizationType:rest","normalizationField","normalizationTotal"],b,this);var e=b.minValue;(b=b.classBreakInfos)&&(b[0]&&q.isDefined(b[0].classMaxValue))&&m.forEach(b,function(a){var b=a.classMaxValue;a.minValue=e;e=a.maxValue=b},this);m.forEach(b,
this._addBreakInfo,this)}else this.defaultSymbol=a,this.attributeField=c},addBreak:function(a,c,b){a=f.isObject(a)?a:{minValue:a,maxValue:c,symbol:b};this._addBreakInfo(a)},removeBreak:function(a,c){var b,e=this.breaks,d,h=e.length,g=this._symbols;for(d=0;d<h;d++)if(b=e[d],b[0]==a&&b[1]==c){e.splice(d,1);delete g[a+"-"+c];this.infos.splice(d,1);break}},clearBreaks:function(){this.breaks=[];this._symbols={};this.infos=[]},getBreakIndex:function(a){var c=this.attributeField,b=a.attributes,e=this.breaks,
d=e.length,h=this.isMaxInclusive;if(this._compiledFunc)a=p.executeFunction(this._compiledFunc,p.createExecContext(a,a._getView()));else if(f.isFunction(c))a=c(a);else{a=parseFloat(b[c]);var c=this.normalizationType,g;if(c)if(g=parseFloat(this.normalizationTotal),b=parseFloat(b[this.normalizationField]),"log"===c)a=Math.log(a)*Math.LOG10E;else if("percent-of-total"===c&&!isNaN(g))a=100*(a/g);else if("field"===c)if(!isNaN(a)&&!isNaN(b))a/=b;else return-1}if(null!=a&&!isNaN(a)&&"number"===typeof a)for(b=
0;b<d;b++)if(c=e[b],c[0]<=a&&(h?a<=c[1]:a<c[1]))return b;return-1},getBreakInfo:function(a){a=this.getBreakIndex(a);return-1!==a?this.infos[a]:null},getSymbol:function(a){return(a=this.breaks[this.getBreakIndex(a)])?this._symbols[a[0]+"-"+a[1]]:this.defaultSymbol},setMaxInclusive:function(a){this.isMaxInclusive=a},setValueExpression:function(a){this.valueExpression=a;this._compiledFunc=p.createFunction(a)},_normalizationTypeEnums:[["field","esriNormalizeByField"],["log","esriNormalizeByLog"],["percent-of-total",
"esriNormalizeByPercentOfTotal"]],_classificationMethodEnums:[["natural-breaks","esriClassifyNaturalBreaks"],["equal-interval","esriClassifyEqualInterval"],["quantile","esriClassifyQuantile"],["standard-deviation","esriClassifyStandardDeviation"],["geometrical-interval","esriClassifyGeometricalInterval"]],_copy:function(a,c,b){m.forEach(a,function(a){var d=a.split(":"),h,g,f;1<d.length&&(a=d[0],h=this["_"+a+"Enums"],"rest"===d[1]?(g="1",f="0"):"sdk"===d[1]&&(g="0",f="1"));d=c[a];if(void 0!==d&&(b[a]=
d,h&&g)){var l,k=h.length;for(l=0;l<k;l++)if(h[l][g]===d){b[a]=h[l][f];break}}},this)},_addBreakInfo:function(a){var c=a.minValue,b=a.maxValue;this.breaks.push([c,b]);this.infos.push(a);var e=a.symbol;e&&!e.declaredClass&&(a.symbol=n.fromJson(e));this._symbols[c+"-"+b]=a.symbol},toJson:function(){var a=this.infos||[],c=q.fixJson,b=a[0]&&a[0].minValue,e=this.backgroundFillSymbol,a=f.mixin(this.inherited(arguments),{type:"classBreaks",field:this.attributeField,valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,
legendOptions:f.clone(this.legendOptions),defaultSymbol:this.defaultSymbol&&this.defaultSymbol.toJson(),backgroundFillSymbol:e&&e.toJson(),minValue:-Infinity===b?-Number.MAX_VALUE:b,classBreakInfos:m.map(a,function(a){a=f.mixin({},a);a.symbol=a.symbol&&a.symbol.toJson();a.classMaxValue=Infinity===a.maxValue?Number.MAX_VALUE:a.maxValue;delete a.minValue;delete a.maxValue;return c(a)})});this._copy(["defaultLabel","classificationMethod:sdk","normalizationType:sdk","normalizationField","normalizationTotal"],
this,a);a.hasOwnProperty("normalizationType")&&!a.normalizationType&&delete a.normalizationType;a.hasOwnProperty("classificationMethod")&&!a.classificationMethod&&delete a.classificationMethod;return c(a)}});r("extend-esri")&&f.setObject("renderer.ClassBreaksRenderer",k,s);return k});