// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang ../../core/Accessor ../../core/Evented ../../core/HandleRegistry ../../core/lang ../../core/watchUtils ../../geometry/Extent ../../geometry/support/webMercatorUtils".split(" "),function(q,r,s,t,n,h,u,v){return r.createSubclass([s],{properties:{attributionText:{dependsOn:["items","itemDelimiter"],readOnly:!0},itemDelimiter:{},items:{},state:{dependsOn:["view.ready"],readOnly:!0},view:{}},declaredClass:"esri.widgets.Attribution.AttributionViewModel",constructor:function(){this._handles=
new t;this._pendingAttributionItemsByLayerId={};this._attributionDataByLayerId={};this._updateAttributionItems=this._updateAttributionItems.bind(this)},getDefaults:function(){return q.mixin(this.inherited(arguments),{items:[]})},initialize:function(){this._handles.add(h.init(this,"view",this._viewWatcher))},destroy:function(){this._handles.destroy();this.view=this._handles=null},_handles:null,_pendingAttributionItemsByLayerId:null,_attributionDataByLayerId:null,attributionText:null,_attributionTextGetter:function(){return this.items.join(this.itemDelimiter)},
itemDelimiter:" | ",items:null,state:"disabled",_stateGetter:function(){return this.get("view.ready")?"ready":"disabled"},view:null,_viewWatcher:function(a){var b=this._handles;b&&b.remove();a&&(b.add([a.allLayerViews.on("change",function(a){this._addLayerViews(a.added);0<a.removed.length&&(a.removed.forEach(function(a){b.remove(a.uid)}),this._updateAttributionItems())}.bind(this)),h.init(a,"stationary",this._updateAttributionItems)]),this._addLayerViews(a.allLayerViews))},_addLayerViews:function(a){a.forEach(function(a){this._handles.has(a.uid)||
this._handles.add(h.init(a,"suspended",this._updateAttributionItems),a.uid)},this)},_updateAttributionItems:function(){var a=[];this._getActiveLayerViews().forEach(function(b){var c=b.layer,d,f;c.hasAttributionData?(d=this._attributionDataByLayerId,d[c.uid]?(b=this._getDynamicAttribution(d[c.uid],this.view,c),this._isUnique(a,b)&&a.push(b)):(f=this._pendingAttributionItemsByLayerId,this._inProgress(f[c.uid])||(f[c.uid]=c.fetchAttributionData().then(function(a){a=this._createContributionIndex(a,this._isBingLayer(c));
delete f[c.uid];d[c.uid]=a;this._updateAttributionItems()}.bind(this))))):(b=c.copyright,this._isUnique(a,b)&&a.push(b))},this);this._itemsChanged(this.items,a)&&(this.items=a)},_itemsChanged:function(a,b){return a.length!==b.length||a.some(function(a,d){return a!==b[d]})},_inProgress:function(a){return a&&!a.isFulfilled()},_getActiveLayerViews:function(){return(this.get("view.allLayerViews")||[]).filter(function(a){return!a.suspended&&a.get("layer.attributionVisible")})},_isUnique:function(a,b){return b&&
-1===a.indexOf(b)},_isBingLayer:function(a){return-1!==a.declaredClass.toLowerCase().indexOf("vetiledlayer")},_createContributionIndex:function(a,b){var c=a.contributors,d={},f,g,e,k,m,l,h,p;if(!c)return d;for(k=0;k<c.length;k++)if(f=c[k],g=f.coverageAreas)for(m=0;m<g.length;m++){e=g[m];l=e.bbox;p=e.zoomMin-(b&&e.zoomMin?1:0);h=e.zoomMax-(b&&e.zoomMax?1:0);f={extent:v.geographicToWebMercator(new u({xmin:l[1],ymin:l[0],xmax:l[3],ymax:l[2]})),attribution:f.attribution||"",score:n.isDefined(e.score)?
e.score:100,id:k};for(e=p;e<=h;e++)d[e]=d[e]||[],d[e].push(f)}d.maxKey=Math.max.apply(null,Object.keys(d));return d},_getDynamicAttribution:function(a,b,c){var d=b.extent;b=c.tileInfo.scaleToZoom(b.scale);var f,g;b=Math.min(a.maxKey,Math.round(b));if(!d||!n.isDefined(b)||-1>=b)return"";a=a[b];f=d.center.clone().normalize();g={};return a.filter(function(a){var b=!g[a.id]&&a.extent.contains(f);b&&(g[a.id]=!0);return b}).sort(function(a,b){return b.score-a.score||a.objectId-b.objectId}).map(function(a){return a.attribution}).join(", ")}})});