// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../../geometry/Geometry ../languageUtils ../../geometry/geometryEngine ../kernel ../Feature".split(" "),function(s,n,h,g,f,k,m){function p(d,e,b,c){try{if(e===d.length)return b;var l=d[e];if(null!==l){var q=f.planarArea(l,c);b+=q}return p(d,e+1,b,c)}catch(a){throw a;}}function r(d,e,b,c){try{if(e===d.length)return b;var l=d[e];if(null!==l){var q=f.planarLength(l,c);b+=q}return r(d,e+1,b,c)}catch(a){throw a;}}n.spatialrelationFunction=function(d,e,b,c){return c(d,e,function(c,
d,a){g.pcCheck(a,2,2);if(a[0]instanceof h)if(a[1]instanceof h)switch(b){case "esriSpatialRelEnvelopeIntersects":return f.intersects(k.shapeExtent(a[0]),k.shapeExtent(a[1]));case "esriSpatialRelIntersects":return f.intersects(a[0],a[1]);case "esriSpatialRelContains":return f.contains(a[0],a[1]);case "esriSpatialRelOverlaps":return f.overlaps(a[0],a[1]);case "esriSpatialRelWithin":return f.within(a[0],a[1]);case "esriSpatialRelTouches":return f.touches(a[0],a[1]);case "esriSpatialRelCrosses":return f.crosses(a[0],
a[1]);default:throw Error("Unrecognised Relationship");}else{if(null===a[1])return!1;throw Error("Spatial Relation cannot accept this parameter type");}else if(null===a[0]){if(a[1]instanceof h||null===a[1])return!1}else throw Error("Spatial Relation cannot accept this parameter type");})};n.spatialTopoFunction=function(d,e,b,c){return c(d,e,function(c,d,a){g.pcCheck(a,2,3);if(a[0]instanceof h){if(void 0===a[1]&&"union"===b)return a[0];if(a[1]instanceof h){c=g.defaultUndefined(a[2],!0);d=null;switch(b){case "difference":d=
f.difference(a[0],a[1]);break;case "intersection":d=f.intersect(a[0],a[1]);break;case "symmetricdifference":d=f.symmetricDifference(a[0],a[1]);break;case "union":d=f.union([a[0],a[1]]);break;default:throw Error("Unrecognised Relationship");}c&&null!==d&&d.type!==a[0].type&&(d=null);return d}if(null===a[1])switch(b){case "difference":return a[0];case "intersection":return null;case "symmetricdifference":return a[0];case "union":return a[0];default:throw Error("Unrecognised Relationship");}else throw Error("Spatial Topo cannot accept this parameter type");
}else if(null===a[0])if(a[1]instanceof h)switch(b){case "difference":return null;case "intersection":return null;case "symmetricdifference":return a[1];case "union":return a[1];default:throw Error("Unrecognised Relationship");}else{if(null===a[1])return null;throw Error("Spatial Topo cannot accept this parameter type");}else throw Error("Spatial Topo cannot accept this parameter type");})};n.registerFunctions=function(d,e){d.buffer=function(b,c){return e(b,c,function(b,c,a){g.pcCheck(a,2,4);if(a[0]instanceof
h)return f.buffer(a[0],a[1],k.convertLinearUnitsToCode(a[2]),g.defaultUndefined(a[3],!1));if(a[0]instanceof m)return b=new m(a[0]),b.geometry=f.buffer(b.geometry,a[1],k.convertLinearUnitsToCode(a[2]),g.defaultUndefined(a[3],!1)),b;throw Error("Buffer cannot accept this parameter type");})};d.sumarea=function(b,c){return e(b,c,function(b,c,a){g.pcCheck(a,1,2);b=k.convertSquareUnitsToCode(a[1]);if(g.isArray(a[0]))return p(a[0],0,0,b);if(a[0]instanceof h)return f.planarArea(a[0],b);if(g.isImmutableArray(a[0]))return p(a[0].toArray(),
0,0,b);if(a[0]instanceof m)return null===a[0].geometry?0:f.planarArea(a[0].geometry,b);if(null===a[0])return 0;throw Error("Invalid Parameters for Area");})};d.area=d.sumarea;d.sumlength=function(b,c){return e(b,c,function(b,c,a){g.pcCheck(a,1,2);b=k.convertLinearUnitsToCode(a[1]);if(g.isArray(a[0]))return r(a[0],0,0,b);if(g.isImmutableArray(a[0]))return r(a[0].toArray(),0,0,b);if(a[0]instanceof h)return f.planarLength(a[0],b);if(a[0]instanceof m)return null===a[0].geometry?0:f.planarLength(a[0].geometry,
b);if(null===a[0])return 0;throw Error("Invalid Parameters for Length");})};d.length=d.sumlength;d.intersects=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelIntersects",e)};d.envelopeintersects=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelEnvelopeIntersects",e)};d.contains=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelContains",e)};d.overlaps=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelOverlaps",e)};d.within=
function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelWithin",e)};d.touches=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelTouches",e)};d.crosses=function(b,c){return this.spatialrelationFunction(b,c,"esriSpatialRelCrosses",e)};d.equals=function(b,c){return e(b,c,function(b,c,a){g.pcCheck(a,2,2);return a[0]===a[1]?!0:a[0]instanceof h&&a[1]instanceof h?f.equals(a[0],a[1]):g.isDate(a[0])&&g.isDate(a[1])?a[0].getTime()===a[1].getTime():!1})};d.intersection=function(b,
c){return this.spatialTopoFunction(b,c,"intersection",e)};d.difference=function(b,c){return this.spatialTopoFunction(b,c,"difference",e)};d.symmetricdifference=function(b,c){return this.spatialTopoFunction(b,c,"symmetricdifference",e)};d.union=function(b,c){return this.spatialTopoFunction(b,c,"union",e)}}});