// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ../core/Error ../core/lang ../geometry/Extent ../core/JSONSupport ../core/Loadable ./Portal ./PortalRating ../core/promiseUtils".split(" "),function(m,s,n,d,c,f,p,g,q,r,h,e,k){return function(l){function b(a){l.call(this);this.url=this.typeKeywords=this.type=this.title=this.tags=this.snippet=this.size=this.portal=this.owner=this.numViews=this.numRatings=this.numComments=
this.name=this.modified=this.licenseInfo=this.itemControl=this.id=this.extent=this.description=this.culture=this.created=this.avgRating=this.accessInformation=this.access=null}n(b,l);Object.defineProperty(b.prototype,"displayName",{get:function(){var a=this.type,b=this.typeKeywords||[],c=a;"Feature Service"===a||"Feature Collection"===a?c=-1<b.indexOf("Table")?"Table":-1<b.indexOf("Route Layer")?"Route Layer":"Feature Layer":"Image Service"===a?c=-1<b.indexOf("Elevation 3D Layer")?"Elevation Layer":
"Imagery Layer":"Scene Service"===a?c="Scene Layer":"Scene Package"===a?c="Scene Layer Package":"Stream Service"===a?c="Feature Layer":"Geoprocessing Service"===a&&this.portal&&this.portal.isPortal?c=-1<b.indexOf("Web Tool")?"Tool":"Geoprocessing Service":"Geocoding Service"===a?c="Locator":"Microsoft Powerpoint"===a?c="Microsoft PowerPoint":"GeoJson"===a?c="GeoJSON":"Globe Service"===a?c="Globe Layer":"Vector Tile Service"===a?c="Tile Layer":"Map Service"===a?c=-1<b.indexOf("Hosted Service")||-1<
b.indexOf("Tiled")?"Tile Layer":"Map Image Layer":a&&-1<a.toLowerCase().indexOf("add in")?c=a.replace(/(add in)/ig,"Add-In"):"datastore catalog service"===a&&(c="Big Data File Share");return c},enumerable:!0,configurable:!0});b.prototype.readExtent=function(a){return a&&a.length?new g(a[0][0],a[0][1],a[1][0],a[1][1]):null};Object.defineProperty(b.prototype,"iconUrl",{get:function(){var a=this.type&&this.type.toLowerCase()||"",b=this.typeKeywords||[],c=!1,d=!1,e=!1;0<a.indexOf("service")||"feature collection"===
a||"kml"===a||"wms"===a||"wmts"===a||"wfs"===a?(c=-1<b.indexOf("Hosted Service"),"feature service"===a||"feature collection"===a||"kml"===a||"wfs"===a?(d=-1<b.indexOf("Table"),e=-1<b.indexOf("Route Layer"),a=d?"table":e?"routelayer":c?"featureshosted":"features"):a="map service"===a||"wms"===a||"wmts"===a?c||-1<b.indexOf("Tiled")||"wmts"===a?"maptiles":"mapimages":"scene service"===a?-1<b.indexOf("Line")?"sceneweblayerline":-1<b.indexOf("3DObject")?"sceneweblayermultipatch":-1<b.indexOf("Point")?
"sceneweblayerpoint":-1<b.indexOf("IntegratedMesh")?"sceneweblayermesh":-1<b.indexOf("PointCloud")?"sceneweblayerpointcloud":-1<b.indexOf("Polygon")?"sceneweblayerpolygon":"sceneweblayer":"image service"===a?-1<b.indexOf("Elevation 3D Layer")?"elevationlayer":"imagery":"stream service"===a?"streamlayer":"vector tile service"===a?"vectortile":"datastore catalog service"===a?"datastorecollection":"geocoding service"===a?"geocodeservice":"layers"):a="web map"===a||"cityengine web scene"===a?"maps":"web scene"===
a?-1<b.indexOf("ViewingMode-Local")?"webscenelocal":"websceneglobal":"web mapping application"===a||"mobile application"===a||"application"===a||"operation view"===a||"desktop application"===a?"apps":"map document"===a||"map package"===a||"published map"===a||"scene document"===a||"globe document"===a||"basemap package"===a||"mobile basemap package"===a||"mobile map package"===a||"project package"===a||"project template"===a||"pro map"===a||"layout"===a||"layer"===a&&-1<b.indexOf("ArcGIS Pro")||"explorer map"===
a&&b.indexOf("Explorer Document")?"mapsgray":"service definition"===a||"csv"===a||"shapefile"===a||"cad drawing"===a||"geojson"===a||"360 vr experience"===a?"datafiles":"explorer add in"===a||"desktop add in"===a||"windows viewer add in"===a||"windows viewer configuration"===a?"appsgray":"arcgis pro add in"===a||"arcgis pro configuration"===a?"addindesktop":"rule package"===a||"file geodatabase"===a||"csv collection"===a||"kml collection"===a||"windows mobile package"===a||"map template"===a||"desktop application template"===
a||"arcpad package"===a||"code sample"===a||"form"===a||"document link"===a||"vector tile package"===a||"operations dashboard add in"===a||"rules package"===a||"image"===a||"workflow manager package"===a||"desktop style"===a||"explorer map"===a&&-1<b.indexOf("Explorer Mapping Application")||-1<b.indexOf("Document")?"datafilesgray":"network analysis service"===a||"geoprocessing service"===a||"geodata service"===a||"geometry service"===a||"geoprocessing package"===a||"locator package"===a||"geoprocessing sample"===
a||"workflow manager service"===a||"raster function template"===a?"toolsgray":"layer"===a||"layer package"===a||"explorer layer"===a?"layersgray":"scene package"===a?"scenepackage":"tile package"===a?"tilepackage":"task file"===a?"taskfile":"report template"===a?"report-template":"statistical data collection"===a?"statisticaldatacollection":"insights workbook"===a?"workbook":"insights model"===a?"insightsmodel":"insights page"===a?"insightspage":"relational database connection"===a?"relationaldatabaseconnection":
"big data file share"===a?"datastorecollection":"image collection"===a?"imagecollection":"style"===a?"style":"maps";return a?m.toUrl("../images/portal/"+a+"16.png"):null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isLayer",{get:function(){return-1<"Map Service;Feature Service;Feature Collection;Scene Service;Image Service;Stream Service;Vector Tile Service".split(";").indexOf(this.type)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"itemUrl",{get:function(){var a=
this.get("portal.restUrl");return a?a+"/content/items/"+this.id:null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"thumbnailUrl",{get:function(){var a=this.itemUrl,b=this.thumbnail;return a&&b?this.portal._normalizeUrl(a+"/info/"+b):null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"userItemUrl",{get:function(){var a=this.get("portal.restUrl");if(!a)return null;var b=this.owner||this.get("portal.user.username");return!b?null:a+"/content/users/"+(this.ownerFolder?
b+"/"+this.ownerFolder:b)+"/items/"+this.id},enumerable:!0,configurable:!0});b.prototype.load=function(){var a=this;this.portal||(this.portal=h.getDefault());var b=this.portal.load().then(function(){return a.resourceInfo?a.resourceInfo:a.id&&a.itemUrl?a.portal._request(a.itemUrl):{}}).then(function(b){a.resourceInfo=b;a.read(b)});this.addResolvingPromise(b);return this};b.prototype.addRating=function(a){var b={method:"post",query:{}};a instanceof e&&(a=a.rating);!isNaN(a)&&"number"===typeof a&&(b.query.rating=
a);return this.portal._request(this.itemUrl+"/addRating",b).then(function(){return new e({rating:a,created:new Date})})};b.prototype.deleteRating=function(){return this.portal._request(this.itemUrl+"/deleteRating",{method:"post"}).then(function(){})};b.prototype.fetchData=function(a){void 0===a&&(a="json");return this.portal._request(this.itemUrl+"/data",{responseType:a})};b.prototype.fetchRating=function(){return this.portal._request(this.itemUrl+"/rating").then(function(a){return null!=a.rating?
(a.created=new Date(a.created),new e(a)):null})};b.prototype.fetchRelatedItems=function(a){return this.portal._requestToTypedArray(this.itemUrl+"/relatedItems",{query:a},"PortalItem")};b.prototype.update=function(a){var b=this;if(!this.id)return k.reject(new f("portal:item-does-not-exist","The item does not exist yet and cannot be updated"));var c=a&&a.data;a={method:"post"};a.query=this._getPostQuery();for(var d in a.query)null===a.query[d]&&(a.query[d]="");a.query.clearEmptyFields=!0;null!=c&&("string"===
typeof c?a.query.text=c:"object"===typeof c&&(a.query.text=JSON.stringify(c)));return(d=this.userItemUrl)?this.portal._request(d+"/update",a).then(function(){return b.loaded?b._reload():b.load()}):k.reject(new f("portal:not-signed-in","Not signed in"))};b.prototype.toJSON=function(){var a=this.extent,a={created:this.created&&this.created.getTime(),description:this.description,extent:a&&[[a.xmin,a.ymin],[a.xmax,a.ymax]],id:this.id,modified:this.modified&&this.modified.getTime(),name:this.name,owner:this.owner,
ownerFolder:this.ownerFolder,snippet:this.snippet,tags:this.tags,thumbnail:this.thumbnail,title:this.title,type:this.type,typeKeywords:this.typeKeywords,url:this.url};return p.fixJson(a)};b.fromJSON=function(a){if(!a)return null;if(a.declaredClass)throw Error("JSON object is already hydrated");return new b({resourceInfo:a})};b.prototype._reload=function(){var a=this;return this.portal._request(this.itemUrl,{query:{_ts:(new Date).getTime()}}).then(function(b){a.resourceInfo=b;a.read(b);return a})};
b.prototype._getPostQuery=function(){var a=this.toJSON(),b;for(b in a)"tags"===b&&null!==a[b]&&(a[b]=a[b].join(", ")),"typeKeywords"===b&&null!==a[b]&&(a[b]=a[b].join(", "));return a};d([c.property()],b.prototype,"access",void 0);d([c.property()],b.prototype,"accessInformation",void 0);d([c.property()],b.prototype,"avgRating",void 0);d([c.property({type:Date})],b.prototype,"created",void 0);d([c.property()],b.prototype,"culture",void 0);d([c.property()],b.prototype,"description",void 0);d([c.property({dependsOn:["type",
"typeKeywords"],readOnly:!0})],b.prototype,"displayName",null);d([c.property({type:g})],b.prototype,"extent",void 0);d([c.read("extent")],b.prototype,"readExtent",null);d([c.property({dependsOn:["type","typeKeywords"],readOnly:!0})],b.prototype,"iconUrl",null);d([c.property()],b.prototype,"id",void 0);d([c.property({dependsOn:["type"],readOnly:!0})],b.prototype,"isLayer",null);d([c.property()],b.prototype,"itemControl",void 0);d([c.property({dependsOn:["portal.restUrl","id"],readOnly:!0})],b.prototype,
"itemUrl",null);d([c.property()],b.prototype,"licenseInfo",void 0);d([c.property({type:Date})],b.prototype,"modified",void 0);d([c.property()],b.prototype,"name",void 0);d([c.property()],b.prototype,"numComments",void 0);d([c.property()],b.prototype,"numRatings",void 0);d([c.property()],b.prototype,"numViews",void 0);d([c.property()],b.prototype,"owner",void 0);d([c.property()],b.prototype,"ownerFolder",void 0);d([c.property({type:h})],b.prototype,"portal",void 0);d([c.property()],b.prototype,"resourceInfo",
void 0);d([c.property()],b.prototype,"size",void 0);d([c.property()],b.prototype,"snippet",void 0);d([c.property()],b.prototype,"tags",void 0);d([c.property()],b.prototype,"thumbnail",void 0);d([c.property({dependsOn:["itemUrl","thumbnail","portal.credential.token"],readOnly:!0})],b.prototype,"thumbnailUrl",null);d([c.property()],b.prototype,"title",void 0);d([c.property()],b.prototype,"type",void 0);d([c.property()],b.prototype,"typeKeywords",void 0);d([c.property()],b.prototype,"url",void 0);d([c.property({dependsOn:["portal.restUrl",
"portal.user.username","owner","ownerFolder","id"],readOnly:!0})],b.prototype,"userItemUrl",null);return b=d([c.subclass("esri.portal.PortalItem")],b)}(c.declared(q,r))});