// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("../../../core/declare dojo/on ../support/mathUtils ../support/earthUtils ../support/projectionUtils ../support/aaBoundingRect ../lib/glMatrix ../webgl-engine/Stage ../webgl-engine/lib/Texture ../webgl-engine/lib/Util".split(" "),function(y,z,q,A,r,B,t,v,C,D){var w=t.vec2d,s=t.vec3d,h=t.vec4d,E=D.assert,k={width:0,height:0,pixelRatio:0,views:null},x=[{viewport:h.create(),extent:h.create()}],F=[x[0],{viewport:h.create(),extent:h.create()}],l=h.create(),m=s.create(),u=[h.create(),h.create()];
return y(null,{constructor:function(a,b){this._view=b;this._stage=b._stage;this._renderSR=this._overlaySR=null;this._overlaySREqualsRenderSR=!0;this.terrainSurface=a;this._renderer=this._stage.getTextureGraphicsRenderer();this._connectedLayers={};this._overlays=void 0;this._scale=0;this._dirty=!1},destroy:function(){for(var a in this._connectedLayers)this.unregisterLayerView(this._connectedLayers[a]);this._disposeOverlays()},hasOverlays:function(){return!!this._overlays},setSpatialReference:function(a,
b){(this._overlaySR=a)?(this._renderSR=this._view.renderSpatialReference,this._overlaySREqualsRenderSR=this._overlaySR.equals(this._renderSR),this._longitudeCyclical=(this._isSpherical=b)?a.isWebMercator?new q.Cyclical(-2.0037508342788905E7,2.0037508342788905E7):new q.Cyclical(-180,180):null):(this._disposeOverlays(),this._longitudeCyclical=null)},registerLayerView:function(a){var b=a.layer.uid;E(!this._connectedLayers[b],"layer already connected");var c=z(a,"draped-data-change",function(){this.setOverlayDirty()}.bind(this));
this._connectedLayers[b]={eventHandles:[c],layerView:a};if(a.setDrapingExtent&&this._overlays)for(b=0;b<this._overlays.length;b++)a.setDrapingExtent(b,this._overlays[b].extent,this._overlaySR,2048);this.setOverlayDirty()},unregisterLayerView:function(a){for(var b in this._connectedLayers){var c=this._connectedLayers[b];if(c.layerView===a){if(c.eventHandles)for(var d=0;d<c.eventHandles;d++)c.eventHandles[d].remove();delete this._connectedLayers[b];this.setOverlayDirty();a.destroyed||(a._overlayUpdating=
!1,a._evaluateUpdatingState())}}},onElevationChange:function(a){var b=a.extent;this._view.renderCoordsHelper.fromRenderCoords(this._view.navigation.currentCamera.center,m,a.spatialReference);b[0]<=m[0]&&(b[1]<=m[1]&&b[2]>m[0]&&b[3]>m[1])&&this.setOverlayDirty()},setOverlayDirty:function(){this._dirty||(this._setOverlayUpdating(!0),this._dirty=!0)},_setOverlayUpdating:function(a){for(var b in this._connectedLayers){var c=this._connectedLayers[b].layerView;if(!a||!c.suspended&&c.hasDraped)c._overlayUpdating=
a,c._evaluateUpdatingState()}if(b=this._view._graphicsView)b._overlayUpdating=a,b._evaluateUpdatingState()},updateOverlay:function(){if(this._overlaySR){var a=this._computeOverlayExtents();if(a){this._overlays||this._initOverlays();for(var b=0;b<this._overlays.length;b++){var c;a:{c=a[b];for(var d=this._overlays[b].extent,e=1E-5*Math.max(c[2]-c[0],c[3]-c[1],d[2]-d[0],d[3]-d[1]),f=0;4>f;f++)if(Math.abs(d[f]-c[f])>e){c=!0;break a}c=!1}if(c){h.set(a[b],this._overlays[b].extent);for(var g in this._connectedLayers)c=
this._connectedLayers[g].layerView,c.setDrapingExtent&&c.setDrapingExtent(b,a[b],this._overlaySR,2048)}}this._setOverlayUpdating(!1);this._drawOverlays();this.terrainSurface._updateTileOverlayParams();this._dirty=!1}}},overlaysNeedUpdate:function(){return this._dirty&&this._overlaySR},updateOpacity:function(a){var b=1;if(this._overlays){var c=this._scale;a=this._view.renderCoordsHelper.getAltitude(a);3.5*a<c&&(b=Math.sqrt(q.clamp((a-c/10)/(c/3.5-c/10),0,1)))}return b},setOverlayParamsOfTile:function(a,
b,c){a=a.extent;var d=-1;this._rectInsideRect(a,this._overlays[0].extent)?d=0:this._rectanglesOverlap(a,this._overlays[1].extent)&&(d=1);if(0<=d){var e=this._overlays[d].extent;b.overlayTexScale[0]=(a[2]-a[0])/(e[2]-e[0]);b.overlayTexScale[1]=(a[3]-a[1])/(e[3]-e[1]);var f=a[0];if(this._longitudeCyclical){var f=this._longitudeCyclical.minimalMonotonic(e[0],f),g=this._longitudeCyclical.minimalMonotonic(e[0],a[2]);f>g&&(f=g-(a[2]-a[0]))}w.set2((f-e[0])/(e[2]-e[0]),(a[1]-e[1])/(e[3]-e[1]),b.overlayTexOffset);
b.overlayTexId=this._overlays[d].texture.getId();b.overlayOpacity=void 0!==c?c:1}else b.overlayTexId=null},overlayPixelSizeInMapUnits:function(a){var b;this._overlays&&(this._overlays[0]&&this._pointIsInExtent(a,this._overlays[0].extent)?b=this._overlays[0].extent:this._overlays[1]&&(b=this._overlays[1].extent));return b?(b[2]-b[0])/2048:0},_initOverlays:function(){this._overlays=Array(2);for(var a=0;2>a;a++){var b=new C(null,"overlay",{wrapClamp:!0,mipmap:!0});this._stage.add(v.ModelContentType.TEXTURE,
b);this._overlays[a]={texture:b,extent:h.create()}}},_disposeOverlays:function(){if(this._overlays){var a=this._stage;this._overlays.forEach(function(b){a.remove(v.ModelContentType.TEXTURE,b.texture.getId())});this._overlays=null}},_overlayExtentIncTable:[[0,-1,2,1],[0,-2,2,0],[-1,-2,1,0],[-2,-2,0,0],[-2,-1,0,1],[-2,0,0,2],[-1,0,1,2],[0,0,2,2]],_computeOverlayExtents:function(){var a=this._view.navigation.currentCamera,b=this.terrainSurface.extent,c=s.create();s.set(a.center,c);this._scale=this._view.renderCoordsHelper.getAltitude(a.eye);
var d=r.vectorToPoint(c,this._renderSR,this.terrainSurface.spatialReference);(d=this.terrainSurface.getElevation(d))?this._view.renderCoordsHelper.setAltitude(d,c):this._view.navigation.getCenterIntersectManifold(a.eye,a.center,c);var e=s.dist(a.eye,c),d=a.angleOfElevation;if(!isNaN(d)){this._overlaySREqualsRenderSR||r.vectorToVector(c,this._renderSR,c,this._overlaySR);var e=2*1024*a.perPixelRatio*e,f=!1,g=Infinity;this._isSpherical&&(this._overlaySR.isWebMercator?(e/=Math.cos(r.webMercator.y2lat(c[1])),
g=this.terrainSurface.extent[3],g*=0.999):(f=!0,e/=A.metersPerDegree,g=90),e>=g&&(e=g,c[1]=0,this._overlaySR.isWebMercator&&(c[0]=0)));var k=1;f&&(k=1/Math.max(0.2,Math.cos(Math.abs(q.deg2rad(c[1])))),180<e*k&&(k=180/e));var p=e*k,n=u[0];n[0]=c[0]-p;n[1]=c[1]-e;n[2]=c[0]+p;n[3]=c[1]+e;this._isSpherical&&this._shiftExtentToFitBounds(n,Infinity,g);f=u[1];h.set(n,f);6*p>b[2]-b[0]?h.set(b,f):d>0.25*Math.PI?(f[0]-=p,f[1]-=e,f[2]+=p,f[3]+=e):(r.vectorToVector(a.eye,this._renderSR,m,this._overlaySR),w.subtract(c,
m,l),a=-Math.atan2(l[1],l[0])+0.125*Math.PI,0>a&&(a+=2*Math.PI),h.scale(this._overlayExtentIncTable[Math.floor(a/(0.25*Math.PI))],2*e,l),l[0]*=k,l[2]*=k,h.add(f,l,f));this._isSpherical&&(f[0]=this._longitudeCyclical.clamp(f[0]),f[2]=this._longitudeCyclical.clamp(f[2]),f[1]=Math.max(f[1],-g),f[3]=Math.min(f[3],g));this.opacity=1;return u}},_drawOverlays:function(){for(var a=this._overlays[0].extent[2]-this._overlays[0].extent[0],b=this._stage.getTextureGraphicsRenderer(),c=0;c<this._overlays.length;c++){var d=
this._overlays[c].extent,e=this._longitudeCyclical?d[2]>this._longitudeCyclical.max:!1,f=this._longitudeCyclical?d[0]<this._longitudeCyclical.min:!1;if(e||f){k.views=F;var f=Math.round(2048*((e?this._longitudeCyclical.max-d[0]:this._longitudeCyclical.min-d[0])/(d[2]-d[0]))),g=k.views[0];h.set4(0,0,f,2048,g.viewport);h.set4(d[0],d[1],this._longitudeCyclical.max,d[3],g.extent);e||(g.extent[0]+=this._longitudeCyclical.range);g=k.views[1];h.set4(f,0,2048-f,2048,g.viewport);h.set4(this._longitudeCyclical.min,
d[1],d[2],d[3],g.extent);e&&(g.extent[2]-=this._longitudeCyclical.range)}else k.views=x,h.set(d,k.views[0].extent),h.set4(0,0,2048,2048,k.views[0].viewport);k.width=2048;k.height=2048;k.pixelRatio=a/(d[2]-d[0]);b.draw(this._overlays[c].texture,k)}},_rectanglesOverlap:function(a,b){return this._longitudeCyclical?(this._longitudeCyclical.contains(b[0],b[2],a[0])||this._longitudeCyclical.contains(b[0],b[2],a[2]))&&!(a[1]>b[3]||a[3]<b[1]):!(a[0]>b[2]||a[2]<b[0]||a[1]>b[3]||a[3]<b[1])},_rectInsideRect:function(a,
b){return this._longitudeCyclical?this._longitudeCyclical.contains(b[0],b[2],a[0])&&this._longitudeCyclical.contains(b[0],b[2],a[2])&&a[1]>b[1]&&a[3]<b[3]:a[0]>b[0]&&a[2]<b[2]&&a[1]>b[1]&&a[3]<b[3]},_pointIsInExtent:function(a,b){if(this._longitudeCyclical)return this._longitudeCyclical.contains(b[0],b[2],a.x)&&a.y>=b[1]&&a.y<=b[3];var c=a.x,d=a.y;return c>b[0]&&c<b[2]&&d>b[1]&&d<b[3]},_shiftExtentToFitBounds:function(a,b,c){var d=0,e=0;a[0]<-b?d=a[0]+b:a[2]>b&&(d=b-a[2]);a[1]<-c?e=a[1]+c:a[3]>c&&
(e=c-a[3]);B.offset(a,d,e)}})});