// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/i18n!../../nls/smartMapping dojo/_base/lang ../../../core/lang ../../ClassBreaksRenderer ../statistics/summaryStatistics ../symbology/size ../../support/utils ../../../core/promiseUtils ../../../views/SceneView ./support/utils ../support/utils".split(" "),function(G,s,y,r,z,A,B,p,t,f,u,d,m){function C(b){if(!b||!b.layer||!b.field&&!b.valueExpression&&!b.sqlExpression)return f.reject(d.createError("size-visual-variable:missing-parameters","'layer' and 'field', 'valueExpression' or 'sqlExpression' parameters are required"));
var a=r.mixin({},b);a.basemap=d.getBasemapId(a.basemap);a.layer=m.createLayerAdapter(a.layer);return!a.layer?f.reject(d.createError("size-visual-variable:invalid-parameters","'layer' must be one of these types: "+v)):a.worldScale&&!(a.view instanceof u)?f.reject(d.createError("size-visual-variable:invalid-parameters","'view' parameter should be an instance of SceneView when 'worldScale' parameter is true")):a.layer.load().then(function(){var e=a.layer.geometryType;if(a.worldScale&&!("point"===e||
"multipoint"===e))return f.reject(d.createError("size-visual-variable:not-supported","'worldScale' sizing is not supported for polyline and polygon layers"));e=m.getFieldsList({field:a.field,normalizationField:a.normalizationField,valueExpression:a.valueExpression});return(e=d.verifyBasicFieldValidity(a.layer,e,"size-visual-variable:invalid-parameters"))?f.reject(e):a})}function D(b){if(!b||!b.layer||!b.field&&!b.valueExpression&&!b.sqlExpression)return f.reject(d.createError("size-continuous-renderer:missing-parameters",
"'layer' and 'field', 'valueExpression' or 'sqlExpression' parameters are required"));var a=r.mixin({},b);a.basemap=d.getBasemapId(a.basemap);a.symbolType=a.symbolType||"2d";a.layer=m.createLayerAdapter(a.layer);return!a.layer?f.reject(d.createError("size-continuous-renderer:invalid-parameters","'layer' must be one of these types: "+v)):"3d-volumetric"===a.symbolType&&!(a.view instanceof u)?f.reject(d.createError("size-continuous-renderer:invalid-parameters","'view' parameter should be an instance of SceneView when 'symbolType' parameter is '3d-volumetric'")):
a.layer.load().then(function(){var e=a.layer.geometryType;if(-1<a.symbolType.indexOf("3d")&&!("point"===e||"multipoint"===e))return f.reject(d.createError("size-continuous-renderer:not-supported","3d symbols are not supported for polyline and polygon layers"));e=m.getFieldsList({field:a.field,normalizationField:a.normalizationField,valueExpression:a.valueExpression});return(e=d.verifyBasicFieldValidity(a.layer,e,"size-continuous-renderer:invalid-parameters"))?f.reject(e):a})}function E(b){b=r.mixin({},
b);var a="3d-volumetric"===b.symbolType;delete b.symbolType;delete b.defaultSymbolEnabled;b.worldScale=a;return b}function w(b){return C(b).then(function(a){var e=a.normalizationField,b=e?"field":void 0;return(a.statistics?f.resolve(a.statistics):B({layer:a.layer,field:a.field,valueExpression:a.valueExpression,sqlExpression:a.sqlExpression,sqlWhere:a.sqlWhere,normalizationType:b,normalizationField:e,minValue:a.minValue,maxValue:a.maxValue})).then(function(b){var c=a.layer,h=a.field,l=h&&"function"!==
typeof h?c.getField(h):null,l=l&&l.type===F,g=c.geometryType;c=(c=a.sizeScheme)?p.cloneScheme(c):(c=p.getSchemes({basemap:a.basemap,geometryType:g,worldScale:a.worldScale,view:a.view}))&&c.primaryScheme;if(c){var k;switch(g){case "point":case "multipoint":k=[c.minSize,c.maxSize];break;case "polyline":k=[c.minWidth,c.maxWidth];break;case "polygon":k=[c.marker.minSize,c.marker.maxSize]}g=(l=d.getDefaultDataRange(b,l,!1))||[b.min,b.max];b=f.resolve({basemapId:a.basemap,visualVariable:{type:"size",field:h,
valueExpression:a.valueExpression,valueUnit:"unknown",normalizationField:e,minSize:k[0],maxSize:k[1],minDataValue:g[0],maxDataValue:g[1],legendOptions:a.legendOptions},statistics:b,defaultValuesUsed:!!l,sizeScheme:p.cloneScheme(c),authoringInfo:{visualVariables:[{type:"size",minSliderValue:b.min,maxSliderValue:b.max}]}})}else b=f.reject(d.createError("size-visual-variable:insufficient-info","Unable to find size scheme"));return b})})}var F="date",x=Math.pow(2,53)-1,v=m.supportedLayerTypes.join(", ");
s.createVisualVariable=w;s.createContinuousRenderer=function(b){return D(b).then(function(a){return w(E(a)).then(function(b){var f=a.normalizationField,m=f?"field":void 0,c=a.field,h=a.layer.geometryType,l=null==a.defaultSymbolEnabled?!0:a.defaultSymbolEnabled,g=p.cloneScheme(b.sizeScheme),k="polygon"===h,n=k?g.marker:g,q=k?g.background:null,g="polyline"===h?n.noDataWidth:n.noDataSize,q=q?d.createSymbol(q,q.color,h,a.symbolType):null;return{renderer:new A({backgroundFillSymbol:q,classBreakInfos:[{minValue:-x,
maxValue:x,symbol:d.createSymbol(n,n.color,k?"point":h,a.symbolType)}],defaultLabel:l?y.other:null,defaultSymbol:l?d.createSymbol(n,n.noDataColor,k?"point":h,a.symbolType,g):null,field:c,normalizationField:f,normalizationType:m,valueExpression:a.valueExpression,visualVariables:[t.cloneSizeVariable(b.visualVariable)],authoringInfo:z.clone(b.authoringInfo)}),visualVariable:t.cloneSizeVariable(b.visualVariable),statistics:b.statistics,defaultValuesUsed:b.defaultValuesUsed,sizeScheme:p.cloneScheme(b.sizeScheme),
basemapId:b.basemapId}})})}});