// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ./Layer ../core/MultiOriginJSONSupport ./mixins/PortalLayer ./mixins/OperationalLayer ../support/LayersMixin ../core/accessorSupport/utils ../core/accessorSupport/decorators".split(" "),function(q,r,g,c,h,k,l,m,n,p,b){return function(f){function a(e){f.call(this);this._visibilityHandles={};this.fullExtent=void 0;this.operationalLayerType="GroupLayer";this.spatialReference=void 0;this.type="group";this._visibilityWatcher=
this._visibilityWatcher.bind(this)}g(a,f);a.prototype.initialize=function(){this._enforceVisibility(this.visibilityMode,this.visible);this.watch("visible",this._visibleWatcher.bind(this),!0)};a.prototype._writeLayers=function(e,a,b){var d=[];if(!e)return d;e.forEach(function(a){a.write&&(a=a.write(null,b))&&a.layerType&&d.push(a)});a.layers=d};Object.defineProperty(a.prototype,"visibilityMode",{set:function(a){this._get("visibilityMode")!==a&&this._enforceVisibility(a,this.visible);this._set("visibilityMode",
a)},enumerable:!0,configurable:!0});a.prototype.load=function(){this.addResolvingPromise(this.loadFromPortal({supportedTypes:["Feature Service","Feature Collection","Scene Service"]}));return this};a.prototype.layerAdded=function(a,b){a.visible&&"exclusive"===this.visibilityMode?this._turnOffOtherLayers(a):"inherited"===this.visibilityMode&&(a.visible=this.visible);this._visibilityHandles[a.uid]=a.watch("visible",this._visibilityWatcher,!0)};a.prototype.layerRemoved=function(a,b){var c=this._visibilityHandles[a.uid];
c&&(c.remove(),delete this._visibilityHandles[a.uid]);this._enforceVisibility(this.visibilityMode,this.visible)};a.prototype._turnOffOtherLayers=function(a){this.layers.forEach(function(b){b!==a&&(b.visible=!1)})};a.prototype._enforceVisibility=function(a,b){if(p.getProperties(this).initialized){var c=this.layers,d=c.find(function(a){return a.visible});switch(a){case "exclusive":c.length&&!d&&(d=c.getItemAt(0),d.visible=!0);this._turnOffOtherLayers(d);break;case "inherited":c.forEach(function(a){a.visible=
b})}}};a.prototype._visibleWatcher=function(a){"inherited"===this.visibilityMode&&this.layers.forEach(function(b){b.visible=a})};a.prototype._visibilityWatcher=function(a,b,c,d){switch(this.visibilityMode){case "exclusive":a?this._turnOffOtherLayers(d):this._isAnyLayerVisible()||(d.visible=!0);break;case "inherited":d.visible=this.visible}};a.prototype._isAnyLayerVisible=function(){return this.layers.some(function(a){return a.visible})};c([b.shared({"2d":"../views/layers/GroupLayerView","3d":"../views/layers/GroupLayerView"})],
a.prototype,"viewModulePaths",void 0);c([b.property()],a.prototype,"fullExtent",void 0);c([b.property({json:{readable:!1,writeAlways:!0}})],a.prototype,"layers",void 0);c([b.write("layers")],a.prototype,"_writeLayers",null);c([b.property()],a.prototype,"operationalLayerType",void 0);c([b.property({json:{writable:!1}})],a.prototype,"portalItem",void 0);c([b.property()],a.prototype,"spatialReference",void 0);c([b.property({json:{readable:!1}})],a.prototype,"type",void 0);c([b.property({json:{readable:!1,
writable:!1}})],a.prototype,"url",void 0);c([b.property({value:"independent",json:{writable:!0}})],a.prototype,"visibilityMode",null);return a=c([b.subclass("esri.layers.GroupLayer")],a)}(b.declared(h,n,k,m,l))});