// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require dojo/_base/lang dojo/Deferred ../core/sniff ../core/Collection ../Graphic ../geometry/SpatialReference ./FeatureLayer".split(" "),function(h,e,k,f,l,m,g,n){return n.createSubclass({declaredClass:"esri.layers.StreamLayer",constructor:function(a,b){"WebSocket"in window||(this.loadError=Error("WebSocket is not supported in this browser"),console.log("WebSocket is not supported in this browser. StreamLayer will not have real-time connection with the stream service."))},normalizeCtorArgs:function(a,
b){return"string"===typeof a?e.mixin({},{url:a},b):a&&a.layerDefinition?e.mixin({},{collectionLayer:a},b):a},getDefaults:function(a){return e.mixin(this.inherited(arguments)||{},{purgeOptions:{displayCount:2E3},outFields:["*"]})},properties:{definitionExpression:{value:null,set:function(a){this.source?this._set("requestedDefinitionExpression",a):this._set("definitionExpression",a)}},geometryDefinition:{value:null,set:function(a){a&&"extent"!==a.type?this.emit("error",new TypeError("Invalid geometry. It must have an extent")):
this.get("source")?this._set("requestedGeometryDefinition",a):this._set("geometryDefinition",a)}},maxReconnectAttempts:10,maximumTrackPoints:1,objectIdField:{json:{readFrom:["fields"],read:function(a,b){if(!a){var c=b.fields;c.some(function(b){"esriFieldTypeOID"===b.type&&(a=b.name);return!!a})}var d=1,e=[];if(!a){c.forEach(function(a){"objectid"===a.name.split("_")[0]&&e.push(a.name)});if(e.length)for(;-1!==e.indexOf("objectid_"+d);)d+=1;a="objectid_"+d}return a}}},operationalLayerType:"ArcGISStreamLayer",
purgeOptions:{value:null,set:function(a){var b=this._get("purgeOptions"),c={},d=!1;if(a&&!("object"!==typeof a||b===a))if(a.hasOwnProperty("displayCount")&&0<a.displayCount&&(c.displayCount=a.displayCount,d=!0),a.hasOwnProperty("age")&&0<=a.age&&(c.age=a.age,d=!0),d)return this._set("purgeOptions",c)}},requestedDefinitionExpression:null,requestedGeometryDefinition:null,socketDirection:"subscribe",spatialReference:{value:null,type:g,json:{readFrom:["spatialReference"],read:function(a){return a&&g.fromJSON(a)}}},
type:{value:"stream",json:{readable:!1}}},createGraphicsSource:function(){var a=new k;h(["./graphics/sources/StreamLayerSource"],e.hitch(this,function(b){var c=new b({layer:this});c.then(e.hitch(this,function(){this.emit("graphics-source-create",{graphicsSource:c});a.resolve(c)}),function(b){a.reject(b)})}));return a.promise},createGraphicsController:function(a){var b=new k,c=a.layerView,d=c.view.map,f=l.ofType(m),d=d.view===c.view?this.graphics:new f,g=e.mixin(a.options||{},{layer:this,layerView:c,
graphics:d});h(["./graphics/controllers/StreamController"],e.hitch(this,function(a){var d=new a(g);d.then(e.hitch(this,function(){this.emit("graphics-controller-create",{graphicsController:d});b.resolve(d)}),function(a){b.reject(a)})}));return b.promise},loadFromPortal:function(a){a=e.mixin(a,{supportedTypes:["Stream Service"]});return this.inherited(arguments,[a])},_initLayerProperties:function(a){this.source=a;var b=this.source.relatedFeaturesInfo;b&&(this.objectIdField=b.joinField,this.source.relatedFeaturesInfo.outFields=
this.outFields?this.outFields.splice(0):null);a=a.layerDefinition;this.read(a,{origin:"service",url:this.parsedUrl});if(b&&b.outFields&&"*"!==b.outFields[0]){var c=b.outFields.map(function(a){return a.toLowerCase()});(this.requiredFields||[]).forEach(function(a){-1===c.indexOf(a.toLowerCase())&&b.outFields.push(a)})}a._ssl&&(this.url=this.url.replace(this.reHttp,"https:"));this._verifyFields();this._fixSymbolUrls();this.useQueryTimestamp=f("ie")||f("safari")},_verifyFields:function(){var a=this.parsedUrl&&
this.parsedUrl.path||"undefined";this.objectIdField||console.log("StreamLayer: 'objectIdField' property is not defined (url: "+a+")")}})});