// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/Collection ../core/Logger ../core/collectionUtils ../core/Warning ../core/urlUtils ./Symbol ./Symbol3DLayer ./IconSymbol3DLayer ./ObjectSymbol3DLayer ./LineSymbol3DLayer ./PathSymbol3DLayer ./FillSymbol3DLayer ./ExtrudeSymbol3DLayer ./TextSymbol3DLayer ./support/Thumbnail ./support/StyleOrigin ../portal/Portal ../core/accessorSupport/decorators".split(" "),function(E,F,p,e,q,r,s,h,f,t,k,u,v,w,x,
y,z,A,B,g,C,d){var D={Icon:u,Object:v,Line:w,Path:x,Fill:y,Extrude:z,Text:A},l=q.ofType(k),m=r.getLogger("esri.symbols.Symbol3D");return function(n){function b(a){n.call(this);this.type=this.thumbnail=this.styleOrigin=null;this._set("symbolLayers",this._createSymbolLayersCollection())}p(b,n);Object.defineProperty(b.prototype,"symbolLayers",{set:function(a){var b=this._get("symbolLayers");b?(b.removeAll(),b.addMany(a)):(b=this._createSymbolLayersCollection(a),this._set("symbolLayers",b))},enumerable:!0,
configurable:!0});b.prototype.readSymbolLayers=function(a,b,c){b=this._createSymbolLayersCollection();for(var d=0;d<a.length;d++){var e=a[d],f=e.type,g=D[f];g?(e=new g,e.read(a[d],c),b.add(e)):(m.warn("Unknown symbol layer type: "+f),c&&c.messages&&c.messages.push(new h("symbol-layer:unsupported","Symbol layers of type '"+(f||"unknown")+"' are not supported",{definition:e,context:c})))}return b};b.prototype.readStyleOrigin=function(a,b,c){if(a.styleUrl&&a.name)return b=f.read(a.styleUrl,c),new g({styleUrl:b,
name:a.name});if(a.styleName&&a.name)return new g({portal:c&&c.portal||C.getDefault(),styleName:a.styleName,name:a.name});c&&c.messages&&c.messages.push(new h("symbol3d:incomplete-style-origin","Style origin requires either a 'styleUrl' or 'styleName' and a 'name' property",{context:c,definition:a}))};b.prototype.writeStyleOrigin=function(a,b,c){a.styleUrl&&a.name?(c=f.write(a.styleUrl,c),b.styleOrigin={styleUrl:c,name:a.name}):a.styleName&&a.name&&(a.portal&&c&&c.portal&&!f.hasSamePortal(a.portal.restUrl,
c.portal.restUrl)?c&&c.messages&&c.messages.push(new h("symbol:cross-portal","The symbol style origin cannot be persisted because it refers to an item on a different portal than the one being saved to.",{symbol:this})):b.styleOrigin={styleName:a.styleName,name:a.name})};b.prototype.normalizeCtorArgs=function(a){return a instanceof k?{symbolLayers:this._createSymbolLayersCollection([a])}:Array.isArray(a)?{symbolLayers:this._createSymbolLayersCollection(a)}:a};b.prototype._createSymbolLayersCollection=
function(a){var b=this;a=new l(a);a.on("before-add",function(a){return b._onSymbolLayersBeforeAdd(a)});return a};b.prototype._onSymbolLayersBeforeAdd=function(a){0>this._allowedLayerTypes.indexOf(a.item.type)&&(m.error("Symbol layer of type '"+a.item.type+"' is not allowed for symbol of type '"+this.type+"'"),a.preventDefault())};e([d.property({json:{writable:!1}})],b.prototype,"color",void 0);e([d.property({type:l,json:{writable:!0}}),d.cast(s.castForReferenceSetter)],b.prototype,"symbolLayers",
null);e([d.read("symbolLayers")],b.prototype,"readSymbolLayers",null);e([d.property({type:g})],b.prototype,"styleOrigin",void 0);e([d.read("styleOrigin")],b.prototype,"readStyleOrigin",null);e([d.write("styleOrigin")],b.prototype,"writeStyleOrigin",null);e([d.property({type:B.default,json:{readable:!1}})],b.prototype,"thumbnail",void 0);e([d.property({type:String,readOnly:!0,json:{readable:!1}})],b.prototype,"type",void 0);return b=e([d.subclass("esri.symbols.Symbol3D")],b)}(d.declared(t))});