// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ./Widget ./support/widget dojo/i18n!../nls/common dojo/i18n!./LayerList/nls/LayerList ../core/HandleRegistry ./LayerList/LayerListViewModel ../core/watchUtils".split(" "),function(u,z,v,e,g,w,c,p,q,x,r,k){var y=u.toUrl("./LayerList/images/default-action.svg");return function(s){function b(){s.call(this);this._handleRegistry=new x;this.view=this.createActionsFunction=null;
this.viewModel=new r}v(b,s);b.prototype.postInitialize=function(){var a=this,d=this.operationalItems;this.own(k.on(this,"operationalItems","change",function(){return a._itemsChanged(d)}))};b.prototype.destroy=function(){this._handleRegistry.destroy();this._handleRegistry=null};b.prototype.render=function(){var a=this,d=this._getItems(),d=0===d.length?c.jsxFactory.createElement("div",{"class":"esri-layer-list__no-items"},q.noItemsToDisplay):c.jsxFactory.createElement("ul",{"class":c.join("esri-layer-list__list",
"esri-layer-list__list--root","esri-layer-list__list--independent"),role:"tree"},d.map(function(d,c){return a._renderItem(d,null)})),b=(f={},f["esri-disabled"]="disabled"===this.viewModel.state,f);return c.jsxFactory.createElement("div",{"class":"esri-layer-list esri-widget",classes:b},d);var f};b.prototype._getItems=function(){var a=this;return this.operationalItems.toArray().filter(function(d){return a.errorsVisible||!d.error})};b.prototype._renderItem=function(a,d){var b=this,f=this.id+"_"+a.uid,
t=f+"_actions",e=!!a.children.length,g=!!a.error,k=g?q.layerError:"",m=a.visibilityMode,r=a.children&&a.children.toArray(),s=(n={},n["esri-layer-list__list--exclusive"]="exclusive"===m,n["esri-layer-list__list--inherited"]="inherited"===m,n["esri-layer-list__list--independent"]="inherited"!==m&&"exclusive"!==m,n),n=(h={},h["esri-layer-list__item--has-children"]=e,h["esri-layer-list__item--error"]=!!k,h["esri-layer-list__item--updating"]=a.updating&&!d,h["esri-layer-list__item--invisible-at-scale"]=
!a.visibleAtCurrentScale,h),u=(h=this._countActions(a.actionsSections))?this._renderActionMenuItem(a.actionsSections):null,v=(l={},l["esri-icon-handle-horizontal"]=!a.actionsOpen,l["esri-icon-close"]=a.actionsOpen,l),l=1<h?c.jsxFactory.createElement("div",{key:a.uid+"__actions-menu-toggle","data-item":a,onclick:this._toggleActionsOpen,onkeydown:this._toggleActionsOpen,"class":"esri-layer-list__item-actions-menu-item",tabindex:"0",role:"button","aria-controls":t,"aria-expanded":a.actionsOpen?"true":
"false",title:a.actionsOpen?p.close:p.open},c.jsxFactory.createElement("span",{"aria-hidden":"true",classes:v})):null,l=h?c.jsxFactory.createElement("div",{key:a.uid+"__actions-menu","class":"esri-layer-list__item-actions-menu"},u,l):null,t=1<h?this._renderActionsSections(a,a.actionsSections,t):null,m=e?c.jsxFactory.createElement("ul",{key:a.uid+"__child-list","class":"esri-layer-list__list",classes:s,id:f,role:"exclusive"===m?"radiogroup":"group",hidden:a.open?null:!0},r.map(function(d,c){return b._renderItem(d,
a)})):null,f=e?c.jsxFactory.createElement("span",{onclick:this._toggleChildrenClick,onkeydown:this._toggleChildrenClick,"data-item":a,key:f+"__toggle-children","class":"esri-layer-list__child-toggle",tabindex:"0",role:"button","aria-expanded":a.open?"true":"false","aria-controls":f,title:a.open?p.collapse:p.expand},c.jsxFactory.createElement("span",{"aria-hidden":"true","class":c.join("esri-layer-list__child-toggle-icon--closed","esri-icon-right-triangle-arrow")}),c.jsxFactory.createElement("span",
{"aria-hidden":"true","class":c.join("esri-layer-list__child-toggle-icon--opened","esri-icon-down-arrow")}),c.jsxFactory.createElement("span",{"aria-hidden":"true","class":c.join("esri-layer-list__child-toggle-icon--closed-rtl","esri-icon-left-triangle-arrow")})):null,e=this._createLabelNode(a,d),g=g?c.jsxFactory.createElement("div",{key:a.uid+"__error","class":"esri-layer-list__item-error-message",role:"alert"},c.jsxFactory.createElement("span",{"aria-hidden":"true","class":"esri-icon-notice-triangle"}),
c.jsxFactory.createElement("span",null,k)):null;return c.jsxFactory.createElement("li",{key:a.uid+"__list-item","class":"esri-layer-list__item",classes:n,role:"treeitem"},c.jsxFactory.createElement("div",{key:a.uid+"__list-item-container","class":"esri-layer-list__item-container"},f,e,l),g,t,m);var n,h,l};b.prototype._createLabelNode=function(a,d){var b=d&&d.visibilityMode,f=(e={},e["esri-icon-radio-checked"]="exclusive"===b&&a.visible,e["esri-icon-radio-unchecked"]="exclusive"===b&&!a.visible,e["esri-icon-visible"]=
"exclusive"!==b&&a.visible,e["esri-icon-non-visible"]="exclusive"!==b&&!a.visible,e),e="exclusive"===b?"radio":"checkbox",g=a.visible?"true":"false",k=c.jsxFactory.createElement("span",{"class":"esri-layer-list__item-title"},a.title||q.untitledLayer);return"inherited"===b?c.jsxFactory.createElement("span",{key:a.uid+"__label","class":"esri-layer-list__item-label",title:!a.visibleAtCurrentScale?q.layerInvisibleAtScale:""},k):c.jsxFactory.createElement("span",{key:a.uid+"__label",onclick:this._labelClick,
onkeydown:this._labelClick,"data-item":a,"data-parent-visibility":b,"class":"esri-layer-list__item-label",tabindex:"0","aria-checked":g,role:e,title:!a.visibleAtCurrentScale?q.layerInvisibleAtScale:a.visible?p.visibility.hide:p.visibility.show},c.jsxFactory.createElement("span",{"class":"esri-layer-list__item-toggle"},c.jsxFactory.createElement("span",{"class":"esri-layer-list__item-toggle-icon"},c.jsxFactory.createElement("span",{"aria-hidden":"true",classes:f}))),k);var e};b.prototype._renderActionMenuItem=
function(a){if(a=(a=a.getItemAt(0))&&a.getItemAt(0)){var d=this._getActionImageStyles(a),b=(f={},f[a.className]=a.className,f["esri-layer-list__item-action-image"]=d["background-image"],f);return c.jsxFactory.createElement("div",{key:a.uid+"__action-menu-item",bind:this,"data-action":a,onclick:this._triggerAction,onkeydown:this._triggerAction,"class":"esri-layer-list__item-actions-menu-item",role:"button",tabindex:"0",title:a.title},c.jsxFactory.createElement("span",{classes:b,styles:d}))}var f};
b.prototype._watchActionSectionChanges=function(a,d){var b=this;this._handleRegistry.add(a.on("change",this.scheduleRender.bind(this)),"action-section"+d);a.forEach(function(a){return b._renderOnActionChanges(a,d)})};b.prototype._renderOnActionChanges=function(a,d){var b=this;this._handleRegistry.add([k.init(a,"className, image, id, title, visible",function(){return b.scheduleRender()})],"actions"+d)};b.prototype._renderOnItemChanges=function(a){var d=this,b=a.uid;this._handleRegistry.add([k.init(a,
"actionsOpen, visible, open, updating, title, visibleAtCurrentScale, error, visibilityMode",function(){return d.scheduleRender()}),a.actionsSections.on("change",function(){return d.scheduleRender()}),a.children.on("change",function(){return d.scheduleRender()})],"items"+b);a.children.forEach(function(a){return d._renderOnItemChanges(a)});a.actionsSections.forEach(function(a){return d._watchActionSectionChanges(a,b)})};b.prototype._itemsChanged=function(a){var d=this;this._handleRegistry.removeAll();
a.forEach(function(a){return d._renderOnItemChanges(a)});this.scheduleRender()};b.prototype._renderActionsSections=function(a,d,b){var e=this;d=d.toArray().map(function(d){return c.jsxFactory.createElement("ul",{key:a.uid+"__actions-list","class":"esri-layer-list__item-actions-list"},e._renderActionSection(d))});return c.jsxFactory.createElement("div",{key:a.uid+"__actions-section",id:b,"class":"esri-layer-list__item-actions",hidden:a.actionsOpen?null:!0},d)};b.prototype._renderActionSection=function(a){var d=
this;return(a&&a.toArray()).map(function(a){return d._renderAction(a)})};b.prototype._renderAction=function(a){var d=this._getActionImageStyles(a),b=(e={},e[a.className]=a.className,e["esri-layer-list__item-action-image"]=d["background-image"],e);return c.jsxFactory.createElement("li",{key:a.uid+"__action",bind:this,"data-action":a,onclick:this._triggerAction,onkeydown:this._triggerAction,"class":"esri-layer-list__item-action",tabindex:"0",role:"button",title:a.title},c.jsxFactory.createElement("span",
{"aria-hidden":"true","class":"esri-layer-list__item-action-icon",classes:b,styles:d}),c.jsxFactory.createElement("span",{"class":"esri-layer-list__item-action-title"},a.title));var e};b.prototype._countActions=function(a){return a.reduce(function(a,b){return a+b.length},0)};b.prototype._getActionImageStyles=function(a){var b=a.image||null;!a.className&&!b&&(b=y);return{"background-image":b?'url("'+b+'")':null}};b.prototype._toggleActionsOpen=function(a){a=a.currentTarget["data-item"];a.actionsOpen=
!a.actionsOpen};b.prototype._triggerAction=function(a){this.triggerAction(a.currentTarget["data-action"])};b.prototype._labelClick=function(a){var b=a.currentTarget;a=b.getAttribute("data-parent-visibility");b=b["data-item"];"exclusive"===a&&b.visible||(b.visible=!b.visible)};b.prototype._toggleChildrenClick=function(a){a=a.currentTarget["data-item"];a.open=!a.open};e([g.aliasOf("viewModel.createActionsFunction"),c.renderable()],b.prototype,"createActionsFunction",void 0);e([g.property(),c.renderable()],
b.prototype,"errorsVisible",void 0);e([g.aliasOf("viewModel.operationalItems"),c.renderable()],b.prototype,"operationalItems",void 0);e([g.aliasOf("viewModel.view"),c.renderable()],b.prototype,"view",void 0);e([c.vmEvent("trigger-action"),g.property({type:r}),c.renderable("viewModel.state")],b.prototype,"viewModel",void 0);e([g.aliasOf("viewModel.triggerAction")],b.prototype,"triggerAction",void 0);e([c.accessibleHandler()],b.prototype,"_toggleActionsOpen",null);e([c.accessibleHandler()],b.prototype,
"_triggerAction",null);e([c.accessibleHandler()],b.prototype,"_labelClick",null);e([c.accessibleHandler()],b.prototype,"_toggleChildrenClick",null);return b=e([g.subclass("esri.widgets.LayerList")],b)}(g.declared(w))});