// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ./Print/PrintViewModel ../tasks/support/PrintTemplate ../core/watchUtils ./Widget ./support/widget dojo/i18n!./Print/nls/Print".split(" "),function(s,t,n,f,h,l,p,q,r,a,b){return function(m){function c(){m.call(this);this._attribution=!0;this._exportedFileNameMap={};this._legend=this._layoutTabSelected=!0;this._pendingExportScroll=this._advancedOptionsVisible=!1;this._selectedTemplate=
new p;this._scaleEnabled=!1;this.view=this._viewpoint=this._extent=this._templatesInfo=null;this.viewModel=new l;this.printServiceUrl=null}n(c,m);c.prototype.postInitialize=function(){var a=this;this.viewModel.getPrintTemplatesFromService().then(function(b){a._templatesInfo=b;a._selectedTemplate.layout=a._templatesInfo.layout.defaultValue;a._selectedTemplate.format=a._templatesInfo.format.defaultValue;"MAP_ONLY"===a._selectedTemplate.layout&&(a._layoutTabSelected=!1);a.scheduleRender()});q.init(this.viewModel.view,
"scale",function(b){a._scaleEnabled||(a._scale=b,a.scheduleRender())});this._width=this._selectedTemplate.exportOptions.width;this._height=this._selectedTemplate.exportOptions.height};c.prototype.render=function(){var k=this,c=a.jsxFactory.createElement("div",{key:"title-section","class":"esri-print__form-section-container"},a.jsxFactory.createElement("label",{"for":this.id+"__title"},this._layoutTabSelected?b.title:b.fileName),a.jsxFactory.createElement("input",{id:this.id+"__title",name:"title",
type:"text",tabIndex:0,placeholder:this._layoutTabSelected?b.titlePlaceHolder:b.fileNamePlaceHolder,"class":"esri-print__input-text",oninput:this._updateInputValue,bind:this})),d=this.get("_templatesInfo.format.choiceList")||[],d=0<d.length?d.map(function(b){return a.jsxFactory.createElement("option",{key:b},b)}):a.jsxFactory.createElement("option",{key:"format-default-option"},b.formatDefaultOption),d=a.jsxFactory.createElement("div",{key:"file-format-section","class":"esri-print__form-section-container"},
a.jsxFactory.createElement("label",{"for":this.id+"__formats"},b.fileFormatTitle),a.jsxFactory.createElement("select",{id:this.id+"__formats",onchange:this._updateFromOption,"data-target-property":"format",bind:this},d)),e=this.get("_templatesInfo.layout.choiceList")||[],e=0<e.length?e.map(function(b){return a.jsxFactory.createElement("option",{key:b,bind:k},b)}):a.jsxFactory.createElement("option",{key:"layout-default-option"},b.layoutDefaultOption),e=a.jsxFactory.createElement("div",{key:"page-setup-section",
"class":"esri-print__form-section-container"},a.jsxFactory.createElement("label",{"for":this.id+"__layouts"},b.layoutTitle),a.jsxFactory.createElement("select",{id:this.id+"__layouts",onchange:this._updateFromOption,"data-target-property":"layout",bind:this},e)),f=this._advancedOptionsVisible?a.jsxFactory.createElement("div",{"aria-labelledby":this.id+"__advancedOptions","class":"esri-print__advanced-options-container"},a.jsxFactory.createElement("div",{"class":a.join("esri-print__scale-info-container",
"esri-print__form-section-container")},a.jsxFactory.createElement("input",{id:this.id+"__scaleEnabled",name:"scaleEnabled",type:"checkbox",tabIndex:0,onchange:this._toggleInputValue,bind:this}),a.jsxFactory.createElement("label",{"for":this.id+"__scaleEnabled"},b.scale),a.jsxFactory.createElement("div",{"class":"esri-print__scale-input-container"},a.jsxFactory.createElement("input",{id:this.id+"__scale","aria-label":b.scaleLabel,type:"number",name:"scale","class":a.join("esri-print__input-text","esri-print__scale-input"),
tabIndex:0,oninput:this._updateInputValue,disabled:!this._scaleEnabled,value:""+this._scale,bind:this}),a.jsxFactory.createElement("button",{role:"button","aria-label":b.reset,"class":a.join("esri-widget-button","esri-print__refresh-button","esri-icon-refresh"),tabIndex:0,onclick:this._resetToCurrentScale,bind:this}))),a.jsxFactory.createElement("div",{"class":a.join("esri-print__author-info-container","esri-print__form-section-container")},a.jsxFactory.createElement("label",{"for":this.id+"__author"},
b.author),a.jsxFactory.createElement("input",{id:this.id+"__author",type:"text",name:"author","class":"esri-print__input-text",tabIndex:0,oninput:this._updateInputValue,bind:this})),a.jsxFactory.createElement("div",{"class":a.join("esri-print__copyright-info-container","esri-print__form-section-container")},a.jsxFactory.createElement("label",{"for":this.id+"__copyright"},b.copyright),a.jsxFactory.createElement("input",{id:this.id+"__copyright",type:"text",name:"copyright","class":"esri-print__input-text",
tabIndex:0,oninput:this._updateInputValue,bind:this})),a.jsxFactory.createElement("div",{"class":a.join("esri-print__legend-info-container","esri-print__form-section-container")},a.jsxFactory.createElement("input",{id:this.id+"__legend",type:"checkbox",name:"legend",tabIndex:0,checked:!0,onchange:this._toggleInputValue,bind:this}),a.jsxFactory.createElement("label",{"for":this.id+"__legend"},b.legend))):null,c=this._layoutTabSelected?a.jsxFactory.createElement("section",{id:this.id+"__layoutContent",
key:"layout-content","aria-labelledby":this.id+"__layoutTab","class":"esri-print__layout-section"},a.jsxFactory.createElement("div",{key:"layout","class":"esri-print__panel-container"},c,e,this._layoutTabSelected?d:null),a.jsxFactory.createElement("div",{key:"advanced-section","class":a.join("esri-print__panel-container","esri-print__advanced-options-section")},a.jsxFactory.createElement("button",{id:this.id+"__advancedOptions","aria-label":b.advancedOptions,"aria-expanded":this._advancedOptionsVisible?
"true":"false",role:"button","class":"esri-print__advanced-options-button",onclick:this._showAdvancedOptions,bind:this},a.jsxFactory.createElement("div",{"class":"esri-print__advanced-options-button-container"},a.jsxFactory.createElement("span",{"aria-hidden":"true","class":a.join("esri-icon-right-triangle-arrow","esri-print__advanced-options-button-icon--closed")}),a.jsxFactory.createElement("span",{"aria-hidden":"true","class":a.join("esri-icon-left-triangle-arrow","esri-print__advanced-options-button-icon--closed-rtl")}),
a.jsxFactory.createElement("span",{"aria-hidden":"true","class":a.join("esri-icon-down-arrow","esri-print__advanced-options-button-icon--opened")}),a.jsxFactory.createElement("span",{"class":"esri-print__advanced-options-button-title"},b.advancedOptions))),f)):a.jsxFactory.createElement("section",{id:this.id+"__mapOnlyContent","aria-labelledby":this.id+"__mapOnlyTab",key:"map-only-content","class":"esri-print__map-only-section"},a.jsxFactory.createElement("div",{key:"mapOnly","class":"esri-print__panel-container"},
c,this._layoutTabSelected?null:d,a.jsxFactory.createElement("div",{"class":a.join("esri-print__size-container","esri-print__form-section-container")},a.jsxFactory.createElement("div",{"class":"esri-print__width-container"},a.jsxFactory.createElement("label",{"for":"width"},b.width),a.jsxFactory.createElement("input",{id:this.id+"__width",type:"text",name:"width","class":"esri-print__input-text",onchange:this._updateInputValue,value:""+this._width,tabIndex:0,bind:this})),a.jsxFactory.createElement("div",
{"class":"esri-print__height-container"},a.jsxFactory.createElement("label",{"for":"height"},b.height),a.jsxFactory.createElement("input",{id:this.id+"__height",type:"text",name:"height","class":"esri-print__input-text",onchange:this._updateInputValue,value:""+this._height,tabIndex:0,bind:this})),a.jsxFactory.createElement("button",{role:"button","aria-label":b.swap,"class":a.join("esri-widget-button","esri-print__swap-button","esri-icon-swap"),onclick:this._switchInput,tabIndex:0,bind:this})),a.jsxFactory.createElement("div",
{key:"attribution-container","class":"esri-print__form-section-container"},a.jsxFactory.createElement("input",{id:this.id+"__attribution",name:"attribution",type:"checkbox",onchange:this._toggleInputValue,tabIndex:0,checked:!0,bind:this}),a.jsxFactory.createElement("label",{"for":"attribution"},b.attribution)))),d=this.exportedLinks.toArray(),e=(g={},g["esri-disabled"]=!this._selectedTemplate.layout&&!this._selectedTemplate.format,g),g=a.jsxFactory.createElement("div",{id:this.id+"__printContainer",
key:"print-widget-panel"},a.jsxFactory.createElement("div",{"class":"esri-print__container"},a.jsxFactory.createElement("header",{"class":"esri-print__header-title"},b.export),a.jsxFactory.createElement("ul",{"class":"esri-print__layout-tab-list",role:"tablist",onclick:this._toggleLayoutPanel,onkeydown:this._toggleLayoutPanel,bind:this},a.jsxFactory.createElement("li",{id:this.id+"__layoutTab","data-tab-id":"layoutTab","class":"esri-print__layout-tab",role:"tab",tabIndex:0,"aria-selected":""+this._layoutTabSelected,
bind:this},b.layoutTab),a.jsxFactory.createElement("li",{id:this.id+"__mapOnlyTab","data-tab-id":"mapOnlyTab","class":"esri-print__layout-tab",role:"tab",tabIndex:0,"aria-selected":""+!this._layoutTabSelected,bind:this},b.mapOnlyTab)),c,a.jsxFactory.createElement("button",{"aria-label":b.export,role:"button","class":"esri-print__export-button",tabIndex:0,classes:e,onclick:this._handlePrintMap,bind:this},b.export),a.jsxFactory.createElement("div",{id:this.id+"__exportedFilesContainer","class":"esri-print__export-panel-container",
afterUpdate:this._scrollExportIntoView,bind:this},a.jsxFactory.createElement("h2",{"class":"esri-print__export-title"},b.exportText),0<d.length?null:a.jsxFactory.createElement("div",{key:"exported-section-hints"},a.jsxFactory.createElement("div",null,b.exportHint)),d.map(function(b){var k=(c={},c["esri-icon-loading-indicator"]="pending"===b.state,c["esri-rotating"]="pending"===b.state,c["esri-icon-download"]="ready"===b.state,c["esri-icon-error"]="error"===b.state,c),c=(d={},d["esri-disabled"]="ready"!==
b.state,d),d=""===b.url?null:b.url;return a.jsxFactory.createElement("div",{key:b.name,"class":"esri-print__exported-file"},a.jsxFactory.createElement("a",{href:d,classes:k,tabIndex:0,download:!0}),a.jsxFactory.createElement("a",{href:d,classes:c,tabIndex:0,target:"_blank"},b.name));var c,d}))));return a.jsxFactory.createElement("div",{"class":"esri-print esri-widget"},g);var g};c.prototype._configurePrintTemplate=function(){this._selectedTemplate.attributionVisible=this._attribution;this._width&&
(this._selectedTemplate.exportOptions.width=this._width);this._height&&(this._selectedTemplate.exportOptions.height=this._height);this._selectedTemplate.layoutOptions={titleText:this._title||"",authorText:this._author||"",copyrightText:this._copyright||""};this._legend||(this._selectedTemplate.layoutOptions.legendLayers=[]);this.scale=this._scale;this._scaleEnabled&&(this._extent=this.viewModel.getExtent(this._viewpoint,this.scale,this.viewModel.view.size))};c.prototype._resetToCurrentScale=function(){this._scale=
this.viewModel.view.scale};c.prototype._updateInputValue=function(a){a=a.target;this["_"+a.name]=a.value};c.prototype._handlePrintMap=function(){var a=this;this._configurePrintTemplate();var c=this._title||b.untitled,d=-1<this._selectedTemplate.format.toLowerCase().indexOf("png")?"png":this._selectedTemplate.format.toLowerCase(),e=c+"."+d,f=e;void 0!==this._exportedFileNameMap[e]?(this._exportedFileNameMap[e]++,f=c+"("+this._exportedFileNameMap[e]+")."+d):this._exportedFileNameMap[e]=0;this.viewModel.addExportedLinks(f);
var g=this.exportedLinks.length-1;this._pendingExportScroll=!0;(null!=this._extent?this.viewModel.print(this._selectedTemplate,this._extent):this.viewModel.print(this._selectedTemplate)).then(function(b){var c=a.exportedLinks.getItemAt(g);c.url=b.url;c.state="ready";a.scheduleRender()},function(){a.exportedLinks.getItemAt(g).state="error"})};c.prototype._updateFromOption=function(a){var b=a.target;a=b.selectedOptions[0].value;var c=this._selectedTemplate,b=b.getAttribute("data-target-property");c[b]=
a};c.prototype._switchInput=function(){a=[this._height,this._width];this._width=a[0];this._height=a[1];var a};c.prototype._showAdvancedOptions=function(){this._advancedOptionsVisible=!this._advancedOptionsVisible};c.prototype._scrollExportIntoView=function(a){this._pendingExportScroll&&(this._pendingExportScroll=!1,a.scrollIntoView())};c.prototype._toggleInputValue=function(a){a=a.target;var b="_"+a.name;this[b]=a.checked;"_scaleEnabled"===b&&(this[b]?this._viewpoint=this.viewModel.view.viewpoint.clone():
(this._resetToCurrentScale(),this._extent=null))};c.prototype._resetInputValue=function(){this._title="";this._selectedTemplate.format=this._templatesInfo.format.defaultValue};c.prototype._toggleLayoutPanel=function(a){this._resetInputValue();(this._layoutTabSelected="layoutTab"===a.target.getAttribute("data-tab-id"))?(a=this.get("_templatesInfo.layout.choiceList"),this._selectedTemplate.layout=a&&a[0]):this._selectedTemplate.layout="MAP_ONLY"};f([h.aliasOf("viewModel.view"),a.renderable()],c.prototype,
"view",void 0);f([h.property({type:l})],c.prototype,"viewModel",void 0);f([h.aliasOf("viewModel.printServiceUrl")],c.prototype,"printServiceUrl",void 0);f([h.aliasOf("viewModel.scale"),a.renderable()],c.prototype,"scale",void 0);f([h.aliasOf("viewModel.exportedLinks"),a.renderable()],c.prototype,"exportedLinks",void 0);f([a.accessibleHandler()],c.prototype,"_toggleLayoutPanel",null);return c=f([h.subclass("esri.widgets.Print")],c)}(h.declared(r))});