// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dgrid/OnDemandGrid ./ColorRampSelector dijit/TitlePane ../core/accessorSupport/decorators ./Widget ./RasterSymbologyEditor/RasterSymbologyEditorViewModel dojo/dom-construct dojo/store/Memory dijit/form/FilteringSelect dijit/form/NumberTextBox dijit/form/CheckBox dijit/form/NumberSpinner ./support/widget dojo/i18n!./RasterSymbologyEditor/nls/RasterSymbologyEditor".split(" "),function(F,G,A,f,B,x,t,e,C,y,
h,l,k,q,D,E,c,g){var d={base:"esri-raster-symbology-editor",filteringSelect:"esri-raster-symbology-editor__filtering-select",stretchColorSchemeRow:"esri-raster-symbology-editor__stretch-color-ramp-row",percentClipOptionsRow:"esri-raster-symbology-editor__percent-clip-row",stdDeviationOptionsRow:"esri-raster-symbology-editor__std-deviation-row",stretchOptionsBlock:"esri-raster-symbology-editor__stretch-options",stretchGammaBlock:"esri-raster-symbology-editor__stretch-gamma-row",stretchDraBlock:"esri-raster-symbology-editor__stretch-dra-row",
displayHidden:"esri-raster-symbology-editor--hidden",displayBlock:"esri-raster-symbology-editor--block",table:"esri-raster-symbology-editor__table",thumbnailImage:"esri-raster-symbology-editor__thumbnail-image",bandCombinationPresetNaturalColorImg:"esri-raster-symbology-editor__band-combination-natural-color-img",bandCombinationPresetLanduseImg:"esri-raster-symbology-editor__band-combination-landuse-img",bandCombinationPresetLandWaterImg:"esri-raster-symbology-editor__band-combination-land-water-img",
bandCombinationPresetVegetationImg:"esri-raster-symbology-editor__band-combination-vegetation-img",bandCombinationPresetShallowBathymetricImg:"esri-raster-symbology-editor__band-combination-bathymetric-img",bandCombinationPresetColorInfraredImg:"esri-raster-symbology-editor__band-combination-color-infrared-img",minMaxStretchTypeImg:"esri-raster-symbology-editor__stretch-type-min-max-img",noneStretchTypeImg:"esri-raster-symbology-editor__stretch-type-none-img",standardDeviationStretchTypeImg:"esri-raster-symbology-editor__stretch-type-standard-deviation-img",
percentClipStretchTypeImg:"esri-raster-symbology-editor__stretch-type-percent-clip-img",rgbSymbologyTypeImg:"esri-raster-symbology-editor__symbology-type-rgb-img",stretchSymbologyTypeImg:"esri-raster-symbology-editor__symbology-type-stretch-img",uniqueValueSymbologyTypeImg:"esri-raster-symbology-editor__symbology-type-unique-value-img",menuItemTd:"esri-raster-symbology-editor__menu-item-td",dgridSymbolCell:"esri-raster-symbology-editor__dgrid-symbol-cell",menuItemText:"esri-raster-symbology-editor__menu-item-text",
checkbox:"esri-raster-symbology-editor__checkbox"};return function(z){function b(){z.apply(this,arguments);this.defaultParams=this.layer=null;this.viewModel=new y;this._components=[];this._stretchTitlePane=this._stretchTypeSelect=this._noDataInput=this._stretchColorRampSelect=this._bandSelect=this._noDataTitlePane=this._colorSchemeTitlePane=this._symbologySelect=null;this.stretchType=0;this.symbologyType="";this._stretchStatisticsCheckBox=this._standardDeviationsInput=this._gammaInput=this._maxPercentInput=
this._minPercentInput=null;this._supportsBandPresets=!1;this._uniqueValuesSymbolData=this._uniqueValuesGrid=this._uniqueValueNoDataInput=this._uniqueValueColorSchemeSelect=this._uniqueValueFieldSelect=this._blueBandSelect=this._greenBandSelect=this._redBandSelect=this._bandCombinationPresetSelect=this._bandCombinationTitlePane=null;this._showLoadingGif=!1}A(b,z);b.prototype.postInitialize=function(a){this.defaultParams=this.viewModel.getDefaultRenderParameters();this._createUIComponents()};b.prototype.destroy=
function(){this._components.forEach(function(a){a&&a.destroy()})};b.prototype.render=function(){var a=this.symbologyType,b=this.stretchType,e=this.viewModel.isStretchColorRampApplicable(b),f=c.jsxFactory.createElement("div",null,c.jsxFactory.createElement("div",{afterCreate:this._placeSymbologySelect,bind:this})),e=c.jsxFactory.createElement("div",{classes:(r={},r[d.displayBlock]="stretch"===a,r[d.displayHidden]="stretch"!==a,r)},c.jsxFactory.createElement("div",{afterCreate:this._createColorSchemeTitlePane,
bind:this},c.jsxFactory.createElement("table",{"class":d.table},c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.bandSelectionLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeBandSelect,bind:this}))),c.jsxFactory.createElement("tr",{classes:(s={},s[d.stretchColorSchemeRow]=e,s[d.displayHidden]=!e,s)},c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.colorSchemeLabel)),
c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeColorRampSelect,bind:this})))))),r=c.jsxFactory.createElement("div",{classes:(h={},h[d.displayBlock]="stretch"===a||"rgb"===a,h[d.displayHidden]="stretch"!==a,h)},c.jsxFactory.createElement("div",{afterCreate:this._createNoDataTitlePane,bind:this},c.jsxFactory.createElement("table",{"class":d.table},c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",
null,g.noDataLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeNoDataInput,bind:this})))))),h=c.jsxFactory.createElement("div",{afterCreate:this._placeStretchTypeSelect,bind:this}),s=c.jsxFactory.createElement("tr",{classes:(m={},m[d.percentClipOptionsRow]=6===b,m[d.displayHidden]=6!==b,m)},c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.minLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",
{afterCreate:this._placeMinPercentInput,bind:this})),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.maxLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeMaxPercentInput,bind:this}))),m=c.jsxFactory.createElement("tr",{classes:(k={},k[d.stdDeviationOptionsRow]=3===b,k[d.displayHidden]=3!==b,k)},c.jsxFactory.createElement("td",{colSpan:2},c.jsxFactory.createElement("label",null,g.nStdDeviationsLabel)),c.jsxFactory.createElement("td",
{colSpan:2},c.jsxFactory.createElement("div",{afterCreate:this._placeStandardDeviationsInput,bind:this}))),b=c.jsxFactory.createElement("div",{classes:(n={},n[d.displayBlock]="stretch"===a||"rgb"===a,n[d.displayHidden]="stretch"!==a,n)},c.jsxFactory.createElement("div",{afterCreate:this._createStretchTitlePane,bind:this},c.jsxFactory.createElement("table",{"class":d.table},c.jsxFactory.createElement("tr",{"class":d.stretchOptionsBlock},c.jsxFactory.createElement("td",{colSpan:2},c.jsxFactory.createElement("label",
null,g.stretchTypeLabel)),c.jsxFactory.createElement("td",{colSpan:2},h)),s,m,c.jsxFactory.createElement("tr",{classes:(p={},p[d.stretchGammaBlock]=0!==b,p[d.displayHidden]=0===b,p)},c.jsxFactory.createElement("td",{colSpan:2},c.jsxFactory.createElement("label",null,g.gammaLabel)),c.jsxFactory.createElement("td",{colSpan:2},c.jsxFactory.createElement("div",{afterCreate:this._placeGammaInput,bind:this}))),c.jsxFactory.createElement("tr",{classes:(u={},u[d.stretchDraBlock]=0!==b,u[d.displayHidden]=
0===b,u)},c.jsxFactory.createElement("td",{colSpan:4},c.jsxFactory.createElement("div",{"class":d.checkbox,afterCreate:this._placeStretchStatisticsCheckbox,bind:this}),c.jsxFactory.createElement("label",null,g.draStatisticsTitle)))))),n=c.jsxFactory.createElement("div",{classes:(v={},v[d.displayBlock]="rgb"===a,v[d.displayHidden]="rgb"!==a,v)},c.jsxFactory.createElement("div",{afterCreate:this._createBandCombinationTitlePane,bind:this},c.jsxFactory.createElement("table",{"class":d.table},c.jsxFactory.createElement("tr",
{classes:(w={},w[d.stdDeviationOptionsRow]=this._supportsBandPresets,w[d.displayHidden]=!this._supportsBandPresets,w)},c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.bandCombinationPresetLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeBandCombinationPresetSelect,bind:this}))),c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.redBandTitle)),c.jsxFactory.createElement("td",
null,c.jsxFactory.createElement("div",{afterCreate:this._placeRedBandSelect,bind:this}))),c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.greenBandTitle)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeGreenBandSelect,bind:this}))),c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.blueBandTitle)),c.jsxFactory.createElement("td",
null,c.jsxFactory.createElement("div",{afterCreate:this._placeBlueBandSelect,bind:this})))))),a=c.jsxFactory.createElement("div",{classes:(l={},l[d.displayBlock]="uniqueValue"===a,l[d.displayHidden]="uniqueValue"!==a,l)},c.jsxFactory.createElement("div",null,c.jsxFactory.createElement("table",{"class":d.table},c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.valueFieldTitle)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",
{afterCreate:this._placeUniqueValueFieldSelect,bind:this}))),c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.colorSchemeLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",{afterCreate:this._placeUniqueValueColorSchemeSelect,bind:this}))),c.jsxFactory.createElement("tr",null,c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("label",null,g.noDataLabel)),c.jsxFactory.createElement("td",null,c.jsxFactory.createElement("div",
{afterCreate:this._placeUniqueValueNoDataInput,bind:this})))),c.jsxFactory.createElement("div",{afterCreate:this._placeUniqueValuesGrid,bind:this})));return c.jsxFactory.createElement("div",null,f,e,n,r,b,a);var r,s,h,m,k,n,p,u,v,w,l};b.prototype._createUIComponents=function(){this._createSymbologySelect();this._createStretchStatisticsCheckbox();this._createBandSelect();this._createStretchTypeSelect();this._createColorRampSelect();this._createBandCombinationPresetSelect();this._createRedBandSelect();
this._createGreenBandSelect();this._createBlueBandSelect();this._createNoDataInput();this._createMinPercentInput();this._createMaxPercentInput();this._createStandardDeviationsInput();this._createGammaInput();this._createUniqueValueFieldSelect();this._createUniqueValueColorSchemeSelect();this._createUniqueValueNoDataInput();this._createUniqueValuesGrid()};b.prototype._createSymbologySelect=function(){var a=this;this._symbologySelect=new k({store:this._getSymbologyStore(),"class":d.filteringSelect,
labelAttr:"label",labelType:"html",onChange:function(b){a._updateSymbologyType(b)},value:this.defaultParams.symbologyType});this._components.push(this._symbologySelect);this._symbologySelect.startup()};b.prototype._createStretchStatisticsCheckbox=function(){var a=this;this._stretchStatisticsCheckBox=new D({onChange:function(){a._updateSymbology()}});this._components.push(this._stretchStatisticsCheckBox);this._stretchStatisticsCheckBox.startup()};b.prototype._createColorSchemeTitlePane=function(a){this._colorSchemeTitlePane=
new t({title:g.colorRampTitle},a);this._components.push(this._colorSchemeTitlePane);this._colorSchemeTitlePane.startup()};b.prototype._createNoDataTitlePane=function(a){this._noDataTitlePane=new t({title:g.backgroundTitle},a);this._components.push(this._noDataTitlePane);this._noDataTitlePane.startup()};b.prototype._createStretchTitlePane=function(a){this._stretchTitlePane=new t({title:g.stretchTitle},a);this._components.push(this._stretchTitlePane);this._stretchTitlePane.startup()};b.prototype._createBandCombinationTitlePane=
function(a){this._bandCombinationTitlePane=new t({title:g.bandCombinationTitle},a);this._components.push(this._bandCombinationTitlePane);this._bandCombinationTitlePane.startup()};b.prototype._createBandSelect=function(){var a=this;this._bandSelect=new k({"class":d.filteringSelect,onChange:function(){a._updateSymbology()}});this._components.push(this._bandSelect);this._bandSelect.startup();this._populateBandSelect()};b.prototype._createStretchTypeSelect=function(){var a=this;this._stretchTypeSelect=
new k({"class":d.filteringSelect,onChange:function(b){a._onStretchTypeChange(b)},labelAttr:"label",labelType:"html"});this._components.push(this._stretchTypeSelect);this._stretchTypeSelect.startup();this._populateStretchTypeSelect()};b.prototype._createColorRampSelect=function(){var a=this;this._stretchColorRampSelect=new x({"class":d.filteringSelect,maxHeight:300});this._components.push(this._stretchColorRampSelect);this._stretchColorRampSelect.on("change",function(){a._updateSymbology()});this._stretchColorRampSelect.startup()};
b.prototype._createBandCombinationPresetSelect=function(){var a=this;this._bandCombinationPresetSelect=new k({"class":d.filteringSelect,onChange:function(b){a._updateBandCombination(b)},labelType:"html",labelAttr:"label",maxHeight:350});this._components.push(this._bandCombinationPresetSelect);this._bandCombinationPresetSelect.startup()};b.prototype._createRedBandSelect=function(){var a=this;this._redBandSelect=new k({"class":d.filteringSelect,onChange:function(){a._bandCombinationChanged()}});this._components.push(this._redBandSelect);
this._redBandSelect.startup();this._populateBandLists()};b.prototype._createGreenBandSelect=function(){var a=this;this._greenBandSelect=new k({"class":d.filteringSelect,onChange:function(){a._bandCombinationChanged()}});this._components.push(this._greenBandSelect);this._greenBandSelect.startup();this._populateBandLists()};b.prototype._createBlueBandSelect=function(){var a=this;this._blueBandSelect=new k({"class":d.filteringSelect,onChange:function(){a._bandCombinationChanged()}});this._components.push(this._blueBandSelect);
this._blueBandSelect.startup();this._populateBandLists()};b.prototype._createNoDataInput=function(){var a=this;this._noDataInput=new q({"class":d.filteringSelect,onChange:function(){a._updateSymbology()}});this._components.push(this._noDataInput);this._noDataInput.startup()};b.prototype._createMinPercentInput=function(){var a=this;this._minPercentInput=new q({"class":d.filteringSelect,onChange:function(){a._updateSymbology()},value:this.defaultParams.minPercent});this._components.push(this._minPercentInput);
this._minPercentInput.startup()};b.prototype._createMaxPercentInput=function(){var a=this;this._maxPercentInput=new q({"class":d.filteringSelect,onChange:function(){a._updateSymbology()},value:this.defaultParams.maxPercent});this._components.push(this._maxPercentInput);this._maxPercentInput.startup()};b.prototype._createStandardDeviationsInput=function(){var a=this;this._standardDeviationsInput=new q({"class":d.filteringSelect,onChange:function(){a._updateSymbology()},value:this.defaultParams.numberOfStandardDeviations});
this._components.push(this._standardDeviationsInput);this._standardDeviationsInput.startup()};b.prototype._createGammaInput=function(){var a=this;this._gammaInput=new E({"class":d.filteringSelect,onChange:function(){a._updateSymbology()},value:this.defaultParams.gamma,smallDelta:0.1});this._components.push(this._gammaInput);this._gammaInput.startup()};b.prototype._createUniqueValueFieldSelect=function(){var a=this;this._uniqueValueFieldSelect=new k({"class":d.filteringSelect,onChange:function(){a._updateUniqueValueGrid()}});
this._components.push(this._uniqueValueFieldSelect);this._populateUniqueValueFieldSelect()};b.prototype._createUniqueValueColorSchemeSelect=function(){var a=this;this._uniqueValueColorSchemeSelect=new x({"class":d.filteringSelect,maxHeight:300});this._components.push(this._uniqueValueColorSchemeSelect);this._uniqueValueColorSchemeSelect.on("change",function(){a._updateUniqueValueGrid()});this._uniqueValueColorSchemeSelect.startup()};b.prototype._createUniqueValueNoDataInput=function(){var a=this;
this._uniqueValueNoDataInput=new q({"class":d.filteringSelect,onChange:function(){a._updateSymbology()}});this.defaultParams.uniqueValuesColorRamp&&(this.defaultParams.uniqueValuesColorRamp.name=g.uniqueValuesColorRampTitle,this._uniqueValueColorSchemeSelect.addColorRamp(this.defaultParams.uniqueValuesColorRamp,!0));this._components.push(this._uniqueValueNoDataInput);this._uniqueValueNoDataInput.startup()};b.prototype._createUniqueValuesGrid=function(){this._uniqueValuesGrid=new B({columns:[{field:"esriRasterSymbologyEditorUniqueValueSymbol",
renderCell:function(a,b,c){c.innerHTML="\x3cdiv class \x3d "+d.dgridSymbolCell+' \n          style \x3d "background: rgb( '+a.esriRasterSymbologyEditorUniqueValueSymbol.r+", \n          "+a.esriRasterSymbologyEditorUniqueValueSymbol.g+", \n          "+a.esriRasterSymbologyEditorUniqueValueSymbol.b+'");\x3e\x3c/div\x3e'},label:g.symbolLabel},{field:"esriRasterSymbologyEditorUniqueValueValue",label:g.valueLabel}]});this._components.push(this._uniqueValuesGrid);this._uniqueValuesGrid.startup()};b.prototype._placeSymbologySelect=
function(a){this._symbologySelect&&h.place(this._symbologySelect.domNode,a)};b.prototype._placeStretchStatisticsCheckbox=function(a){this._stretchStatisticsCheckBox&&h.place(this._stretchStatisticsCheckBox.domNode,a)};b.prototype._placeBandSelect=function(a){this._bandSelect&&h.place(this._bandSelect.domNode,a)};b.prototype._placeStretchTypeSelect=function(a){this._stretchTypeSelect&&h.place(this._stretchTypeSelect.domNode,a)};b.prototype._placeColorRampSelect=function(a){this._stretchColorRampSelect&&
h.place(this._stretchColorRampSelect.domNode,a)};b.prototype._placeBandCombinationPresetSelect=function(a){this._bandCombinationPresetSelect&&h.place(this._bandCombinationPresetSelect.domNode,a)};b.prototype._placeRedBandSelect=function(a){this._redBandSelect&&h.place(this._redBandSelect.domNode,a)};b.prototype._placeGreenBandSelect=function(a){this._colorSchemeTitlePane&&h.place(this._greenBandSelect.domNode,a)};b.prototype._placeBlueBandSelect=function(a){this._blueBandSelect&&h.place(this._blueBandSelect.domNode,
a)};b.prototype._placeNoDataInput=function(a){this._noDataInput&&h.place(this._noDataInput.domNode,a)};b.prototype._placeMinPercentInput=function(a){this._minPercentInput&&h.place(this._minPercentInput.domNode,a)};b.prototype._placeMaxPercentInput=function(a){this._maxPercentInput&&h.place(this._maxPercentInput.domNode,a)};b.prototype._placeStandardDeviationsInput=function(a){this._standardDeviationsInput&&h.place(this._standardDeviationsInput.domNode,a)};b.prototype._placeGammaInput=function(a){this._gammaInput&&
h.place(this._gammaInput.domNode,a)};b.prototype._placeUniqueValueFieldSelect=function(a){this._uniqueValueFieldSelect&&h.place(this._uniqueValueFieldSelect.domNode,a)};b.prototype._placeUniqueValueColorSchemeSelect=function(a){this._uniqueValueColorSchemeSelect&&h.place(this._uniqueValueColorSchemeSelect.domNode,a)};b.prototype._placeUniqueValueNoDataInput=function(a){this._uniqueValueNoDataInput&&h.place(this._uniqueValueNoDataInput.domNode,a)};b.prototype._placeUniqueValuesGrid=function(a){this._uniqueValuesGrid&&
h.place(this._uniqueValuesGrid.domNode,a)};b.prototype._bandCombinationChanged=function(){this._redBandSelect&&(this._redBandSelect.validate()&&this._greenBandSelect&&this._greenBandSelect.validate()&&this._blueBandSelect&&this._blueBandSelect.validate())&&this._updateSymbology()};b.prototype._updateBandCombination=function(a){if("custom"===a)this._redBandSelect.set("disabled",!1),this._greenBandSelect.set("disabled",!1),this._blueBandSelect.set("disabled",!1);else{var b;this._bandCombinationPresetSelect.store.data.some(function(c){a===
c.id&&(b=c.combination)});b&&(this._redBandSelect.set({value:b[0]-1,disabled:!0}),this._greenBandSelect.set({value:b[1]-1,disabled:!0}),this._blueBandSelect.set({value:b[2]-1,disabled:!0}),this._updateSymbology())}};b.prototype._updateSymbologyType=function(a){this.symbologyType=a;this._updateSymbology()};b.prototype._updateUniqueValueGrid=function(){var a=this.viewModel.getUniqueValueGridData(this._uniqueValueColorSchemeSelect.colorRamp,this._uniqueValueFieldSelect.value);this._uniqueValuesGrid.refresh();
this._uniqueValuesGrid.renderArray(a);this._uniqueValuesSymbolData=a;this._updateSymbology()};b.prototype._populateUniqueValueFieldSelect=function(){var a=this.viewModel.getUniqueValueFields(),a=new l({data:a,idProperty:"name"});this._uniqueValueFieldSelect.set({store:a,labelAttr:"alias",value:this.defaultParams.uniqueValuesField})};b.prototype._populateStretchTypeSelect=function(){var a=this.viewModel.stretchTypes,b,c,e;a.forEach(function(a){b=g[a.name+"StretchTypeDescription"]||g[a.name+"TypeDescription"];
e=d[a.name+"StretchTypeImg"];c=g[a.name+"StretchTitle"];a.label="\x3chtml\x3e\x3cbody\x3e\x3csection\x3e\n        \x3ch4\x3e"+c+"\x3c/h4\x3e\n        \x3ctable\x3e\x3ctr\x3e\n          \x3ctd class\x3d"+d.menuItemTd+'\x3e\n            \x3cimg class\x3d"'+e+" "+d.thumbnailImage+'" /\x3e\n          \x3c/td\x3e\n          \x3ctd class\x3d'+d.menuItemTd+"\x3e\n            \x3cp class\x3d"+d.menuItemText+"\x3e\x3ci\x3e"+b+"\x3c/i\x3e\x3c/p\x3e\n          \x3c/td\x3e\n          \x3c/tr\x3e\x3c/table\x3e\n        \x3c/section\x3e\x3c/body\x3e\x3c/html\x3e";
a.name=c});this._stretchTypeSelect.set({store:new l({data:a}),value:this.defaultParams.stretchType,labelAttr:"label",labelType:"html"})};b.prototype._populateBandSelect=function(){var a=this,b;this.viewModel.getBandData().then(function(c){b=new l({data:c.lists[0],idProperty:"index"});a._bandSelect.set("store",b);1===c.lists[0].length&&a._bandSelect.set({value:c.lists[0][0].index,disabled:!0})})};b.prototype._populateBandLists=function(){var a=this;if(this._redBandSelect&&this._greenBandSelect&&this._blueBandSelect&&
this._bandCombinationPresetSelect){var b=[this._redBandSelect,this._greenBandSelect,this._blueBandSelect],c=[],e,f,h,k,m,n,q;this.viewModel.getBandData().then(function(p){p.lists.forEach(function(a,c){a.some(function(a){if(a.selected)return f=a.index,!0});h=new l({data:a,idProperty:"index"});b[c].set({store:h,value:f})});p.presets&&p.presets.length?(a._supportsBandPresets=!0,p.presets.forEach(function(a,b){e=Object.keys(a)[0];m=g["bandComboName"+e];n=g["bandComboDesc"+e];q=d["bandCombinationPreset"+
e+"Img"];c.push({name:g["bandComboName"+e],label:"\x3chtml\x3e\x3cbody\x3e\x3csection\x3e\n              \x3ch4\x3e"+m+"\x3c/h4\x3e\n              \x3ctable\x3e\x3ctr\x3e\n                \x3ctd class\x3d"+d.menuItemTd+'\x3e\n                  \x3cimg class\x3d "'+q+" "+d.thumbnailImage+'" /\x3e\n                \x3c/td\x3e\n                \x3ctd class\x3d'+d.menuItemTd+"\x3e\n                  \x3cp class\x3d"+d.menuItemText+"\x3e\x3ci\x3e"+n+"\x3c/i\x3e\x3c/p\x3e\n                \x3c/td\x3e\n              \x3c/tr\x3e\x3c/table\x3e\n            \x3c/section\x3e\x3c/body\x3e\x3c/html\x3e",
combination:a[e],id:e})}),c.push({name:g.bandComboNameCustom,combination:null,id:"custom",label:"\x3chtml\x3e\x3cbody\x3e\x3csection\x3e\n            \x3ch4\x3e "+g.bandComboNameCustom+":\x3c/h4\x3e\n            \x3ctable cellspacing\x3d'5'\x3e\n              \x3ctr\x3e\n                \x3ctd class\x3d"+d.menuItemTd+"\x3e\n                  \x3cp class\x3d"+d.menuItemText+"\x3e\x3ci\x3e"+g.bandComboNameCustom+"\x3c/i\x3e\x3c/p\x3e\n                \x3c/td\x3e\n              \x3c/tr\x3e\n            \x3c/table\x3e\n          \x3c/section\x3e\x3c/body\x3e\x3c/html\x3e"}),
k=new l({data:c}),a._bandCombinationPresetSelect.set({store:k,value:"custom"})):a._supportsBandPresets=!1;a.scheduleRender()})}};b.prototype._onStretchTypeChange=function(a){var b;this.viewModel.stretchTypes.forEach(function(c){c.id===a&&(b=c.filterType)});this.stretchType=b;this._updateSymbology()};b.prototype._updateSymbology=function(){if(this._symbologySelect&&this._stretchTypeSelect&&this._stretchColorRampSelect&&this._noDataInput&&this._minPercentInput&&this._maxPercentInput&&this._stretchTypeSelect&&
this._gammaInput&&this._standardDeviationsInput){var a=this._getProperties();this.viewModel.updateRendering(a)}};b.prototype._getProperties=function(){var a={};a.symbologyType=this._symbologySelect.value;a.stretchType=this.stretchType;a.minPercent=this._minPercentInput.value;a.maxPercent=this._maxPercentInput.value;a.numberOfStandardDeviations=this._standardDeviationsInput.value;a.noData="uniqueValue"===this.symbologyType?this._uniqueValueNoDataInput.value:this._noDataInput.value;a.gamma=this._gammaInput.value;
a.colorRampName=this._stretchColorRampSelect.colorRampName;a.dra=this._stretchStatisticsCheckBox.checked;a.selectedBand=this._bandSelect.value;a.bandIds=[this._redBandSelect.value,this._greenBandSelect.value,this._blueBandSelect.value];a.uniqueValuesColorRamp=this._uniqueValueColorSchemeSelect.colorRamp;a.uniqueValuesSymbolData=this._uniqueValuesSymbolData;return a};b.prototype._getSymbologyStore=function(){var a=[],b,c,e;this.viewModel.getSymbologyTypes().forEach(function(f){b=g[f+"Title"];c=g[f+
"Description"]||g[f+"Title"];e=d[f+"SymbologyTypeImg"];a.push({id:f,name:b,label:"\x3chtml\x3e\x3cbody\x3e\x3csection\x3e\n          \x3ch4\x3e"+b+"\x3c/h4\x3e\n          \x3ctable\x3e\x3ctr\x3e\n            \x3ctd class\x3d"+d.menuItemTd+"\x3e\x3cimg class\x3d "+e+" /\x3e\x3c/td\x3e\n            \x3ctd class\x3d"+d.menuItemTd+"\x3e\n              \x3cp class\x3d"+d.menuItemText+"\x3e\x3ci\x3e"+c+"\x3c/i\x3e\x3c/p\x3e\n            \x3c/td\x3e\n          \x3c/tr\x3e\x3c/table\x3e\n        \x3c/section\x3e\x3c/body\x3e\x3c/html\x3e"})},
this);return new l({data:a})};f([e.property(),c.renderable()],b.prototype,"layer",void 0);f([e.property()],b.prototype,"defaultParams",void 0);f([e.property({type:y})],b.prototype,"viewModel",void 0);f([e.property()],b.prototype,"_components",void 0);f([e.property()],b.prototype,"_symbologySelect",void 0);f([e.property()],b.prototype,"_colorSchemeTitlePane",void 0);f([e.property()],b.prototype,"_noDataTitlePane",void 0);f([e.property()],b.prototype,"_bandSelect",void 0);f([e.property()],b.prototype,
"_stretchColorRampSelect",void 0);f([e.property()],b.prototype,"_noDataInput",void 0);f([e.property()],b.prototype,"_stretchTypeSelect",void 0);f([e.property()],b.prototype,"_stretchTitlePane",void 0);f([e.property(),c.renderable()],b.prototype,"stretchType",void 0);f([e.property(),c.renderable()],b.prototype,"symbologyType",void 0);f([e.property()],b.prototype,"_minPercentInput",void 0);f([e.property()],b.prototype,"_maxPercentInput",void 0);f([e.property()],b.prototype,"_gammaInput",void 0);f([e.property()],
b.prototype,"_standardDeviationsInput",void 0);f([e.property()],b.prototype,"_stretchStatisticsCheckBox",void 0);f([e.property()],b.prototype,"_supportsBandPresets",void 0);f([e.property()],b.prototype,"_bandCombinationTitlePane",void 0);f([e.property()],b.prototype,"_bandCombinationPresetSelect",void 0);f([e.property()],b.prototype,"_redBandSelect",void 0);f([e.property()],b.prototype,"_greenBandSelect",void 0);f([e.property()],b.prototype,"_blueBandSelect",void 0);f([e.property()],b.prototype,"_uniqueValueFieldSelect",
void 0);f([e.property()],b.prototype,"_uniqueValueColorSchemeSelect",void 0);f([e.property()],b.prototype,"_uniqueValueNoDataInput",void 0);f([e.property()],b.prototype,"_uniqueValuesGrid",void 0);f([e.property()],b.prototype,"_uniqueValuesSymbolData",void 0);f([e.property(),c.renderable()],b.prototype,"_showLoadingGif",void 0);return b=f([e.subclass("esri.widgets.RasterSymbologyEditor")],b)}(e.declared(C))});