// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("dojo/_base/array ../core/declare dojo/_base/lang dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-style dojo/html dojo/keys dojo/on dojo/query dojo/sniff dojo/string dstore/Memory dijit/focus dijit/form/TextBox dijit/registry dijit/Tooltip dijit/_OnDijitClickMixin dijit/_TemplatedMixin ./Widgette dgrid/OnDemandGrid dgrid/Selection dgrid/Keyboard ../core/lang dojo/i18n!./Tags/nls/Tags dojo/NodeList-traverse dojo/NodeList-manipulate".split(" "),function(I,y,c,h,s,f,g,l,t,m,
q,k,u,r,v,p,z,A,w,B,C,D,E,F,G,x,H){return D.createSubclass([B,C],{declaredClass:"esri.widgets.Tags",templateString:'\x3cdiv class\x3d"${baseClass}"\x3e\x3c/div\x3e',baseClass:"esri-tags",constructor:function(a){this._idProperty="tag";this._tags=[];this._selRows=[];this._CHOICE_ALL_SELECTOR=this._CSS_STYLES.CLASS_SELECTOR+this._CSS_STYLES.CHOICE+this._CSS_STYLES.ALL_SELECTOR;this._CHOICE_FOCUS=this._CSS_STYLES.CLASS_SELECTOR+this._CSS_STYLES.SEARCH_CHOICE_FOCUS;this._CHOICE_FOCUS_ALL=this._CHOICE_FOCUS+
this._CSS_STYLES.ALL_SELECTOR},postMixInProperties:function(){this.inherited(arguments);var a=(new Date).getTime();this._tagsId="userTags-"+a;this._gridId="grid-"+a;this._filterId="filter-"+a;this.i18n=H},postCreate:function(){this._attachmentNode=g.create("div",{id:this._tagsId,className:"grid_1"},this.domNode);this._createContainerNode();this._createTagList();this._createDropDownList();this._createInput();var a=[{field:this._idProperty}],b=[{property:this._idProperty,ascending:!0}];this._store=
new v({idProperty:this._idProperty,data:[]});this._grid=new (y([E,F,G]))({collection:this._store,showHeader:!1,noDataMessage:this.i18n.noTagsFound,selectionMode:"extended",allowSelectAll:!0,cellNavigation:!1,columns:a,sort:b,renderRow:this._renderItem},this._dropDownList);this._grid.startup();f.add(this._grid.domNode,"grid-height-limiter");var d;this.own(this._inputTextBox.watch("value",c.hitch(this,function(a,b,c){d&&(clearTimeout(d),d=null);this._grid.refresh()})));this.own(this._grid.on(".dgrid-row:click",
c.hitch(this,function(a){var b="";!this._shiftKeyPressed&&!this._metaKeyPressed?(b=this._grid.row(a).data.tag,this._createTags(b),this._store.remove(b),this._grid.refresh(),this._resetInputTextBox()):!a.shiftKey&&(!a.metaKey&&!a.ctrlKey)&&(b=this._selRows[0],this._createTags(b),this._store.remove(b),this._grid.refresh(),this._resetInputTextBox())})));this.own(this._grid.on("dgrid-deselect",c.hitch(this,function(a){this._selRows=[];for(var b in this._grid.selection)this._grid.selection.hasOwnProperty(b)&&
this._selRows.push(b)})));this.own(this._grid.on("dgrid-select",c.hitch(this,function(a){this._selRows=[];for(var b in this._grid.selection)this._grid.selection.hasOwnProperty(b)&&this._selRows.push(b)})));this.own(q(this.domNode,"keydown",c.hitch(this,this._keydownHandler)));this.own(q(this.domNode,"keyup",c.hitch(this,this._keyupHandler)));window.onkeydown=c.hitch(this,function(a){if(a.shiftKey||a.ctrlKey||224===a.keyCode)this._metaKeyPressed=!0});this.own(q(document,"onkeydown",c.hitch(this,function(a){this._metaKeyPressed=
this._shiftKeyPressed=!0})))},_attachmentNode:"",_autocompleteList:"",_grid:"",_store:"",_idProperty:"",_gridId:"",_filterId:"",_placeHolder:"",_noDataMsg:"",_inputTextBox:"",_gridHasFocus:!1,_metaKeyPressed:!1,_shiftKeyPressed:!1,_CSS_STYLES:{CLASS_SELECTOR:".",ALL_SELECTOR:"\x3e",MULTI:"select2-container select2-container-multi",CHOICES:"select2-choices",CHOICE:"select2-search-choice",SEARCH_CHOICE_FOCUS:"select2-search-choice-focus",SEARCH_FIELD:"select2-search-field",CLOSE_ICON:"select2-search-choice-close"},
_selRows:[],_CHOICE_SELECTOR:"",_CHOICE_FOCUS:"",_CHOICE_FOCUS_ALL:"",properties:{value:{set:function(a){this._setTagValues(a)},get:function(){return this._getTagValues()}},knownTags:{set:function(a){var b=[],d=this._tags,e;for(e=0;e<a.length;e++)0>d.indexOf(a[e])&&b.push(a[e]);this._store=new v({idProperty:this._idProperty,data:b});this._grid.set("collection",this._store);this._grid.refresh()}},required:!1,maxWidth:{value:"auto",cast:function(a){return a?a:"auto"}},minWidth:{value:"auto",cast:function(a){return a?
a:"auto"}},matchParam:{value:"first",cast:function(a){return a?a:"first"}}},isValid:function(){return!this.required||x.isDefined(this._tags)&&0<this._tags.length},validate:function(){this._created&&!this.isValid()?(s.set(this.domNode,"aria-invalid","true"),this._displayMessage(this.i18n.required)):(s.set(this.domNode,"aria-invalid","false"),this._clearMessage())},reset:function(){this.clearTags()},focus:function(){p.focus(this.domNode);this._inputTextBox.focus()},prepopulate:function(a){a.forEach(c.hitch(this,
function(a,d){this._createTags(a);this._store.remove(a)}))},clearTags:function(){var a=k(this._CSS_STYLES.CLASS_SELECTOR+this._CSS_STYLES.CHOICE,h.byId(this.id)),b;0<a.length&&(a.forEach(c.hitch(this,function(a,e){try{b=k(this._CHOICE_ALL_SELECTOR,h.byId(this.id))[0].title,this._store.add({tag:b})}catch(n){}g.destroy(a)})),this._tags=[],this._set("value",""))},addStyledTags:function(a,b){f.add(h.byId(b),this._CSS_STYLES.MULTI);var d=g.create("ul",null,h.byId(b));f.add(d,this._CSS_STYLES.CHOICES);
l.set(d,"border","none");a.forEach(function(a,b){var c=g.create("li",null,d);l.set(c,"padding","3px 5px 3px 5px");f.add(c,"select2-search-resultSet");c=g.create("div",{title:a},c);t.set(c,a)})},_setTagValues:function(a){var b;"string"===typeof a?b=a.split(","):a&&Array.isArray(a)&&(b=a);this.clearTags();this.prepopulate(b?this._getUniqueTags(b):[])},_getTagValues:function(){return this._tags?this._tags.join(","):""},_clearMessage:function(){this._displayMessage(null)},_displayMessage:function(a){var b=
h.byId(this._tagsId);a&&this.focused?w.show(a,b):w.hide(b)},_resetInputTextBox:function(){this._inputTextBox.set("value","")},_isEmpty:function(a){return 0===a.trim().length},_navigate:function(a,b,d,e){0<a.length&&1>b?("right"===e?this._hightlightTag(a.next()):this._hightlightTag(a.prev()),this._unhighlightTag(a)):1>b&&this._hightlightTag(d)},_contains:function(a,b){return 0<=a.indexOf(b)},_hightlightTag:function(a){a.addClass(this._CSS_STYLES.SEARCH_CHOICE_FOCUS)},_unhighlightTag:function(a){a.removeClass(this._CSS_STYLES.SEARCH_CHOICE_FOCUS)},
_removeTag:function(a){a&&-1!==this._tags.indexOf(a)&&(this._tags.splice(this._tags.indexOf(a),1),this._set("value",this._tags.join(",")))},_hideGrid:function(){h.byId(this._gridId)&&l.set(h.byId(this._gridId),"display","none");this._gridHasFocus=!1},_showGrid:function(){l.set(h.byId(this._gridId),"display","block");var a=l.get(h.byId(this._attachmentNode),"width");l.set(h.byId(this._gridId),"width",a+"px")},_setFocusOnFirstRow:function(a,b){return k(".dgrid-content .dgrid-cell",this._grid.domNode)[b]||
k(".dgrid-content .dgrid-row",this._grid.domNode)[b]},_createTags:function(a){k(this._CHOICE_FOCUS,h.byId(this.id)).removeClass("select2-search-choice-focus");var b=g.create("li",null,this._autocompleteList);f.add(b,this._CSS_STYLES.CHOICE);b=g.create("div",{title:a},b);t.set(b,this._htmlEncode(a));b=g.create("a",{href:"#"},b);f.add(b,this._CSS_STYLES.CLOSE_ICON);q(b,"click",c.hitch(this,function(a){var b=a.target.parentElement.innerText||a.target.parentElement.textContent;try{this._store.add({tag:b})}catch(c){}this._grid.refresh();
this._removeTag(b);g.destroy(a.target.parentNode.parentNode);a.preventDefault()}));b=A.byId(this._filterId);g.place(b.domNode,this._autocompleteList,"last");this._hideGrid();this._tags.push(a);this._set("value",this._tags.join(","))},_renderItem:function(a){return g.create("div",{innerHTML:a.tag})},_createContainerNode:function(){this._containerNode=g.create("div",null,this._attachmentNode);f.add(this._containerNode,this._CSS_STYLES.MULTI);l.set(this._containerNode,{maxWidth:this.maxWidth,minWidth:this.minWidth})},
_createTagList:function(){this._autocompleteList=g.create("ul",null,this._containerNode);f.add(this._autocompleteList,this._CSS_STYLES.CHOICES)},_createInput:function(){var a=g.create("li",null,this._autocompleteList,"last");f.add(a,this._CSS_STYLES.SEARCH_FIELD);this._inputTextBox=new z({id:this._filterId,placeHolder:this.i18n.addTags,intermediateChanges:!0,trim:!0,style:{border:"none"}},a);f.add(this._inputTextBox,"input-text-box");l.set(this._inputTextBox,"width",this.minWidth);(8<u("ie")||4<u("trident"))&&
f.add(this._inputTextBox.domNode,"ie-style");this.own(p.watch("curNode",c.hitch(this,this._blurHandler)))},_createDropDownList:function(){this._dropDownList=g.create("div",{id:this._gridId},this._containerNode);f.add(this._dropDownList,"drop-down-list");l.set(this._dropDownList,"width",this.minWidth)},_getUniqueTags:function(a){var b=[],d;a.forEach(c.hitch(this,function(a){d=this._stripHTML(a);x.isDefined(d)&&0<d.length&&b.push(d)}));return b.filter(c.hitch(this,function(a,c){return b.indexOf(a)===
c}))},_stripHTML:function(a){return a&&a.replace(/<(?:.|\s)*?>/g,"")},_htmlEncode:function(a){return!a?a:r.escape(a)},_keyupHandler:function(a){0<(this._inputTextBox?this._inputTextBox.get("value").length:0)?this._applyFilter():this._removeFilter()},_keydownHandler:function(a){this._clearMessage();var b=k(this._CHOICE_FOCUS,h.byId(this.id)),d=k(this._CSS_STYLES.CLASS_SELECTOR+this._CSS_STYLES.CHOICE,h.byId(this.id)).last(),e,n;void 0!==p.curNode.value&&(n=p.curNode.value.length);switch(a.keyCode){case m.RIGHT_ARROW:this._navigate(b,
n,d,"right");this._hideGrid();break;case m.LEFT_ARROW:this._navigate(b,n,d,"left");this._hideGrid();break;case m.DOWN_ARROW:a.preventDefault();this._unhighlightTag(b);"none"===l.get(this._gridId,"display")&&this._showGrid();this._gridHasFocus||(this._grid.focus(this._setFocusOnFirstRow(this._grid,0)),this._gridHasFocus=!0);break;case m.UP_ARROW:break;case m.BACKSPACE:var f;if(0===n&&0===k(this._CHOICE_FOCUS_ALL).length&&void 0!==k(this._CHOICE_ALL_SELECTOR)[k(this._CHOICE_ALL_SELECTOR).length-1]&&
(f=k(this._CHOICE_ALL_SELECTOR)[k(this._CHOICE_ALL_SELECTOR).length-1].title,0<k("li",this._attachmentNode).length&&(g.destroy(d[0]),void 0!==f)))try{this._store.add({tag:f})}catch(q){}if(0<k(this._CHOICE_FOCUS_ALL).length&&(f=k(this._CHOICE_FOCUS_ALL).text(),g.destroy(b[0]),void 0!==f))try{this._store.add({tag:f})}catch(s){}this._grid.refresh();0===n&&this._hideGrid();this._removeTag(f);this.validate();break;case m.CTRL:this._metaKeyPressed=!0;break;case m.META:this._metaKeyPressed=!0;break;case m.SHIFT:this._shiftKeyPressed=
!0;break;case m.ENTER:if(0<n)b=this._stripHTML(p.curNode.value),b=b.split(","),e=[],b.forEach(function(a,b){-1===e.indexOf(a)&&e.push(r.trim(a))}),e.forEach(c.hitch(this,function(a,b){this._isEmpty(a)||this._contains(this._tags,a)||this._createTags(a)}));else{for(b=0;b<this._selRows.length;b++)this._createTags(this._selRows[b]),this._store.remove(this._selRows[b]);this._metaKeyPressed=this._shiftKeyPressed=!1}this._resetInputTextBox();a.preventDefault();p.focus(h.byId(this._filterId));break;case m.TAB:if(!(p.curNode.id===
this._filterId&&0===n)){if(0<n)b=this._stripHTML(p.curNode.value),b=b.split(","),e=[],b.forEach(function(a,b){-1===e.indexOf(a)&&e.push(r.trim(a))}),e.forEach(c.hitch(this,function(a,b){this._isEmpty(a)||this._contains(this._tags,a)||this._createTags(a)}));else{for(b=0;b<this._selRows.length;b++)this._createTags(this._selRows[b]),this._store.remove(this._selRows[b]);this._metaKeyPressed=this._shiftKeyPressed=!1}this._resetInputTextBox();a.preventDefault();p.focus(h.byId(this._filterId))}break;case m.ESCAPE:this._hideGrid();
break;default:-1<n&&("none"===l.get(h.byId(this._gridId),"display")&&this._showGrid(),this._unhighlightTag(b)),this._metaKeyPressed=!1}},_applyFilter:function(){var a=new this._store.Filter,b=this._inputTextBox?this._inputTextBox.get("value")+"":"",c=RegExp("^"+b.toLowerCase(),"i"),b=RegExp(b.toLowerCase(),"i"),a="first"===this.matchParam?a.match(this._idProperty,c):a.match(this._idProperty,b);this._grid.set("collection",this._store.filter(a));this._grid.refresh()},_removeFilter:function(){this._grid.set("collection",
this._store);this._grid.refresh()},_blurHandler:function(a,b,d){if(!this.focused){a=this._stripHTML(this._inputTextBox.value);if(0<a.length){var e=[];a.split(",").forEach(function(a,b){-1===e.indexOf(a)&&e.push(r.trim(a))});e.forEach(c.hitch(this,function(a,b){this._isEmpty(a)||this._contains(this._tags,a)||this._createTags(a)}));this._resetInputTextBox()}this._hideGrid()}this.validate()}})});