// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require dojo/_base/array dojo/_base/config dojo/Deferred dojo/_base/lang dojo/_base/url dojo/request dojo/io-query dojo/when ./kernel ./config ./core/sniff ./core/lang ./core/urlUtils ./core/deferredUtils ./core/promiseUtils dojo/has!host-browser?dojo/io/script dojo/has!host-browser?dojo/io/iframe dojo/has!host-browser?dojo/dom-construct".split(" "),function(Y,B,C,O,p,r,D,P,Z,q,$,d,y,k,aa,K,ba,ca,S){function da(a,c,b){if(b)return K.reject(p.mixin(Error(),{message:"When using responseType 'image', URL length cannot exceed 2000 characters."}));
if(b=P.objectToQuery(a.content))a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+b;var e=new Image;a.allowImageDataAccess&&(a.withCredentials?e.crossOrigin="use-credentials":c&&(e.crossOrigin="anonymous"));var f=!1,d=new O(function(a){f=!0;e.onload=e.onerror=e.onabort=null;e.src=""});c=function(a){e.onload=e.onerror=e.onabort=null;f||d.reject(a)};e.onload=function(){e.onload=e.onerror=e.onabort=null;f||d.resolve(this)};e.onerror=c;e.onabort=c;e.alt="";e.src=a.url;return d.promise}function G(a){a=new r(a);
return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function T(a,c,b){var e=!!a.useProxy,f=a.method||"auto",l;l=a.crossOrigin;a=p.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));var E=a.content,m=a.url,g=c&&a.form;l=y.isDefined(l)?l:h.useCors;a.load=function(a){var b;a&&(a.error?(b=p.mixin(Error(),a.error),b.log=C.isDebug):"error"===a.status&&(b=p.mixin(Error(),a),b.log=C.isDebug),b&&!y.isDefined(b.httpCode)&&(b.httpCode=b.code));return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();
a instanceof Error||(a=p.mixin(Error(),a));a.log=C.isDebug;return a};a._token&&(a.content=a.content||{},a.content.token=a._token);var s=0,n;m&&(n=P.objectToQuery(E),s=n.length+m.length+1,d("esri-url-encodes-apostrophe")&&(s=n.replace(/'/g,"%27").length+m.length+1));a.timeout=y.isDefined(a.timeout)?a.timeout:h.timeout;a.handleAs=a.handleAs||"json";try{var t,u,v=l&&k.canUseXhr(a.urlObj)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),x=k.hasSameOrigin(a.urlObj,k.appUrl)||v,z="post"===f||
c||s>h.maxUrlLength?!0:!1,A=!x&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!c?!0:!1,F=k.getProxyRule(a.url)||h.forceProxy||e||("image"!==a.handleAs||a.allowImageDataAccess)&&(!A||z)&&!x?!0:!1;c&&(!d("esri-file-upload")&&!F&&v)&&(F=!0);if((d("host-browser")||d("host-webworker"))&&F)if(t=k.getProxyUrl(m,l),u=t.path,t._xo&&(v=!0),!z&&u.length+1+s>h.maxUrlLength&&(z=!0),a.url=u+"?"+m,z)a.content=p.mixin(t.query||{},E);else{var U=P.objectToQuery(p.mixin(t.query||{},E));U&&(a.url+=(-1===m.indexOf("?")?
"?":"\x26")+U);a.content=null}if((d("host-browser")||d("host-webworker"))&&A&&!z)return!y.isDefined(a.isAsync)&&4>d("ff")&&(a.isAsync=!0),ba.get(w?w(a):a);var H=a.headers;if((d("host-browser")||d("host-webworker"))&&(!H||!H.hasOwnProperty("X-Requested-With")))H=a.headers=H||{},H["X-Requested-With"]=null;if(d("host-browser")&&c){var L=a.callbackParamName||"callback.html",V=a.callbackElementName||"textarea",I,M,J,N,G=g.elements?g.elements.length:0,Q;if(E=a.content)for(I in E)if(J=E[I],y.isDefined(J)){M=
null;for(N=0;N<G;N++)if(Q=g.elements[N],Q.name===I){M=Q;break}M?M.value=J:b?g.append(I,J):g.appendChild(S.create("input",{type:"hidden",name:I,value:J}))}if(d("esri-file-upload"))B.forEach(g.elements,function(a){a.name===L&&g.removeChild(a)}),a.contentType=!1,a.postData=b?g:new FormData(g),delete a.form;else{g.enctype="multipart/form-data";9>d("ie")&&(g.encoding="multipart/form-data");g.method="post";B.some(g.elements,function(a){return a.name===L})||g.appendChild(S.create("input",{type:"hidden",
name:L,value:V}));if(-1!==m.toLowerCase().indexOf("addattachment")||-1!==m.toLowerCase().indexOf("updateattachment"))a.url=m+(-1===m.indexOf("?")?"?":"\x26")+L+"\x3d"+V,F&&(a.url=u+"?"+a.url);delete a.content}}if(v&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===h.useCors){b=F?u:m;var R=k.getCorsConfig(b);if(R&&R.hasOwnProperty("withCredentials"))R.withCredentials&&(a.withCredentials=!0);else if(q.id){var r=q.id.findServerInfo(b);r&&r.webTierAuth&&(a.withCredentials=!0)}}a=w?w(a):a;if("image"===
a.handleAs)return da(a,v,z);if(z){a.data=a.content;if(d("host-browser")&&c&&!d("esri-file-upload"))return ca.send(a);!F&&d("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+ea++);return D.post(a.url,a)}a.query=a.content;return D.get(a.url,a)}catch(K){return c=new O,c.reject(a.error(K)),c}}function W(a){var c=h.corsStatus,b=k.getCorsConfig(a,!0);-1<b&&h.corsEnabledServers.splice(b,1);c[G(a)]=1;return b}function X(a){var c=h.corsStatus;try{var b=G(a.url);if(h.corsDetection&&
h.useCors&&d("esri-cors")&&a.url&&-1!==a.url.toLowerCase().indexOf("/rest/services")&&!k.hasSameOrigin(a.urlObj,k.appUrl)&&!k.canUseXhr(a.urlObj)){if(c[b])return c[b];var e=new O;c[b]=e.promise;var f=a.url.substring(0,a.url.toLowerCase().indexOf("/rest/")+6)+"info";D.get(f,{query:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*h.corsDetectionTimeout}).then(function(c){c?(k.canUseXhr(a.url)||h.corsEnabledServers.push(b),e.resolve()):e.reject()},function(a){e.reject()});
return e.promise}}catch(l){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function x(a,c,b,e){function f(a){a._pendingDfd=T(b,t,r);if(a._pendingDfd){var c=!!a._pendingDfd.response;(a._pendingDfd.response||a._pendingDfd).then(function(b){var d=c?b.data:b;b=c?b.getHeader.bind(b):fa;var f=null;a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;if(d&&(d.error?(f=p.mixin(Error(),d.error),f.log=C.isDebug):"error"===d.status&&(f=p.mixin(Error(),d),f.log=C.isDebug),f&&
!y.isDefined(f.httpCode)&&(f.httpCode=f.code),f))throw f;a.resolve({data:d,url:e.url,requestOptions:e.requestOptions,getHeader:b});a._pendingDfd=null}).then(null,function(c){var d,f,A;c&&(d=c.code,f=c.subcode,A=(A=c.messageCode)&&A.toUpperCase());if(c&&403==d&&(4==f||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;x(a,!0,b,e);return}}else if(c&&415==c.status){if(W(b.url),!b._err415){b._err415=1;x(a,!0,
b,e);return}}else if(q.id&&-1!==B.indexOf(q.id._errorCodes,d)&&!q.id._isPublic(b.url)&&!n&&(403!=d||-1===B.indexOf(ga,A)&&(!y.isDefined(f)||2==f&&b._token))){ha(a,b,e,c);return}a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;a.reject(c);a._pendingDfd=null})}else{a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;var d=Error("Deferred object is missing");d.log=C.isDebug;a.reject(d);a._pendingDfd=null}}var l=b.form,n=b.disableIdentityLookup,m=b._preLookup,g=!1;if(d("esri-workers")&&!1!==h.useWorkers)if(!0===
b.useWorkers||!0===h.useWorkers)g=!0;else if(b.workerOptions){var s=b.workerOptions;if(s.callback||s.worker&&s.worker.worker instanceof Worker)g=!0}var r=l&&d("esri-file-upload")&&l instanceof FormData,t=l&&(l.elements?B.some(l.elements,function(a){return"file"===a.type}):r),u=-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||t&&B.some(l.elements,function(a){return"token"===a.name})?1:0;if(!c){a.then(function(a){if((/\/sharing\/rest\/accounts\/self/i.test(b.url)||/\/sharing\/rest\/portals\/self/i.test(b.url))&&
!u&&!b._token&&a.user&&a.user.username){var c=h.corsEnabledServers,d=k.getCorsConfig(b.url,!0),f={host:G(b.url),withCredentials:!0};if(-1===d)c.push(f);else{var e=c[d];"object"===typeof e?e.withCredentials=!0:c.splice(d,1,f)}}if(c=b._credential)if(d=(d=q.id.findServerInfo(c.server))&&d.owningSystemUrl)d=d.replace(/\/?$/,"/sharing"),(c=q.id.findCredential(d,c.userId))&&-1===q.id._getIdenticalSvcIdx(d,c)&&c.resources.splice(0,0,d);return a}).always(function(a){delete b._credential;a&&(a.ssl=!!b._ssl)});
var v=b.load,w=b.error;v&&a.then(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return v.call(c&&c.args,b,c)});w&&a.then(null,function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return w.call(c&&c.args,b,c)})}if(q.id&&!u&&!b._token&&!q.id._isPublic(b.url)&&(!n||m))if(c=q.id.findCredential(b.url))b._token=c.token,b._ssl=c.ssl;g?b.workerOptions&&b.workerOptions.worker?(D=b.workerOptions.worker,f(a)):Y(["./workers/RequestClient"],function(c){if(b.workerOptions){var d=b.workerOptions;D=c.getClient(d.callback,
d.cbFunction)}else D=c.getClient();f(a)}):f(a);return a.promise}function ha(a,c,b,d){a._pendingDfd=q.id.getCredential(c.url,{token:c._token,error:d});a._pendingDfd.then(function(d){c._token=d.token;c._credential=d;c._ssl=c._sslFromServer||d.ssl;x(a,!0,c,b)}).then(null,function(b){a.reject(b);a._pendingDfd=null})}function n(a,c){"string"!==typeof a&&console.error("esri/request: the first parameter should be a url string");var b=p.mixin({},c),e={url:a,requestOptions:p.mixin({},c)};b.content=b.query;
delete b.query;b.preventCache=!!b.cacheBust;delete b.cacheBust;b.handleAs=b.responseType;delete b.responseType;"array-buffer"===b.handleAs&&(b.handleAs="arraybuffer");if("image"===b.handleAs){if(d("host-webworker"))return K.reject(p.mixin(Error(),{message:"The responseType 'image' is not supported in Web Workers or Node environment."}));b.preventCache&&(b.content=b.content||{},b.content["request.preventCache"]=Date.now());b.method="auto"}b.url=k.normalize(a);"file"!==k.appUrl.scheme&&(b.url=k.makeAbsolute(b.url));
b.urlObj=new r(b.url);var f=aa.makeDeferredCancellingPending();Z(X(b)).always(function(){x(f,!1,b,e)});return f.promise}var w,h=$.request,ga=["COM_0056","COM_0057"],ea=0,fa=function(){return null};n._makeRequest=T;n._processRequest=x;n._disableCors=W;n._detectCors=X;n.setRequestPreCallback=function(a){w=a};return n});