// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports ./tsSupport/declareExtendsHelper ./tsSupport/decorateHelper dojo/aspect ./accessorSupport/decorators ./accessorSupport/ensureType ./Accessor ./ArrayPool ./Evented ./ObjectPool ./Scheduler ./lang".split(" "),function(D,Q,G,z,H,u,I,J,v,K,L,M,N){function w(e){return!e?!1:e.isInstanceOf&&e.isInstanceOf(E)?!0:!1}function A(e){return!e?[]:w(e)?e.toArray():e.length?Array.prototype.slice.apply(e):[]}function B(e){return!e||!e.length?void 0:e[0]}function F(e,b,a,c){b&&b.forEach(function(b,
d,f){e.push(b);F(e,a.call(c,b,d,f),a,c)})}(function(){return function(){}})();D=function(){function e(){this.target=null;this.defaultPrevented=this.cancellable=!1}e.prototype.preventDefault=function(){this.cancellable&&(this.defaultPrevented=!0)};e.prototype.reset=function(b){this.defaultPrevented=!1;this.item=b};return e}();var O=function(){},l=new L(D,function(){this.target=this.item=null}),r=new Set,s=new Set,t=new Set,C=new Map,P=0,E=function(e){function b(a){e.call(this,a);this._boundDispatch=
this._dispatchColChange.bind(this);this._chgListeners=[];this._timer=this._notifications=null;this.length=0;this._items=[];Object.defineProperty(this,"uid",{value:P++})}G(b,e);b.ofType=function(a){if(!a)return b;if(C.has(a))return C.get(a);var c=b.createSubclass({declaredClass:"esri.core.Collection\x3c"+a.prototype.declaredClass+"\x3e"});Object.defineProperty(c.prototype,"itemType",{value:a});C.set(a,c);return c};b.prototype.normalizeCtorArgs=function(a){return!a?{}:Array.isArray(a)||w(a)?{items:a}:
a};Object.defineProperty(b.prototype,"items",{get:function(){return this._items},set:function(a){this._emitBeforeChanges()||(this._splice.apply(this,[0,this.length].concat(A(a))),this._emitAfterChanges())},enumerable:!0,configurable:!0});b.prototype.on=function(a,c){var b;Array.isArray(a)?b=a:-1<a.indexOf(",")&&(b=a.split(/\s*,\s*/));if(b){for(var d=[],f=0;f<b.length;f++)d.push(this.on(b[f],c));d.remove=function(){for(var a=0;a<d.length;a++)d[a].remove()};return d}if("change"===a){var k=this._chgListeners,
e={removed:!1,callback:c};k.push(e);this._notifications&&this._notifications.push({listeners:k.slice(),items:this._items.slice(),changes:[]});return{remove:function(){this.remove=O;e.removed=!0;k.splice(k.indexOf(e),1)}}}return H.after(this,"on"+a,c,!0)};b.prototype.hasEventListener=function(a){return"change"===a?0<this._chgListeners.length:this.inherited(arguments)};b.prototype.add=function(a,c){if(this._emitBeforeChanges())return this;var b=this.getNextIndex(c);this._splice(b,0,a);this._emitAfterChanges();
return this};b.prototype.addMany=function(a,c){void 0===c&&(c=this._items.length);if(this._emitBeforeChanges())return this;var b=this.getNextIndex(c);this._splice.apply(this,[b,0].concat(A(a)));this._emitAfterChanges();return this};b.prototype.removeAll=function(){if(!this.length||this._emitBeforeChanges())return[];var a=this._splice(0,this.length)||[];this._emitAfterChanges();return a};b.prototype.clone=function(){return this._createNewInstance({items:this._items.map(N.clone)})};b.prototype.concat=
function(){for(var a=[],c=0;c<arguments.length;c++)a[c-0]=arguments[c];a=a.map(A);return this._createNewInstance({items:(b=this._items).concat.apply(b,a)});var b};b.prototype.drain=function(a,c){if(this.length&&!this._emitBeforeChanges()){for(var b=this._splice(0,this.length),d=0,f=b.length;d<f;d++)a.call(c,b[d],d,b);this._emitAfterChanges()}};b.prototype.every=function(a,c){return this._items.every(a,c)};b.prototype.filter=function(a,c){var b;b=2===arguments.length?this._items.filter(a,c):this._items.filter(a);
return this._createNewInstance({items:b})};b.prototype.find=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,d=0,f=b.length;d<f;d++){var k=b[d];if(a.call(c,k,d,b))return k}};b.prototype.findIndex=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,d=0,f=b.length;d<f;d++)if(a.call(c,b[d],d,b))return d;return-1};b.prototype.flatten=function(a,c){var x=[];F(x,this,a,c);return new b(x)};b.prototype.forEach=
function(a,c){for(var b=this._items,d=0,f=b.length;d<f;d++)a.call(c,b[d],d,b)};b.prototype.getItemAt=function(a){return this._items[a]};b.prototype.getNextIndex=function(a){var c=this.length;a=null==a?c:a;0>a?a=0:a>c&&(a=c);return a};b.prototype.includes=function(a,c){void 0===c&&(c=0);return!arguments.length?!1:-1!==this._items.indexOf(a,c)};b.prototype.indexOf=function(a,c){void 0===c&&(c=0);return this._items.indexOf(a,c)};b.prototype.join=function(a){void 0===a&&(a=",");return this._items.join(a)};
b.prototype.lastIndexOf=function(a,c){void 0===c&&(c=this.length-1);return this._items.lastIndexOf(a,c)};b.prototype.map=function(a,c){var x=this._items.map(a,c);return new b({items:x})};b.prototype.reorder=function(a,c){void 0===c&&(c=this.length-1);var b=this.indexOf(a);if(-1!==b){0>c?c=0:c>=this.length&&(c=this.length-1);if(b!==c){if(this._emitBeforeChanges())return a;this._splice(b,1);this._splice(c,0,a);this._emitAfterChanges()}return a}};b.prototype.pop=function(){if(this.length&&!this._emitBeforeChanges()){var a=
B(this._splice(this.length-1,1));this._emitAfterChanges();return a}};b.prototype.push=function(){for(var a=[],c=0;c<arguments.length;c++)a[c-0]=arguments[c];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[this.length,0].concat(a));this._emitAfterChanges();return this.length};b.prototype.reduce=function(a,c){var b=this._items;return 2===arguments.length?b.reduce(a,c):b.reduce(a)};b.prototype.reduceRight=function(a,b){var e=this._items;return 2===arguments.length?e.reduceRight(a,
b):e.reduceRight(a)};b.prototype.remove=function(a){return this.removeAt(this.indexOf(a))};b.prototype.removeAt=function(a){if(!(0>a||a>=this.length||this._emitBeforeChanges()))return a=B(this._splice(a,1)),this._emitAfterChanges(),a};b.prototype.removeMany=function(a){if(!a||!a.length||this._emitBeforeChanges())return[];a=w(a)?a.toArray():a;for(var b=this._items,e=[],d=0,f=a.length;d<f;d++){var k=b.indexOf(a[d]);if(-1<k){for(var p=a,q=b,g=d+1,h=k+1,n=Math.min(p.length-g,q.length-h),m=0;m<n&&p[g+
m]===q[h+m];)m++;p=1+m;(k=this._splice(k,p))&&0<k.length&&e.push.apply(e,k);d+=p-1}}this._emitAfterChanges();return e};b.prototype.reverse=function(){if(this._emitBeforeChanges())return this;var a=this._splice(0,this.length);a&&(a.reverse(),this._splice.apply(this,[0,0].concat(a)));this._emitAfterChanges();return this};b.prototype.shift=function(){if(this.length&&!this._emitBeforeChanges()){var a=B(this._splice(0,1));this._emitAfterChanges();return a}};b.prototype.slice=function(a,b){void 0===a&&
(a=0);void 0===b&&(b=this.length);return this._createNewInstance({items:this._items.slice(a,b)})};b.prototype.some=function(a,b){return this._items.some(a,b)};b.prototype.sort=function(a){if(!this.length||this._emitBeforeChanges())return this;var b=this._splice(0,this.length);arguments.length?b.sort(a):b.sort();this._splice.apply(this,[0,0].concat(b));return this};b.prototype.splice=function(a,b){for(var e=[],d=2;d<arguments.length;d++)e[d-2]=arguments[d];if(this._emitBeforeChanges())return[];e=this._splice.apply(this,
[a,b].concat(e))||[];this._emitAfterChanges();return e};b.prototype.toArray=function(){return this._items.slice()};b.prototype.toJSON=function(){return this.toArray()};b.prototype.toLocaleString=function(){return this._items.toLocaleString()};b.prototype.toString=function(){return this._items.toString()};b.prototype.unshift=function(){for(var a=[],b=0;b<arguments.length;b++)a[b-0]=arguments[b];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[0,0].concat(a));this._emitAfterChanges();
return this.length};b.prototype._createNewInstance=function(a){return new this.constructor(a)};b.prototype._splice=function(a,b){for(var e=this,d=[],f=2;f<arguments.length;f++)d[f-2]=arguments[f];var k=this._items,p=this.constructor.prototype.itemType,q,g;!this._notifications&&this.hasEventListener("change")&&(this._notifications=[{listeners:this._chgListeners.slice(),items:this._items.slice(),changes:[]}],this._timer&&this._timer.remove(),this._timer=M.schedule(this._boundDispatch));if(b){g=k.splice(a,
b);if(this.hasEventListener("before-remove")){f=l.acquire();f.target=this;f.cancellable=!0;for(var h=0,n=g.length;h<n;h++)q=g[h],f.reset(q),this.emit("before-remove",f),f.defaultPrevented&&(g.splice(h,1),k.splice(a,0,q),a+=1,h-=1,n-=1);l.release(f)}this.length=this._items.length;if(this.hasEventListener("after-remove")){f=l.acquire();f.target=this;f.cancellable=!1;h=0;for(n=g.length;h<n;h++)f.reset(g[h]),this.emit("after-remove",f);l.release(f)}this._notifyChangeEvent(null,g)}if(d&&d.length){p&&(d=
d.map(I.ensureType.bind(null,p)));if(this.hasEventListener("before-add")){var m=l.acquire();m.target=this;m.cancellable=!0;d=d.filter(function(a){m.reset(a);e.emit("before-add",m);return!m.defaultPrevented});l.release(m)}k.splice.apply(k,[a,0].concat(d));this.length=this._items.length;if(this.hasEventListener("after-add")){f=l.acquire();f.target=this;f.cancellable=!1;k=0;for(p=d;k<p.length;k++)q=p[k],f.reset(q),this.emit("after-add",f);l.release(f)}this._notifyChangeEvent(d,null)}return g};b.prototype._emitBeforeChanges=
function(){var a=!1;if(this.hasEventListener("before-changes")){var b=l.acquire();b.target=this;b.cancellable=!0;this.emit("before-changes",b);a=b.defaultPrevented;l.release(b)}return a};b.prototype._emitAfterChanges=function(){if(this.hasEventListener("after-changes")){var a=l.acquire();a.target=this;a.cancellable=!1;this.emit("after-changes",a);l.release(a)}};b.prototype._notifyChangeEvent=function(a,b){this.hasEventListener("change")&&this._notifications[this._notifications.length-1].changes.push({added:a,
removed:b})};b.prototype._dispatchColChange=function(){this._timer&&(this._timer.remove(),this._timer=null);if(this._notifications){var a=this._notifications;this._notifications=null;for(var b=function(a){var b=a.changes;r.clear();s.clear();t.clear();for(var c=0;c<b.length;c++){var d=b[c],g=d.added,d=d.removed;if(g)if(0===t.size&&0===s.size)for(var h=0,n=g;h<n.length;h++)g=n[h],r.add(g);else{h=0;for(n=g;h<n.length;h++)g=n[h],s.has(g)?(t.add(g),s.delete(g)):t.has(g)||r.add(g)}if(d)if(0===t.size&&0===
r.size)for(h=0;h<d.length;h++)g=d[h],s.add(g);else for(h=0;h<d.length;h++)g=d[h],r.has(g)?r.delete(g):(t.delete(g),s.add(g))}var m=v.acquire();r.forEach(function(a){m.push(a)});var l=v.acquire();s.forEach(function(a){l.push(a)});var u=e._items,w=a.items,y=v.acquire();t.forEach(function(a){w.indexOf(a)!==u.indexOf(a)&&y.push(a)});if(a.listeners&&(m.length||l.length||y.length)){b={target:e,added:m,removed:l,moved:y};c=0;for(g=a.listeners.length;c<g;c++)d=a.listeners[c],d.removed||d.callback.call(e,
b)}v.release(m);v.release(l);v.release(y)},e=this,d=0;d<a.length;d++)b(a[d])}};b.isCollection=w;z([u.property()],b.prototype,"length",void 0);z([u.property()],b.prototype,"items",null);return b=z([u.subclass("esri.core.Collection")],b)}(u.declared(J,K));return E});