// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/window dojo/_base/lang dojo/_base/url dojo/io-query ../config ./lang ./sniff ./Logger ./Error".split(" "),function(y,e,R,S,l,t,z,A,B,T,U){function u(a){var b={path:null,query:null},c=new l(a),d=a.indexOf("?");null===c.query?b.path=a:(b.path=a.substring(0,d),b.query=t.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b}function C(a,b){void 0===a&&(a=!1);void 0===b&&(b=!0);
var c,d=n.proxyUrl;if("string"===typeof a){c=/^\s*https:/i.test(a)||f(a)&&"https"===e.appUrl.scheme;var g=v(a);g&&(d=g.proxyUrl)}else c=!!a;if(!d)throw V.warn(D),new U("urlutils:proxy-not-set",D);var k;c&&(b&&"https"===e.appUrl.scheme)&&(c=E(d),F(c)&&(d=c,k=1));d=u(d);d._xo=k;return d}function G(a){var b=a.indexOf("?");-1!==b?(p.path=a.slice(0,b),p.query=a.slice(b+1)):(p.path=a,p.query=null);return p}function H(a){a=G(a).path;if(!a||"/"!==a[a.length-1])a+="/";a=w(a,!0);return a=a.toLowerCase()}function v(a){var b=
n.proxyRules;a=H(a);for(var c=0;c<b.length;c++)if(0===a.indexOf(b[c].urlPrefix))return b[c]}function I(a){a=q(a);var b=a.indexOf("/sharing");return 0<b?a.substring(0,b):a.replace(/\/+$/,"")}function J(a,b,c){void 0===c&&(c=!1);a=x(a);b=x(b);return!c&&a.scheme!==b.scheme?!1:a.host.toLowerCase()===b.host.toLowerCase()&&a.port===b.port}function F(a){return B("esri-phonegap")?!0:!B("esri-cors")?!1:null!=K(a)}function K(a,b){void 0===b&&(b=!1);"string"===typeof a&&(a=r(a)?x(a):e.appUrl);for(var c=n.corsEnabledServers||
[],d=0;d<c.length;d++)for(var g=c[d],k=void 0,k="string"===typeof g?L(g):g.host?L(g.host):[],h=0;h<k.length;h++)if(J(a,k[h]))return b?d:g;return b?-1:null}function L(a){e.corsServersUrlCache[a]||(!s.test(a)&&!f(a)?e.corsServersUrlCache[a]=[new l("http://"+a),new l("https://"+a)]:e.corsServersUrlCache[a]=[new l(m(a))]);return e.corsServersUrlCache[a]}function m(a,b,c){void 0===b&&(b=e.appBaseUrl);if(f(a))return c&&c.preserveProtocolRelative?a:"file"===e.appUrl.scheme?"https:"+a:e.appUrl.scheme+":"+
a;if(s.test(a))return a;c=M;if("/"===a[0]){var d=b.indexOf("//"),d=b.indexOf("/",d+2);b=-1===d?b:b.slice(0,d)}return c(b,a)}function N(a,b){void 0===b&&(b=e.appBaseUrl);if(!r(a))return a;for(var c=q(a),d=c.toLowerCase(),g=q(b).toLowerCase().replace(/\/+$/,""),k=function(a,b,c){c=a.indexOf(b,c);return-1===c?a.length:c},h=k(d,"/",d.indexOf("//")+2),f=-1;d.slice(0,h+1)===g.slice(0,h)+"/";){f=h+1;if(h===d.length)break;h=k(d,"/",h+1)}if(-1===f)return a;a=c.slice(f);c=g.slice(f-1).replace(/[^/]+/g,"").length;
if(0<c)for(d=0;d<c;d++)a="../"+a;else a="./"+a;return a}function q(a){a=m(a);a=W(a);return a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,"$1www.$2")}function M(){for(var a=[],b=0;b<arguments.length;b++)a[b-0]=arguments[b];if(a&&a.length){b=[];if(r(a[0])){var c=a[0],d=c.indexOf("//");b.push(c.slice(0,d+1));O.test(a[0])&&(b[0]+="/");a[0]=c.slice(d+2)}else"/"===a[0][0]&&b.push("");a=a.reduce(function(a,b){return a.concat(b.split("/"))},[]);for(c=0;c<a.length;c++)d=a[c],".."===d&&0<b.length?b.pop():d&&("."!==
d||0===b.length)&&b.push(d);return b.join("/")}}function r(a){return f(a)||s.test(a)}function P(a){return"data:"===a.slice(0,5)}function f(a){return a&&"/"===a[0]&&"/"===a[1]}function E(a){return f(a)?"https:"+a:a.replace(Q,"https:")}function w(a,b){void 0===b&&(b=!1);if(f(a))return a.slice(2);a=a.replace(s,"");b&&(1<a.length&&"/"===a[0]&&"/"===a[1])&&(a=a.slice(2));return a}function W(a){var b=z.request.httpsDomains;if(!(Q.test(a)||f(a)&&"http"===e.appUrl.scheme)||!("https"===e.appUrl.scheme||O.test(e.appBaseUrl)))return a;
var c=a.indexOf("/",7),d;d=-1===c?a:a.slice(0,c);if(A.endsWith(d,""+e.appUrl.host+(null!=e.appUrl.port?":"+e.appUrl.port:""))||b&&b.some(function(a){return A.endsWith(d,a)}))a=E(a);return a}function x(a){if("string"===typeof a)return new l(m(a));a.scheme||(a.scheme=e.appUrl.scheme);return a}y=R.global;var V=T.getLogger("esri.core.urlUtils"),n=z.request,D="esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled\n server, please push the domain into esriConfig.request.corsEnabledServers.",
s=/^\s*[a-z][a-z0-9-+.]*:(?![0-9])/i,Q=/^\s*http:/i,O=/^\s*file:/i;e.appUrl=new l(y.location);e.corsServersUrlCache={};e.appBaseUrl=function(){var a=e.appUrl.path,a=a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-1]));return""+(e.appUrl.scheme+"://"+e.appUrl.host+(null!=e.appUrl.port?":"+e.appUrl.port:""))+a}();e.urlToObject=u;e.getProxyUrl=C;e.addProxy=function(a){var b=v(a),c,d;b?(d=G(b.proxyUrl),c=d.path,d=d.query?t.queryToObject(d.query):null):n.forceProxy&&(d=C(),c=d.path,d=d.query);
c&&(b=u(a),a=c+"?"+b.path,(c=t.objectToQuery(S.mixin(d||{},b.query)))&&(a=a+"?"+c));return a};var p={path:"",query:""};e.addProxyRule=function(a){a={proxyUrl:a.proxyUrl,urlPrefix:H(a.urlPrefix)};for(var b=n.proxyRules,c=a.urlPrefix,d=b.length,e=0;e<b.length;e++){var f=b[e].urlPrefix;if(0===c.indexOf(f)){if(c.length===f.length)return-1;d=e;break}0===f.indexOf(c)&&(d=e+1)}b.splice(d,0,a);return d};e.getProxyRule=v;e.hasSamePortal=function(a,b){a=I(a);b=I(b);return w(a)===w(b)};e.hasSameOrigin=J;e.canUseXhr=
F;e.getCorsConfig=K;e.makeAbsolute=m;e.makeRelative=N;e.normalize=q;e.join=M;e.getOrigin=function(a){if(P(a))return null;var b=a.indexOf("://");if(-1===b&&f(a))b=2;else if(-1!==b)b+=3;else return null;b=a.indexOf("/",b);return-1===b?a:a.slice(0,b)};e.isAbsolute=r;e.isDataProtocol=P;e.isProtocolRelative=f;e.read=function(a,b){var c=b&&b.url&&b.url.path;return!a||!c?a:m(a,c,{preserveProtocolRelative:!0})};e.write=function(a,b){if(!a)return a;a=m(a);var c=b&&b.url&&b.url.path;c&&(a=N(a,c));return a}});