// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.19/esri/copyright.txt for details.
//>>built
define("esri/dijit/Bookmarks","dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/has dojo/keys dojo/on dojo/query dojo/window dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dnd/Avatar dojo/dnd/Source dojo/i18n!../nls/jsapi dijit/a11yclick dijit/_WidgetBase ../kernel ../domUtils ../Evented ../geometry/Extent ./BookmarkItem".split(" "),function(k,d,s,f,y,z,q,n,A,B,g,m,v,u,C,r,t,D,E,w,F,p,x){s=s([D,F],{declaredClass:"esri.dijit.Bookmarks",bookmarks:[],bookmarkDomNode:null,
bookmarkTable:null,initBookmarks:null,editable:null,map:null,_oldGenerateText:null,_customGenerateText:!1,_LTR:!0,_dndSource:null,_inputBox:null,_label:null,_css:{esriBookmarks:"esriBookmarks",esriBookmarksRTL:"esriBookmarksRTL",esriBookmarkList:"esriBookmarkList",esriBookmarkTable:"esriBookmarkTable",esriBookmarkEditImage:"esriBookmarkEditImage",esriBookmarkRemoveImage:"esriBookmarkRemoveImage",esriBookmarkLabel:"esriBookmarkLabel",esriBookmarkItem:"esriBookmarkItem",esriBookmarkHighlight:"esriBookmarkHighlight",
esriAddBookmark:"esriAddBookmark",esriBookmarkEditBox:"esriBookmarkEditBox"},_clickHandlers:[],_mouseOverHandlers:[],_mouseOutHandlers:[],_removeHandlers:[],_editHandlers:[],_dndHandlers:[],_eventMap:{click:!0,edit:!0,remove:!0},onClick:function(){},onEdit:function(){},onRemove:function(){},constructor:function(a,b){this.map=a.map;this.editable=a.editable;this.initBookmarks=a.bookmarks;delete a.bookmarks;this.bookmarkDomNode=m.create("div");g.add(this.bookmarkDomNode,this._css.esriBookmarkList);this.bookmarkTable=
m.create("div");g.add(this.bookmarkTable,this._css.esriBookmarkTable);this.bookmarkDomNode.appendChild(this.bookmarkTable);b=B.byId(b);b.appendChild(this.bookmarkDomNode);this.srcNodeRef=b;g.add(this.srcNodeRef,this._css.esriBookmarks);(this._LTR=this.isLeftToRight())||g.add(this.srcNodeRef,this._css.esriBookmarksRTL);this._dndSource=new C(this.bookmarkTable,{creator:this._avatarCreator,singular:!0,checkAcceptance:function(a,b){return this===a?!0:!1}});this._dndSourceNodes=this._dndSource.getAllNodes();
this._dndHandlers.push(q(this._dndSource,"DndStart",f.hitch(this,function(a){a===this._dndSource&&(this._oldGenerateText=u.prototype._generateText,u.prototype._generateText=f.hitch(this,this._generateText),this._customGenerateText=!0,this._inputBox&&this._inputBox.blur())})));this._dndHandlers.push(q(this._dndSource,"DndDrop",f.hitch(this,function(a){a===this._dndSource&&(this._syncBookmarksAfterReorder(),this.emit("reorder",this.bookmarks))})));this._dndHandlers.push(q(this._dndSource,"DndCancel",
f.hitch(this,function(){this._customGenerateText&&(u.prototype._generateText=this._oldGenerateText,this._customGenerateText=!1)})));this._addInitialBookmarks()},destroy:function(){this.map=null;k.forEach(this._clickHandlers,function(a){d.disconnect(a)});k.forEach(this._mouseOverHandlers,function(a){d.disconnect(a)});k.forEach(this._mouseOutHandlers,function(a){d.disconnect(a)});k.forEach(this._removeHandlers,function(a){d.disconnect(a)});k.forEach(this._editHandlers,function(a){d.disconnect(a)});
m.destroy(this.bookmarkDomNode)},addBookmark:function(a){var b,c,l,e;"esri.dijit.BookmarkItem"===a.declaredClass?b=a:(b=new p(a.extent),b=new x({name:a.name,extent:b}));this.editable?(l=r.widgets.bookmarks,e=l.NLS_bookmark_edit,l=l.NLS_bookmark_remove,c=m.create("div",{innerHTML:'\x3cdiv tabindex\x3d"0" role\x3d"button" class\x3d\'esriBookmarkLabel\'\x3e'+a.name+'\x3c/div\x3e\x3cdiv tabindex\x3d"0" role\x3d"button" title\x3d\''+l+"' class\x3d'esriBookmarkRemoveImage'\x3e\x3cbr/\x3e\x3c/div\x3e\x3cdiv tabindex\x3d\"0\" role\x3d\"button\" title\x3d'"+
e+"' class\x3d'esriBookmarkEditImage'\x3e\x3cbr/\x3e\x3c/div\x3e"}),e=n(".esriBookmarkEditImage",c)[0],l=n(".esriBookmarkRemoveImage",c)[0],this._removeHandlers.push(d.connect(l,t,this,"_removeBookmark")),this._editHandlers.push(d.connect(e,t,this,"_editBookmarkLabel"))):c=m.create("div",{innerHTML:"\x3cdiv tabindex\x3d\"0\" class\x3d'esriBookmarkLabel'\x3e"+a.name+"\x3c/div\x3e"});g.add(c,this._css.esriBookmarkItem);"esri.geometry.Extent"!==a.extent.declaredClass&&new p(a.extent);e=n(".esriBookmarkLabel",
c)[0];this._clickHandlers.push(d.connect(e,t,f.hitch(this,"_onClickHandler",a)));this._mouseOverHandlers.push(d.connect(c,"onmouseover",f.hitch(this,function(){g.add(c,this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(d.connect(c,"onmouseout",f.hitch(this,function(){g.remove(c,this._css.esriBookmarkHighlight)})));this.bookmarks.push(b);this._dndSource.insertNodes(!1,[c]);this._dndSourceNodes=this._dndSource.getAllNodes();A.scrollIntoView(c);this._syncBookmarksAfterReorder()},removeBookmark:function(a){this._inputBox&&
this._inputBox.blur();var b;b=n(".esriBookmarkLabel",this.bookmarkDomNode);b=k.filter(b,function(b){return b.innerHTML===a});k.forEach(b,function(a){a.parentNode.parentNode.parentNode.removeChild(a.parentNode.parentNode)});for(b=this.bookmarks.length-1;0<=b;b--)this.bookmarks[b].name===a&&this.bookmarks.splice(b,1);this.onRemove()},hide:function(){w.hide(this.bookmarkDomNode)},show:function(){w.show(this.bookmarkDomNode)},_addInitialBookmarks:function(){if(this.editable){var a=m.create("div",{tabIndex:0,
role:"button",innerHTML:"\x3cdiv\x3e"+r.widgets.bookmarks.NLS_add_bookmark+"\x3c/div\x3e"});g.add(a,this._css.esriBookmarkItem);g.add(a,this._css.esriAddBookmark);this._clickHandlers.push(d.connect(a,t,this,this._newBookmark));this._mouseOverHandlers.push(d.connect(a,"onmouseover",f.hitch(this,function(){g.add(a,this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(d.connect(a,"onmouseout",f.hitch(this,function(){g.remove(a,this._css.esriBookmarkHighlight)})));this.srcNodeRef.appendChild(a)}this.bookmarks=
[];k.forEach(this.initBookmarks,function(a){this.addBookmark(a)},this)},_newBookmark:function(){var a,b,c,l,e,h;h=this.map;a=r.widgets.bookmarks.NLS_new_bookmark;var d=h.extent;h.spatialReference._isWrappable()?(b=p.prototype._normalizeX(d.xmin,h.spatialReference._getInfo()).x,c=p.prototype._normalizeX(d.xmax,h.spatialReference._getInfo()).x,b>c&&(l=(e=h.spatialReference.isWebMercator())?2.0037508342788905E7:180,e=e?-2.0037508342788905E7:-180,Math.abs(b-l)>Math.abs(c-e)?c=l:b=e),h=new p(b,d.ymin,
c,d.ymax,h.spatialReference)):h=d;a=new x({name:a,extent:h});this.addBookmark(a);a=n(".esriBookmarkItem",this.bookmarkDomNode);h=a[a.length-1];a={target:{parentNode:null}};a.target.parentNode=h;this._editBookmarkLabel(a)},_removeBookmark:function(a){a.target.parentNode.parentNode.parentNode.removeChild(a.target.parentNode.parentNode);this.removeBookmark(a.target.parentNode.textContent)},_syncBookmarksAfterReorder:function(){var a=[],b=this._dndSource.getAllNodes();k.forEach(b,f.hitch(this,function(b){var d=
this._dndSourceNodes.map(function(a,d){if(a===b)return d}).filter(isFinite)[0];a.push(this.bookmarks[d])}));this.bookmarks=a;this._dndSourceNodes=b},_generateText:function(){return this._dndSource&&this._dndSource.getSelectedNodes()[0]&&this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML?this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML:""},_editBookmarkLabel:function(a){this._inputBox&&this._inputBox.blur();var b=r.widgets.bookmarks.NLS_new_bookmark;a=a.target.parentNode;
var c=a.firstChild||n(".esriBookmarkLabel",a)[0],d=v.position(a,!0),e=d.y;this._label=c;this._inputBox=m.create("input",{className:"esriBookmarkEditBox",value:c.innerHTML!==b?c.textContent:"",style:{top:e+"px",left:this._LTR?d.x+"px":"0px"}},this.srcNodeRef);q(this._inputBox,"keyup",f.hitch(this,function(a){switch(a.keyCode){case z.ENTER:this._inputBox.blur()}}));q(this._inputBox,"blur",f.hitch(this,this._finishEdit));this._inputBox.focus();this._inputBox.select();b=v.position(a,!0);this._inputBox.style.left=
this._LTR?b.x+"px":"0px";this._inputBox.style.top=b.y+"px"},_finishEdit:function(){if(this._inputBox){var a=r.widgets.bookmarks.NLS_new_bookmark,b=n(".esriBookmarkLabel",this.bookmarkDomNode),c=this._inputBox.value;c===this._label.innerHTML?(this._inputBox.parentNode.removeChild(this._inputBox),this._inputBox=null):(this._label.textContent=""!==c?c:a,k.forEach(this.bookmarks,function(a,c){a&&b[c]&&(a.name=b[c].innerHTML)}),this._inputBox.parentNode.removeChild(this._inputBox),this._inputBox=null,
this.onEdit())}},_avatarCreator:function(a,b){var c=m.create("div");c.id=dojo.dnd.getUniqueId();g.add(c,"dojoDndItem");"avatar"!==b&&m.place(a,c);return{node:c,data:a,type:"something"}},_onClickHandler:function(a){var b=a.extent;a.extent.declaredClass||(b=new p(a.extent));this.map.setExtent(b);this.onClick()},toJson:function(){var a=[];k.forEach(this.bookmarks,function(b){b&&a.push(b.toJson())});return a}});y("extend-esri")&&f.setObject("dijit.Bookmarks",s,E);return s});