// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.2/esri/copyright.txt for details.
//>>built
define(["./SpatialReference","./Geometry","./support/webMercatorUtils","./support/spatialReferenceUtils"],function(p,q,m,r){var k=[0,0],l=m.lngLatToXY,n=m.xyToLngLat,g=q.createSubclass({declaredClass:"esri.geometry.Point",normalizeCtorArgs:function(a,b,d,e,f){var c;Array.isArray(a)?(c=a,f=b,a=c[0],b=c[1],d=c[2],e=c[3]):a&&"object"===typeof a?(c=a,a=null!=c.x?c.x:c.longitude,b=null!=c.y?c.y:c.latitude,d=null!=c.z?c.z:c.altitude,e=c.m,(f=c.spatialReference)&&"esri.SpatialReference"!==f.declaredClass&&
(f=new p(f)),!c.declaredClass&&(f&&f.isWebMercator&&null!=c.longitude&&null!=c.latitude)&&(b=l(c.longitude,c.latitude,!1,k),a=b[0],b=b[1])):this.isSR(d)?(f=d,d=null):this.isSR(e)&&(f=e,e=null);a={x:a,y:b};null!=f&&(a.spatialReference=f);null!=d&&(a.z=d);null!=e&&(a.m=e);return a},properties:{cache:{dependsOn:["x","y","z","m"]},hasM:{dependsOn:["m"],get:function(){return void 0!==this.m},set:function(a){var b=this._get("hasM");a!==b&&(this._set("m",a?0:void 0),this._set("hasM",a))}},hasZ:{dependsOn:["z"],
get:function(){return void 0!==this.z},set:function(a){var b=this._get("hasZ");a!==b&&(this._set("z",a?0:void 0),this._set("hasZ",a))}},latitude:{dependsOn:["y"],get:function(){var a=this._get("spatialReference");if(a){if(a.isWebMercator)return n(this.x,this.y,!1,k)[1];if(4326===a.wkid)return this._get("y")}return null},set:function(a){var b=this._get("spatialReference");b&&(b.isWebMercator?this._set("y",l(this.x,a,!1,k)[1]):4326===b.wkid&&this._set("y",a),this._set("latitude",a))}},longitude:{dependsOn:["x"],
get:function(){var a=this._get("spatialReference");if(a){if(a.isWebMercator)return n(this._get("x"),this._get("y"),!1,k)[0];if(4326===a.wkid)return this._get("x")}return null},set:function(a){var b=this._get("spatialReference");b&&(b.isWebMercator?this._set("x",l(a,this._get("y"),!1,k)[0]):4326===b.wkid&&this._set("x",a),this._set("longitude",a))}},x:0,y:0,z:void 0,m:void 0,type:"point"},clone:function(){var a=new g;a.x=this.x;a.y=this.y;a.z=this.z;a.m=this.m;a.spatialReference=this.spatialReference;
return a},copy:function(a){g.copy(a,this);return this},equals:function(a){if(!a)return!1;var b=this.x,d=this.y,e=this.z,f=this.m,c=this.spatialReference,g=a.x,h=a.y,k=a.z,m=a.m;a=a.spatialReference;if(!c.equals(a))if(c.isWebMercator&&4326===a.wkid)h=l(g,h),g=h[0],h=h[1],a=c;else if(4326===c.wkid&&a.isWebMercator)h=n(g,h),g=h[0],h=h[1],a=c;else return!1;return b===g&&d===h&&e===k&&f===m&&c.wkid===a.wkid},offset:function(a,b,d){this.x+=a;this.y+=b;null!=d&&this.hasZ&&(this.z+=d);return this},normalize:function(){var a=
this.x,b=this.spatialReference;if(b){var d=r.getInfo(b);if(d){var b=d.valid[0],e=d.valid[1],d=2*e;a>e?(b=Math.ceil(Math.abs(a-e)/d),a-=b*d):a<b&&(b=Math.ceil(Math.abs(a-b)/d),a+=b*d)}}this._set("x",a);return this},distance:function(a){return g.distance(this,a)},toArray:function(){var a=this.hasZ,b=this.hasM;return a&&b?[this.x,this.y,this.z,this.m]:a?[this.x,this.y,this.z]:b?[this.x,this.y,this.m]:[this.x,this.y]},toJSON:function(){var a=this.spatialReference,b={x:this.x,y:this.y};this.hasZ&&(b.z=
this.z);this.hasM&&(b.m=this.m);b.spatialReference=a&&a.toJSON();return b}});g.lngLatToXY=l;g.xyToLngLat=n;g.copy=function(a,b){b.x=a.x;b.y=a.y;b.z=a.z;b.m=a.m;b.spatialReference=Object.isFrozen(a.spatialReference)?a.spatialReference:a.spatialReference.clone()};g.distance=function(a,b){var d=a.x-b.x,e=a.y-b.y,f=a.hasZ&&b.hasZ?a.z-b.z:0;return Math.sqrt(d*d+e*e+f*f)};return g});